### ISSUE TITLE
Not able to pair device. 

### ISSUE THREAD

**Issue by SmashleyG** [MycroftAI/mycroft-core#101]
I have logged into https://cerberus.mycroft.ai and followed the instruction, I type in the code, but I get no response or that device failed to pair. 

I also get a lot of 500: Internal Server Error. 

I have used both Firefox and chrome. I am using Ubuntu gnome 16.04. 

Thanks.

**Comment by ryanleesipes** [comment]
@SmashleyG this should be fixed, we are going to be doing some updating and better monitoring to ensure this isn't an issue going forward.

**Comment by SmashleyG** [comment]
Thanks, everything is working fine :)
