### ISSUE TITLE
Conflict between voc/regex files in different skills

### ISSUE THREAD

**Issue by Merkaran** [MycroftAI/mycroft-core#1017]
Hi
I am building my own meeting skill and one of the intent is used to get the desired location 
(build : `IntentBuilder("LocationIntent").require("InKeyword").require("Location").build()` )
with this regex (named **Location.rx**): `in (?P<Location>.+)` but when I test it with a city name beginning with **la** like 
> in La Paz

I get `{"type": "MeetingSkill:LocationIntent", "data": {"confidence": 0.6666666666666666, "target": null, "intent_type": "MeetingSkill:LocationIntent" , "InKeyword": "in", "Location": "Los Angeles california", "utterance": "in La Paz"}, "context": {"target": null}}` 

I looked where it could come from and it appears **la** is an alias of **Los Angeles california** in the **Location.voc** file from the default skill **skill-weather** 

To be sure I also tried with another alias
> in portland

and get : `{"type": "MeetingSkill:LocationIntent", "data": {"confidence": 1.0, "target": null, "intent_type": "MeetingSkill:LocationIntent", "InKeyword": "in", "Location": "portland oregon", "utterance": "in portland"}, "context": {"target": null}}`

**Comment by btotharye** [comment]
Hey @Merkaran I'll try this out do you happen to have your code already up somewhere, otherwise I can test it by building out a test skill.

Thanks

**Comment by Merkaran** [comment]
Hi,
No sorry

**Comment by btotharye** [comment]
Maybe I was hoping @Merkaran had an example we could test with, I didn't get to test it yet you beat me to it :)

**Comment by forslund** [comment]
Yeah, that would be best, to have the failing case to test against

**Comment by forslund** [comment]
We've added a feature isolating the skills' vocabulary back in february, so this should be resolved. Sorry for the long response time. Closing this, if the implementation is lacking please reopen this issue.
