### ISSUE TITLE
expect_response parameter in speak_dialog() method is not taken into account

### ISSUE THREAD

**Issue by linuxipho** [MycroftAI/mycroft-core#1019]
When using `expect_response=True` in self.speak_dialog() method, the paramater is well passed to speak_dialog() but not to sub-called speak() method in mycroft/skills/core.py

The effect is no response is expected and we can't do interaction in skills without directly starting recording. 

Solution is to add `expect_response=expect_response` parameter at the end of self.speak() call line 463 in mycroft/skills/core.py which give this:
`self.speak(self.dialog_renderer.render(key, data), expect_response=expect_response)`

**Comment by forslund** [comment]
Thanks for reporting, your solution looks good. Will implement it and a matching test case

**Comment by linuxipho** [comment]
Glad to help

**Comment by forslund** [comment]
This should be fixed now. Closing
