### ISSUE TITLE
Intent_service fails when a one_of rule is matched

### ISSUE THREAD

**Issue by deevrek** [MycroftAI/mycroft-core#1022]
Hello,
this issue occurs inside the update_context method:

>     def update_context(self, intent):
>             for tag in intent['__tags__']:
>                 context_entity = tag.get('entities')[0]
>                 if self.context_greedy:
>                     self.context_manager.inject_context(context_entity)
>                 elif context_entity['data'][0][1] in self.context_keywords:
>                     self.context_manager.inject_context(context_entity)
  
 _tags_ returned from adapt when a "one_of" rule is matched contains the entire Keyword match instead of the "entities" attribute.
The raised exception causes the failure of the skill.

I proposed a solution in the Adapt repository.
https://github.com/MycroftAI/adapt/pull/66

**Comment by forslund** [comment]
Thanks for reporting this. In the meantime I shall add a check so that it doesn't break functionality.

**Comment by forslund** [comment]
This was resolved in #1026, closing
