### ISSUE TITLE
Add pep8 bot

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1025]
Open for discussion, but it might be better to enable [this pep8speaks bot][bot] instead of or alongside the t
current travis PEP8 check. It will only comment on pull requests if there is a PR and it can be configured to enable/disable particular pep8 warnings. This would make it clearer every time there's a PR that had a failing travis test because of something like an extra newline. [Here's a demo](https://github.com/MatthewScholefield/mycroft-core/pulls).

[bot]:https://github.com/orkohunter/pep8speaks

**Comment by btotharye** [comment]
agreed something like this would be good or just set it up in travis if that isn't already there.  Not sure if you have travis already setup to do pep checks or not.

**Comment by forslund** [comment]
This seems really useful, Travis is good but the result might be missed until the next time the contributor checks in on her/his PR and notices the red X. This will give clear response and directions.

**Comment by MatthewScholefield** [comment]
Yeah, Travis has had Pep8 for a while, it's just it's often a pain to read through the Travis logs for something as small as Pep8.

**Comment by btotharye** [comment]
yep I agree I think it would be better for people that don't know what travis is and need better visualization directly in the PR

**Comment by forslund** [comment]
@penrods and/or @aatchison should probably have a say in this, also I don't have the rights to install the bot here so it'll be up to one of them.
