### ISSUE TITLE
UnicodeDecodeError with accents in dialog files in other languages

### ISSUE THREAD

**Issue by linuxipho** [MycroftAI/mycroft-core#1027]
Hi, I'm french and we have a lot of accents there !

Should be smart to add utf-8 support while opening dialog files ?
Using codecs module works fine for me in `mycroft/dialog/__init__.py` line 47:

`import codecs`
`with codecs.open(filename, 'r', 'utf-8') as f:`

**Comment by forslund** [comment]
For future proofing maybe `io.open()` should be used instead?

**Comment by linuxipho** [comment]
Yes you're right indeed, `io.open()` is a better way (the default python3 way).

**Comment by forslund** [comment]
Played around with this a bit and found a couple of more internationalization errors. PR coming soonish.

Mycroft's french is terrible by the way :)
