### ISSUE TITLE
Add portuguese translation

### ISSUE THREAD

**Issue by 00tiagopolicarpo00** [MycroftAI/mycroft-core#1034]
I dont see what is the best way to translation the content files on folder 
mycroft/util/
parse.py, and format.py
I am not coder.

**Comment by JarbasAI** [comment]
i can tackle this one :) you could help by tanslating all dialog files, no coding experience needed,  also if you feel like it translate also the skill repos!

**Comment by 00tiagopolicarpo00** [comment]
I am, now translation skill, i finish amarok-player-skill, plasma-activities-skill, plasma-sendsms-skill,  and my period is official skill if the coder have other i translation in the same process.
.

**Comment by forslund** [comment]
The main work on translating core has been done so I'm closing this. Feel free to open new issues for any bugs in the translation.
