### ISSUE TITLE
Cli client console script broken

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1036]
In `mycroft/client/text/main.py`, the `if __name__ == '__main__':` contents need to be moved inside `def main()` so that the only thing called is `main()`. This is because, the console script doesn't call the file; it calls the `mycroft.client.text.main:main`.

**Comment by Mn0491** [comment]
@MatthewScholefield can this be closed now?

**Comment by MatthewScholefield** [comment]
Yep
