### ISSUE TITLE
Support for Xiaomi Smart Speakers

### ISSUE THREAD

**Issue by confin234** [MycroftAI/mycroft-core#1037]
Hello everyone, I'm fairly new here, so bare with me here. I recently found out that Xiaomi made a smart speaker with their new AI called Patchwall, and it has amazing sound according to every sound test I've heard. The problem is that Patchwall is only available in Chinese. I know that they are pretty open to modifying their products, so I wanted to see if I could buy it sometime and somehow install Mycroft on it because let's face it, Mycroft is far better than any other AI from a big company, especially considering that as a programming hobbyist with lots of free time, I can add as much functionality as I want, without getting in trouble. Plus, it currently costs $70 at GearBest. They are releasing a new speaker very soon but there is no specs leaked for it.

So, the specs of their current smart speaker, the Mi Wi-Fi Speaker is as follows.

Amlogic AML8726-M3 Single Core ARM Cortex A9 CPU at 1 Ghz
2GB DDR3 RAM
8GB Internal Flash Memory
Bluetooth 4.1 and 802.11ac
1 Full size USB Port as an added bonus.
It probably has a pretty good DAC and Amp in it, but I don't know for sure.

So, it has more than enough to run Ubuntu with CLI only and lots of things open at once. The only potential problem I can see right now is the old CPU architecture, but the specs are exponentially better than the Amazon Echo, although the Amazon Echo doesn't need to run an entire linux distro.

I have lots of free time, so I am willing to contribute as much as possible.

**Comment by Mn0491** [comment]
@confin234 this would be awesome if it can work. The problem i do see is the speaker is a single core which might be a problem for mimic and pocket sphinx.

**Comment by forslund** [comment]
You could probably get it going by changing TTS to google TTS (simple setting) and patch in the snowboy wake word recognizer (there's an example available somewhere around here)

**Comment by confin234** [comment]
Ok then,

**Comment by confin234** [comment]
Ok, that sounds plausible. Is there a Google TTS engine that sounds similar to the one it uses now, like a male british english voice? I can't seem to find a demo online for one of those.

**Comment by confin234** [comment]
Also, sorry for closing the thread, I pressed the wrong button.

**Comment by confin234** [comment]
Ok, for those of you reading this who want to change the TTS voice to Google TTS without sacrificing Mycroft's beautiful voice featured in the Kickstarter video, the best voice to use is Male 3 from Voice Pack 2 of the British English language. Voice pack 1's male voices basically sound like a stereotype of a gay hair stylist in different levels of enthusiasm. Voice pack 2's male voices are less enthusiastic the farther down you go, but Mycroft's voice is supposed to sound like actual Mycroft from the Sherlock TV series, which basically sounding like a stereotype of a super wealthy spoiled child's butler.

Don't hate me for using stereotypes as examples for how the voice sounds, I'm just trying to give you an idea of what it sounds like through using stereotypes from TV, as you already know what those sound like.

**Comment by krisgesling** [comment]
Hi there, as this is quite old now and there doesn't seem to be any actions needed from it, I'm closing the issue.
