### ISSUE TITLE
skill config parameter could be more user friendly

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#1044]
Currently the skill config parameter is defaulted to `None` if the skill has no entry in the configuration. This makes configuration checks a bit more complicated than necessary since the skill creator always need to check that 

```
if self.config is not None:
    val = self.config.get('val')
```

or similar.

Defaulting `self.config` to an empty dict `{}` would simplify this a bit.

**Comment by cowang4** [comment]
Has this been fixed? I'm looking at contributor friendly issues, but I can't seem to find the piece of code that you're referring to.

**Comment by forslund** [comment]
Hi, sorry for the long delay.

The issue is referring to https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/core.py#L213

The configs are initiated to the config if existing or `None` if missing. This could be changed to an empty dict `{}` if missing so the skill creator doesn't need to check if the member is set or not before accessing
```python
if self.config:
    my_var = self.config.get('my_var')
```

could be simplified if the skill creator can trust that the config member is always a dict.

```python
    my_var = self.config.get('my_var')
```
