### ISSUE TITLE
French language on Picroft gives : RuntimeError: new_Decoder returned -1

### ISSUE THREAD

**Issue by r3z3** [MycroftAI/mycroft-core#1055]
I all,
I allways got this beautiful error when I try to use another language (french) for my Picroft, using this wiki  
https://github.com/MycroftAI/mycroft-core/wiki/Mycroft-in-French

self._load_config()
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.20-py2.7.egg/mycroft/client/speech/listener.py", line 212, in _load_config
    self.mycroft_recognizer = self.create_mycroft_recognizer(rate, lang)
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.20-py2.7.egg/mycroft/client/speech/listener.py", line 224, in create_mycroft_recognizer
    threshold, rate, lang)
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.20-py2.7.egg/mycroft/client/speech/recognizer/pocketsphinx_recognizer.py", line 42, in __init__
    self.decoder = Decoder(self.create_config(dict_name))
  File "/usr/local/lib/python2.7/site-packages/pocketsphinx/pocketsphinx.py", line 271, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

Here is my mycroft conf 

{
  // Definition and documentation of all variables used by mycroft-core.
  // 
  // Settings seen here are considered DEFAULT.  Settings can also be
  // overridden at the REMOTE level (set by the user via 
  // https://home.mycroft.ai), at the SYSTEM level (typically in the file
  // '/etc/mycroft/mycroft.conf'), or at the USER level (typically in the
  // file '~/.mycroft/mycroft.conf').
  //
  // The Override: comment indicates at what level (if any) this is 
  // overridden by the system to a value besides the default shown here.

  // Language used for speech-to-text and text-to-speech.
  // Code is a BCP-47 identifier (https://tools.ietf.org/html/bcp47), lowercased
  // TODO: save unmodified, lowercase upon demand
  // Override: none
  //"lang": "en-us",
  "lang": "fr",
  // Measurement units, either 'metric' or 'english'
  // Override: REMOTE
  "system_unit": "metric",
  
  // Time format, either 'half' (e.g. "11:37 pm") or 'full' (e.g. "23:37")
  // Override: REMOTE
  "time_format": "full",
  
  // Date format, either 'MDY' (e.g. "11-29-1978") or 'DMY' (e.g. "29-11-1978")
  // Override: REMOTE
  "date_format": "DMY",
  
  // Play a beep when system begins to listen?
  // Override: none
  "confirm_listening": true,
  
  // File locations of sounds to play for system events
  // Override: none
  "sounds": {
    "start_listening": "snd/start_listening.wav",
    "end_listening": "snd/end_listening.wav"
  },
  
  // Mechanism used to play WAV audio files
  // Override: SYSTEM
  "play_wav_cmdline": "paplay %1 --stream-name=mycroft-voice",
  
  // Mechanism used to play MP3 audio files
  // Override: SYSTEM
  "play_mp3_cmdline": "mpg123 %1",
  
  // Location where the system resides
  // NOTE: Although this is set here, an Enclosure can override the value.
  //       For example a mycroft-core running in a car could use the GPS.
  // Override: REMOTE
  "location": {
    "city": {
      "code": "Niort",
      "name": "Niort",
      "state": {
        "code": "NI",
        "name": "Niort",
        "country": {
          "code": "FR",
          "name": "FRANCE"
        }
      }
    },
    "coordinate": {
      "latitude": 46.316244,
      "longitude": -0.474497
    },
    "timezone": {
      "code": "Europe/Paris",
      "name": "Central Standard Time",
      "dstOffset": 3600000,
      "offset": -21600000
    }
  },
  
  // General skill values
  // Override: none
  "skills": {
    // Directory to look for user skills
    "directory": "~/.mycroft/skills",
    // TODO: Old unused kludge, remove from code
    "stop_threshold": 2.0,
    // blacklisted skills to not load
    "blacklisted_skills": ["skill-media", "send_sms", "skill-wolfram-alpha"]
  },
  
  // Address of the REMOTE server
  // Override: none
  "server": {
    "url": "https://api.mycroft.ai",
    "version": "v1",
    "update": false,
    "metrics": false
  },
  
  // The mycroft-core messagebus' websocket
  // Override: none
  "websocket": {
    "host": "0.0.0.0",
    "port": 8181,
    "route": "/core",
    "ssl": false
  },
  
  // Settings used by the wake-up-word listener
  // Override: REMOTE
  "listener": {
	"producer": "pocketsphinx",
	"grammar": "lm",
    "sample_rate": 16000,
    "channels": 1,
    "record_wake_words": false,
    "wake_word": "hey mycroft",
    "phonemes": "HH EY . M AY K R AO F T",
    "phoneme_duration": 120,
    "threshold": 1e-90,
    "multiplier": 1.0,
    "energy_ratio": 1.5
  },
  
  // Mark 1 enclosure settings
  // Override: SYSTEM (e.g. Picroft)
  "enclosure": {
    // Platform name (e.g. 'Picroft', 'Mark_1'
    // Override: SYSTEM (set by specific enclosures)
    # "platform": "picroft",
    
    // COMM params to the Arduino/faceplate
    "port": "/dev/ttyAMA0",
    "rate": 9600,
    "timeout": 5.0,
    
    // ??
    "update": false,
    
    // Run a self test at bootup?
    "test": false
  },

  // Level of logs to store, one of  "CRITICAL", "ERROR", "WARNGIN", "INFO", "DEBUG"
  // Override: none
  "log_level": "DEBUG",
  
  // Messagebus types that will NOT be output to logs
  // Override: none
  "ignore_logs": ["enclosure.mouth.viseme"],

  // Settings related to remote sessions
  // Overrride: none
  "session": {
    // Time To Live, in seconds
    "ttl": 180
  },

  // Speech to Text parameters
  // Override: REMOTE
  "stt": {
    // Engine.  Options: "mycroft", "google", "wit", "ibm", "kaldi"
    "module": "mycroft"
    // "kaldi": {
    //   "uri": "http://localhost:8080/client/dynamic/recognize"
    // }
  },

  // Text to Speech parameters
  // Override: REMOTE
  "tts": {
    // Engine.  Options: "mimic", "google", "marytts", "fatts", "espeak", "spdsay"
    "module": "mimic",
    "mimic": {
      "voice": "ap"
    },
    "espeak": {
      "lang": "fr",
      "voice": "m1"
    }
  },

  "padatious": {
    "intent_cache": "~/.mycroft/intent_cache",
    "train_delay": 4
  },

  // =================================================================
  // All of the follow are specific to particular skills and will soon
  // be removed from this file.
  // =================================================================

  "wifi": {
    "setup": false
  },
  "ConfigurationSkill": {
    "max_delay": 60
  },
  "WikipediaSkill": {
    "max_results": 5,
    "max_phrases": 2
  },
  "WolframAlphaSkill": {
    "api_key": "",
    "proxy": true
  },
  "WeatherSkill": {
    "api_key": "",
    "proxy": true,
    "temperature": "fahrenheit"
  },
  "NPRNewsSkill": {
    "url_rss": "http://www.npr.org/rss/podcast.php?id=500005"
  },
  "AlarmSkill": {
    "filename": "alarm.mp3",
    "max_delay": 600,
    "repeat_time": 20,
    "extended_delay": 60
  },
  "ReminderSkill": {
    "max_delay": 600,
    "repeat_time": 60,
    "extended_delay": 60
  },
  "VolumeSkill": {
    "default_level": 6,
    "min_volume": 0,
    "max_volume": 100
  },
  "AudioRecordSkill": {
    "filename": "/tmp/mycroft-recording.wav",
    "free_disk": 100,
    "max_time": 600,
    "notify_delay": 5,
    "rate": 16000,
    "channels": 1
  },
  "SkillInstallerSkill": {
  },
  "Audio": {
    "backends": {
      "local": {
        "type": "mpg123",
        "active": true
      },
      "vlc": {
        "type": "vlc",
        "active": true
      }
    },
    "default-backend": "local"
  }
}

**Comment by forslund** [comment]
Hi,

I'm by no means an expert on setting up pocketsphinx but I'll share what little I know.

That error usually means one of two things:

1. Pocket sphinx can't find the appropriate model for the voice (https://github.com/MycroftAI/mycroft-core/wiki/Mycroft-in-French#11-download-the-generic-french-dictionary-and-the-french-acoustic-model-trained-with-latest-sphinxtrain). I'm not really sure about the procedure here. This installs into default location what might well work, if it doesn't work I think the speech client checks mycroft/client/speech/recognizer/model/[LANG]/

2. The Wakeword settings Wakeword (Hey Mycroft) or phonemes for the wakeword are inconsistent or wrong for the current model.

**Comment by r3z3** [comment]
I didn't change the wakeword (or the phonemes) and followed the wiki.
Anyone else can help me ?

**Comment by forslund** [comment]
Did you try placing the french model inside the directory suggested above?

**Comment by r3z3** [comment]
Yes I did, whithout any success :[

**Comment by forslund** [comment]
I'm closing this in favor for the task specified in #2563 which should resolve this issue.
