### ISSUE TITLE
Kathy testing Mattermost / GitHub webhook integration

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/mycroft-core#1070]
This issue is to test the Mattermost / GitHub webhook integration. It can be safely ignored and will be closed when the webhooks are working properly. 

Tyger! Tyger! burning bright, 
In the forests of the night, 
What immortal hand or eye 
Could frame thy fearful symmetry?

**Comment by ryanleesipes** [comment]
@KathyReid  - you guys are using Mattermost, but the link still points at the Slack channel! Oh no!

![need_mattermost](https://user-images.githubusercontent.com/2141621/31259508-6d942e7e-aa04-11e7-8832-2a5f5833ef95.png)

**Comment by forslund** [comment]
Closing...
