### ISSUE TITLE
CLI crashes if chat history height set too high

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1083]
With the feature introduced by #1081, typing something like `:history 1000` will crash the CLI.

**Comment by penrods** [comment]
I debated about what to do here and took the lazy/easy "asking it to do stupid things might provide stupid results", especially since this is a programmer tool.  But I probably should cap the use of this value based on the minimum number of lines needed to render other screen elements.

**Comment by zachwelch** [comment]
With PR #1436 merged, this issue can be closed.

**Comment by forslund** [comment]
Ok, closing!
