### ISSUE TITLE
MSM Virtualenv Issue

### ISSUE THREAD

**Issue by btotharye** [MycroftAI/mycroft-core#1090]
I'm proposing we change https://github.com/MycroftAI/mycroft-core/blob/5b31047ccd6039846308a8e923c142c2f7cf2a41/msm/msm#L195 to not exit and just echo so that docker and other people that install mycroft not in a virtualenv can still use msm default to install the skills.

Right now because it errors on the unable to activate virtualenv part it fails to keep installing skills so its only doing them 1 at a time by running msm default over and over or just running msm install skill-pairing, etc.

Let me know your thoughts.

**Comment by el-tocino** [comment]
A prompt there might be a way to help?  And we're moving to more non-standard installs, so there should be an easy way to handle that in the future.

**Comment by el-tocino** [comment]
There is this comment in msm now:
  # TODO: Allow skipping virtualwrapper with an option?

In hindsight if we find the virtualenv, instead of waiting for the parameter to be called and then jump into and out of it we should probably start it and handle the rest of the script from within it.

**Comment by el-tocino** [comment]
I think this is a fairly doable fix.  Will put a pr for it in a bit and let someone else take a look.
Log an info message if not picroft/mk1 and no venv detected.  If it is detected, start the mycroft venv before parsing args, deactivate after.

**Comment by KathyReid** [comment]
@btotharye @el-tocino is this still an Issue now that `msm` has been rewritten in Python?

**Comment by forslund** [comment]
I'm closing this issue since there's been no communication in a couple of months and msm has been rewritten from scratch.
