### ISSUE TITLE
Wrong virtualenv found with oh-my-zsh

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1100]
In MSM, the `locate virtualenvwrapper` finds the directory `~/.oh-my-zsh/plugins/virtualenvwrapper` instead of the correct script causing it to error out. It should probably use `which virtualenvwrapper.sh` or something, but I'm not entirely sure.

**Comment by el-tocino** [comment]
Started with `which` to begin with and ended up with `locate` for some reason; I believe it had to do with the variability of install locations and env variables. Perhaps `lsvirtualenv` might be useful here instead.

**Comment by el-tocino** [comment]
The following presumes a viable result from a locate (which does not find the .sh in two systems I have), and only one mycroft virtualenv.  Something like:

source $(locate virtualenvwrapper.sh)
if hash lsvirtualenv ; then
  if lsvirtualenv -b | grep -q mycroft ; then
    workon mycroft
    echo "working on mycroft!"
    deactivate
  else 
    echo "Not able to workon mycroft."
  fi
else
  echo "unable to run lsvirtualenv."
fi

**Comment by MatthewScholefield** [comment]
This has been resolved with recent msm changes.
