### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1102]
I propose that we write tests to go through all of the code, increasing our coverage from where it is now at ~40% to something more like 80%. There doesn't need to be a single assertion in these tests. The key would be just running through the code to make sure there are no syntax errors/import errors or anything of the like. For instance, in #1095, I mistakenly deleted an import in the messagebus service `main.py`, but the unit tests still passed.

**Comment by forslund** [comment]
This may be a good idea, my main concern would be that it gives a false sense of that we actually have good tests. Current ~40% status only lie a little bit. That said just loading the code is also a valid test.

Shouldn't a linter catch these type of things?

**Comment by MatthewScholefield** [comment]
Well, for instance the linter didn't catch the problem in that PR since the problem line was already marked as syntax error in the original code and it just somehow didn't error out when the unused include was placed there. Also, I don't think a linter would catch anything like perhaps a divide by 0 or accessing an out of bounds index on an array. I do see the point about inflated coverage results, but that is a test in itself. And, for things like the service main, how much better of a test could we write?

**Comment by forslund** [comment]
Main loops are generally not unittested but may as you suggested be imported or run in an integration test. Maybe we create a separate test (not unittest) for this type of check and report coverage from the unittests?

That should work and still keep us honest. There might even be an integration test for the messagebus service.

**Comment by MatthewScholefield** [comment]
Yeah, I like that idea. Something not necessarily testing anything, just running through all code branches.

**Comment by forslund** [comment]
Closing this one since it's rather vague.
