### ISSUE TITLE
Add Dutch translations to mycroft/skills/time_rules.py

### ISSUE THREAD

**Issue by valdr** [MycroftAI/mycroft-core#1109]
Class created, copied from PT-BR while I mull over the correctness of the translations.

**Comment by arjenlentz** [comment]
Happy to assist with this (I'm a native Dutch speaker), which repo/branch is this hiding in?

**Comment by ljo13** [comment]
Happy to assist as well. Is it me or are there still some dialog files missing? Would love to contribute to this exciting project.

**Comment by forslund** [comment]
Time rules has been removed from the project, there are other translation mechanisms now with some dutch support. Closing this issue.
