### ISSUE TITLE
scripts/mycroft-use.sh broken

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1121]
It looks for `./start.sh` which no longer exists.

**Comment by davfsa** [comment]
One question.... Where does it look for ./start (I reviced the program and didn't find anything...)

**Comment by forslund** [comment]
I think this one has been fixed. The script was very much rebuilt in PR #1182. @MatthewScholefield can we close this?

**Comment by MatthewScholefield** [comment]
It looks like it's still buried in `scripts/mycroft-use.sh`, embedded in a
few really ugly sed statements.

**Comment by forslund** [comment]
Ah yes, I see it now,

**Comment by davfsa** [comment]
What did `./start.sh` use to do??

**Comment by forslund** [comment]
It started the individual services in the foreground. it has now been replaced by mycroft.start.sh (which is slightly different and starts the services in the background but shouldn't matter)

**Comment by davfsa** [comment]
So what program should ti start insted of `./start.sh`??

**Comment by davfsa** [comment]
How can I make a pull request to fix this bug???

**Comment by krisgesling** [comment]
Hi there, this seems resolved. Closing.
