### ISSUE TITLE
install on ubuntu 17.04

### ISSUE THREAD

**Issue by absentdream** [MycroftAI/mycroft-core#1131]
ok.
testing install on a brand new ubuntu 17.04 VM (trying this a 16.04 works fine :) ) so i am looking for what errors in dev-setup.sh

![capture](https://user-images.githubusercontent.com/3314310/31193366-cfd9b30c-a93b-11e7-947f-de9b77131a98.PNG)

i wonder if this helps.. :)

**Comment by absentdream** [comment]
there is a diff in the way they handle "cd folder*"

![capture](https://user-images.githubusercontent.com/3314310/31194506-45f8f0a4-a93f-11e7-9c11-0b66340fa4eb.PNG)

16.04   cd py2cairo* works
17.04  cd py2cairo* DONT

**Comment by absentdream** [comment]
and if i change all 3 cd xxxx* comands to cd xxxxx-version etc it works and installs and pairs... :)

**Comment by arjenlentz** [comment]
"cd basename*" only works (at least in Ubuntu 17.04) if there is no ambiguity - that is, if there is only one possible directory.  Thus, it's not safe to use in a script or make context.

**Comment by absentdream** [comment]
ok so building again from clean os.. 
and noticed that in install-pygtk.sh
**line 87 is**
`cd pygtk-*`

but the other 2 **line 47** and **line 66** are 
`cd pygobject*
cd py2cairo*
`

notice the missing "-" this mean line 47 and 66 fail but not line 87.. so can we change install-pygtk.sh and add the 2 mising "-" as this removes the ambiguity of cd command

many thanks

**Comment by zachwelch** [comment]
This issue was fixed by @darkphoenix in the following commit:
```
 commit 3582c0d1e407a4e0b4e811ad653acc5901f571e5
 Author: Jonas Blahut <jonas@die-blahuts.de>
 Date:   Sun Oct 15 19:33:27 2017 +0200

    Fix cd syntax to avoid "too many arguments" error.
```
... so this issue can be closed.

**Comment by forslund** [comment]
Excellent, thanks for pointing it out. Closing
