### ISSUE TITLE
Reference location context in time and weather answers

### ISSUE THREAD

**Issue by arjenlentz** [MycroftAI/mycroft-core#1134]
Currently, Mycroft provides a rather terse answer to time and weather questions.
This causes a problem.
For instance, try:
 1) Hey Mycroft, what's the time in New York
 2) Hey Mycroft, what's the weather ...

Since Mycroft does pick up some context/intent, it will answer with the weather for New York.
While that can be technically correct, it may not be what the human intended.

thus, I propose Mycroft answers a bit more verbose, like so:
```
  The time in <location> is ...
  The weather forecast for <location> is ...

```
(I may be able to produce a patch for this myself, but just so it's referenced an issue is good)

**Comment by arjenlentz** [comment]
Update.. ok it appears that in some phrasing for weather, Mycroft is already clearer but not consistent throughout the skill.  And for time it's absent.
Examples:

```
what's the weather in brisbane
 >> It's currently broken clouds and 27 degrees celsius in brisbane.
 >> Today's forecast is for a high of 25 and a low of 18.
what time is it
 >> It's 15:27
what's the weather
 >> It's currently light intensity shower rain and 25 degrees celsius in brisbane. Today's forecast is for a high of 25 and a low of 18.
what's tomorrow's weather forecast
 >> The forcast for Saturday is 25 for a high and 18 for a low
what's the time in new york
 >> 01:30
what's the weather
 >> Right now, it's broken clouds and 21 degrees, for a high of 21 and a low of 21 in new york.
what's tomorrow's weather
 >> Saturday, new york will have a high of 21 and a low of 21, with light rain conditions
```

So currently, some weather related responses note the location, some don't.
And time doesn't appear to ever note the location.

**Comment by forslund** [comment]
The location context was mainly left in as an example of the context manager. It's still early days for this feature so it might be betterif we disabled it completely for the time being. There need to be a mechanism for determining when context is desired.

**Comment by arjenlentz** [comment]
Perhaps it could be enabled through a config option?
Backend docu (even code comments) to assist potential devs would be good.

**Comment by forslund** [comment]
In #1181 The location was removed as a default context. It is still an option. I will do some work detecting when context is required.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
