### ISSUE TITLE
Both master and dev branch failing to setup/update/build since most recent commit

### ISSUE THREAD

**Issue by arjenlentz** [MycroftAI/mycroft-core#1135]
Ping @MatthewScholefield 

Both master and dev branch appear to fail since this morning.
dev_setup.sh and update-dev.sh report:

```
Collecting padatious==0.3.3 (from -r requirements.txt (line 39))
  Downloading padatious-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-MmkiHA/padatious/setup.py", line 5, in <module>
        with open(join(dirname(abspath(__file__)), 'requirements.txt')) as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-MmkiHA/padatious/requirements.txt'
```
If I change the version to 0.3.4 it works ok.  0.3.2 also worked ok so I presume the problem was introduced with this commit:
```
commit b6bc4ee482deda3f376c3def026d8732259e5ac6
Author: Matthew D. Scholefield <matthew3311999@gmail.com>
Date:   Wed Oct 4 21:50:54 2017 -0500

    Increment padatious version number to 0.3.3
    This adds a bugfix for empty containers
```
Effectively the bug will have been in the packaging of padatious 0.3.3 and not in mycroft-core.
Anyhow it'll be important to update mycroft-core to use 0.3.4 otherwise it just won't build/run.

**Comment by MatthewScholefield** [comment]
Thanks for the info! I've fixed this in dev. (master should be fine since it didn't get merged into there)

**Comment by arjenlentz** [comment]
Happy to help @MatthewScholefield !
Yes you're right - the master ref was my mistake, I thought one of my branches was master where in fact it was dev also.
