### ISSUE TITLE
msm install / update issue

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#1137]
The basic issue is loading/reloading the skill before msm has installed requirements (if new requirements are needed) causing the skill to not load at all. (Issue Identified by @penrods)

Install skill:
When msm is installing a new skill it clones directly into the skill directory resulting that the reload skill thread will load the skill as soon as it's there without looking if msm is done.

Update skill:
Currently this is not a problem because on update setup scripts don't seem to be run, which is a problem in itself. but will need to be handled as well at some point

Solutions:
Filesystem: msm cloned into /tmp and all setup scripts (pip install -r requirements.txt, requirements.sh) are run and the skill is then moved to the skill directory. For update I think adding support for a LOCK file in the skill directory. msm places the lock file in the directory before starting the update procedure and removes it afterwards. the reload thread looks for this file and if it's present no reload will be performed.

Another solution is to download and run the requirement.txt requirements.sh scripts before cloning / updating a skill.

@el-tocino, @btotharye since you're part of the skills team maybe you have some more insights into this?

**Comment by forslund** [comment]
#1143 Is basically what I had in mind.

**Comment by el-tocino** [comment]
Can also just pull the requirements.* files, pending that working, clone the rest into the skill dir?

**Comment by forslund** [comment]
@el-tocino that is true but I feel that is slightly more complicated and the requirements.sh might need additional files (datafiles, compressed archives or something) from the skill repo to do it's thing.

**Comment by penrods** [comment]
I'm a little concerned that the post-install script might do something unexpected, like save the skill folder into another system.  What do you think of leaving the current approach alone but just sending notifications at the start/end of the install, allowing various systems to react appropriately.  For example, the Plasmoid might update the list of installed skills upon a successful install, or mycroft-core would pause/resume the loading of skills.

**Comment by forslund** [comment]
That will be easy when using the install skill but using msm directly from the command line will be more complex.

I've never been a fan of installing directly into the skill directory, to me it feels dodgy. Probably because I don't know all the details about git clone and the architecture of msm.

In any case we might need a global lock file for msm (similar to the one apt-get uses) to make sure multiple installs/updates happens simultaneously.

**Comment by btotharye** [comment]
would there also be a option to install by releases or branch maybe instead of having to check out that branch after you install it via MSM?

**Comment by penrods** [comment]
I believe #1152 deals with this cleanly.  Everyone OK with closing this?

**Comment by forslund** [comment]
Indeed, Closing.
