### ISSUE TITLE
Filler response after questions

### ISSUE THREAD

**Issue by ftyers** [MycroftAI/mycroft-core#1138]
According to the demo, Mycroft currently takes a while to respond to questions, which makes the interactions a bit unnatural, e.g. "Mycroft, what's the time" _long wait_ "it's four thirty". or "Mycroft, what's the weather out like?" _long wait_ "It's cloudy...". How about speaking some filler after the the question is asked but before the answer is ready, something like "just a sec" or "hang on, I'll check". Anyway, it's just a thought/feature request, feel free to close the issue if it's not relevant.

**Comment by KathyReid** [comment]
Really really like this idea - it's great conversational UI / UX.

**Comment by Mn0491** [comment]
I think this would be a really good idea. But instead of making it a default thing, i think it makes more sense to build an api that skills can interface with, so that way the filler responses can be customize per skill. Some skill takes longer then others to find a responsible answer.

**Comment by ftyers** [comment]
Check out [this](https://ai.googleblog.com/2018/05/duplex-ai-system-for-natural-conversation.html) blogpost from Google about a similar thing.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
