### ISSUE TITLE
IRC bridge?

### ISSUE THREAD

**Issue by ftyers** [MycroftAI/mycroft-core#1139]
IRC is very popular among open-source/free software types, perhaps an IRC-to-mattermost bridge[1] could be installed to allow people in `#mycroft` on `irc.freenode.net` and the main chat to communicate?

1. https://github.com/42wim/matterbridge

**Comment by ftyers** [comment]
Any news on this?

**Comment by forslund** [comment]
Not really, I'll be looking into it. Would be fun connecting the old `#mycroft` on freenode.

**Comment by ftyers** [comment]
Thanks @forslund ! I'm mostly on IRC, and don't like webchats so it's a bit of a barrier to my participation in the community. I saw that you guys gave one of my students great help yesterday on the chat so am eager to be able to participate! (via IRC) :)

**Comment by ftyers** [comment]
It's now up and running for the languages channel: ` #mycroft-languages ` on freenode. There are some issues with the main `#mycroft` channel, i think because it is closed to unregistered users or something. Anyway, would be happy if anyone knew how to fix it.

**Comment by forslund** [comment]
I gave this a shot last week but I got stopped by the multi factor authentication. I've asked for support but haven't gotten an answer yet

**Comment by forslund** [comment]
Ok got an answer and the MFA isn't supported so it doesn't seem possible :/

**Comment by forslund** [comment]
Ok, I created a new user and I think I may have gotten it working

**Comment by ftyers** [comment]
@forslund it seems like I've got it working (user "zubia" on mattermost and "zubiak" on freenode)

**Comment by krisgesling** [comment]
Just closing a very old issue. No further action seems needed here.
