### ISSUE TITLE
No audio on ubuntu trusty desktop install

### ISSUE THREAD

**Issue by sigmonsays** [MycroftAI/mycroft-core#1141]
I am attempting to run mycroft on my desktop and it is not working correctly. My expectation is that I can issue commands in the CLI and hear responses. For instance if I type "say Hello" then I should hear hello spoken.

After a lot of debugging it seems to be a problem with how mimic is being invoked. It *seems* like the wav files are not being generated (or being deleted later) or the pho files are missing. 

I am running ubuntu trusty, python version 2.7. I have attempted running mycroft master branch (release/v0.9.0-19-g7e660bc) and also the release-v0.8.22 branch and nothing seems to work.

I have gone into the code and put various debug statements into the tts mimic handler to see what commands it executes. When I run the commands manually they properly create .wav files and .pho files in /tmp/mycroft/cache/tts. What is weird though is these files are disappearing, and I suspect it is happening after they are generated. If I chattr +i the files they can not be deleted, and I see stack traces showing the cache clean function is being called. Is it possible these files are being deleted from the cache too soon?

What I have proven though is everything is "working" -- if I generate a wav/pho file and log the file name written to disk, I can chattr both files. This means mycroft can't delete the files. So.. when I issue "say Hello" its the same hash (ie /tmp/mycroft/cache/tts/04af779804e578a145250c722cbfddef.pho) and i actually hear Hello spoken. However this required a lot of manual trickery and log watching. 

Unfortunately due to the async nature of mycroft I do not have the time to invest debugging it fully. I lost the flow after it started putting talk messages into queues.

**Comment by forslund** [comment]
It could be possible. The cache is pruned if the remaining disk space on the tmp partition is too low. Too low in this case is < 5% free space.

Could that be it?

**Comment by sigmonsays** [comment]
That is questionable logic. I have 99% used on root (where /tmp is) but root is a 225G mount and 1% is 2.6G free, more than enough space. What is the function called? 

I will go look later and disable that behavior, unless there is a configuration parameter.

**Comment by forslund** [comment]
Yes, I can see the issue here.

Called from here:
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/tts/__init__.py#L241

The function is located here:
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/__init__.py#L158

**Comment by sigmonsays** [comment]
appreciate it, this is what was causing my issue. I cleaned up my hard drive to drop above 5% free and everything works now. 

In terms of the bad logic, treating 5% free as a cleanup threshold seems wrong (5% of 1TB drive is a lot of space). Second, the real underlying issue is how a cleanup routine can delete a file from cache before it is being used. Perhaps it makes sense to update the curate_cache function to check timestamps of files and not delete them if they are under an age threshold.

Thanks

**Comment by forslund** [comment]
I will take all three things in consideration and give it a go tomorrow.
