### ISSUE TITLE
Verify wake word configuration

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1144]
Rather than letting parameters pass to Pocketsphinx and crash with New Decoder returned -1, it should catch the exception and apply default parameters if invalid.

**Comment by highjinx411** [comment]
I also think the hotword factory is not processing correct config files.  I was going to create some unit tests around this. . I could probably do this one maybe.. Just to see how it all goes..

**Comment by forslund** [comment]
Hi @highjinx411, this particular issue was resolved by #1170 if I've understood everything correctly.

We are however very happy to get more unittests and/or bugreports
