### ISSUE TITLE
dev_setup.sh fails during build

### ISSUE THREAD

**Issue by Clifspeare** [MycroftAI/mycroft-core#115]
OS: Archlinux
date repo cloned: Jun 8, 16
I ensured that all necessary packages mentioned in docs were installed.

http://pastebin.com/0nnNLsFp

**Comment by Clifspeare** [comment]
Hmm.  I ran the build_host_setup on my kubuntu system and it ran.  Maybe I'm just missing a package on Arch?

**Comment by aatchison** [comment]
Unfourtunatly, build_host_setup.sh is apt-centric.

**Comment by aatchison** [comment]
Ahh, sorry. I misread that.

**Comment by ethanaward** [comment]
Was this ever solved?

**Comment by cgtopher** [comment]
Same happening on Fedora 23. Verified all req. software was install per the docs. It looks like it's related to gcc according to the error I'm getting. 

`gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
`

**Comment by aatchison** [comment]
Is python-dev installed?

**Comment by clusterfudge** [comment]
@cgtopher the lack of ffi.h suggests you do not have the libffi development headers installed, which would be the libffi-devel package in the fedora repos. libffi-dev is listed [here](https://github.com/MycroftAI/mycroft-core/blob/master/build_host_setup.sh#L13). You should review the build_host_setup.sh script again to make sure you have all of the dependencies installed.

**Comment by aatchison** [comment]
Until we have more operating specific instructions, I'm closing this issue.
