### ISSUE TITLE
Fails to install jdk 7 from oracle 

### ISSUE THREAD

**Issue by ericalbers** [MycroftAI/mycroft-core#1158]
Ubuntu version 16,04.3 LTS  xenial
on bash dev_setup.sh I get a
Error 404 not found
download failed
Oracle JDK 7 is NOT installed

Are you SURE its possible to install the JDK this way?

**Comment by forslund** [comment]
Hi, Thanks for reporting.

I'm not quite sure which part of the dev-setup would do this. Is this during package install (right after the text "Installing packages" or when `pip` starts downloading the python packages?

**Comment by ericalbers** [comment]
Heres a redirect of running dev_setup.sh

Installing packages...
Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.69-9).
automake is already the newest version (1:1.15-4ubuntu1).
bison is already the newest version (2:3.0.4.dfsg-1).
libffi-dev is already the newest version (3.2.1-4).
libjpeg-dev is already the newest version (8c-2ubuntu8).
libtool is already the newest version (2.4.6-0.1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
portaudio19-dev is already the newest version (19+svn20140130-1build1).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
python-gobject-dev is already the newest version (3.20.0-0ubuntu1).
python-setuptools is already the newest version (20.7.0-1).
screen is already the newest version (4.3.1-2build1).
flac is already the newest version (1.3.1-4).
libfann-dev is already the newest version (2.2.0+ds-2).
mpg123 is already the newest version (1.22.4-1).
s3cmd is already the newest version (1.6.1-1).
swig is already the newest version (3.0.8-0ubuntu3).
virtualenvwrapper is already the newest version (4.3.1-2).
curl is already the newest version (7.47.0-1ubuntu2.3).
git is already the newest version (1:2.7.4-0ubuntu1.3).
libglib2.0-dev is already the newest version (2.48.2-0ubuntu1).
libicu-dev is already the newest version (55.1-7ubuntu0.2).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.8).
python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
The following packages were automatically installed and are no longer required:
  ca-certificates-java libice-dev libpthread-stubs0-dev libsm-dev libx11-dev
  libx11-doc libxau-dev libxcb1-dev libxdmcp-dev libxt-dev
  linux-headers-4.4.0-93 linux-headers-4.4.0-93-generic linux-headers-4.4.0-96
  linux-headers-4.4.0-96-generic linux-image-4.10.0-28-generic
  linux-image-4.10.0-33-generic linux-image-4.4.0-93-generic
  linux-image-4.4.0-96-generic linux-image-extra-4.10.0-28-generic
  linux-image-extra-4.10.0-33-generic linux-image-extra-4.4.0-93-generic
  linux-image-extra-4.4.0-96-generic linux-signed-image-4.10.0-28-generic
  linux-signed-image-4.10.0-33-generic x11proto-core-dev x11proto-input-dev
  x11proto-kb-dev xorg-sgml-doctools xtrans-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
Downloading Oracle Java 7...
--2017-10-16 04:47:56--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 209.91.151.14, 209.91.151.8
Connecting to download.oracle.com (download.oracle.com)|209.91.151.14|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz [following]
--2017-10-16 04:47:56--  https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 104.93.179.190, 2600:140a:0:382::2d3e, 2600:140a:0:38c::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|104.93.179.190|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1508143796_9b1d55a9d3c9c2f6ba7a5dbcf95f2453 [following]
--2017-10-16 04:47:56--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1508143796_9b1d55a9d3c9c2f6ba7a5dbcf95f2453
Connecting to download.oracle.com (download.oracle.com)|209.91.151.14|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-16 04:47:58 ERROR 404: Not Found.

download failed
Oracle JDK 7 is NOT installed.
dpkg: error processing package oracle-java7-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java7-installer

**Comment by forslund** [comment]
Ok, seems like it's a systems package trying to install java.

Try doing 
```
sudo apt-get update
sudo apt-get autoremove
```

and then rerun the dev setup script

**Comment by ericalbers** [comment]
It appears Oracle has moved the installer, and now requires acceptance of license terms, making a script install impossible??

**Comment by forslund** [comment]
Seems like it's been moved but that should be taken care of by apt and you should be able to accept the license manually when running the script.

**Comment by ericalbers** [comment]
hmmm, sudo apt-get autoremove ends similarly...

Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up oracle-java7-installer (7u80+7u60arm-0~webupd8~1) ...
Downloading Oracle Java 7...
--2017-10-16 05:03:28--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 209.91.151.8, 209.91.151.14
Connecting to download.oracle.com (download.oracle.com)|209.91.151.8|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz [following]
--2017-10-16 05:03:28--  https://edelivery.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 104.93.179.190, 2600:140a:0:38c::2d3e, 2600:140a:0:382::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|104.93.179.190|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1508144729_89d5e2aa56de08db8949eb76701a7a02 [following]
--2017-10-16 05:03:29--  http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz?AuthParam=1508144729_89d5e2aa56de08db8949eb76701a7a02
Connecting to download.oracle.com (download.oracle.com)|209.91.151.8|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-16 05:03:29 ERROR 404: Not Found.

download failed
Oracle JDK 7 is NOT installed.
dpkg: error processing package oracle-java7-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java7-installer

**Comment by forslund** [comment]
I've checked my bare mycroft install and it doesn't seem like any of mycroft's requirements pulls in the java package.

Looking at the output above you may have half-installed some java application before and apt is in some weird state.

**Comment by ericalbers** [comment]
I have downloaded the jdk 9 gz file from oracle, but they have not given any installation instructions, its not a dpkg etc.  Not sure if that would help

**Comment by forslund** [comment]
Can this be of help: https://askubuntu.com/questions/173654/trying-to-install-java-jdk-every-time-i-install-remove-anything

**Comment by ericalbers** [comment]
I'll try a purge on apt-get

**Comment by ericalbers** [comment]
ok for the record, if others have this issue, purging seems to have worked (its downloading and apparently installing now in the dev_setup.sh

sudo apt-get purge oracle-java7-installer
sudo apt-get autoremove
sudo apt-get install -f

After doing those commands the install script appears to be moving forward, will update if it fails.

**Comment by ericalbers** [comment]
Thanks for the help!

**Comment by forslund** [comment]
Glad to be of service!

**Comment by forslund** [comment]
Hi any follow up errors? Can we close this issue?

**Comment by junkericalbers** [comment]
Nope, all working, can close, don't see a way to do it myself

**Comment by forslund** [comment]
Different user? OK closing!
