### ISSUE TITLE
Mycroft gives me 3 registration codes at the same time

### ISSUE THREAD

**Issue by mghoffmann** [MycroftAI/mycroft-core#1163]
I just re-flashed the SD card on my Mark 1, and when I boot him up, nothing happens until I say "Hey, Mycroft" (no response to the head button). He responds to the wake phrase, but his response to anything I say after that is that he's connected to the internet and needs to be registered. This is normal I'm guessing, but he's flashing 3 different 6-digit codes on his display and then reading them all over each other, one letter at a time, with the codes all jumbled up. I tried registering with the 3rd code he gave me, and it seemed to work, but then he didn't respond to anything I said, and the head button still does nothing.

**Comment by KathyReid** [comment]
Hi @mghoffmann, thanks for reporting this. Is the Mark 1 still in this state?

**Comment by mghoffmann** [comment]
Yes, it is. I haven't changed anything.

**Comment by MatthewScholefield** [comment]
@mghoffmann Try flashing [this new image](https://mycroft.ai/to/mark-1-image) we just released. The previous image was very old and had a lot of problems.

**Comment by forslund** [comment]
@mghoffmann Do you still see these issues we've updated the pairing procedure quite heavily and it should be much more stable now.

**Comment by mghoffmann** [comment]
I just updated, and this issue is gone for me. I registered with no issues. I'm having [another issue](https://github.com/MycroftAI/mycroft-core/issues/1385) now, but this one seems to be fixed.

**Comment by forslund** [comment]
Closing this one as resolved.
