### ISSUE TITLE
Install error on pine64 Ubuntu 16.04.2 LTS 

### ISSUE THREAD

**Issue by gaerank** [MycroftAI/mycroft-core#1171]
Hello?
I've just try install Mycroft on Pine64 and got error as below.
please let me know how to fix it and how to complete the installation.

Thank you.

ubuntu@pine64:~/mycroft-core$ bash dev_setup.sh 

... few hours later

checking build system type... ./config.guess: unable to guess system type

This script, last modified 2009-12-30, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2009-12-30

uname -m = aarch64
uname -r = 3.10.104
uname -s = Linux
uname -v = #13 SMP PREEMPT Mon Dec 12 15:00:06 MYT 2016

/usr/bin/uname -p = 
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 3.10.104
UNAME_SYSTEM  = Linux
UNAME_VERSION = #13 SMP PREEMPT Mon Dec 12 15:00:06 MYT 2016
configure: error: cannot guess build type; you must specify one
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
ubuntu@pine64:~/mycroft-core$ 
ubuntu@pine64:~/mycroft-core$

**Comment by el-tocino** [comment]
Guessing you've gotten past this since it's closed, but if not I can try loading the current version onto my pine.

**Comment by jorritsmit** [comment]
how was this resolved? i have the same issue.. it seems pygtk is using old config.guess files

**Comment by el-tocino** [comment]
Doesn't say how, the original poster closed it themselves.
