### ISSUE TITLE
NeonGecko features

### ISSUE THREAD

**Issue by GuyDaniels** [MycroftAI/mycroft-core#1190]
Our changes are almost entirely in mycroft/client/speech:
- optional local STT,
- optional multiple wake words, 
- use of grammar (jsgf) files, 
- skip-wake-words option for almost continuous recording.
- optional transcription and audio file saving

**Comment by forslund** [comment]
Since the PR was closed and no further work has been done on this as far as I've seen I'll close this Issue.
