### ISSUE TITLE
Calling the pause() function does not pause the playback

### ISSUE THREAD

**Issue by akailash** [MycroftAI/mycroft-core#1194]
This [pause() function](https://github.com/MycroftAI/mycroft-core/blob/a9d627c979b98053719200c6084f3b31a9a97c62/mycroft/skills/audioservice.py#L83) does not have the desired effect of pausing the playback. 
`self.emitter.emit(Message('mycroft.sudio.service.stop'))`
This stops the playback, but the Audioservice does not expose a stop function. I could make the commit to add the stop() function if agreed upon.

**Comment by forslund** [comment]
The pause method is not supported by all backends, for example mpg123 doesn't support it but if the vlc backend is selected as default it will work. (The vlc backend should be set as default, it's tested well enough now)

Adding stop to the interface is a good idea, I'd be happy to accept a PR with this :)

The stop signal is currently tied to the the global stop (writing `stop` in cli or pressing the button on top of the mark-1), a message bus `mycroft.audio.service.stop` exists to handle it so it would be good to have that added to the interface.

**Comment by akailash** [comment]
Thanks for the explanation. I was using mpg123. Please review PR submitted for the stop interface.
