### ISSUE TITLE
Fix client/speech/listener.reload()

### ISSUE THREAD

**Issue by GuyDaniels** [MycroftAI/mycroft-core#1208]
Two things:
   1. I couldn't get it to work.  The speech client would just hang.  I played around with it, but gave up.  Given I'm a bit new to python, I approached it differently by going out to the shell and restarting the speech client there -- but more on that in the upcoming PR...
  2. There's no external access to the function.  I want to be able to reload from a skill.  In the PR I added listeners for running reload().

**Comment by forslund** [comment]
I'm pretty sure this is working, since there's been no communication here for 18 months I'm going to close this issue. If you still have issues feel free to reopen and we'll investigate further.
