### ISSUE TITLE
Architecture improvement - separation of concerns (data and skills)

### ISSUE THREAD

**Issue by theCalcaholic** [MycroftAI/mycroft-core#1214]
## Idea

Currently, the modularity of Mycroft boils down to installing different skills. However, I think it would be greatly beneficial to separate between data provider and skill modules. Therefore I propose the following architecture, inspired by agent oriented systems.

## Architecture
Additionally to skill modules which register intents at the core, there would be data provider modules which register data sources/data services (the latter could allow skills to store data, the former only allows requests). Every service is also a source. 
A skill which requires a certain kind of data would now ask the core for available services which provide that kind of data (by source id) and get data from them (either in order of precedence or from all available services, depending on the use case).
A skill could also ask the core to store data of a certain type and receive a list of valid service. 

## Example
Let's say we have a music player skill which let's a user play a song by name. It would ask mycroft-core for services providing the source 'music' and get 3 installed services: 'samba' (which searches a samba server for music files) , 'spotify' and 'soundcloud'. The skill would now request the song name from each of the services and play the best match, prioritizing the 'samba' source (based on a priority value set on registration of the service). 
Alternatively, the user could ask for a specific source, e. g. 'play Darude Sandstorm from Youtube' and the skill could fuzzy-search for a matching service. 

## Benefits
* Skills can be agnostic towards the source of the data
* A permission system controlling access to certain data sources for different skills could easily be implemented
* Avoids multiple implementations of the same requests (for different skills using the same data)
* Enables skills to share data (e. g. contacts for different messaging skills)
* Services/Sources could be managed similar to skills (e. g. by msm)

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
