### ISSUE TITLE
configuration update error

### ISSUE THREAD

**Issue by ToeiRei** [MycroftAI/mycroft-core#1220]
I was trying to sync the configuration, which failed.

debug log says:

```
19:06:11.697 - mycroft.skills.core:wrapper:371 - ERROR - An error occurred while processing a request in ConfigurationSkill
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.1-py2.7.egg/mycroft/skills/core.py", line 358, in wrapper
handler(message)
File "/opt/mycroft/skills/skill-configuration/__init__.py", line 46, in handle_update_intent
if self.update():
File "/opt/mycroft/skills/skill-configuration/__init__.py", line 66, in update
config["location"] = location
TypeError: 'NoneType' object does not support item assignment
```

**Comment by ToeiRei** [comment]
So far it looks like it's caused by a server reply which has to do something with the location.

**Comment by forslund** [comment]
Hey, sorry for the loooooong reply time. We believe the underlying issue has been fixed (since a couple of minutes) but your account need to have some data regenerated. If you send the e-mail address connected with your account to ake.forslund@mycroft.ai I'll make sure the account gets fixed.

**Comment by forslund** [comment]
Hi @ToeiRei, since there's been no communication around this I'm closing the issue since the underlying cause has been found and fixed. If you're still having issues with this, please reopen this issue and we try to figure it out.
