### ISSUE TITLE
Adding Italiano

### ISSUE THREAD

**Issue by piretro999** [MycroftAI/mycroft-core#1224]
Hello I am starting to translate some commands in openhab, domoticz, and other modules of mycroft in italian.
Can you please add this possibility to your code?
Thank you.

**Comment by penrods** [comment]
You are able to translate mycroft-core and skills already.  Here are some examples of doing translations:

Translating strings in mycroft-core to French:
https://github.com/MycroftAI/mycroft-core/pull/1011

Translating a specific skill to German:
https://github.com/MycroftAI/skill-pairing/pull/19


Does this give you enough info to get going?

**Comment by forslund** [comment]
There are now basic translations for italian in core and the [translate.mycroft.ai](https://translate.mycroft.ai) has quite a bit of strings translated already so I'm closing this. You're very welcome to join the translation effort!

Closing this issue.
