### ISSUE TITLE
Unable to Pair Mycroft

### ISSUE THREAD

**Issue by oddsage** [MycroftAI/mycroft-core#1228]
Hi
I am really struggling to get going with Mycroft and cannot seem to get anywhere with pairing the device.
I have installed the latest version in a Pi 3 with a usb combined microphone/speaker.  After fumbling around in the dark I believe I have a working configuration.   When I say hey mycroft - it hears but makes no sound!

20:06:16.598 - mycroft.client.speech.mic:listen:492 - DEBUG - Waiting for wake word...
20:06:17.011 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/stt?lang=en-US&limit=1 HTTP/1.1" 401 38
20:06:17.029 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
20:06:17.730 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
20:06:17.798 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
20:06:18.964 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/stt?lang=en-US&limit=1 HTTP/1.1" 401 38
20:06:18.989 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
20:06:24.746 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
20:06:24.761 - mycroft.client.speech.listener:transcribe:153 - WARNING - Access Denied at mycroft.ai
20:06:24.764 - mycroft.client.speech.main:handle_utterance:55 - INFO - Utterance: ['pair my device']

When I use the command line - speak "text" I can hear it.
But that is far as I can get, I have tried reinstalling this several times now.
I have googled this and the skills appear to be there.
How do I get the pairing code ????

**Comment by forslund** [comment]
Hi,

Firstly a couple of basic questions:
Are you using a git clone installation on the Pi or a Picroft installation?

If you're running a git clone installation are you on Jessie or Stretch?

When you say "Hey mycroft" do you hear a chime?

Can you play audio with `mpg123 "http://remix.kwed.org/files/RKOfiles/Chronblom%20-%20Bomb%20Jack%20subtune%206%20(violin%20version).mp3"`

From the logs you're posting it looks like the voice is picked up correctly (as you said), can you verify that the skills exist in `/opt/mycroft/skills/` (for pairing the most critical is _skill-pairing_). The default skills are downloaded at first startup and will take a couple of minutes until finished.

For mycroft voice and *.wav playback we're using paplay and that might not be available on Rasbian Stretch by default. and installation or reconfiguration of Mycroft to use *aplay* might be necessary.

**Comment by penrods** [comment]
To be clear, when you say you installed the latest version do you mean you are using the Picroft image from https://mycroft.ai/to/picroft-image?

When mycroft comes up you should be prompted to visit https://home.mycroft.ai, where you can either login in or create a new account, then click on the Devices tab and "Add Device" where you can enter the spoken pairing code (something like "A2B4CR").  After that, Mycroft should confirm that the pairing process succeeded.

**Comment by oddsage** [comment]
Hi
I am using the picroft image.
When I say "hey mycroft" I  more often that not hear the 'chime' but not always.
When I reboot it did once say 'rebooting'.
When I use 'speak' it says what I typed.
At no time has it spoken the pairing code.
I cannot do the play mp3 test until I get home later.

**Comment by oddsage** [comment]
forslund, I  did the wav test and yes that plays fine
So to recap
It responds to "hey mycroft" and prints the text ending in ['pair my device'] but i hear no sound or chime.
I can type 'speak "text" ' and that plays fine also.
I didn't realise I was going to need a masters degree to get this working, does it really have to be this hard to setup ?

**Comment by forslund** [comment]
For the picroft the hard part is usually if the mic gives you trouble. (Which does not seem to be the case here)

Here all parts seem working but pairing doesn't work.

What if you type `pair my device` in the cli?

It feels like the pairing skill is broken some how. Can you post /var/log/mycroft/mycroft-skills.log

Or you could try to reimage the device :/

**Comment by augustnmonteiro** [comment]
@oddsage did the `pair my device` worked?

**Comment by forslund** [comment]
Hi @oddsage, as there has been no communication in quite a while I'm assuming the issue was resolved or you moved on. In either case I'm closing this issue (but if it's the second case I'm a bit sad and hope you'll give us another shot in the future)
