### ISSUE TITLE
Sounds to indicate processing and finished listening

### ISSUE THREAD

**Issue by bhargavgv** [MycroftAI/mycroft-core#1237]
When I say "Hey Mycroft", I hear a sound, but I don't hear a sound when it has finished listening and is processing the command. I think it would be helpful if this was added, sort of like [Cortana](https://youtu.be/r-4yNMSNGV4?t=30s).

**Comment by penrods** [comment]
I totally agree that there should be an audible "working" sound -- the equivalent of the hourglass on a GUI system.  I'm planning on implementing that to kick in if a skill takes more than a short time (0.5 secs or so) to respond.  There is some infrastructure needed to make that happen.

Thanks for the feedback!

**Comment by JarbasAl** [comment]
star trek spaceship sounds come to mind, then we start making sound packs for mycroft :)

**Comment by penrods** [comment]
Pew pew!

**Comment by ftyers** [comment]
#1138 is related to this.

**Comment by krisgesling** [comment]
Hey, just going through old issues and in case anyone is looking for this I made a Skill to add an end listening sound a little while ago:
https://github.com/MycroftAI/mycroft-skills/pull/1158

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
