### ISSUE TITLE
Mycroft core breaks Python installation on debian

### ISSUE THREAD

**Issue by michalzubkowicz** [MycroftAI/mycroft-core#1238]
It installs /usr/local/bin python2.7 and there is 2 installations of python on one system because of that. After removing Mycroft core everything backs to normal

**Comment by penrods** [comment]
This seems very odd.  Can you please provide more details?  For example:
- Machine type (Raspberry Pi, desktop, etc.)
- What OS  and OS version?
- How you installed (Debian package, Github install, other?)

Thanks, these details will help figure out what happened!

**Comment by michalzubkowicz** [comment]
Desktop PC,  Debian Stretch 9, Debian Package

I've installed it from repo:
http://repo.mycroft.ai/repos/apt/debian

During install mycroft-core puts python2.7 under /usr/local/bin and it's shadows default python installation. I've found that it's mycroft-core file by doing  dpkg -S /usr/local/bin/python.27. 

After uninstall everything was back to normal

**Comment by penrods** [comment]
On a desktop, you should use the Github install.  As it stands the debian package is really geared for Mark 1 or other Raspberry Pi installation (e.g. Picroft).  It does things like creating root system cron jobs that you likely don't want done on your desktop.

**Comment by penrods** [comment]
See:  https://github.com/MycroftAI/mycroft-core#getting-started

**Comment by michalzubkowicz** [comment]
Maybe I've followed wrong instructions. 
https://askubuntu.com/questions/796274/mycroft-on-desktop-how
There is a dead link also so maybe instructions changed.
