### ISSUE TITLE
add support in Mycroft-core to use proxy (configuration parameters to use proxy in Mycroft's config file or scripts)

### ISSUE THREAD

**Issue by yannick56** [MycroftAI/mycroft-core#1245]
Hello,

Can you add Mycroft's configuration parameters to use proxy in mycroft.conf file and/or scripts ?

I use the latest Mycroft-core source code in git repo.
Without proxy , I can ask question by cli by using the following commands:
./start-mycroft.sh all
./start-mycroft.sh cli

But if I want to use Mycroft-core behind a proxy, it does not work.
I try to use Mycroft with a proxy like this:
export http_proxy=http://proxy_hostname.com:8080
export https_port=http://proxy_hostname.com:8080 
./start-mycroft.sh all
./start-mycroft.sh cli

In the cli tool, I have the following error:
00:24:56.519 - root - DEBUG - Connecting proxy...
00:24:56.524 - mycroft.messagebus.client.ws:on_error:70 - ERROR - Exception("Uncaught 'error' event.",)
00:24:56.525 - mycroft.messagebus.client.ws:on_error:71 - WARNING - WS Client will reconnect in 20 seconds.

Then can you add proxy support In Mycroft-core to use Mycroft's configuration parameters for proxy in mycroft.conf file and/or scripts ?
In one location, it will better.
Do you have a workaround for this problem ?

Best regards. 

Thank you for your help

**Comment by forslund** [comment]
I'm not very good at proxy-related-things but it seems I can get around it by excluding 0.0.0.0 from proxy by editing [mycroft/messagebus/client/ws.py Line113](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/messagebus/client/ws.py#L113) and replace it with

```python
ws.run_forever(http_no_proxy=['http://0.0.0.0'])
```

This means that the ws connections don't use the proxy at all. Is this acceptable behavior?

**Comment by forslund** [comment]
Ok I take it back. It's not quite this simple

**Comment by forslund** [comment]
Try this in the command line:
`export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,0.0.0.0"`

**Comment by yannick56** [comment]
@forslund 

Hello,

1)
>Try this in the command line:
>export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,0.0.0.0"
IT WORKS !
Thank you

2)
For https://github.com/MycroftAI/mycroft-core/issues/1245#issuecomment-346363199
Yes I think that the file mycroft/messagebus/client/ws.py Line113 need a change ,
maybe add the line ws.run_forever(http_no_proxy=...) for all these values: localhost,127.0.0.1,localaddress,.localdomain.com,0.0.0.0 ?

3)
And the file https://github.com/MycroftAI/mycroft-core/blob/dev/README.md need the following lines
"
if you are behind a proxy without authentication, add the following environment variables:
export http_proxy=http://proxy_hostname.com:proxy_port
export https_port=http://proxy_hostname.com:proxy_port
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,0.0.0.0"
and
if you are behind a proxy with authentication, add the following environment variables:
export http_proxy=http://user:password@proxy_hostname.com:proxy_port
export https_port=http://user:password@proxy_hostname.com:proxy_port
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,0.0.0.0"
"

**Comment by forslund** [comment]
Wooooo! Nice!

I tried number 2 and did not get it to work directly. I'll do some more research to see if I can figure out the format and get these settings into the config.

In the mean time we'll proceed with number 3. Ping @KathyReid, can you see if this can be added to the documentation and/or the readme here?

**Comment by KathyReid** [comment]
On it
