### ISSUE TITLE
Patch for mycroft-core : patch to add support for Mageia Linux in dev_setup.sh script

### ISSUE THREAD

**Issue by yleny-dev** [MycroftAI/mycroft-core#1267]
Hello,

Can you patch the file dev_setup.sh in the mycroft-core git repositery to add support for Mageia Linux ?
Mageia Linux (https://en.wikipedia.org/wiki/Mageia )

[add_mageia_support_in_dev_setup.sh.patch.txt](https://github.com/MycroftAI/mycroft-core/files/1511509/add_mageia_support_in_dev_setup.sh.patch.txt)

Thank you

**Comment by MatthewScholefield** [comment]
Thank you for this. Would you mind submitting a pull request for this? An easy way to do it would be to click the edit button [here on the file on GitHub](https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh) which will set some things up and create a PR.

**Comment by forslund** [comment]
Hi, I believe this is outdated now so I'm closing it. Thank you for your work, we'd love to have a PR with an updated version for the python3 environment we're running now!
