### ISSUE TITLE
mycroft-core : mycroft cli does not display the accented characters

### ISSUE THREAD

**Issue by yleny-dev** [MycroftAI/mycroft-core#1268]
Hello,

I'm working on french translation for all the mycroft-core official skills installed by default in the folder /opt/mycroft/skills/.
For example, I have translated all the *.dialog and .voc files for skill-hello-world.
espeak speak correctly in french the sentences and word in the french translation.
Translation files use UTF-8 without BOM for encoding.
For the system environment variables, I have:
$ env | grep LANG
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR.UTF-8:fr 
mycroft cli started by the command line ./start-mycroft.sh cli

My problem is that when espeak speak correctly in french the sentence "Bonjour à vous aussi" with all the words, mycroft cli display only:
>>"Bonjour   vous aussi"

The "à" letter is missing in the Mycroft cli

Can you fix this problem ?

**Comment by penrods** [comment]
I'm guessing we will have to wait until we make the jump to Python 3, which should be in the next couple months.

For reference, I'm linking to this message.  I attempted using locale and then calling locale.setlocale() as used in their example, but that wasn't adequate.  I think Unicode support will be needed.

**Comment by yleny-dev** [comment]
> I'm guessing we will have to wait until we make the jump to Python 3, 
Because of: http://lucumr.pocoo.org/2013/7/2/the-updated-guide-to-unicode/ ?

> which should be in the next couple months.
Bad news, it will be more harder for me to test skills translated in french in the Mycroft cli.
Maybe I will need to write *.dialog and .voc files for skills without accented characters for testing and next add accented characters for commit in git repositeries.
No tips in this document to use accented characters with python 2.7: 
https://docs.python.org/2/howto/unicode.html ?

**Comment by forslund** [comment]
Feel free to try out #1273, it may be a bit of a hack but works for me.

**Comment by forslund** [comment]
Thanks for testing @yleny-dev. I pushed an update to it (7502e1025d3b226c6738cfd6c8b04a1cd43658c5) earlier today.

This fixes the crash @penrods reported in #1273. Not sure it's the same you're experiencing though. I'll keep testing and trying to provoke a crash.

**Comment by yleny-dev** [comment]
@penrods and @forslund 

The 2 patchs: 
Attempt to allow CLI to display utf-8 encoded text. 
https://github.com/MycroftAI/mycroft-core/commit/8254c1778cdf9fd82ecd09f34bc5707a9ca573a2
and
Replace open with more modern io.open 
https://github.com/MycroftAI/mycroft-core/commit/7502e1025d3b226c6738cfd6c8b04a1cd43658c5
from the ticket
https://github.com/MycroftAI/mycroft-core/pull/1273
fix my problem with accented characters in Mycroft cli.
Now I can see the "à" letter in the sentence in french "Bonjour à vous aussi".
And no mycroft CLI crash.

**Comment by forslund** [comment]
Sounds good, please tell me if you bump into more issues and I'll try to tackle them!
