### ISSUE TITLE
mycroft-skills : french translation for the hello-world-skill 

### ISSUE THREAD

**Issue by yleny-dev** [MycroftAI/mycroft-core#1269]
Hello,

All the files for the french translation for the hello-world-skill.
https://github.com/mycroftai/skill-hello-world/

For the README.md file for this skill,
one README.md by language like README-language_suffix_2_letters.md like README-FR.md for french
or
one README.md file with usage for several languages in this file, then form at http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html need changes ?

Can you commit these files in the git repo ?

[skill-hello-world-french-patch.tar.gz](https://github.com/MycroftAI/mycroft-core/files/1511671/skill-hello-world-french-patch.tar.gz)

PS : I have 7 others skills translated in french but I need to test them.

**Comment by penrods** [comment]
First, @yleny-dev, thanks for tackling this!

Can you please submit your changes as a PR directly to the repo containing the skill?  Then we can pull it in there.  And one more thing:

To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any code contribution. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by yleny-dev** [comment]
@penrods
>thanks for tackling this
Steve , I spent $224.99 for a Mycroft Mark 1, then I want it in french.
But because there is no contributor, I do the job of adapting Mycroft-core and Mycroft-skills to the French language. Not an easy task...

>Can you please submit your changes as a PR directly to the repo containing the skill? Then we can >pull it in there.
Do I need to follow the steps in the document/URL below for this task ? 
https://github.com/MycroftAI/mycroft-core/blob/dev/CONTRIBUTING.md

>Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!
Done

**Comment by IsTypiNOVanS** [comment]
@yleny-dev 
I'm trying to change the mycroft language to french. I follow these (https://mycroft.ai/documentation/language-support/french/#change-the-wake-word-to-french) steps successfully but MyCroft is still in english. Are you able to help me ?

**Comment by forslund** [comment]
I'm not 100% sure about this but the `"lang": "fr"` (at the top level in the config) might be incorrect since the language files are in the directory `fr-fr`. Try using `"lang"": "fr-fr"` instead and the mycroft dialogs are.

I also believe the documentation is slightly wrong. you should probably use the `~/.mycroft/mycroft.conf` when doing this configuration instead of the default one as suggested in the docs (which may be overridden by the settings from home.mycroft.ai)

**Comment by forslund** [comment]
I'm going to close this issue. Via the https://translate.mycroft.ai platform many skills have been updated to French.

If the README translation is something you think should be tacked it may be good to open an issue in [mycroft-skills](https://github.com/mycroftai/mycroft-skills) for further discussion regarding to that point.
