### ISSUE TITLE
 Raspbian Stretch: SSL issue

### ISSUE THREAD

**Issue by esoleyman** [MycroftAI/mycroft-core#1285]
I'm seeing this error with the most recent upgrade. I have openssl, libssl-dev and the latest python 2.7 packages. I'm not sure where to go from here to debug.

```Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/opt/mycroft/enclosure/verifyArduino.py", line 32, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     import mycroft.configuration
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.7-py2.7.egg/mycroft/__init__.py", line 20, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     from mycroft.skills.core import MycroftSkill, FallbackSkill, \
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.7-py2.7.egg/mycroft/skills/core.py", line 29, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     from mycroft.client.enclosure.api import EnclosureAPI
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.7-py2.7.egg/mycroft/client/enclosure/__init__.py", line 26, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     from mycroft.client.enclosure.display_manager import \
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.7-py2.7.egg/mycroft/client/enclosure/display_manager.py", line 20, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     from mycroft.messagebus.client.ws import WebsocketClient
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.7-py2.7.egg/mycroft/messagebus/client/ws.py", line 20, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     from websocket import WebSocketApp
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/usr/local/lib/python2.7/site-packages/websocket/__init__.py", line 22, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     from ._core import *
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 39, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     from ._socket import *
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:   File "/usr/local/lib/python2.7/site-packages/websocket/_socket.py", line 28, in <module>
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]:     from ._ssl_compat import *
Dec 06 11:13:42 mark_1 mycroft-enclosure-client[543]: AttributeError: 'module' object has no attribute 'ssl'
```

**Comment by MatthewScholefield** [comment]
On StackOverflow a few people mention `source ~/.virtualenvs/mycroft/bin/activate; pip install -U pyopenssl` might solve that. See if that helps.

**Comment by tjoen** [comment]
I also tried running picroft on stretch. Even compiled my own python with ssl... But I ran into several problems. I would not recommend it at this moment.

**Comment by penrods** [comment]
Yeah, I think Stretch is just not ready for Picroft yet.

**Comment by esoleyman** [comment]
I've upgraded the Mark 1 from Jessy to Stretch and ran into this issue.


-
Emil Soleyman-Zomalan

On Dec 20, 2017 15:44, "Steve Penrod" <notifications@github.com> wrote:

Yeah, I think Stretch is just not ready for Picroft yet.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MycroftAI/mycroft-core/issues/1285#issuecomment-353191080>,
or mute the thread

**Comment by mariusrugan** [comment]
I'm experimenting installing via picroft packages on stretch on a rpi b+. 

Debian Stretch moved to OpenSSL 1.1 which has non-backward-compatible APIs to 1.0x, and was released officially somewhere mid 2017. 

Without the intent of creating a huge mess, it became so :D 
Also, there are 2 python installations,  [also referenced into a a different issue]

```
pi@picroft:/usr/share $ ls -lah /usr/local/bin/python
-rwxr-xr-x 1 mycroft mycroft 3.1M Mar 14 18:57 /usr/local/bin/python
pi@picroft:/usr/share $ /usr/local/bin/python -V
Python 2.7.9
```

and

```
pi@picroft:/usr/share $ /usr/bin/python -V
Python 2.7.13
```

so, installing Mycroft on Raspberry Pi 3 B+ **is a no go** unfortunately, without a HUGE amount of work (maintaining 2 runtime OpenSSL versions; Figuring a proper cleanup & auditing of the system ). Given the fact that Raspberry Pi 3 B+ would be THE choice for picroft-ing, what are your thoughts about this @MatthewScholefield @penrods ?

**Comment by tlc** [comment]
/usr/local/bin/python is installed from the mycroft-core package.  Why is mycroft core installing a custom python?

**Comment by tlc** [comment]
This is probably only a problem because mycroft-core installs the old python (& pip) in /usr/local/bin.

> $ /usr/bin/python -c "import ssl; print ssl.OPENSSL_VERSION"
> OpenSSL 1.1.0f  25 May 2017
> $ /usr/local/bin/python -c "import ssl; print ssl.OPENSSL_VERSION"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python2.7/ssl.py", line 98, in <module>
>     import _ssl             # if we can't import it, let the error propagate
> ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

And

> $ sudo apt-get install python-pip
> $ /usr/bin/pip install websocket-client
> $ /usr/bin/python -c "import websocket"
> $ /usr/local/bin/python -c "import websocket"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python2.7/site-packages/websocket/__init__.py", line 22, in <module>
>     from ._core import *
>   File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 39, in <module>
>     from ._socket import *
>   File "/usr/local/lib/python2.7/site-packages/websocket/_socket.py", line 28, in <module>
>     from ._ssl_compat import *
> AttributeError: 'module' object has no attribute 'ssl'

It appears that Debian Stretch and Raspian are fine.

**Comment by neongeckoinc** [comment]
Is there any update on this? Has anyone gotten Mycroft to run on a Pi 3 B+? 
@mariusrugan did you have any breakthroughs on these issues, or is it still a huge mess?

If not, what is the plan going forward?

**Comment by tlc** [comment]
I've gotten a git clone "linux install" to run on the 3B+.  As I said above, the biggest problem with the apt-get (picroft) install is that an old python is included.

I haven't built mimic yet, so it's running espeak.  A few more things had to be apt-get installed and pip installed.  

I had to build and replace precise-stream (the binary is downloaded at run time and hidden in ~/.mycroft).  See https://github.com/MycroftAI/mycroft-core/issues/1533.

**Comment by forslund** [comment]
I do think this has been resolved with the newer picroft images for Stretch. Closing this issue, if this is still a problem for you feel free to reopen the issue.
