### ISSUE TITLE
Mycroft listens on all nics by default 

### ISSUE THREAD

**Issue by the7erm** [MycroftAI/mycroft-core#131]
By default mycroft will listen on `0.0.0.0` if `service_config` is `None` or an empty string.

```python
application.listen(service_config.get("port"), service_config.get("host"))
```
https://github.com/MycroftAI/mycroft-core/blob/master/mycroft/messagebus/service/main.py#L43

This is a security issue because any device on the Lan can access the service.  This also is a problem if the user puts mycroft in a DMZ or directly on the net.

**Comment by the7erm** [comment]
Here's the main reason why I think it's a good idea to force 127.0.0.1 if it's an empty string:
http://www.securityweek.com/configuration-issue-exposes-30000-mongodb-instances-researcher

Mongodb didn't and because of it they jeopardized their reputation as well as millions of users' data. 

I figure if you're smart enough to change it to 0.0.0.0 then you know what you're doing, but the fact that an empty string defaults to this is bad from a security standpoint.

**Comment by aatchison** [comment]
Getting closer: https://github.com/MycroftAI/mycroft-core/pull/132

**Comment by aatchison** [comment]
This was merged.
