### ISSUE TITLE
Make Mycroft stop beeping all the time

### ISSUE THREAD

**Issue by JohnMH** [MycroftAI/mycroft-core#1319]
Is it possible to make Mycroft stop beeping just because it's listening, and rather have it beep when it hears the wakeup word?

**Comment by JarbasAl** [comment]
it is only supposed to listen when it hears the wakeword...

i think you may need to change the threshold to reduce false positives (thats what all the beeping is probably)

**Comment by JohnMH** [comment]
I've changed the threshold with no actual change. Any time my mic picks up any sound, it beeps.

**Comment by MatthewScholefield** [comment]
@JohnMH Make sure the listener is set to default via the voice command `change the wake word listener to the default`. Precise is still WIP and a recent regression in the models caused behavior similar to this.

**Comment by JohnMH** [comment]
@MatthewScholefield To clarify, I've tried both models, and they both have this issue on my system.

**Comment by EWouters** [comment]
I'm experiencing the same issue: "Any time my mic picks up any sound, it beeps.".

I've tried disabling the `confirm_listening`, but that disables a different beep, not the one that is very frequent and annoying.
```
// Play a beep when system begins to listen?
  "confirm_listening": false,
```

**Comment by EWouters** [comment]
I think I figured out what it was, there were some alarms or timers that had gone off in the background and were screaming for attention! I just had to "Delete all timers.".

**Comment by forslund** [comment]
I do believe the problem with the alarm has been handled. I'm closing this issue now, if the problem still persists and I'm closing this prematurely feel free to re-open it.
