### ISSUE TITLE
Wrong version of SpeechRecognition in requirements.txt

### ISSUE THREAD

**Issue by turboproc** [MycroftAI/mycroft-core#1329]
Hi,

had some difficulties in making Google Speech Cloud working with Mycroft which was, amongst other issues, related to Python Speech Recognition not being aligned with the current Google API definition.
Had to change version to "v1" and sample rate to "SampleRateHertz".

Some further investigation made clear that version 3.8.1 of Speech Recognition has this fixed. Therefore suggesting to have this changed in the file requirements.txt, i.e. from 

`SpeechRecognition==3.7.1`

to 

`SpeechRecognition==3.8.1`

**Comment by penrods** [comment]
Just verifying -- you are using "Google" as your speech to text provider in you settings, correct?

I know Google disabled an older version of their API this week, so that is likely the source.  We'll bump the SpeechRecognition version next release.  Thanks for pointing that out!

**Comment by turboproc** [comment]
Hi , using Google Cloud (as opposed to Google). Works while typing ;-)

**Comment by forslund** [comment]
Updated in #1346. Closing
