### ISSUE TITLE
Master branch commit log?

### ISSUE THREAD

**Issue by cwegener** [MycroftAI/mycroft-core#1341]
What is going on with the commit log of the master branch?

There are 8200 commits in the master branch related to 'CONTRIBUTING.md' which seem complete garbage.

The output of `git log --all --oneline` is therefore unusable.

**Comment by Cliabhach** [comment]
It's...just the same two commits, repeated over and over again, right? I think @aatchison might be able to help here.

**Comment by cwegener** [comment]
The ~8200 commits have the same content, yes. But they are still ~8200 individual commits with the same content being repeated over and over again.

**Comment by forslund** [comment]
The master commit log is a bit messed up due to the release script and the measures taken to guarantee a conflict free merge. @aatchinson and @MatthewScholefield knows the details best I think.

The default branch (i.e. dev) has the clean log history

**Comment by MatthewScholefield** [comment]
We were considering manually force synching dev to master to resolve the issue. What do you think? This would resolve the problem described above but require anyone using master to re-clone or run `git fetch && git reset --hard origin/master`, (getting rid of any changes).

**Comment by cwegener** [comment]
@MatthewScholefield I'm not a git guru. Rewinding master to the same ref as dev is the only thing I can think of too. Which should be fine, since development appears to happen in branches that are based off the dev branch.

Such rewind should still be documented somehow with a reference back to this issue ID.

Also, if the release script hasn't been fixed yet, the root cause should definitely be addressed to prevent such situation in the future.

**Comment by forslund** [comment]
The release script has been fixed.

I'm not comfortable with modifying the history on master, apart from it being annoying to anyone using the repo it would break the picroft stable updates (based on git pull).

I'm closing the issue now, if you think it should be discussed more feel free to reopen.
