### ISSUE TITLE
Raspbian audio input freeze

### ISSUE THREAD

**Issue by mikonse** [MycroftAI/mycroft-core#1348]
As described in forum posts https://community.mycroft.ai/t/speech-rec-for-mycroftpi-using-kinect/1267/7 and https://community.mycroft.ai/t/mic-just-stopped-working-weird-right-and-will-not-come-back-local-usb-or-mic-jack/2191/17 the audio input on a raspberry pi installation goes dead after a few minutes. Mycroft cannot record any more audio input and the mic level display in the cli just freezes.

It occurred to me both with a regular picroft image on a rpi3 as well as an install on raspbian stretch from the master branch of the repo with two different usb microphones. In my setup the bug is reproducable every time when starting a mycroft instance, however it does not seem to be widespread, so i don´t know what is causing it specifically.

In the code the problem originates in the MutableStream class where at some point calls to the pyaduio `stream.read()` method only result in IOErrors. IOErrors are thrown on input overflows as described in http://stackoverflow.com/questions/10733903/pyaudio-input-overflowed. The AudioProducer Thread therefore only handles those errors, no audio is processed.

This seems to be a pyaudio internal issue on the raspberry pi. 
It can however be fixed easily by passing a parameter `exception_on_overflow=False` to the pyaudio `stream.read()` method.

**Comment by forslund** [comment]
Thanks for the great detective work. I'll start testing it out and see if there seem to be any downside to using this parameter on any other device. (but it sounds quite safeso should be no worries)
