### ISSUE TITLE
no mention of docker on Linux install page 

### ISSUE THREAD

**Issue by OmgImAlexis** [MycroftAI/mycroft-core#1352]
At the bottom of the [download page](https://mycroft.ai/get-mycroft/ ) the Linux option shows `Docker` listed yet the page [it links to](https://github.com/MycroftAI/mycroft-core/blob/dev/README.md) contains nothing at all about an official Docker image or how to build the container.

![screen shot 2018-01-08 at 4 17 47 pm](https://user-images.githubusercontent.com/6525926/34660085-8beffd64-f48f-11e7-9d41-f267c959ae3e.png)

**Comment by KathyReid** [comment]
Hi there @OmgImAlexis, we've removed the reference to Docker as we don't officially support it. 
Kind regards, 
Kathy

**Comment by OmgImAlexis** [comment]
You still have a container on docker hub though?
https://hub.docker.com/r/mycroftai/docker-mycroft/

**Comment by penrods** [comment]
Sorry about the confusion with this -- that docker container was created by a community member, and they've stopped working on it.  I'll see if we can get up to speed with wherever it was left, but I honestly have never used it myself.

**Comment by OmgImAlexis** [comment]
Maybe I should open a new issue about adding proper support for Docker? Once someone has the container setup there isn't really anything that needs to be changed on the Docker side of things for future versions.
