### ISSUE TITLE
Alternative triggers.

### ISSUE THREAD

**Issue by virtadpt** [MycroftAI/mycroft-core#1357]
Is there a way to set an alternative trigger on Mycroft?  For example, let's say that I don't want a voice trigger but instead would like to use a button connected to the GPIO pins of a RasPi or a USB device plugged into a spare laptop?

**Comment by penrods** [comment]
Yes.  On a Mark 1 the button on top of the unit is dual-purpose.  It acts a a Stop command if the unit is active (e.g. playing an NPR newscast); and it will act as an alternative activation mechanism -- the equivalent of "Hey Mycroft" if not.

For some historical reasons the implementation of this is a little messy and the specific enclosure is mixed in with mycroft-core still.  But for today you can replicate this in a Skill that monitors the GPIO pins for an alternative button.

The code that manages the Mark 1 "buttonPress" signal can be seen at: 
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/enclosure/__init__.py#L91

```python
    if "mycroft.stop" in data:  # <-- This comes from the Mark 1's Arduino when the button is pushed
            if has_been_paired():
                create_signal('buttonPress')  # <-- this is what you really want
                self.ws.emit(Message("mycroft.stop"))
```

For handling a button connected to a GPIO pin, you can look at this example:
https://github.com/MycroftAI/picroft_example_skill_gpio

FYI: I will be doing something similar very soon for Picroft running on Google AIY hardware.

**Comment by forslund** [comment]
You can trigger the listening by sending a `mycroft.mic.listen` message on the bus.

`mycroft/messagebus/send.py` can be used to send a message from the command line or you can import it in a python script listening for other system events.

**Comment by forslund** [comment]
Since there's been no communication here for a while and scripts and example code for triggering mycroft from an external source exists I'm closing this issue.

**Comment by machinekoder** [comment]
This here is the best resource I found so far: https://github.com/andlo/picroft-google-aiy-voicekit-skill/blob/master/__init__.py

**Comment by forslund** [comment]
That's a very good example. There's also a simple bash script shipped with mycroft core: https://github.com/MycroftAI/mycroft-core/blob/dev/bin/mycroft-listen

**Comment by machinekoder** [comment]
@forslund Nice. Btw. do you know if the events triggered in https://github.com/MycroftAI/mycroft-messagebus-client#sending-a-message-on-the-bus are prefixed with `mycroft` or not? So could I read `mycroft.mic.listen` or `mic.listen` there?

**Comment by forslund** [comment]
There is no automatic prefixing in the mycroft-bus-client.
"speak" is a very old one so it doesn't have the `mycroft.` prefix we tried to standardize upon later. In this case you should use `mycroft.mic.listen`

Refer to the documentation for the [message types](https://github.com/MycroftAI/mycroft-core/issues/1357)

**Comment by machinekoder** [comment]
@forslund Thanks. Can I trigger the `mycroft.mic.listen` to happen with a specific skill active?

**Comment by krisgesling** [comment]
@machinekoder looks like the link was wrong in the previous message, docs are here:
https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-types#mycroft-mic-listen
It also has some brief example code to emit or listen for each message type.

Not sure what your use case is, but if you want to prompt the user from within a Skill [`self.get_response()`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html#mycroft.MycroftSkill.get_response) is the way to go.

**Comment by forslund** [comment]
Thanks for correcting that gez
