### ISSUE TITLE
Missing libfann in Arch Linux

### ISSUE THREAD

**Issue by Ceda-EI** [MycroftAI/mycroft-core#1361]
The dev-setup.sh does not include the installation of libfann on Arch Linux which is in the [AUR](https://aur.archlinux.org/packages/libfann/). 
Checked with commit: f48068a

**Comment by devinmcelheran** [comment]
I don't recommend using yaourt or pacaur for the installation, this can be unreliable for many reasons. There are many AUR repo tools, I myself use pkgbuilder, and I know others have their own preferences. They can also become outdated and incompatible with the newer pacman libraries and whatnot. What I recommend is ensuring that the build dependencies are met, then pulling down the [PKGBUILD file](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=libfann) and building/installing it so as to eliminate dependency on tools not available in the official repo.

**Comment by forslund** [comment]
Hi @Ceda-EI and @devinmcelheran,

None of the mycroft devs are arch users and don't really know best practices. Can you guys work together and agree on a good solution?

The #1362 PR handles the yaurt and pacaur as optionals so there's no requirement that these are used, but it sounds like using the PKGBUILD file method would work on any installation and might be better?

**Comment by Ceda-EI** [comment]
I will probably implement that in the next week.

**Comment by femans** [comment]
Hi, I just ran into this as well. 
I use pacaur myself, but indeed for installer script this should better download the AUR and run [makepkg](https://wiki.archlinux.org/index.php/makepkg) on it? AFAIK pacaur simply does that.

**Comment by devinmcelheran** [comment]
femans, most AUR package managers do that, but with additional dependency management, particularly installing dependencies from the AUR. The manual way would be little more than you described, simply [curl | wget]-ing the PKGBUILD file and using 'makepkg -s && pacman -U libfann_package.xz', then some cleanup.

If needed, I can implement the fix, I'll just have to find the time.

**Comment by femans** [comment]
Thanks for the explanation! I was happy enough finding here a manual fix using pacaur, didn't cost too much time.

**Comment by Ceda-EI** [comment]
Added a new pull request that installs libfann via the pkgbuild method requiring no need of an AUR Helper.
