### ISSUE TITLE
Google Calendar skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-core#137]
Would be nice to ask Mycroft for scheduled events and stuff. Also this could be maybe combined with some general combined "Report skill" for Mycroft which could at the morning for example give information regarding weather, news and scheduled events.

**Comment by ryanleesipes** [comment]
Assigned to @ChristopherRios7 to research.

**Comment by ethanaward** [comment]
Here's the Google Calendar API page: https://developers.google.com/google-apps/calendar/v3/reference/

**Comment by chrisvella** [comment]
Consider making a calendar skill which uses the CalDAV standard rather than just working with Google calendar. Perfect for people who selfhost their calendar server i.e. owncloud users.

**Comment by ryanleesipes** [comment]
@chrisvella I assume Google calendar supports CalDav? Yeah, that's fine if we can find a good library to make that really easy to write - that would be awesome.

**Comment by chrisvella** [comment]
@ryanleesipes For some reason its difficult to find information on... but I believe so. [Source](https://support.mozilla.org/en-US/questions/1097284)

**Comment by ethanaward** [comment]
Here's a [CalDAV python library](https://pypi.python.org/pypi/caldav) as well as [Google's page](https://developers.google.com/google-apps/calendar/caldav/v2/guide#connecting_to_googles_caldav_server) for using their CalDAV API.

**Comment by the7erm** [comment]
I started reading over the terms of service.
https://console.developers.google.com/tos?id=universal

> Developer credentials (such as passwords, keys, and client IDs) are intended to be used by you and identify your API Client. You will keep your credentials confidential and make reasonable efforts to prevent and discourage other API Clients from using your credentials. Developer credentials may not be embedded in open source projects.

That's an interesting clause.  I'm not sure how to handle it.  I guess all the users are going to have to create their own key.

**Comment by ethanaward** [comment]
Yeah, users are going to have to provide their own client ID and secret, I think.

**Comment by aatchison** [comment]
There are now several calendar skills in the https://github.com/MycroftAI/mycroft-skills repository.
