### ISSUE TITLE
mark 1 - deactivate mouth events not working

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#1374]
Trying to add some animations for mark1 faceplate, i saw in pairing and ip skill that to display text you call then call enclosure.mouth.text() to display text and finally in the end reactivate mouth events

this happened correctly in pairing, when adding the same functionality to display bitcoin price i noticed the mouth visemes still interrupt the scrolling text

ip address skill shows same behavior, scrolling ip address gets interrupted, when i first SSHed into the unit it worked correctly

expected behavior: when scrolling text mouth visemes would not interrupt after enclosure.deactivate_mouth_events() 

observed behavior: as soon as mycroft speaks text gets interrupted by mouth visemes

platform: this is a mark1, running 0.9.14

logs: https://pastebin.com/BHugxW6Q

code:

```
    self.enclosure.deactivate_mouth_events()
    text = price[:7] + " " + currency
    self.enclosure.mouth_text(text)

    self.speak_dialog("cryptonator.price", {"base": coin, "target":
        currency, "price": price})

    # Just show the price while still speaking
    wait_while_speaking()
    self.enclosure.activate_mouth_events()
    self.enclosure.mouth_reset()
```

**Comment by JarbasAl** [comment]
it seems that if i do it after a speak message it works, i think because it needs a call to `self.enclosure.register(self.name)`

**Comment by forslund** [comment]
@Mn0491 can you look into this you know most of how the system is designed and how it's intended to be used.

**Comment by krisgesling** [comment]
I believe this is resolved. Please reopen if I'm mistaken
