### ISSUE TITLE
Update french translation

### ISSUE THREAD

**Issue by zecakeh** [MycroftAI/mycroft-core#1376]
Hi,
I'm planning to update the french translation since it's not complete, somewhat outdated, and contains some typos/unnatural language.

I haven't seen any other open issue nor PR about that yet but stop me if I'm wrong.

I have found the following files to translate : 
- mycroft/res/text/
- mycroft/skills/time_rules.py
- mycroft/util/lang/

Are there others ?

PS: I'm waiting for the CLA mail now to sign it.

**Comment by forslund** [comment]
Hi @zecakeh, big thanks for working on this.

You should also create the `mycroft/util/lang/parse_fr.py` and `format_fr.py` and link them into `mycroft/util/format.py` and `parse.py`

I'm not sure about time_rules.py, it might be depreciated I'll look into that.

**Comment by zecakeh** [comment]
Fixed with PR #1416
