### ISSUE TITLE
MQTT skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-core#138]
As discussed on slack, to keep you developers aware that it would be cool to have so other open source home automation software could integrate with it, for example Node-red :D....Other idea would be to fork node-red or mqttwarn and integrate it into Mycroft. :) But the end result should be the same, it should spew out MQTT sentences.

**Comment by ryanleesipes** [comment]
Completely agree. I like the idea of integrating node-red, but we really need a leader who understands this to walk us through how to best do this.

**Comment by ryanleesipes** [comment]
@ChristopherRios7 please familiarize yourself with [MQTT](https://en.wikipedia.org/wiki/MQTT) at length.

[Node-Red](http://nodered.org/) uses this at length, perhaps you could have a conversation with them about this protocol.

**Comment by ryanleesipes** [comment]
@ethanaward assigned to assess this.

**Comment by marksev1** [comment]
On Youtube there are nice clips describing MQTT. This broker: http://mosquitto.org/ is popular.choice. Here is the relevant python library - https://pypi.python.org/pypi/paho-mqtt/1.1

**Comment by aatchison** [comment]
There is now an MQTT skill in the https://github.com/MycroftAI/mycroft-skills repository.

**Comment by nconder** [comment]
@aatchison where has the MQTT skill gone?
