### ISSUE TITLE
My Croft Does not seem to recognize voice input not wake word in Latest Picroft image

### ISSUE THREAD

**Issue by ghost** [MycroftAI/mycroft-core#1381]
## Be clear about the software, hardware and version you are running
* Running on a raspberry Pi 3
* Latest Picroft Image
* With the standard Wake Word

## Try to provide steps that we can use to replicate the Issue

For example: 

1. Burn the 0.9.10 image to Micro SD card using Etcher
2. Seat the Micro SD card in the RPi 3
3. Boot Picroft
4. wait for the console to come up and skills to load
5. try to speak to my croft and he does not answer or seem to acknowledge I'm talking
    - however, when I type in utterances, mycroft gives broken answers. there does not seem to be a specific wake word.

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

* I expect Mycroft to respond to the name I gave it when I added it, however, it seems to respond to anything, 
* I expect mycroft to answer "the try me out" questions correctly, it doesn
- "Who is Johnathan Davis?" returns " musis" (probably the category of the Wiki page) 
- "Who is adolft Hilter" returns "polit" 
- "What is Circa Survive" returns an accurate one-liner of the band.

* I expect to see mycroft start a recording of my "utterance", it does not
* I expect to see the mic meter move as I speak, it does not.

## Provide log files or other output to help us see the error

logs, basically /var/log/mycroft-*.log
https://box.alternativeresearch.co/cloud/index.php/s/JHb33Ld4AqpPUkz

In my Picroft image, the automatically generating a support package appears to be broken. but that's a separate issue. Just thought I would supply a heads up

## Upload any files to the Issue that will be useful in helping us to investigate

I have none other than the logs I linked to

**Comment by el-tocino** [comment]
Picroft .9.16 is out and has a bunch of fixes that might help if you haven't already upgraded.
Looks like you've tried to name it Jarvis? Did you do that in local config or on home.mycroft.ai? 
The query about Davis falls back to wolfram alpha.  Try "tell me about ...." for someone's bio next time. Same with adolf.  See the mycroft-skills.log for more on how these are handled (search for "lang" to find what it thinks it heard, then follow along for how it handles that).

**Comment by anupamnath** [comment]
Interestingly, the same version doesn't recognise the wake word using a webcam microphone!! I am not sure what could be the issue! tried to go through the config file mycroft.conf

{
  "play_wav_cmdline": "aplay -Dhw:0,0 %1",
  "play_mp3_cmdline": "mpg123 -a hw:0,0 %1",
  "enclosure": {
    "platform": "picroft",
    "update": true,
    "test": false
  },
  "tts": {
    "mimic": {
      "path": "/usr/local/bin/mimic"
    }
  },
  "ipc_path": "/ramdisk/mycroft/ipc/",
  "hotwords": {
    "hey mycroft": {
      "module": "precise"
    }
  },
  "SkillInstallerSkill": {
    "path": "/usr/local/bin/msm"
  }
}


Couldn't figure out anything from the logs either!! Any suggestions appreciated.

**Comment by forslund** [comment]
Since there has been no communication for about a year I'm closing this issue. Let me know if this is still an issue and we can reopen it on the picroft repo.
