### ISSUE TITLE
Mycroft only connects to some sites, doesn't accept ICMP

### ISSUE THREAD

**Issue by mghoffmann** [MycroftAI/mycroft-core#1385]
I suspect this may be an issue with my home network, but I don't know enough about what Mycroft is trying to do to debug it. I'm using a Mark I with mark-1_production_20171019_build-10.img flashed to it. I was able to connect Mycroft to my Wi-Fi network alright, but now when it turns on, it says it can't connect to the internet, and they eyes stay yellow. I can SSH in from another host on my internal network. When I `ping 8.8.8.8`, I get the following:

```
pi@mark_1:~ $ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 192.168.0.1 icmp_seq=3 Destination Host Unreachable
From 192.168.0.1 icmp_seq=4 Destination Host Unreachable
From 192.168.0.1 icmp_seq=5 Destination Host Unreachable
From 192.168.0.1 icmp_seq=6 Destination Host Unreachable
```

From what I can gather, this `icmp` message means that my router is trying to tell Mycroft that there's a better way to get where it's trying to go? I'm not quite sure how to set Mycroft to accept that suggestion, if that's the case.
I'm also confused because this only happens with certain external hosts, and only with Mycroft. I ran `apt update` and `apt upgrade` without any connectivity issues at all immediately after connecting to Wi-Fi. I can also ping www.mycroft.ai and some other websites without getting this message.

I don't know if it's relevant, but I'm running [Pi-Hole](https://pi-hole.net/) (a local DNS service) on my network. No other hosts on my network are having these issues though- just Mycroft.

**Comment by forslund** [comment]
Hi, this sounds a bit like the wifi-setup didn't shut down the peer-to-peer connection or something the gateway isn't configured correctly.

Can you run `ifconfig` and report which network interfaces are listed?

**Comment by mghoffmann** [comment]
I can get the exact output late tonight or tomorrow night, but I remember it listed `eth0` and `wlan0`. Only `wlan0` had an IP address, which was expected because the Ethernet was unplugged. `ifconfig` showed the correct gateway IP as well.

**Comment by forslund** [comment]
Since there is a fallback method and there's been no communication for a year I'm closing this issue.
