### ISSUE TITLE
Do not require virtual environments

### ISSUE THREAD

**Issue by bartfeenstra** [MycroftAI/mycroft-core#1391]
The automation scripts Mycroft comes with, specifically [dev_setup.sh](https://github.com/bartfeenstra/mycroft-core/blob/dev/dev_setup.sh) and [start-mycroft.sh](https://github.com/bartfeenstra/mycroft-core/blob/dev/start-mycroft.sh), require virtual environments to be used. However, my environment is a container, and virtual environments just add overhead.

## Proposal
Be less opinionated about deployment environments, and do not enforce the use of virtual environments. For backwards compatibility, adding an option to disable this for the entire application (so it won't have to be set upon every command), would solve this issue, as the default behavior would remain unchanged.

Thank you :)

**Comment by forslund** [comment]
The dev_setup script has mainly been used to setup a development environment. So the goal is a simple standard installation, of mycroft on a developers machine.

That said a --no-virtualenv flag could definitely be added. Thanks for suggesting it.

**Comment by bartfeenstra** [comment]
Thanks for the quick response :)

I'm still trying to make this work in a fresh Docker container by installing from the source. Will report back if I find out more, and hopefully contribute some improvements.

**Comment by forslund** [comment]
Just so you haven't missed it there are install-scripts for the needed builds in the scripts folder.

**Comment by JarbasAI** [comment]
https://github.com/MycroftAI/mycroft-core/pull/1354

**Comment by bartfeenstra** [comment]
Thanks, both of you, for the information. I'm hoping to be able to work on this container some more this week. I'll share the results here :)

**Comment by MatthewScholefield** [comment]
What if we renamed `mycroft-base-setup.py` and `mycroft-base-MANIFEST.in` to the standard `setup.py` and `MANIFEST.in`? Then you could just install dependencies and run `sudo pip install`. As it is right now, you *might* be able to just do `sudo python3 mycroft-base-setup.py install`.

**Comment by forslund** [comment]
I like the proposition from @MatthewScholefield. It makes the module more standardized and easy to use by people used to other python projects.

**Comment by forslund** [comment]
@bartfeenstra we're now using the python standard setup.py install allowing anyone to setup the project in any environment the way @MatthewScholefield talks about above.

**Comment by forslund** [comment]
Since there's been no communication and there are methods available to install without venv I'm closing this issue.
