### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by Batcastle** [MycroftAI/mycroft-core#1398]
I am running Mycroft version 0.9.8 on in Linux Mint.

I am proposing a **feature** for use in the desktop version of Mycroft.

A loading screen would be nice, to get a since of how far into starting up Mycroft is, and also to give it at least a small amount of GUI.

Creating such a loading screen is neither hard, nor would take very long. It would also make it look a little nicer. Furthermore, making one the right way could make the AI only minimally larger.

**Comment by apachano** [comment]
I also use mint, I want to start development on a desktop widget for Mycroft (Functionally similar to how cortana on windows 10 is setup so you can also use textual commands) , currently I am doing some research on how to achieve this. It could watch Mycroft boot and give feedback on how ready it is.

**Comment by Batcastle** [comment]
@apachano This sounds like it would be super useful! Is it going to work in just Cinnamon or do you plan to support other desktops as well, such as Gnome, Xfce, KDE, etc.?

I am currently working on an actual loading screen to be used with Mycroft. If you wish to use it with your widget, the code can be found here: https://github.com/Ubudroid-Development/mycroft-core/tree/feature/loading-screen 

Almost all of it is in `/MLS`, but it also includes `mycroft.sh` and a few minor changes made at the end of `dev_setup.sh` Feel free to tinker with it all you want.

**Comment by apachano** [comment]
I will take a look through what you have done, I am brand new to Mycroft and everything linux related will be new as well.

I spent some time thinking about it and I don't see why it cant be compatible with everything. If it is created as a widget in the notifications area it should work out of the box with most desktops and will be completely customize able based on what the desktop provides. I am also thinking some kind of lock screen support would be cool but I will work on the widget first. 

![image](https://user-images.githubusercontent.com/2256569/38056786-5202872a-3292-11e8-8fd5-0478d616ab07.png)

**Comment by penrods** [comment]
Mycroft is, by default, not tied to any GUI or specific distro/desktop -- it's just a service.  The "GUI" side of it is specific to the desktop.  There is currently a KDE widget which loads and provides an visual interface for implementations of KDE.  This is independent of mycroft-core.  That is the model I would like to follow on this -- the widget uses mycroft-core, but mycroft-core is not dependent on it.

Make sense?

**Comment by Batcastle** [comment]
@apachano @penrods I know with my loading screen it is similar to the KDE widget in that it depends on mycroft-core, but mycroft-core doesn't depend on it. Could we distribute this n a way similar to the KDE widget, then? If so, how would we go about that? Could we just put it in a launchpad PPA and be done?

**Comment by forslund** [comment]
I'm closing this issue since there's been a long time since there was any communication. The loading screen for desktop is more of an enclosure issue.
