### ISSUE TITLE
Listener Improvements

### ISSUE THREAD

**Issue by jdorleans** [MycroftAI/mycroft-core#14]
1. To prevent many of the listener "dead state" (avoiding unwanted exceptions to break the loop)
2. Wake up must work for both "mycroft wake up" and "wake up mycroft"
3. To ensure "mycroft" keyword is always detected when it exists
4. To rely on "mycroft" instead of "hey mycroft"
5. To process "ok", "okay" and "allright" as part of the wake word detection
6. Faster and more precise Wakeword extraction

**Comment by Wolfgange3311999** [comment]
Reposting what was said on this, for #4 and possibly #3 thew threshold parameter should be decreased when changing the keyword to only Mycroft.

As for #5 (and I think #2) I was thinking of having an array of pocketsphinx wakeword recognizers for each preposition ('hey mycroft', 'okay mycroft', etc) and it tests to find the one that has been detected and passes that wakeword recognizer to the wakeword extractor to remove the entire phrase. And I don't believe this will add significant latency as pocketsphinx calls should only take something like 0.02 seconds.

@jdorleans Could you expand on #1?

**Comment by ryanleesipes** [comment]
Let's focus on this and get it merged ASAP, the most common complaint is regarding the listener.

**Comment by jdorleans** [comment]
PR #45

**Comment by ryanleesipes** [comment]
#45 merged, closing this issue.
