### ISSUE TITLE
chown: invalid group on ./start-mycroft.sh

### ISSUE THREAD

**Issue by femans** [MycroftAI/mycroft-core#1403]
on Arch linux on commit 5fbbee3 of the master branch.

## steps:

1. After installing, I run ./start-mycroft.sh debug
2. I get the following output: 
```
Initializing...
Changing ownership of /opt/mycroft to user: femans with group: femans
chown: invalid group: ‘femans:femans’
Starting cli
```

## notes:

- clearly the script tries to give user access to the folder under /opt and fails
- the user:group of the folder is still root:root
- the group does indeed not exists. The default group for user is `users`. 
- The cli does not start, but this may be related to other installation issues.

**Comment by forslund** [comment]
I came across the same issue in openSuse, if you have the opportunity try #1355.

**Comment by femans** [comment]
hi @forslund , thanks! 
I would like to try something, but I am not sure what exactly I should try?

**Comment by forslund** [comment]
To try the PR you can pull it to a branch by

```bash
git checkout -b forslund-feature/opensuse-install dev
git pull https://github.com/forslund/mycroft-core.git feature/opensuse-install
```

**Comment by femans** [comment]
I tried it but except for asking me for my password, it doesn't work either. Simply the group does not exist.

**Comment by femans** [comment]
I found this rather peculiar piece of script in scripts/prepare-msm.sh. It seems to me out of place, should the software change ownership of the software? Isn't this an install script thing?

But moreover, it assumes that the group name is the same as the username, which is not the case in my case. After removing the `:${setup_user}` from the script, no error anymore.

```
# Determine which user is running this script
setup_user=$USER

# change ownership of ${mycroft_root_dir} to ${setup_user } recursively 
function change_ownership {
    echo "Changing ownership of" ${mycroft_root_dir} "to user:" ${setup_user} "with group:" ${setup_user}
            sudo chown -Rvf ${setup_user}:${setup_user} ${mycroft_root_dir}
}
```

**Comment by forslund** [comment]
The opensuse patch should change the behavior here, changing it to the default group (instead of user). But dropping it all together might be even safer

**Comment by femans** [comment]
Ok it still tried to set it to my username though. But unfortunately my
hack didnt make the software run still :(

Op zo 4 mrt. 2018 18:18 schreef Åke <notifications@github.com>:

**Comment by forslund** [comment]
@femans, out of curiosity what's the output of `id -gn $USER` for you?

**Comment by forslund** [comment]
Hmm that sounds correct. what is the owner group of `/opt/mycroft/skills` when you set it manually?

Good to hear that it works for you! I'm just trying to figure out why the PR you tested errored out on you

**Comment by MatthewScholefield** [comment]
Since this is over a month old and the changes forslund mentioned seem to fix this issue in most cases, I'm closing this. Feel free to ask to reopen if you still have this problem.

**Comment by droidmahn** [comment]
Please re-open as I'm running into this same issue on arch linux.

**Comment by MatthewScholefield** [comment]
@droidmahn Can you create a new issue and post logs? Thanks!

**Comment by fxdgear** [comment]
I've run into the same issue. 

I had to manually create the group that mycroft assumes to be there but isn't. I feel like the install scripts is making incorrect assumptions about individual systems. The script needs to be either
1. smarter and inspect what groups a user belongs to when starting.
2. doesn't chown with the group option
3. Prompts the user to choose which user:grp to use

**Comment by forslund** [comment]
The current implementation should be 1. See [here](https://github.com/MycroftAI/mycroft-core/blob/dev/scripts/prepare-msm.sh#L32)

What's the result of `id -gn $USER` for you? (and is that output correct?)

**Comment by fxdgear** [comment]
I ended up creating the group manually and adding myself to it. 

previously my groups were
```
~ → groups $USER                                                                                                                                                                                                                                             
sys docker
```

``` 
~ → id -gn $USER                                                                                                                                                                                                                                             
id: cannot find name for group ID 1001
1001
```

**Comment by forslund** [comment]
Ok so there was a group but it didn't have a name? Do you think `id -g` would have worked? (the n asks it to print the group name)
