### ISSUE TITLE
Enhancement - Inform users of server STT 500 errors via speech

### ISSUE THREAD

**Issue by FloatingBoater** [MycroftAI/mycroft-core#1405]
# Use Case
During the recent STT outage, there was no idiciation to users that there was an issue, other than Mycroft failed to act on speech. 
LAN or Internet issues give spoken errors to manage user expectations.

This enhancement request is to catch the STT server 500 error and speak an error message such as:

>   "I'm sorry, there is a server error. Please try later."
>   "My speech recognition is not working right now. Please try later."

# Environment
* Mycroft Mark 1

# Steps to reproduce
* (STT server failure - returns HTTPS 500)
* Speak to Mark 1
* Wake word detected, mouth animation acknowledges listening
* Nothing happens!
* Confused user!

# Desired behaviour
* (STT server failure - returns HTTPS 500)
* Speak to Mark 1
* Wake word detected, mouth animation acknowledges listening
* Client handles STT 500 error more elegantly:
** Logs 500 error to mycroft-speech-client.log
** Mycroft speaks a clear non-technical message to the user

Logs and my steps to understand what was going on (required the Python console) are documented here:
https://community.mycroft.ai/t/mark-1-stt-fails-with-500-errors-skills-work-manually-via-python-console-fixed/2872

The STT outage is documented here:
https://docs.google.com/document/d/15i5spdmlIUTBsHNdnmwbsXuKDeywXXTmtTGvEoO7IaM/edit?usp=sharing

A brief look at the code (N.B. I don't understand the state machine driven from the message bus), suggests HTTP 401 errors are handled, but 500's are not:
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/listener.py

Thanks!

**Comment by JarbasAI** [comment]
we could also make mycroft create a support ticket so you know you are getting internal server errors as soon as they come instead of waiting for someone to complain in mattermost:)

**Comment by forslund** [comment]
We're working on a system handling and reporting errors in a user friendly way. The should either make the upcoming release or the next after that.

**Comment by krisgesling** [comment]
Mycroft now reports if it's having trouble connecting with Mycrofts servers. Closing.

Please flag if I've missed something.
