### ISSUE TITLE
No reaction to voice commands

### ISSUE THREAD

**Issue by kekuskekus** [MycroftAI/mycroft-core#1409]
# How to submit an Issue to a Mycroft repository

When submitting an Issue to a Mycroft repository, please follow these guidelines to help us help you. 

## Be clear about the software, hardware and version you are running

For example: 

* I'm running a parrot os
*Standart git installer
* With the standard Wake Word

## Try to provide steps that we can use to replicate the Issue

For example: 

1. installed via dev_install.sh from git
2. started
3. Mic level is working, its recording if asked through ssh or cli, but its not reacting to voice

I expected mycroft to react to voice commands. but it's not. Also I checked possible prononcuation problems by asking different people to try it.

**Comment by el-tocino** [comment]
Can you look in the skills/logs/mycroft-voice.log file and see if there's anything of note, and post the relevant snippets here?

**Comment by forslund** [comment]
Closing this as there has been no communication from author for over a year. If you feel this is incorrect feel free to reopen.
