### ISSUE TITLE
Leave all nice_number formatting to language 

### ISSUE THREAD

**Issue by zecakeh** [MycroftAI/mycroft-core#1411]
I'm working on the french translation and while creating tests I realized that nice_number is returning decimal numbers with an english formatting. By that I mean that in french for decimals we use a comma instead of a dot, and for thousands separator we use unbreakable spaces rather than commas (that one is just a comment for now). And this is handled directly in the main nice_number function.

Since it looks like the output of this function is directly fed to a display or TTS, the numbers should be formatted according to the language.

If I'm right, I could send a pull request with the changes. Should the english formatting also be included in the other already included languages, waiting for a maintainer to change it if necessary but not breaking anything in the meantime?

**Comment by zecakeh** [comment]
What about using the python string format function? It uses the formatting of the language setting to display numbers nicely. That way it would automagically work for digits whatever the language is, even if it's not implemented.

**Comment by zecakeh** [comment]
As said in PR #1416 , it's not recommended to use the python <code>format</code> function because it involves changing the default locale of the program and it might break things.

Another option would be to use [Babel](http://babel.pocoo.org/en/latest/). It provides functions to format numbers, dates and other things by providing the locale as an argument.

So is it worth including this library ?
It could be used to format data that's supposed to be displayed without needing for developers to code a locale-specific function, they would only need to help TTS. Besides, even if there is no TTS helper, it should help it since I guess, for example, that a french TTS would expect to find decimal numbers with a comma and not a dot.

**Comment by forslund** [comment]
Hi zecakeh, the language modules have been extracted into [lingua-franca](https://github.com/MycroftAI/lingua-franca/). Much development has happened on this front, but I think this discussion is probably better to have over there. I'm closing this issue and you can raise the remaining parts you think needs to be handled over there.
