### ISSUE TITLE
Can mycroft support Project Things? 

### ISSUE THREAD

**Issue by Cole128** [MycroftAI/mycroft-core#1417]
I love the mycroft idea and product, and especially how you guys are keeping open-source alive. A major part of other home assistants is of course their integration with smart devices. Mycroft could create it's own protocol to do that, but as it is not very popular in the mainstream tech community unfortunately this would likely fail, as few or no manufacturers would support it. 

You guys have probably though of this already, but a good way to support open-source and have smart device integration might be to use Mozilla's Project Things framework. It is a decentralized, opensource way for smart devices to communicate, and with some luck, it'll be the way of the future for smart devices and assistants. 

What do you think? Is this something mycroft could support?

**Comment by penrods** [comment]
I'm not sure what you mean by "support".  If you mean "would it be possible to use Mycroft to interact with", then yes of course!  I don't see any reason we or someone in the community wouldn't be able to build a skill that interacts with this framework.  One of my goals is to allow joining all sorts of frameworks together -- I can run my lights regardless of the hub or technology, as long as there is _some_ way to get to them.  However I don't want to be tied to only one framework.

**Comment by Cole128** [comment]
Sorry, I worded it a bit badly. I was more wondering whether it would be possible with mycroft (as I am new to this project) and whether you guys had plans to integrate it. Good to hear that at the very least it could work.

**Comment by penrods** [comment]
Yep, we are designing to do all the things!  :)
