### ISSUE TITLE
Install Mycroft as System Package

### ISSUE THREAD

**Issue by schrieveslaach** [MycroftAI/mycroft-core#1433]
I want to be able to install Mycroft as system package and I want to run Mycroft as arbitrary user who has access to the system.

* With version 0.9.17 of the Mycroft software
* Mycroft is installed as system package, e. g. [Arch Linux User package](https://aur.archlinux.org/packages/mycroft-core)
* However, skills won't work

## Steps to reproduce

1. Install Arch Linux
2. install [mycroft-core AUR](https://aur.archlinux.org/packages/mycroft-core) package
3. Run `source /usr/share/mycroft-core/.virtualenvs/mycroft/bin/activate && WORKON_HOME=/usr/share/mycroft-core/.virtualenvs/ VIRTUALENV_ROOT=/usr/share/mycroft-core/.virtualenvs/mycroft PYTHONPATH=/usr/share/mycroft-core/ /usr/share/mycroft-core/start-mycroft.sh debug`
4. Wait 3 minutes
5. Try to use timer skill
6. Debug contains many errors that it cannot install/use skills

## Try to fix msn scripts

I also tried to fix msn install, c. f. [mycroft-core.install, line 26 and following](https://gitlab.com/schrieveslaach/mycroft-core-aur/blob/master/mycroft-core.install#L26) (for example, log directory in the core needs to be writable for users), however these fixes didn't help. 

I noticed that the msn script does not pick up the user directory as default and I tried to fix that in the script as well, c. f. following snippet which enables Mycroft to install and use skills in the home directory:

```bash
# Get the location of the Skill folder
mycroft_skill_folder="null"
if [[ -r $HOME/.mycroft/mycroft.conf ]] ; then
   mycroft_skill_folder=$( jq -r '.skills.directory' $HOME/.mycroft/mycroft.conf )
fi
if [[ ${mycroft_skill_folder} == "null" ]] && [[ -r /etc/mycroft/mycroft.conf ]] ; then
   mycroft_skill_folder=$( jq -r '.enclosure.skill_folder' /etc/mycroft/mycroft.conf )
fi
if [[ ${mycroft_skill_folder} == "null" ]] ; then
   mycroft_skill_folder="/opt/mycroft/skills"
fi
```

However, I'm still seeing errors in the log: 

```
09:18:06.036 - SKILLS - DEBUG - {"type": "msm.install.failed", "data": {"skill": "/home/marc/.mycroft/skills/fallback-aiml", "error": 121}, "context": null}
09:18:11.815 - SKILLS - DEBUG - {"type": "msm.install.failed", "data": {"skill": "/home/marc/.mycroft/skills/skill-npr-news", "error": 121}, "context": null}
09:18:14.393 - SKILLS - DEBUG - {"type": "msm.install.failed", "data": {"skill": "/home/marc/.mycroft/skills/skill-alarm", "error": 121}, "context": null}
09:18:18.838 - SKILLS - DEBUG - {"type": "msm.install.failed", "data": {"skill": "/home/marc/.mycroft/skills/fallback-wolfram-alpha", "error": 121}, "context": null}
09:18:21.669 - SKILLS - DEBUG - {"type": "msm.install.failed", "data": {"skill": "/home/marc/.mycroft/skills/fallback-duckduckgo", "error": 121}, "context": null}
09:18:25.191 - SKILLS - DEBUG - {"type": "msm.install.failed", "data": {"skill": "/home/marc/.mycroft/skills/skill-pairing", "error": 121}, "context": null}
09:18:28.933 - SKILLS - DEBUG - {"type": "msm.install.failed", "data": {"skill": "/home/marc/.mycroft/skills/skill-wiki", "error": 121}, "context": null}
```

Is it possible to install Mycroft as a system package and run it as arbitrary user?

**Comment by JarbasAl** [comment]
i simply did a sym link to where the system package should be 

https://github.com/JarbasAl/jarbas-core/blob/server/dev_setup.sh#L272

also did it for msm

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
