### ISSUE TITLE
Installation OSX

### ISSUE THREAD

**Issue by camdixon** [MycroftAI/mycroft-core#1442]
Can this be installed on OSX?

## To reproduce: 
1. Use OSX (El Capitan is my version)
2. cd ~ && git clone https://github.com/MycroftAI/mycroft-core.git
3. cd mycroft-core
4. bash dev_setup.sh

`Collecting pep8==1.7.0 (from -r requirements.txt (line 32))
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Collecting fann2==1.0.7 (from -r requirements.txt (line 33))
  Using cached fann2-1.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    running swig
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lw/9z75vpn546s05x7tt57gjg2c0000gn/T/pip-build-YvbiJ9/fann2/setup.py", line 65, in <module>
        build_swig()
      File "/private/var/folders/lw/9z75vpn546s05x7tt57gjg2c0000gn/T/pip-build-YvbiJ9/fann2/setup.py", line 60, in build_swig
        swig_bin = find_swig()
      File "/private/var/folders/lw/9z75vpn546s05x7tt57gjg2c0000gn/T/pip-build-YvbiJ9/fann2/setup.py", line 55, in find_swig
        raise Exception("Couldn't find swig2.0 binary!")
    Exception: Couldn't find swig2.0 binary!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/lw/9z75vpn546s05x7tt57gjg2c0000gn/T/pip-build-YvbiJ9/fann2/
Warning: Failed to install all requirements. Continue? y/N
ydev_setup.sh: line 194: free: command not found
dev_setup.sh: line 195: / 512000: syntax error: operand expected (error token is "/ 512000")
dev_setup.sh: line 196: nproc: command not found`

<img width="1026" alt="screen shot 2018-02-25 at 2 33 05 am" src="https://user-images.githubusercontent.com/4430359/36639185-2193ab6c-19d5-11e8-9f72-b458152c1bde.png">

**Comment by el-tocino** [comment]
"free" and "nproc" are linux only commands, fann2 and swig can be installed for mac osx per some googling.  

A bit of tweaking to account for system memory in bytes, the number of cpu cores, and getting those bits installed (see the requirements.txt file for a more complete list) would probably go a long way towards getting it working.

**Comment by aabutaleb** [comment]
Hi, I might be doing something wrong but compiling in MacOS I can't get passed this:

```
Installing collected packages: pyalsaaudio, xmlrunner, pyserial, psutil, pocketsphinx, inflection, olefile, pillow, python-dateutil, netifaces, zeroconf, protobuf, pychromecast, python-vlc, pulsectl, httplib2, pyasn1, pyasn1-modules, rsa, oauth2client, uritemplate, google-api-python-client, monotonic, pep8, fann2, xxhash, padatious
  Running setup.py install for pyalsaaudio ... error
    Complete output from command /Users/myuser/.virtualenvs/mycroft/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/s2/pc355yhj4dxf_2mhp4xzgj1r0000gn/T/pip-build-I3GtE8/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/s2/pc355yhj4dxf_2mhp4xzgj1r0000gn/T/pip-INgWpX-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/myuser/.virtualenvs/mycroft/include/site/python2.7/pyalsaaudio:
    running install
    running build
    running build_ext
    building 'alsaaudio' extension
    creating build
    creating build/temp.macosx-10.13-intel-2.7
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c alsaaudio.c -o build/temp.macosx-10.13-intel-2.7/alsaaudio.o
    alsaaudio.c:23:10: fatal error: 'alsa/asoundlib.h' file not found
    #include <alsa/asoundlib.h>
             ^~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/myuser/.virtualenvs/mycroft/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/s2/pc355yhj4dxf_2mhp4xzgj1r0000gn/T/pip-build-I3GtE8/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/s2/pc355yhj4dxf_2mhp4xzgj1r0000gn/T/pip-INgWpX-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/myuser/.virtualenvs/mycroft/include/site/python2.7/pyalsaaudio" failed with error code 1 in /private/var/folders/s2/pc355yhj4dxf_2mhp4xzgj1r0000gn/T/pip-build-I3GtE8/pyalsaaudio/
Warning: Failed to install all requirements. Continue? y/N
```

**Comment by el-tocino** [comment]
ALSA is for linux. https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture
Not sure what mac equivalent is.  Pulseaudio appears to be available on mac, though.

**Comment by forslund** [comment]
Seems like alsaaudio is only used for the enclosure so I think it could be skipped for a mac build

**Comment by BenjaminHCCarr** [comment]
So `Alsa` is not an issue, we just use `pulseaudio`.
It _MIGHT_ be possible to install in a `pipenv`
It was possible to use the `docker` image, but that's on hold.

Likely most of you have heard or use [Homebrew](https://github.com/Homebrew/).

I have a good stab at a *native* `mycroft` install using the `Homebrew Formula` in:
https://github.com/BenjaminHCCarr/homebrew-tap/

A couple notes:
- [requirements_to_resources.sh](https://github.com/BenjaminHCCarr/homebrew-tap/blob/master/requirements_to_resources.sh) converts a `python` `reuirements.txt` file to the `resources blocks in a homebrew formula.
- [mycroft-core.rb](https://github.com/BenjaminHCCarr/homebrew-tap/blob/master/Formula/mycroft-core.rb) fails about 10 minutes into the install, and I haven't had time to work on it since my second kid surprised us early.

### I welcome help/additions!

**Comment by penrods** [comment]
Short answer:  Can we install on OSX today -- no.

I'd love to have this solved, but it isn't something the core team is aiming for.  My understanding is that getting to the microphone constantly under OSX is not easy.  So not a huge bang for that development buck.

**Comment by camdixon** [comment]
Ok, let's close the issue then and I'll buy Rasberry PI.  I love the project though.
