### ISSUE TITLE
Naptime skill does not used localized dialog

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#145]
The naptime skill currently has hardcoded dialog rather than localized dialog.

**Comment by ChristopherRios7** [comment]
I can take care of it.

**Comment by ChristopherRios7** [comment]
Assign it to me

**Comment by ethanaward** [comment]
I'm not sure that I can assign people.

**Comment by ryanleesipes** [comment]
@christopher.rios7 no need to be assigned, you can just say "I got this"

**Comment by ryanleesipes** [comment]
Reassigned to @ethanaward

**Comment by ethanaward** [comment]
Fixed by #183, closing.
