### ISSUE TITLE
Easier startup script

### ISSUE THREAD

**Issue by jasonehines** [MycroftAI/mycroft-core#146]
I created a simple bash script that will run the three scripts listed in the README in detached screens and append to their respective logs.

This is my first time contributing code to another project, so if I didn't do it properly, please let me know.

**Comment by ethanaward** [comment]
Thanks, @jasonehines! This is an issue, so we can't actually review or even see your code. To properly suggest additions, you need to [submit a pull request](https://help.github.com/articles/using-pull-requests/). Feel free to also [take a look at our contributing guidelines](https://github.com/MycroftAI/mycroft-core/blob/master/CONTRIBUTING.md).

**Comment by jasonehines** [comment]
I messed up my pull request the first time and did it to my own fork. I did a second one and I think I did it properly. Please let me know if I didn't.

**Comment by aatchison** [comment]
Very close: https://github.com/MycroftAI/mycroft-core/pull/147

**Comment by aatchison** [comment]
Merged PR. https://github.com/MycroftAI/mycroft-core/pull/147
