### ISSUE TITLE
Required tweaks for install on Kali Linux

### ISSUE THREAD

**Issue by doctorgl** [MycroftAI/mycroft-core#1460]
I'm using the Kali Rolling distribution 2018.1 64-bit and had to make a few minor adjustments to the install of Mycroft Core for Linux. Posting here for anyone else running Kali.

The Kali repositories don't have the s3cmd package, so I added the debian repository into /etc/apt/sources.list (deb http://ftp.us.debian.or/debian stable main contrib). You may want to comment out this repository after install.

The python-gobject-dev package is listed as deprecated and replaced by python-gobject-2-dev, so I changed the one mention of python-gobject-dev in the dev_setup script to python-gobject-2-dev

Everything installed fine after these minor tweaks. The only package pulled from the debian repository was s3cmd, everything else came from Kali's repositories.

Hope this helps!

**Comment by forslund** [comment]
Thank you very much, this is good info!

Replacing the python-gobject package is probably something we should do. The s3cmd isn't technically necessary it's mainly used in our packaging script ans should be extracted.

**Comment by EuripideH** [comment]
Hey Doctorgl,

i didn't manage to found the "debian repository" so i'm still stuck with the s3cmd issue.
Please help
You forgot a "g" in the link .org
Thanks in advance

**Comment by EuripideH** [comment]
So it's work !
I can explain for the one who don't know, like me before...
command line
nano /etc/apt/sources.list
then write a line without # "deb  http://ftp.us.debian.org/debian stable main contrib"
Ctrl + Q
Save
then you can go edit the file dev_setup.sh change python-gobject-dev to python-gobject-2-dev
save
then the running of "bash dev_setup.sh -r" will work
Thanks @doctorgl

**Comment by Gh0stInTh3M4ch1n3** [comment]
Thank you @doctorgl this info came with perfect timing.
However... I have a slightly different setup. I'm using kali-pi. And don't want the mycroft image for rpi3. So I was trying to build mycroft on my kali ARM when I found this little nugget. 
The the problem is, yours is for a 64bit Kali, so it removes dependencies needed by about 20 things. What can I do to apply this same fix to Kali ARM 32bit?
