### ISSUE TITLE
the wiki documentation of mycroft core in Spanish is erroneous and contains serious errors

### ISSUE THREAD

**Issue by Manuelhck** [MycroftAI/mycroft-core#1465]
the wiki documentation of mycroft core in Spanish is erroneous and contains serious errors...

https://mycroft.ai/documentation/language-support/spanish/

**Comment by JarbasAl** [comment]
and another complaint about this...someone fix the docs :(

fairly language agnostic guide https://mycroft.ai/documentation/language-support/portuguese/

**Comment by zeehio** [comment]
I was surprised to see that no one had submitted Spanish localization so I started translating some skills. It is useless to have speech recognition or speech synthesis in Spanish if the mycroft core or the mycroft skills are not translated.

Anyone would like to volunteer to translate some skills to Spanish? Here are some examples:

- https://github.com/MycroftAI/mycroft-core/pull/1515
- https://github.com/MycroftAI/fallback-unknown/pull/7
- https://github.com/MycroftAI/skill-volume/pull/10

You can try the result using the `./start-mycroft.sh debug` command, that opens a command line interface to write text to mycroft. With this approach you can test mycroft skills without setting up a wakeword, a speech recognition engine or a speech synthesis engine.

**Comment by forslund** [comment]
The wiki information has been moved to the mycroft documentation and has been updated. closing this issue.
