### ISSUE TITLE
Reducing amount of requests to home.mycroft.ai

### ISSUE THREAD

**Issue by nielstron** [MycroftAI/mycroft-core#1467]
As far as I can tell from the log of mycroft, there are seperate HTTPS-Requests for each skill with a settingsmeta.json to check if the settings have changed since the last download. 
Can this be reduced to one request, that checks via one flag or hashsum if any settings have changed at all (which is the case 99% of the time)?
A hashsum approach would then account for both changes on the device and on the server back-end as the sum of the hashsums of settingsmeta files would change.

**Comment by forslund** [comment]
This is the current behaviour yes.
Your solution is a good one and we have discussed it internally as well.

Another approach suggested during the discussions was to use Etag headers to use a caching mechanism (https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers)

**Comment by forslund** [comment]
@nielstron we just merged #1520 to add support Etags. The number of requests won't change but no data is transferred if there is no change on the server.

**Comment by forslund** [comment]
Is this solution good enough to close this issue?

**Comment by nielstron** [comment]
The merged feature is great for reducing the amount of data consumption by Mycroft. If it's not too hard to implement, I'd like to keep this issue open until the number of requests is reduced. At some point this still leads to clogging the logs aid generating loads of (separate) requests for the mycroft servers.

**Comment by forslund** [comment]
Fair point! Will keep it open.

**Comment by forslund** [comment]
We've added a second feature to reduce the number of requests. We cache the response from fetching skill settings for 30 seconds, now it should only be one actual request for all skills.

The default log is now set to INFO so no logging of url requests will occur in the normal case.

**Comment by nielstron** [comment]
Okay this sounds great 👍 . I will close this issue then.
