### ISSUE TITLE
Switch unit test framework to pytest

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1469]
It's super difficult to find what the error is when running unit tests with the current nose2 framework because sometimes exceptions are outputted as warnings and there's a lot of extra text output. [Here's an example "success" output](https://hastebin.com/asogunenuy.bash).

Because of this, I think we should switch to [pytest](https://docs.pytest.org/en/latest/) which hides all unrelated output and gives far better error descriptions while making the source code cleaner by removing the need for specialized comparisons like `assertEquals`. We can get the same coverage report via the [pytest-cov](https://github.com/pytest-dev/pytest-cov) plugin.

**Comment by forslund** [comment]
This is done now! Closing
