### ISSUE TITLE
mycroft-use should tell you which train you are on

### ISSUE THREAD

**Issue by BenjaminHCCarr** [MycroftAI/mycroft-core#1470]
mycroft-use should tell you which train you are on when `$0 is null`

----
* I'm running a PiCroft
* With version 18.02 of the Mycroft software
* With the standard Wake Word
----

instead of `mycroft-use` falling back to `mycroft-use --help`
```
root@picroft:/home/pi# mycroft-use 
usage: mycroft-use.sh [stable | unstable | home | home-test | github [<path>]]
Switch between mycroft-core install methods

Options:
  stable           switch to the current debian package
  unstable         switch to the unstable debian package
  github [<path>]  switch to the mycroft-core/dev github repo
<snip>
````

It would be useful for it return what `Train` you are currently on! This is ESPECIALLY important for Devs who might have different branches, and the `CLI (master)` may not reflect what mycroft is running.

So something like:
```
root@picroft:/home/pi# mycroft-use
- You are running Mycroft Stable (v0.9.14)
- You are running Mycroft Untable (v18.02)
- You are running a git version from repo: /home/bill/projects/mycroft/custom
- You are running a git version from repo: github.com/billsprojects/mycroft-custom
```

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
