### ISSUE TITLE
[FR] mycroft-version reporting script

### ISSUE THREAD

**Issue by BenjaminHCCarr** [MycroftAI/mycroft-core#1471]
With so many moving parts it can be difficult to identify which part of your or someone else's development work is going sideways.

I suggest a script that has a clearing house of all in-use pieces:
```
$ mycroft-version
Core: 18.02
Mimmic: xx
OpenSTT: N/A (using Google)
Built in Skills: Github:13/3/2018
ETC.....
```

**Comment by krisgesling** [comment]
Love this. Will be good to include in the Support Skills troubleshooting package

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
