### ISSUE TITLE
Can't configure skill from home.mycroft.ai / ERROR - HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out

### ISSUE THREAD

**Issue by THEPADA** [MycroftAI/mycroft-core#1473]
I'm running a Picroft with mycroft-core 18.2.0

I freshly installed it to a pi3 today. But i cant change my Skill-Settings on home.mycroft.ai.
this is the Error log: http://termbin.com/xaly

The Debbuging console of mycroft is Stating:
` 16:08:56.886 - mycroft.skills.settings:_poll_skill_settings:401 - ERROR - HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)
16:08:56.890 - mycroft.skills.settings:_poll_skill_settings:402 - ERROR -
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.0-py2.7.egg/mycroft/skills/settings.py", line 394, in _poll_skill_settings
self.initialize_remote_settings()
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.0-py2.7.egg/mycroft/skills/settings.py", line 135, in initialize_remote_settings
skill_settings = self._request_other_settings(hashed_meta)
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.0-py2.7.egg/mycroft/skills/settings.py", line 478, in _request_other_settings
"path": path
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.0-py2.7.egg/mycroft/api/__init__.py", line 53, in request
return self.send(params)
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.0-py2.7.egg/mycroft/api/__init__.py", line 78, in send
data=data, json=json, timeout=(3.05, 15))
File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)`
The Skill XHR package from home.mycroft.ai is reporting:
`Loading failed for the <script> with source “https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js”.
home.mycroft.ai:1
request.user.parse 
{…}
data: "The server was not able to produce a timely response to your request.\r\nPlease try again in a short while!"
params: Object { path: "/user/***/skill", success: value/<(), uri: "https://api.mycroft.ai/v1/user/***/skill", … }
path: "user"
__proto__: {…}
__defineGetter__: function __defineGetter__()
__defineSetter__: function __defineSetter__()
__lookupGetter__: function __lookupGetter__()
__lookupSetter__: function __lookupSetter__()
constructor: function Object()
hasOwnProperty: function hasOwnProperty()
isPrototypeOf: function isPrototypeOf()
propertyIsEnumerable: function propertyIsEnumerable()
toLocaleString: function toLocaleString()
toSource: function toSource()
toString: function toString()
valueOf: function valueOf()
 
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stack trace:
value@https://home.mycroft.ai/build/bundle.js?master-125:28:13836
value/e.failure/<@https://home.mycroft.ai/build/bundle.js?master-125:28:12864
bundle.js:55:8556 `
thanks for doing this :+1:

**Comment by forslund** [comment]
This is an ongoing issue with the backend and the server load we're currently having. We're aware and are working to fix it as soon as possible

**Comment by forslund** [comment]
Hi, the server issue should be resolved now, do you still have issues or can we close this issue?

**Comment by forslund** [comment]
Hi since there's been no response to this in the last two weeks I'll assume that this is no longer an issue. I'll be closing this issue, feel free to reopen this issue if the problem still persists for you.

**Comment by tekirinka** [comment]
Same issue on latest manjaro linux

**Comment by forslund** [comment]
Hi @tekirinka we had a similar server issue today. It's at least temporary restored now...
