### ISSUE TITLE
libttsmimic_lang_cmu_us_rms.la takes too much to install

### ISSUE THREAD

**Issue by RazorManager89** [MycroftAI/mycroft-core#1483]
How can I fix this?

**Comment by el-tocino** [comment]
It can take several hours.  What hardware are you running on?

**Comment by RazorManager89** [comment]
Mac mini 3,1 with 8GB RAM and Intel Core 2 duo 2,26 ghz. Running Zorin OS 12.3 based on Ubuntu 16.04 with LXDE desktop

**Comment by el-tocino** [comment]
Probably best to let it run.  Don't think there's a packaged version you can install quite yet.

**Comment by el-tocino** [comment]
Any luck?
