### ISSUE TITLE
websockets version is ancient and buggy, pyee has improvements too.

### ISSUE THREAD

**Issue by tlc** [MycroftAI/mycroft-core#1484]
Using mycroft behind a proxy, I see

> 13:14:09.042 - mycroft.messagebus.client.ws:on_error:71 - ERROR - Exception("Uncaught 'error' event.",)

Newer versions of pyee report the underlying error
 

> 13:58:08.839 - mycroft.messagebus.client.ws:on_error:71 - ERROR - WebSocketProxyException('failed CONNECT via proxy status: 403',)

once you upgrade websockets as well, to fix this formatting bug.

```
    if status != 200:
        raise WebSocketProxyException(
            "failed CONNECT via proxy status: %r" + status)
```
The following changes to requirements.txt fixed this.

```
pyee==4.0.1
websocket-client==0.47.0
```

And if you're seeing these errors, you might want to make sure your `no_proxy` setting matches the README.

**Comment by forslund** [comment]
This has finally been resolved. Closing
