### ISSUE TITLE
Roku Support

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core#149]
We be implementing Roku Support! Yarb!

Repo: https://github.com/jcarbaugh/python-roku

**Comment by ryanleesipes** [comment]
https://pypi.python.org/pypi/roku/2.0

**Comment by aatchison** [comment]
In progress: https://github.com/MycroftAI/mycroft-core/pull/166

**Comment by ryanleesipes** [comment]
Looks like we are moving this out to be an optional "third party" skill. So I am closing this ticket. Will pop up a repo for this.
