### ISSUE TITLE
feature: Porcupine wake word engine?

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#1491]
https://github.com/Picovoice/Porcupine would make a nice addition as a possible wake word engine

i started doing some work, but i am having some trouble figuring out how to pass the frame_data correctly 

https://github.com/JarbasAl/jarbas-core/tree/feature_porcupine_wakeword

**Comment by forslund** [comment]
Support has now been added thanks to @alumae
