### ISSUE TITLE
Bug: opt_in not being honored in intent_service for send_metrics

### ISSUE THREAD

**Issue by InconsolableCellist** [MycroftAI/mycroft-core#1494]
The configuration parameter "opt_in" (added in 0569ba40f7213e) isn't being honored in the send_metrics function in intent_service.py:238, contrary to the comment (added in c68ad44b1c64).

Steps to reproduce:

1. Verify "opt_in" is set to false in mycroft.conf:39 (top level)
2. Start mycroft in a manner that lets you see the logs, and issue an utterance

Observed behavior:

While handling an utterance the log prints out "Sending metric," indicating that the code in handle_metrics is executing, including the call to report_timing, and thus eventually the call to the API to make a request to the external Mycroft endpoint.

Expected behavior:

No such metrics are sent when opt_in isn't set to true, and no log message is displayed

**Comment by forslund** [comment]
I tested it, and no metrics is actually sent. The check is done in the send function:
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/metrics/__init__.py#L38

The debug message is a bit misleading though...

**Comment by penrods** [comment]
I verified and commented with details on the PR.  The metrics are not sent, but I recommend we remove that debugging log.  @InconsolableCellist can modify his PR if he'd like to do that.
