### ISSUE TITLE
Issue with using SnowboyHotWord class

### ISSUE THREAD

**Issue by livey0u** [MycroftAI/mycroft-core#1499]
Hi,

I've cloned from github & trying to use a custom wake word. To make it work correctly, I've downloaded a sample file from https://snowboy.kitt.ai. I've found that by passing module name as `snowboy`, it can be used. I did that & got an Import Error for `snowboydecoder` in this [file](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/hotword_factory.py#L237
). 

I am not able to find `snowboydecoder` module. How to install that module? Is it available? 

Thanks in advance!

**Comment by JarbasAl** [comment]
snowboy is not bundled by default, it is supported but must be manually installed

https://github.com/kitt-ai/snowboy#compile-a-python-wrapper

**Comment by aoltra** [comment]
Hi @livey0u 

I am also testing snowboy.

1. You can download snowboy with the python wrapper from [here](https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/ubuntu1404-x86_64-1.1.1.tar.bz2). 

2. Unzip the file in the folder _mycroft-core/mycroft/client/speech_ (actually only the  _snowboydecoder.py_, _snowboydetected.py_ and __snowboydetected.so_ files and folder _resources_ with _common.file_ file are necessary )

3. Install _pyaudio_ and _sox_
`sudo apt-get install python-pyaudio sox`
`pip install pyaudio`

4. Install _libatlas_
`sudo apt-get install libatlas-base-dev`

6. copy your _.pmdl_ in the _resources_ folder or use one of the _.umdl_ provided by snowboy (they are in the resources folder of the compressed file) 

7. Config mycroft to use snowboy. Edit file _.mycroft/mycroft.conf_
    * in _listener_ paragraph change:

         “wake_word”:”hey mycroft” by your _wake word_ word, for instance: “wake_word”:”sherlock”

    * in the _hotwords_ paragraph insert your hot word config, for instance:
```
“sherlock”: {
   “module”: “snowboy”,
   “models”: {
       “sherlock”:”[absolute]/[path]/[to]/[your]/[model]/model.pmdl”
    }
}
```

**Comment by forslund** [comment]
@livey0u, are the above answers enough to get you going or are you facing more issues?

**Comment by forslund** [comment]
@livey0u Since I've heard nothing in the past two weeks I assume this has been resolved or is not relevant any more. I'm closing the issue, if you still have problem feel free to reopen it.
