### ISSUE TITLE
Improve REGEXes documentation

### ISSUE THREAD

**Issue by ldevalbray** [MycroftAI/mycroft-core#1526]
Hey there !

It would be great to improve regexes documentation in order to build a skill. Giving more example on how to build an intent with regex(es),  how to combine different regexes, why to use multiple different regex files. 
Does the regex name has to be the same than the file name ? Can we have multiple regexes in different files with the same name ?
Must we combine an IntentKeyword in Vocab to a regex in order for the regex to work ?

For example : 

This will work

Post.rx: `(post|publish) (?P<Post>.+)`
Comment.rx : `(comment) (?P<Comment>.*) (on|to)` 

This won't (if I'm not wrong) : 

Post.rx: `(post|publish) (?P<Post>.+)`
Comment.rx : `(comment) (?P<Post>.*) (on|to)` 

This is not explained anywhere.

Thank you !!

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
