### ISSUE TITLE
"signals" outlive the processes responsible for them

### ISSUE THREAD

**Issue by tlc** [MycroftAI/mycroft-core#1530]
Working with a git clone development install, I couldn't get the Pairing code to put in the web interface.

I had to LOG debug the pairing skill to find out that it was stuck waiting for the "isSpeaking" "signal" to clear. I dug into the "signals" and found they were just files written to _/tmp/mycroft/ipc/signal._

Why didn't "isSpeaking" clear?  I can only guess it was an earlier _stop-mycroft.sh_  with unlucky timing.  After _stop-mycroft.sh_, **the file was still there.**  I removed the file and it worked.

Hours were lost.

**Comment by penrods** [comment]
Good find.  It should be pretty easy for someone to wipe out that signal file -- basically just check_for_signal("isSpeaking") -- in the Audio service startup.

**Comment by JarbasAl** [comment]
also ran into this.... it was during development so i found it quickly, but i can see how one could waste hours without making sense of it
