### ISSUE TITLE
Allow comments in dialog and voc files

### ISSUE THREAD

**Issue by zeehio** [MycroftAI/mycroft-core#1531]
Having a way to comment dialog and voc files would ease the translation process as the original developer can provide context useful for the translator, and the translator can explain things that motivate his/her choice of words.

I am thinking for instance of voc files where similar words to the target word are used to trigger the skill in order to workaround speech to text errors. Documenting that the meaning of those words should not be translated in a comment would be practical.

Example: the "high" word triggers the hello world skill because "high" is similar to "hi". In the Spanish translation we have "hola" (for "hello") and we should have "ola" (literally "wave") because it sounds like "hola"

Other file formats usually used for translation purposes allow developer/translator comments (see the .po file format for instance)

**Comment by forslund** [comment]
This is a really good idea and shouldn't be too hard to implement.

Adding checks in [mycroft/skills/skill_data.pyL40](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/skill_data.py#L40) for .voc files and [mycroft/skills/skill_data.pyL62](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/skill_data.py#L62) for regex files.

If the line starts with a `#` it should be ignored.
