### ISSUE TITLE
broken precise-stream and sneaky binary downloads

### ISSUE THREAD

**Issue by tlc** [MycroftAI/mycroft-core#1533]
Running a recent git clone on Ubuntu 16.04.

It seems that on the first run of "precise", the mycroft-core *application* downloads and installs binaries in ~/.mycroft.

## One
Discovering your source installed application has downloaded binaries of unknown providence is off-putting.  They might be built from https://github.com/MycroftAI/mycroft-precise but who knows?

Why aren't these *built* by dev_setup.sh?

For that matter, why were they downloaded by the application instead of by dev_setup.sh?

## Two
I only know about this because the precise-stream binary is broken on Ubuntu 16.04.

    dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found

Which means it's built on a newer Linux.  I wonder which one?  What do you guys develop on?

The mycroft documentation, https://mycroft.ai/documentation/linux/ , says that the Linux install is good for

* Debian / Ubuntu
* Arch
* Mint
* KDE Plasmoid

So can we have binaries for Ubuntu 16.04?

**Comment by penrods** [comment]
Can you confirm if this has been corrected in recent builds?

**Comment by krisgesling** [comment]
Hi there, assuming this is resolved as we didn't hear back and it's been a few years. 

Also looking separately at improving the Precise distribution mechanism.
