### ISSUE TITLE
msm errors - virtual environment

### ISSUE THREAD

**Issue by arjenlentz** [MycroftAI/mycroft-core#1537]
Running picroft 2018.03, mycroft-core 18.2.4

Run msm install (some skill)

/home/pi/bin/msm: line 369: workon: command not found
ERROR: Unable to activate 'mycroft' virtualenv, requirements not installed.

**Comment by MatthewScholefield** [comment]
This should be fixed since we've rewitten `msm` to no longer use `workon`.

**Comment by arjenlentz** [comment]
great!
got a commit # where that's in place so we can test it?

**Comment by forslund** [comment]
Latest dev or 98ede5259618a04ca4a219470c675022da0273a8
