### ISSUE TITLE
unit tests run 3 times

### ISSUE THREAD

**Issue by clusterfudge** [MycroftAI/mycroft-core#154]
When using the start.sh unittest command or invoking the test script directly, unit tests are executed 3 times. This is happening because the runner has been put into the __init__ for the root module, and it gets imported and executed multiple times (the original script did not check if __name__ == __main__, and was copied to a new location).

**Comment by aatchison** [comment]
Fixed by: https://github.com/MycroftAI/mycroft-core/pull/155
