### ISSUE TITLE
Network connectivity test - doesn't respect LAN DNS configuration.

### ISSUE THREAD

**Issue by Zotter** [MycroftAI/mycroft-core#1540]
Brand new install on Fedora 27. All seems to be working. Skills respond, etc. NPR news, weather, etc all play as expected. LAN is IPv4 only.

But, at each interaction, there are Log entries saying:
<timestamp> - mycroft.metrics:report_metric:42 - ERROR - Metric couldn't be uploaded, due to a network error (There was an internal server error.)

This appears to be result of Mycroft-core being unable to make a connection to port 53 (DNS) to 8.8.8.8 or 8.8.4.4. Successful connection appears to be the test used to confirm Internet connectivity. 

As no port 53 requests are allowed out of many networks (instead, LANs use local resolvers) LAN nodes can't connect to outside DNS servers, directly. This fails the test Mycroft uses.

Mycroft should respect the host OS DNS configuration and not fail when it's own, internal DNS connections are refused.

**Comment by forslund** [comment]
I

As I've understood this is that it mainly tries to open a connection to verify that the internet is reachable. The DNS isn't used. Doing similar checks on port 80 wouldn't work on capture portals unless the response is well defined. Maybe ifconfig.co could be used as a secondary check?

The error you're seeing isn't related to this, instead I think there's something up with the metrics service at our end.

**Comment by forslund** [comment]
The NCIS test has been added if the default (faster connect to remote server) test should fail.

**Comment by forslund** [comment]
We've added a couple of alternative approaches now and don't solely rely on the DNS check. Closing this issue, if you think this is incorrect please reopen.

**Comment by Zotter** [comment]
Thanks! I'll have to re-load and get back into all this. Expect it to be even better!
