### ISSUE TITLE
install-pygtk link dead

### ISSUE THREAD

**Issue by adberard** [MycroftAI/mycroft-core#1542]
The link used to download pygtk is dead in install-pygtk.sh

replace the line 85 by 

`       curl 'http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/LATEST-IS-2.24.0' > 'pygtk.tar.bz2'
`

**Comment by tlc** [comment]
It's returning 302.  Suggest replacing 'curl' with 'curl -L'.

**Comment by forslund** [comment]
I checked it out in http://www.redirect-checker.org/index.php and got this

```
Result

https://pypi.python.org/packages/source/P/PyGTK/pygtk-2.24.0.tar.bz2
302 Found
https://pypi.org/packages/source/P/PyGTK/pygtk-2.24.0.tar.bz2
301 Moved Permanently
https://files.pythonhosted.org/packages/source/P/PyGTK/pygtk-2.24.0.tar.bz2
302 Found
https://files.pythonhosted.org/packages/7c/18/fa4f2de77500dd62a314fd845ff6e903ac2ce551164cb421c5750969f799/pygtk-2.24.0.tar.bz2
200 OK
```

I'm preparing an update where I change the line to `curl -L 'https://files.pythonhosted.org/packages/source/P/PyGTK/pygtk-2.24.0.tar.bz2' > 'pygtk.tar.bz2'`

which seems like the official current outwards facing url.
