### ISSUE TITLE
Addition of Speech module as STT Engine

### ISSUE THREAD

**Issue by bhaveshAn** [MycroftAI/mycroft-core#1554]
Addition of Speech module as STT Engine

Wanna work on this issue.

**Comment by forslund** [comment]
Just repeating what I said in #1554, I don't think the speech module should be used since it's no longer maintained and is windows XP/Vista only as far as I can tell.

**Comment by forslund** [comment]
Since the speech module is depreciated I'm closing this issue. If you disagree with this feel free to reopen it. Thanks!
