### ISSUE TITLE
Unlocalized functions should warn if they are called with an unsupported language

### ISSUE THREAD

**Issue by zeehio** [MycroftAI/mycroft-core#1556]
Some functions in https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/parse.py (extract_number, extraxt_datetime...) need to be localized. When they are used in an unsupported language they return something (usually the input) without raising a warning.

To make everyone aware that these functions have to be localized, they should raise a warning or log something if the function is being used in an unsupported language. Otherwise some skill translations will not work and we will not know where the error comes from.

**Comment by forslund** [comment]
Fixed by #1831
