### ISSUE TITLE
Any speech with "stop" isn't processed normally

### ISSUE THREAD

**Issue by ndarilek** [MycroftAI/mycroft-core#1566]
When Mycroft encounters any command with the word "stop," it simply isn't processed. So commands of the form:

"Hey Mycroft, when does the next bus depart stop 1068?"

provide no feedback or logs.

I think I recall being told a few months back that there is global "stop" handling that treats any command containing "stop" as a request to stop processing. This makes it very difficult to have conversations about transit stops, though. If I give stop IDs, "tell me about 1078" for instance, Mycroft looks 1078 up on Wikipedia as a year.

I need to be able to use the word "stop" in Mycroft conversations and not have it short-circuit processing. :) Thanks.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
