### ISSUE TITLE
Old config.guess files from pygtk can not identify aarch64

### ISSUE THREAD

**Issue by jorritsmit** [MycroftAI/mycroft-core#1567]
This was a closed issue from someone else, but it is not yet resolved. Building mycroft gives the following error:

checking build system type... ./config.guess: unable to guess system type

This script, last modified 2009-12-30, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to config-patches@gnu.org in order to provide the needed
information to handle your system.

config.guess timestamp = 2009-12-30

uname -m = aarch64
uname -r = 3.10.104
uname -s = Linux
uname -v = #13 SMP PREEMPT Mon Dec 12 15:00:06 MYT 2016

/usr/bin/uname -p =
/bin/uname -X =

hostinfo =
/bin/universe =
/usr/bin/arch -k =
/bin/arch =
/usr/bin/oslevel =
/usr/convex/getsysinfo =

UNAME_MACHINE = aarch64
UNAME_RELEASE = 3.10.104
UNAME_SYSTEM = Linux
UNAME_VERSION = #13 SMP PREEMPT Mon Dec 12 15:00:06 MYT 2016
configure: error: cannot guess build type; you must specify one
make: *** No targets specified and no makefile found. Stop.
make: *** No rule to make target 'install'. Stop.
ubuntu@pine64:/mycroft-core$
ubuntu@pine64:/mycroft-core$

I fixed it by replacing the config.guess files in the pygtk caches, and changing the install-pygtk.sh script to use this cache and not overwriting it, but this isn't correct behaviour.

**Comment by forslund** [comment]
Pygtk isn't installed in the dev_setup-script anymore. So I think this issue can be closed, if you disagree feel free to reopen.

/Åke
