### ISSUE TITLE
Gives me a 4 letter code instead of the required 6

### ISSUE THREAD

**Issue by segaegaf** [MycroftAI/mycroft-core#1573]
https://i.imgur.com/W6DsPTp.png
pretty straight forward fix yo shit.

**Comment by KathyReid** [comment]
@segaegaf thanks for your feedback. 

I would remind you that our repositories are governed by our [Code of Conduct](https://github.com/MycroftAI/mycroft-core/blob/dev/CODE_OF_CONDUCT.md). That means using welcoming and inclusive language. `Fix yo shit` is neither welcoming nor inclusive.

**Comment by forslund** [comment]
As this is a skill-pairing issue. I'm closing this here, I've proposed a solution for making the numbers clearer in https://github.com/MycroftAI/skill-pairing/pull/29
