### ISSUE TITLE
"Whats" is not parsed out when searching WolframAlpha

### ISSUE THREAD

**Issue by Wolfgange3311999** [MycroftAI/mycroft-core#159]
`what is a dog` results in `I am searching for a dog` whereas `Whats a dog` results in `I am searching for whats a dog`.

**Comment by ethanaward** [comment]
This has to do with the basic EnglishQuestionParser that @clusterfudge made in the WA skill. It currently only removes certain words that it parses as question words. This doesn't actually affect what it sends to WA, though. Even though when you ask `what is a dog`, Mycroft responds `I am searching for a dog`, he still sends the query `what is a dog` to Wolfram. The removal of question words only affects responses to the user.

I think that just adding `whats` to the list of question words in the parser would work to solve this, but I was running into minor issues when I tried that out.

**Comment by Wolfgange3311999** [comment]
@ethanaward What minor issues were you running into?

**Comment by ethanaward** [comment]
From what I remember, it was only working some of time, so `whats cats` would give `I'm searching for cats`, but `whats a cat` would give `I'm searching for whats a cat`.
