### ISSUE TITLE
Fedora missing dependencies

### ISSUE THREAD

**Issue by testman42** [MycroftAI/mycroft-core#1602]
Please add `python3-devel` among the packages that `dev_setup.sh` installs.
Otherwise Mycroft compilation fails.

Thank you

**Comment by scherererer** [comment]
#1615

**Comment by testman42** [comment]
awesome, thank you

**Comment by testman42** [comment]
Awesome, thank you

**Comment by jpjp** [comment]
Still fails for me, I got it running with this:

```
$ git diff
diff --git a/dev_setup.sh b/dev_setup.sh
index a2f594b84b..9260801d19 100755
--- a/dev_setup.sh
+++ b/dev_setup.sh
@@ -113,8 +113,7 @@ function install_deps() {
         $SUDO zypper install -y git python3 python3-devel libtool libffi-devel libopenssl-devel autoconf automake bison swig portaudio-devel mpg123 flac curl libicu-devel pkg-config libjpeg-devel libfann-devel python3-curses pulseaudio
         $SUDO zypper install -y -t pattern devel_C_C++
     elif found_exe yum ; then
-        $SUDO yum install epel-release
-        $SUDO yum install -y cmake gcc-c++ git python34 python34-devel libtool libffi-devel openssl-devel autoconf automake bison swig portaudio-devel mpg123 flac curl libicu-devel python34-pkgconfig libjpeg-devel fann-devel python34-libs pulseaudio
+        $SUDO yum install -y cmake gcc-c++ git python3 python3-devel libtool libffi-devel openssl-devel autoconf automake bison swig portaudio-devel mpg123 flac curl libicu-devel python3-pkgconfig libjpeg-devel fann-devel python3-libs pulseaudio
         git clone https://github.com/libfann/fann.git
         cd fann
         git checkout b211dc3db3a6a2540a34fbe8995bf2df63fc9939

```

**Comment by forslund** [comment]
Hi @jpjp I think those changes might break centOS. Is there anyway to reliably differentiate between Fedora and centoOS? Would be excellent to be able to support both

**Comment by forslund** [comment]
Ok, I've looked into this some more now that I'm awake. It seems fedora ships both yam and dnf and for Fedorda dnf was used. Now for centOs a check for yam was added and currently takes precedence.

Can you tell me if it `/etc/os-release` exists in fedora and if it makes sense to read that to determine which package list to use?

**Comment by forslund** [comment]
Thanks @testman42! I've pushed a branch called **bugfix/detect-fedora** it would be awesome if someone running fedora could test it. (and maybe someone running CentOS)

**Comment by testman42** [comment]
@forslund I just tested the detect-fedora branch and it works nicely. Thank you for your effort.
So I believe that you can merge it and tell people who made duplicates of this issue that they can clone and try again :+1:

**Comment by forslund** [comment]
Thanks!
