### ISSUE TITLE
mycroft does not connect to server

### ISSUE THREAD

**Issue by tiagochiavericosta** [MycroftAI/mycroft-core#1603]
I'm trying to figure out where the error occurs and I can not find it. I already researched a lot and it did not work ... could someone help?
The following message appears:
"It seems I cannot connect to the Mycroft servers. Please wait few minutes before trying to speak to me."

I'm using the kubuntu operating system 18.04 and manually installed the latest mycroft-core. I entered the site https://home.mycroft.ai/ and checked the settings, everything is ok. I tried to install via ppa but it has no repository for ubuntu 18.04.

Thank you in advance. ;D

**Comment by forslund** [comment]
Hi, sorry for not responding quicker. Is this still an issue, is this when trying to speak to mycroft? In that case can you check if there are any errors logged in mycroft-speech.log (on a picroft/mark-1 in /var/log/, on a github install in the mycroft-core/scripts/logs/ folder)

**Comment by tiagochiavericosta** [comment]
Thanks for replying, I tested (K)Ubuntu 17.10 and 18.04, reinstalling both the dev and master versions of mycroft-core... the solution I found was to copy the mycroft.conf file to the ".mycrof" folder on the partition of user (cp mycroft.conf ~ / .mycroft).
In Portuguese: 
Obrigado por responder. Eu testei o (K)Ubuntu 17.10 e 18.04, reinstalando tanto a versão dev quanto a master do mycroft-core... a solução que encontrei foi copiar o arquivo mycroft.conf para a pasta ".mycrof" da partição do user (cp mycroft.conf ~ / .mycroft )

**Comment by forslund** [comment]
Glad it's working for you. A bit weird but anyway :)

Maybe the config overwrote the server for some reason?

**Comment by tiagochiavericosta** [comment]
News: I believe that the system is not accepting non English characters, such as "Ribeirão Preto - São Paulo" - my city - then the error occurs. You need to internationalize the source code, for example insert "# - * - coding: utf-8 - * -" in the headers.
In Portuguese:
Novidades: acredito que o sistema não está aceitando caracteres não ingleses, como por exemplo "Ribeirão Preto - São Paulo" - minha cidade - então ocorre o erro. Vocês precisam internacionalizar o codigo fonte, como por exemplo inserir "# -*- coding: utf-8 -*-" nos cabeçalhos.

**Comment by forslund** [comment]
I don't believe that's necessary, the coding should only affect the .py file not the config file. In addition to this I believe the move to python3 sets the coding to utf8 by default so the coding statement isn't needed at all anymore

**Comment by forslund** [comment]
Since there's been no update here in a while I'm closing the issue. Feel free to reopen if you feel it's still an issue.
