### ISSUE TITLE
custom skills

### ISSUE THREAD

**Issue by the7erm** [MycroftAI/mycroft-core#161]
Currently there is no architecture to create a 3rd party skill

- User dir `~/.mycroft/third_party_skills`
- `mycroft/third_party_skills`

**Comment by forslund** [comment]
Would this replace the [skill-sdk](https://docs.mycroft.ai/development/skills-sdk) approach or be in addition to it?

**Comment by the7erm** [comment]
No, it's intended to be used by 3rd party developers of skills.  It's for people like me who want to create custom skills and release them, but know that there's just no way it's going to be adapted to mycroft-core.
