### ISSUE TITLE
Real time speech to text conversion ?

### ISSUE THREAD

**Issue by b-ak** [MycroftAI/mycroft-core#1638]
How do I do a real time speech to text conversion like how Joshua Montgomery demos in the YouTube video ? The title talks about "Pitch Skill", but I did not find it in the skills repository.

Any directions on how to go about this ?

**I'm running a Mycroft on RPi3. I cloned the mycroft-core repo and built it.**

**Comment by el-tocino** [comment]
A pi3 won't handle speech to text on its own anywhere close to real time.  You'd need a separate server running an STT option to do so. IE, Deepspeech with an Nvidia 1070 can do roughly twice speech duration, but it doesn't do it real time yet.

**Comment by bhargav-ak** [comment]
It could get it running on a server with those capabilities. Any information on skills similar to pitch skill ?

**Comment by domcross** [comment]
Zamia-Speech has a [live-demo](https://github.com/gooofy/zamia-speech#live-mic-demo) that runs on a RPI3 with surprisingly short latency. @JarbasAI created the [local-speech-skill](https://github.com/JarbasAl/local-speech-skill/) for this.

**Comment by b-ak** [comment]
I'll give it a try..

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues, or reopen this issue if you feel it should not have been closed. 

Thanks
