### ISSUE TITLE
How to enable / change to the Mimic II / Mimic 2 voice?

### ISSUE THREAD

**Issue by M-arcus** [MycroftAI/mycroft-core#1639]
I couldn't find the docs or the command for changing the voice to Mimic 2.

How do I change to the mimic 2 voice?

**Comment by forslund** [comment]
The mimic-2 tts is still underdevelopment and not available in Mycroft yet. The model is still undergoing tweaks and training. I think it's looking like a release this month but can't say for sure.

**Comment by M-arcus** [comment]
@forslund Thanks for your quick answer. 

On this page https://mycroft.ai/blog/available-voices/ the release is said to be in April 2018. That's why I thought that Mimic 2 / Mimic II was already released.

**Comment by M-arcus** [comment]
@forslund Can you add a notice to the blog post? Or point me to the person, that is responsible for the blog?

**Comment by fermulator** [comment]
(where are the docs now? ;o)
