### ISSUE TITLE
Feature request: own wake-up word for skills like "playback stop"

### ISSUE THREAD

**Issue by gras64** [MycroftAI/mycroft-core#1643]
It would be possible for plugins such as "Playback Control" own Wake up for individual Pulgins.
That would be another step towards natural communication with mycroft AI.
For example, it would be possible to abort the playback with the short phrase "Playback Stop" or turn off the light with "Illumination Off".

**Comment by penrods** [comment]
While I find this interesting, I think there are some architectural reasons to stick with a single wake word for a while.  The main reason is that Wake Word engines are inherently limited today and can't take arbitrary words.  Allowing skills to define their own wake words will rapidly get out of control -- that's just the nature of things.

Down the road if we get to the point where more flexible wake word technology exists, I'd be willing to revisit.  And, of course, you are welcome to hack at Mycroft in general such as what Jarbas illustrated.  But I personally don't think skill-defined wake words/hotwords is going to get us to a good place in the near term.

**Comment by JarbasAl** [comment]
i don't think hotwords would be per skill, for that i agree with matthew, i have a local pocketsphinx listener that can be used inside skills with limited vocab

https://github.com/JarbasAl/local_listener

but i would love to have multiple hotwords for several reasons, I've messed around and used it in the following scenarios:

- multiple names, hey mycroft, hey computer. (specially helpful if some house member can't trigger the hotword easily)
- simple command/offline skills -  good manners, "hey mycroft..... thank you"(annoying to say) vs "thank you" (natural)
- secret skills / cheat codes - listening for hotwords and changing settings (konami code)
- stealth skills (no sound output) - hack the wifi

**Comment by krisgesling** [comment]
This does seem to be along the same track as #986 so closing this to keep all discussion on that issue. 

Let me know if I've misinterpreted something.
