### ISSUE TITLE
small numbers and Scientific Notation support in utility functions

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#1647]
a few considerations about extract_number and pronounce_number:

# names of small numbers support

like PR #1646 and #1642 do for big numbers, support for long and short scale (PR #1663 ) should be added for small numbers in order to include all languages

relevant information:

- https://en.wikipedia.org/wiki/Names_of_small_numbers
- https://en.wikipedia.org/wiki/Long_and_short_scales

# supporting Scientific notation

a lab setting is one of the places an AI assistant makes a lot of sense, this should be a default part of mycroft-core

extract_number ( PR #1652 ) and pronounce_number (PR #1653) should handle scientific notation, optionally if a flag is set

scientific notation pronouncing cases:

- (times/by) 10 to the (minus/negative/positive/plus/ ) (n/nth) (power / )
- (times/by) 10 to the power of (minus/negative/positive/plus/ ) n
- (times/by) 10 to the (minus/negative/positive/plus/ ) power of n
- (times/by) 10 (exponentiated/raised/elevated) to (minus/negative/positive/plus/ ) ( n / nth )

**Comment by forslund** [comment]
Closing this since it's a lingua-franca issue.
