### ISSUE TITLE
Feature request: Set up unknown requests under home.mycroft

### ISSUE THREAD

**Issue by gras64** [MycroftAI/mycroft-core#1674]
I tried to personalize Mycroft by starting the charming-answers-skill. I found that the effort is very large and the skill would eventually be confusing.

there are many questions that Mycroft should answer, i have some examples:
"why is the banana crooked"
"what are you holding by Alexa"
and many thousands of other such questions

Would it be possible to make an editor of these answers at home.mycroft. where everyone can enter a question and the corresponding answer. This response should then be reviewed by the community and then adopted as in the case of Deepspeech or Pecise.
this would be a separation by language and possibly also seriousness of the answer. whether funny or scientific.

**Comment by gras64** [comment]
I work on a skill to train sentence over voice look here https://github.com/gras64/learning-skill

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
