### ISSUE TITLE
Unable to install on ubuntu 18.04

### ISSUE THREAD

**Issue by skashish** [MycroftAI/mycroft-core#1699]
I am trying to install mycroft on ubuntu 18.04.

I followed following steps successfully.
`cd ~/`
`git clone https://github.com/MycroftAI/mycroft-core.git`
`cd mycroft-core`

After these, when I entered `bash dev_setup.sh`, I get 

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglib2.0-dev : Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

After this, I tried this

```
sudo apt install libpcre3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpcre3-dev : Depends: libpcre3 (= 2:8.39-9) but 2:8.41-1.1+ubuntu17.10.1+deb.sury.org+3 is to be installed
E: Unable to correct problems, you have held broken packages.
```
I think the problem is that mycroft wants libpcre3 (= 2:8.39-9) but I have a higher version installed.
Is it so? Also, I suspect I can't uninstall libpcre3 as many basic packages depends on it.

I also tried the following 

`sudo apt-get install libpcre3=2:8.38-3.1 libpcre3-dev=2:8.38-3.1 `

but got 

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '2:8.38-3.1' for 'libpcre3' was not found
E: Version '2:8.38-3.1' for 'libpcre3-dev' was not found



```
So, what shall I do now?

**Comment by forslund** [comment]
I just tested on a fresh ubuntu 18.04 image and it seems to be working for me. Try doing an `sudo apt-get update` and see if the version requirements updates so it's compatible. Otherwise you could try to somthing along the lines of [this](https://askubuntu.com/questions/813788/cant-install-libpcre3-dev)

**Comment by forslund** [comment]
Hi, since there's been no reply for more than 6 months I'm closing this issue. If you still have this issue feel free to reopen it.
