### ISSUE TITLE
weirdness pronouncing very large numbers

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#1718]
Seems to be some weirdness for large numbers:

>>> pronounce_number(10000000000)
'one trillion'
>>> pronounce_number(1000000000000)
'one trillion, , , , '

there also seem to be a small cosmetic issue with extra commas:

>>> pronounce_number(1000001)
'one million, , one'

from PR #1646

**Comment by nielstron** [comment]
On this, found an issue in format_en.py
PR following soonish
