### ISSUE TITLE
`log_level` and `ignore_logs` don't seem to be honored

### ISSUE THREAD

**Issue by ndarilek** [MycroftAI/mycroft-core#1728]
I have the following in ~/.mycroft/mycroft.conf:

```
  "ignore_logs": ["enclosure.mouth.viseme", "enclosure.mouth.display"],
  "log_level": "INFO"
```

Yet I still have very verbose logs like:

```
17:04:32.697 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/63d47614-e4ba-41c0-988c-ad374243e325/metric/timing HTTP/1.1" 200 335
17:04:32.763 - mycroft.messagebus.service.ws:on_message:41 - DEBUG - {"type": "enclosure.mouth.viseme", "data": {"until": 1534111472.894686, "code": "0"}, "context": null}
17:04:32.893 - mycroft.skills.settings:_request_my_settings:440 - DEBUG - getting skill settings from server for HomeAssistantSkill
17:04:32.910 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
17:04:32.911 - mycroft.messagebus.service.ws:on_message:41 - DEBUG - {"type": "enclosure.mouth.viseme", "data": {"until": 1534111473.0393858, "code": "2"}, "context": null}
```

I'm a screen reader user, and reading these logs is painfully tedious. Searching is OK if I know what to search for, but sometimes I don't. Enclosure logs aren't really useful for me since I don't have one, and the API calls to update settings almost always succeed, yet they're outputting 10 lines to the logs every 30 seconds.

I know there are ways to split the logs, and I know the default setup does this, but even when split up, too much information is too much information. It would be very helpful if Mycroft could honor these configuration settings so I can limit what gets logged.

Thanks!

**Comment by forslund** [comment]
The `log_level` seems to be only checked in the sys config `/etc/mycroft/mycroft.conf` /https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/log.py#L65([mycroft/util/log.py#L65](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/log.py#L65))

The `ignore_logs` is set in the cli config `~/.mycroft_cli.conf`

**Comment by forslund** [comment]
To make the logging respect the config in `~/.mycroft/mycroft.conf` the code at https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/log.py#L64

needs to be modified to also read the file `~/.mycroft/mycroft.conf` and do a check if the `log_level` is set there as well before falling back to the default DEBUG
