### ISSUE TITLE
Unable to to save settings on home.mycroft.ai: Javascript error TypeError: e is null

### ISSUE THREAD

**Issue by mathiasconradt** [MycroftAI/mycroft-core#1736]
It's not possible to save settings on home.mycroft.ai. Tested on Chrome and Firefox (latest versions) on Ubuntu Linux / Gnome.

JS error:

```
TypeError: e is null[Learn More] bundle.js:31:771
value
https://home.mycroft.ai/build/bundle.js:31:771
value/<
https://home.mycroft.ai/build/bundle.js:31:702
forEach self-hosted:268:13 value
https://home.mycroft.ai/build/bundle.js:31:667
value
https://home.mycroft.ai/build/bundle.js:31:1772
value
https://home.mycroft.ai/build/bundle.js:67:30519
value self-hosted:982:17 l</e.prototype.__emitToSubscription
https://home.mycroft.ai/build/bundle.js:103:22332
l</e.prototype.emit
https://home.mycroft.ai/build/bundle.js:103:22117
value
https://home.mycroft.ai/build/bundle.js:30:6875
value
https://home.mycroft.ai/build/bundle.js:51:16821
value self-hosted:984:17 r
https://home.mycroft.ai/build/bundle.js:9:4418
i
https://home.mycroft.ai/build/bundle.js:9:2753
```

![screenshot from 2018-08-14 21-45-15](https://user-images.githubusercontent.com/295122/44114465-9010d18e-a00b-11e8-894e-3bd9d7b86652.png)

**Comment by penrods** [comment]
Did this get resolved for you @mathiasconradt ?

**Comment by mathiasconradt** [comment]
@penrods No, not resolved - has there been an update? Getting this error when trying to save the settings.

![image](https://user-images.githubusercontent.com/295122/45218178-fafd0000-b2a6-11e8-98a8-5fe14c0f96d0.png)

**Comment by mathiasconradt** [comment]
@forslund When I click on Advanced, I don't even get that far. Just clicking on advanced already throws another JS error. I think there is somebody broken at the basis somewhere with the web app.

I tested it on Firefox and Chrome, just to be sure it's not my browser. And also disabled 

![image](https://user-images.githubusercontent.com/295122/45223592-f856d680-b2b7-11e8-836a-80923b6136d3.png)

**Comment by matheuslima** [comment]
@mathiasconradt can you send DM me on Mattermost the email associated with your home account? My user there is matheus-mycroft. With this information, I can see if your account has some problem with the database. Thanks.

**Comment by mathiasconradt** [comment]
@matheuslima done.

**Comment by mathiasconradt** [comment]
Support told me regarding https://mycroftai.freshdesk.com/helpdesk/tickets/3969 which is related:

> We just released a new version of Mycroft - you can update by leaving it plugged in (will update at the :04 past every hour) or also using the command line: sudo apt-get update && sudo apt-get install mycroft-core  

However, this doesn't help much.

I installed mycroft via github clone, not via apt. I just cloned and built the recent dev branch as of now (mycroft-core 18.8.0), and the issue still remains. 

Another question: which repos to add so that my Ubuntu finds the package.

**Comment by forslund** [comment]
I can't see the issue in question sadly but we currently don't have a package for Ubuntu. The one mentioned above must refer to the mark-1 or picroft.

**Comment by mathiasconradt** [comment]
I don't have mark1 nor picroft. I run it on plain Linux/Ubuntu. Right, therefore I was surprised I should run `apt-get install`.
Anyway, the issue remains. I don't mind changing the password to something else temporarily and giving a mycroft engineer my account info for debugging, as there is nothing confidential in it. Of course not via github comment.

**Comment by matheuslima** [comment]
I'm working on that now, there's a database inconsistency related to your account and that is breaking your settings.
