### ISSUE TITLE
Padatious Not Installed

### ISSUE THREAD

**Issue by chrismervyn** [MycroftAI/mycroft-core#1746]
`mycroft.skills.padatious_service:__init__:43 - ERROR - Padatious not installed. Please re-run dev_setup.sh
`
* I'm running a Mycroft on Linux Debian
* With the standard Wake Word

After running dev_setup.sh, one I first run the cli in debug, it complains of Padatious not being found and asks to re-run dev_setup and I have done that quite a few times so far.

Please help!

**Comment by forslund** [comment]
When running the dev_setup.sh script do you see any error messages related to installing python packages?

Which version of debian are you running? On Jessie I believe the libfann package may be too old (libfann should be >= 2.2, you can check with `apt list | grep libfann`)

If you have a multiarch system one of the dependencies for padatious the python package `fann2` can fail to install (if you have a multiarch-system). To check if there is an issue installing padatious you can run the following:

```sh
source venv-activate.sh
pip install padatious
```

**Comment by forslund** [comment]
That might be the issue. If you're gutsy you can try installing the package from stretch: https://packages.debian.org/stretch/libfann2, we do that on our mark-1's (running jessie).

Before you do anything maybe @MatthewScholefield can verify that libfann 2.2 is needed.

**Comment by chrismervyn** [comment]
Thanks for your quick reply. I really appreciate it. I have already started installing 2.2. I will update in a few.

**Comment by chrismervyn** [comment]
Finally got it to work. The fann2.2 did it. I just had to remove the virtualenv and then re-run dev_setup.

**Comment by forslund** [comment]
Good to hear!
