### ISSUE TITLE
ubuntu 14.04 missing screen

### ISSUE THREAD

**Issue by the7erm** [MycroftAI/mycroft-core#175]
It looks as if `screen` isn't installed by default in ubuntu 14.04.  It's required by [`mycroft.sh`](https://github.com/MycroftAI/mycroft-core/blob/master/mycroft.sh).
http://releases.ubuntu.com/14.04/ubuntu-14.04.4-desktop-amd64.manifest
It needs to be added to [`build_host_setup.sh`](https://github.com/MycroftAI/mycroft-core/blob/master/build_host_setup.sh)

**Comment by aatchison** [comment]
I wonder if we should keep build deps separate, becasue screen is really not needed at all unless you use the easy start script.
