### ISSUE TITLE
Don't use hardcoded paths or allow path updating

### ISSUE THREAD

**Issue by Arc676** [MycroftAI/mycroft-core#1787]
* I'm running Ubuntu 18.04
* With version `mycroft-core 18.8.0`
* With the standard Wake Word

## Steps to reproduce

1. Download Mycroft and run `dev_setup.sh`
2. Move the Mycroft folder somewhere else (I moved it into a subdirectory)
3. Start the command line interface for Mycroft

## Behavior

When I try to start the command line interface with `./start_mycroft.sh cli`, I get "No module named 'inflection' installed" (mentioned in #1733) instead of the command line interface.

I know the installation was successful because everything was working perfectly before I moved the folder. Yesterday, the `mycroft-core` repository was in `/path/to/mycroft-core`. The next day, I decided to try to write a Mycroft skill, so I made a new parent directory to contain all Mycroft-related folders, thus moving the core folder to `/path/to/mycroft-stuff/mycroft-core`.

I know there are hardcoded paths because I `grep`ped for `/path/to/mycroft-core` and found several results. After redoing the setup (as described below) I ran the search again and got no results.

## Workaround

I deleted the `mimic` and `.venv` folders and re-ran `dev_setup.sh`. Problem solved.

**Comment by forslund** [comment]
The way the linker works will make mimic hard to fix 100% (but I'll see if there's some way to link a relative path).
We're not really in control of the activate script but we can probably patch it after the venv is created to use a relative path.

Were there any other hardcoded paths I should look into?

**Comment by Arc676** [comment]
Thanks for the quick response.

From the `grep` search, the hardcoded paths are mainly the shebangs in the files in `.venv/bin`. They also appear in
```
./.venv/lib/python3.6/site-packages/_virtualenv_path_extensions.pth
Binary file ./.venv/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/__pycache__/__init__.cpython-36.pyc matches (a lot of binary files match)
Binary file ./mimic/.libs/compile_regexes matches
./mimic/.libs/libttsmimic.lai
...
```

There are lots of matches in various configuration files. I won't include everything here, but you can search using:
```
find . -type f -print -exec grep '/path/to/mycroft-core' {} \; | less
```

**Comment by j1nx** [comment]
Isn't the "--relocatable" although experimental the parameter to use when creating the virtualenv? That at least might fix the hard paths created by the pip install.

**Comment by forslund** [comment]
We don't use the virtualenv package. Instead we use the builtin venv module and I don't think that has the --relocatable flag.

**Comment by j1nx** [comment]
Right, my mistake. Indeed, the -m venv does not have the --relocatable flag.

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
