### ISSUE TITLE
Run Mycroft as a service?

### ISSUE THREAD

**Issue by jasonehines** [MycroftAI/mycroft-core#179]
I've setup my computer to start Mycroft automatically after login by adding `/bin/bash /home/jasonehines/Development/mycroft-core/mycroft.sh start` to my Startup Applications.

However, I wonder if it would be a better thing to make it a system service that still has user options. What would be the pros and cons? 

Pros:
- It could potentially be used as a replacement for disabled people to interact with things like the login screen
- On hardware (computer you don't log in to) it could be set to start after a network connection is established

Cons:
- Potential security risk with system level access
- Complicates programming by having to separate general requests from user requests

Those are just quick of the top-of-my-head pros and cons, but I figured I'd start the dialog.

I can write the systemd service scripts and LaunchDaemon for OS X (macOS) if it's wanted.

**Comment by aatchison** [comment]
If you take a look at publish/publsh.sh, you can see that we start system services for Mycroft on the units. I don't know what to do about multiple users, but run that script and it will create a db for you in ./publish.

**Comment by jasonehines** [comment]
Cool. I'll check that out.

**Comment by aatchison** [comment]
This issue really pertains only to packaged instances of Mycroft, not really to developers using the git checkout, so I'm going to close. Feel free to re-open if you need to.
