### ISSUE TITLE
Bad escapes in intent_service

### ISSUE THREAD

**Issue by permafuture** [MycroftAI/mycroft-core#1792]
I've just installed Mycroft-core from the git repo to a brand-new Manjaro Linux on a Lenovo laptop. 

I bushwhacked my way through dev_setup.sh until all the python2 deps were python3 instead, and replaced the call for pyyaml 3.11 with 3.13. That seems to have got me a successful install, at least to the point where I can pair Mycroft with the home.mycroft.ai service.

Now I'm hitting a wall and I can't seem to find anyone else with this problem. I think it has something to do with python 3.7 but not sure how to test that. 

THE PROBLEM: anytime I try to speak to Mycroft, through STT or through the CLI, it immediately gets hung up on the intent_service, failing to recognize a "\w" somewhere and throwing a standard error from re. 

You can find the error logs, or as much as I could grab from the screen, at https://gist.github.com/permafuture/8a81a26bd8b4823b62aab136f65cf14f . For some reason mycroft isn't saving logs to mycroft-core/scripts/logs? I don't know it that's at all related but it is confusing.

Thanks for any help you can give.
Max

**Comment by penrods** [comment]
I believe this is addressed here:
https://github.com/MatthewScholefield/padaos/pull/3

**Comment by permafuture** [comment]
Wow, thank you! I don't know that I ever would have found that on my own. 

This worked for me by changing into the venv and then pip install from git:
` source venv-activate.sh`
`pip install git+https://github.com/MatthewScholefield/padaos.git`

Now Mycroft lives and my life is okay again. Thanks @penrods!
