### ISSUE TITLE
Incidental findings from creating a Buildroot package

### ISSUE THREAD

**Issue by j1nx** [MycroftAI/mycroft-core#1796]
# My findings while creating a Buildroot package

I am in progress of creating a bare minimal embedded OS for Mycroft. Still in designing and tinkering process of how to best proceed. 

https://github.com/j1nx/MycroftOS/

I will step away from the whole virtual environment as the OS has only one purpose of running Mycroft. So no need to protect python package versions through the venv.

python-pip will be installed for use of the skills, however all mycroft python dependencies will be natively (cross)compiled and installed within the system (and possible already some more dependencies in advanced. Most likely the most used python packages that also have C bindings and such)

I would like to create this ISSUE as Work In Progress of all my findings, going through this process. (As I need to go through a lot of files with a fine tooth comb) and for discussion.

## Python unicode / asci decoding
Running Mycroft as system wide python package, shows the below error for two skills (I believe the npw news skill and the fallback unknown)

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mycroft/skills/core.py", line 136, in load_skill
    raise e
  File "/usr/lib/python3.6/site-packages/mycroft/skills/core.py", line 129, in load_skill
    skill.load_data_files(path)
  File "/usr/lib/python3.6/site-packages/mycroft/skills/core.py", line 1022, in load_data_files
    self.init_dialog(root_directory)
  File "/usr/lib/python3.6/site-packages/mycroft/skills/core.py", line 1013, in init_dialog
    self.dialog_renderer = DialogLoader().load(dialog_dir)
  File "/usr/lib/python3.6/site-packages/mycroft/dialog/__init__.py", line 123, in load
    join(path, f))
  File "/usr/lib/python3.6/site-packages/mycroft/dialog/__init__.py", line 49, in load_template_file
    for line in f:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 22: ordinal not in range(128)

Research shows this is most likely because of a locale setting error. However even with enforcing it to be en_US.UTF-8 (export LC_ALL=en_US.UTF-8) it still doesn't work. Python 3 changed some decoding defaults for " open(filename, 'r') ".

Couldn't fix it properly, so I am patching the mycroft code enforcing it by;
https://github.com/j1nx/MycroftOS/blob/7146f7f04d0e64d85ab387974aa388ea63d04ca5/package/python-mycroft/0001-Enforce-UTF8-encoding.patch

However, thinking now if it would not be best practice to do it like this and this encoding addition should not be part of the python 2 -> 3 conversion?

## Starting services not populating "~/" properly
I am starting the messagebus, audio, skills and speech services with an init script. However starting them like that does not adhere to the configuration path (populating "~/" to in our case "/root") Top of the log then basically shows;

17:40:30.341 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /usr/lib/python3.6/site-packages/mycroft/configuration/mycroft.conf loaded
17:40:30.362 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /usr/lib/python3.6/site-packages/mycroft/configuration/mycroft.conf loaded
17:40:30.375 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
17:40:30.388 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/.mycroft/mycroft.conf' not found
17:40:32.482 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/var/tmp/mycroft_web_cache.json' not found
17:40:32.491 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
17:40:32.498 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/.mycroft/mycroft.conf' not found

As you can see; It looks for the user's mycroft.conf at / instead of /root ???

However if I start the cli-client it shows;

17:43:46.534 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /usr/lib/python3.6/site-packages/mycroft/configuration/mycroft.conf loaded
17:43:47.085 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /usr/lib/python3.6/site-packages/mycroft/configuration/mycroft.conf loaded
17:43:47.634 - mycroft.configuration.config:load_local:124 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
17:43:48.179 - mycroft.configuration.config:load_local:129 - DEBUG - Configuration '/root/.mycroft/mycroft.conf' not found

There it shows /root/.mycroft/mycroft.conf ??? 

I am lost at the moment and can't figure out what is causing this behaviour as they both use the same configuration load function.

### <More to come, as we go..>

**Comment by forslund** [comment]
Nice finds. Thanks for reporting them.

**Comment by j1nx** [comment]
No problem! Will keep adding the small things I find while following all those python dependencies / requirements.

**Comment by j1nx** [comment]
Ah right, now I get that part!

Thinking a bit about it. Also with a previous statement about you guys stepped away from virtualenv using the venv module in another issue/topic.

Considering all the "pip install" user error installing pip under system-wide package management and such. Wouldn't it better to maybe look again at using virtuelenv and associated wrappers and such? Because than you can also make use of the tools available to sync --system-packages and such. Still tricky I understand for version control, but I believe it could be setup that system packages get synces within the venv if a system package is not installed within the venv. And if it is but the version in venv is lower it can be discarded, etc.

But anyway, above is seperate from the small findings I find here and there,

**Comment by forslund** [comment]
The suggested changes to dev-setup and requirements has been merged now. Should we close this or is there any outstanding issues remaining?

**Comment by j1nx** [comment]
Leave it open for the time being if you do not mind. 

I will cleanup above by removing what has been fixed, but as I am still developing the buildroot OS there might pop up more later down the road. Up till now I have only been fixing my own F-ups. 

Getting close to something useable though.

**Comment by j1nx** [comment]
Updated the first post. If some could have a look that would be great.

Firmware file for testing and/or have a look yourself can be downloaded from;
https://j1nx.stackstorage.com/s/6vIDwIIIlvYH3Vw

**Comment by forslund** [comment]
I missed the last update here, sorry. Did you get the config path issue resolved? It sounds a bit like the init script doesn't have a `$HOME` variable set?

**Comment by j1nx** [comment]
Yes and No. The standard (very) minimal init system of busybox was so minimal, those typical $HOME variables are not set (yet) that early in the boot process.

https://github.com/j1nx/MycroftOS/issues/14

This issue together with some other issues and the fact that I need udev and dynamic loading of drivers and such made me switch to use systemd + udev as/and standard linux init system. This off course solved the issue, so didn't look any further.

Still some other small issues here and there, but didn't had much time lately, so perhaps they are already solved. Report back as soon as other issues surface.

**Comment by forslund** [comment]
Hi @j1nx is this issue still alive? Is there currently anything we should act on here?

**Comment by j1nx** [comment]
No, you are right. Apologies, this can be closed.

The Buildroot stuff is all done. The "issues" I currently run into, I have and will report at the specific repositories.
