### ISSUE TITLE
Feature Request: Expand units for speaking

### ISSUE THREAD

**Issue by nielstron** [MycroftAI/mycroft-core#1802]
Just like the currently available methods [`nice_number`](https://github.com/MycroftAI/mycroft-core/blob/bd6f9ffde1baf00606ba0eb0a12382a24ec6abad/mycroft/util/format.py#L193) for converting an integer to a nicely speakable version, there could be a method `nice_unit` or `expand_unit` for converting string containing units to a speakable string.

i.e. "The power plant produced 10Wh today" => "The power plant produced ten watt hours today"
"The bathroom temperature is 22 C" => "The bathroom temperature is twenty two degrees celsius"

There exist tools for unit extraction from unstructured text like [quantulum](https://github.com/marcolagi/quantulum) (or its python3 equivalent with further development [quantulum3](https://github.com/nielstron/quantulum3)).
These tools can be used (or supply a method, see `inline_parse_and_expand` at quantulum3), to convert the unit into a string. 

It can be a very helpful method, used to expand wikipedia articles, wolframalpha answers or home assistant replies.

**Comment by forslund** [comment]
This is something for [lingua-franca](https://github.com/MycroftAI/lingua-franca/) now. Closing the issue here.
