### ISSUE TITLE
Unit tests for the dialog loader

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#1829]
Currently there are no dedicated tests for the dialog renderer system:

https://coveralls.io/builds/19246383/source?filename=mycroft/dialog/__init__.py

A couple of simple tests ensuring that comments aren't loaded as dialog could be a nice addition.

**Comment by nielstron** [comment]
On it

**Comment by nielstron** [comment]
> A couple of simple tests ensuring that comments aren't loaded as dialog could be a nice addition.

@forslund what do you mean with that? Typical python like comments are rendered in the result. (i.e. in `Hello # this is a comment`

**Comment by forslund** [comment]
Sorry about that. I missremembered. It turns out only voc-files handled this. Last Friday I created #1847 implementing this.

**Comment by forslund** [comment]
#1847 has been included and more tests for dialogs as well. Closing this issue.
