### ISSUE TITLE
Invalid escape sequence in regex in remote_tts

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#1844]
[mycroft/tts/remote_tts.py](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/tts/remote_tts.py#L58) has an couple of invalid escape characters in a regex.

To fix this, the regex string `'\.+[\s+|\n]'` should be turned into a raw-string (r''). (More info on this can be found [here](https://docs.python.org/3/howto/regex.html)

This is not a major issue right now but python 3.7+ may have issues with these sort of invalid escape sequences.

**Comment by psal93** [comment]
Hi there, I would like to work on this.

**Comment by forslund** [comment]
Closed by #1845
