### ISSUE TITLE
Strange permission issues 

### ISSUE THREAD

**Issue by ftyers** [MycroftAI/mycroft-core#1850]
When running the `dev_setup.sh` script on Linux, the code asks to write to `/usr/local/lib/netscape/mime.types`. It shouldn't be necessary to have to write to a global file like this... 

```
+ cd /home/ADS/ftyers/Codi/mycroft-core
++ python -c 'import sys;print('\''python{}.{}'\''.format(sys.version_info[0], sys.version_info[1]))'
+ PYTHON=python3.5
+ VENV_PATH_FILE=/home/ADS/ftyers/Codi/mycroft-core/.venv/lib/python3.5/site-packages/_virtualenv_path_extensions.pth
+ '[' '!' -f /home/ADS/ftyers/Codi/mycroft-core/.venv/lib/python3.5/site-packages/_virtualenv_path_extensions.pth ']'
+ grep -q /home/ADS/ftyers/Codi/mycroft-core /home/ADS/ftyers/Codi/mycroft-core/.venv/lib/python3.5/site-packages/_virtualenv_path_extensions.pth
+ pip install -r requirements.txt
Collecting six==1.10.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting requests==2.19.1 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting gTTS==1.1.7 (from -r requirements.txt (line 3))
Could not install packages due to an EnvironmentError: [Errno 13] S’ha denegat el permís: '/usr/local/lib/netscape/mime.types'
Consider using the `--user` option or check the permissions.
```

**Comment by KathyReid** [comment]
Hi there @ftyers, thank you for reporting this. 
Are you able to let us know which distro you're on? 
The `dev_setup.sh` does a bunch of distro-specific things, and I suspect this is due to a particular package in a particular distro. 

Best, Kathy

**Comment by forslund** [comment]
Hi @ftyers @KathyReid is probably right. It looks like the virtualenv isn't created/activated before installing the python modules required for mycroft-core. and pip tries to install to the system.

Alternatively pip failed to install into the venv and the pip in the system is being used instead.

Could you delete the venv folder 

`rm -rf .venv`

and then run the dev_setup script and saving the output:
`bash -x dev_setup.sh 2>&1 | tee dev_setup.out`

and then posting the dev_setup.out on pastebin.com or as a github gist?

Also as Kathy said the distro would also be nice to know.

**Comment by ftyers** [comment]
@KathyReid It's Ubuntu ... I'm trying to install it in a really weird setup (thanks to my university) where I have two accounts, one normal account and one account that has `sudo`. I have to log into the normal account and then `su` to the other account if I need to `sudo` something.

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
