### ISSUE TITLE
Mycroft installs skills in /opt and logs in /var

### ISSUE THREAD

**Issue by ftyers** [MycroftAI/mycroft-core#1854]
I'm using Debian and would like to use Mycroft in a separate directory, not in the system directory.

```
+ echo 'Creating /var/log/mycroft/ directory'
Creating /var/log/mycroft/ directory
+ [[ ! -d /var/log/mycroft/ ]]
+ sudo mkdir /var/log/mycroft/
[sudo] contrasenya per a ftyers: 
```

And:

```
$ bash start-mycroft.sh debug
Starting all mycroft-core services
Initializing...
Create /opt/mycroft/skills
[sudo] contrasenya per a ftyers: 
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
```

It shouldn't be hard to have these be relative paths, e.g. created in a `$prefix` with `--prefix` or something like that.

**Comment by el-tocino** [comment]
The logs go to the /var/log directory now, though they prefixed with mycroft-.

**Comment by ftyers** [comment]
@el-tocino yeah, but I'd like them to go in a prefix, for example `/home/ftyers/local/var/logs`. I keep top level directories (`/var`, `/etc`, `/opt`, `/usr`) for programs installed by my package manager, and I think this is fairly common practice.

**Comment by penrods** [comment]
Getting people to the log files has been a surprising big deal, especially when talking about the variety of platforms and the level of users.  I'm not completely opposed to making this an option, but it isn't trivial -- it impacts code, install scripts, crontab jobs and documentation.

Skills CAN be installed in an alternative location.  That is a setting under https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/configuration/mycroft.conf#L92 which can be overriddent in your ~.mycroft/mycroft.conf file.

Also, logs go in /var/logs/mycroft/*.log now and are rotated.

**Comment by krisgesling** [comment]
If I'm not mistaken this should be possible using XDG defined paths with #2687

**Comment by PureTryOut** [comment]
@krisgesling yes with XDG defined paths, but #2687 doesn't allow that. https://github.com/MycroftAI/mycroft-skills-manager/pull/90 however will.

Logs will indeed be written to a different place in #2687, but I'm actually planning to do the system-wide installation differently and will close that PR. However, I am still planning on moving logs to `$XDG_CACHE_DIR`.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
