### ISSUE TITLE
Mycroft uses startswith with two-letter iso codes which could be ambiguous

### ISSUE THREAD

**Issue by ftyers** [MycroftAI/mycroft-core#1863]
In the file `mycroft/util/parse.py`:
```
    if lang_lower.startswith("en"):
        return extract_datetime_en(text, anchorDate, default_time)
```

You don't have Lithuanian (`lt`, `lit`) at the moment, but if you did, then it would be ambiguous in this statement with Luxembougish (`ltz`). A quick hack would be to change the code to 

```
if lang_lower.startswith("en-"):
```

If the purpose of using `startswith` is to be able to match things regardless of country/location. 

This kind of `elif` structure might not be the best way of dealing with things in general, e.g. if scaling to 100s or 1000s of languages.

**Comment by forslund** [comment]
This is being updated in the [lingua-franca](https://github.com/mycroftai/lingua-franca) project right now. Closing the issue here
