### ISSUE TITLE
Wolfram Alpha skill frequently does not work

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#187]
The WA skill always gets responses back from the WA API, but cannot correctly get information from many of them.

**Comment by ethanaward** [comment]
Addressed by #188. Anyone should feel free to test out that new change and see how they feel about WA's new responses.

**Comment by ethanaward** [comment]
Also - #188 may have also not addressed all the Wolfram problems, as there could still be edge cases that this change does not help. There could also be some cases where Mycroft grabs information that is not related to the intended query.

**Comment by aatchison** [comment]
Since we have several PRs merged that address these issues, I am closing this one. More specific errors can be a new issue.
