### ISSUE TITLE
new util, all number pronounciations

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#1875]
pronounce_number methods always output the same string, however numbers may have different pronounciations

"half" = "one half" = "zero point five" = "zero dot five" ....

a util method for all pronounciations would allow to have varied dialog

this new method should also take a couple flags:
- ordinal
- scientific notation 
- long scale

by accounting for "one million" vs "millionth", all the ways to pronounce scientific notation and long vs short scale (this one could probably be hardcoded per language) would also solve the TODO on the extract multiple numbers PR #1867 (which fails when pronounce and extract number don't match), it would improve normalization as well

**Comment by forslund** [comment]
This I think is being handled over in lingua-franca. Closing the issue here.
