### ISSUE TITLE
Mycroft is too light of a sleeper

### ISSUE THREAD

**Issue by Wolfgange3311999** [MycroftAI/mycroft-core#189]
After saying "mycroft sleep", the next time he hears "mycroft" he will wakeup (Even if you didn't say "mycroft wakeup".

**Comment by ryanleesipes** [comment]
True dat.

**Comment by Wolfgange3311999** [comment]
Options:
 - Change phrase from "wake up" to "time to wake up"
 - Change behavior so "hey mycroft wake up" becomes the recognizer (the old way)
 - Verify with externel STT (combined with above)

**Comment by Wolfgange3311999** [comment]
Note: it turns out the current implementation in fact does work alright provided that the threshold be decreased.
