### ISSUE TITLE
using mycroft over phone call

### ISSUE THREAD

**Issue by seniorivn** [MycroftAI/mycroft-core#1892]
I have an idea to set setup gsm modem as an input/output audio devices for mycroft so i would be able to interact with it just by calling it

- Does anyone wants the same?
- any ideas on implementation? i'm new to this project so it would be really helpful if you hint me on the path to implement this
- maybe this is already implemented?

**Comment by KathyReid** [comment]
Hi there @seniorivn, thanks for your suggestion. 
The best place for this suggestion is our [Skill Suggestions](https://community.mycroft.ai/c/skill-suggestions) topic on the Mycroft Forum, where people discuss which Skills they would like to build, and seek community feedback on them.
