### ISSUE TITLE
Strange pronunciation of abbreviations like U.S.A

### ISSUE THREAD

**Issue by andlo** [MycroftAI/mycroft-core#1895]
Mycroft is Ok at pronunciate USA, but if text is U.S.A he dosnt reconize it as one abbreviation but says each letter and the dot makes him waite like at teh end of a sentense. 

He should think that if tehre is a big letter dot bigletter dot and no spaceses it is the same as big letters whitout the dots.

**Comment by forslund** [comment]
Thanks for reporting. Which voice / tts were you using?

**Comment by andlo** [comment]
I am using mimic2. Didnt relaize it were specifik for the voice / tts.

**Comment by forslund** [comment]
@andlo, the tool for helping with mimic-2 pronunciations can be found here: https://mimic.mycroft.ai/pronounce

I've submitted one u.s.a. that sounded weird. Feel free to add more exceptions :)

Are you ok with closing the issue at that?

**Comment by andlo** [comment]
Yah that is link and submission is the way to solve this. So closing :) Thanks.
