### ISSUE TITLE
mycroft-core dev_setup fails due to existing aclocal file

### ISSUE THREAD

**Issue by SteveHigham** [MycroftAI/mycroft-core#1896]
## Be clear about the software, hardware and version you are running
Installing mycroft-core from latest dev branch (02-Dec-2018)
Installing into Ubuntu 18.04 with gnome

## Try to provide steps that we can use to replicate the Issue
Running ./dev_setup.sh produced the following error:
------
Building with 8 cores.
Install from /home/steve/mycroft-core #my debug
WARNING: The following can take a long time to run!
Fetching origin
Fetching all-branches
HEAD is now at 67e43bf Bump version to 1.2.0.2
main::scan_file() called too early to check prototype at /opt/chefdk/embedded/bin/aclocal line 622.
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /opt/chefdk/embedded/bin/automake line 4153.
---------

For some reason the mycroft installer was running the aclocal perl script in my Chef installation under /opt/chefdk/  Deinstalling Chef solved the problem but this should not be necessary.

**Comment by forslund** [comment]
Hi, thanks for reporting. It sounds a bit like a non-standard aclocal was used in place of the systems normal copy. I did a quick google and found this: https://github.com/chef/chef-dk/issues/313 Is that similar to your issue?

**Comment by SteveHigham** [comment]
Hi Åke,

Yes, this looks like the same issue. It never occurred to me that the embedded bin was on my PATH! I do use chef shell-init so that makes perfect sense.

Many thanks for your help,

Steve

**Comment by forslund** [comment]
No problem. Do you consider this question resolved or is there any action you feel we should take here?

**Comment by SteveHigham** [comment]
This is resolved. It was a Chef issue as you identified.

The Chef DK (development kit) is now being phased out and replaced with “Chef Workstation” which doesn’t have the same issue. Therefore it has also been resolved at the Chef end although I suspect many users are still using the DK.

As an aside do you know anyone using Mycroft to control an Ubuntu desktop? I’m trying to do some development work with only my left hand due to a dislocated right shoulder. It’s VERY SLOW! I see there is a Desktop-Conrol skill but it’s pretty basic and development seems to have stopped..

Many thanks for your help resolving my issue.

Kind Regards,

Steve
