### ISSUE TITLE
Multilingual Mycroft

### ISSUE THREAD

**Issue by beemorris** [MycroftAI/mycroft-core#1898]
Hello! I was wondering if it is or if it will be possible to use Mycroft in multiple languages simultaneously? I would like to be able to use Mycroft in English and Swedish, but I don't think that this is currently possible, and I think having Mycroft be multilingual would be a feature that a lot of people would use. Thank you!

**Comment by ftyers** [comment]
It would also be la hostia si Mycroft pudiera permitir codeswitching! :D

**Comment by forslund** [comment]
I for one would really like that. It's something we've briefly talked about and will happen down the road. Hopefully sooner rather than later.

**Comment by Extarys** [comment]
I would be amaze if I could use it in english and french! That would be awesome!

**Comment by penrods** [comment]
At the moment, the core technologies (STT / TTS) are built around a single language.   I see two approaches to become multi-lingual:
* Maintain single-language technologies and switch between tech based on some trigger.  E.g. "Hey Mycroft" hotword makes it operate in English, "Bork bork" hotword makes it operate in Swedish (or at least Swedish Chef).  This would not allow mixing of languages within a single interaction.
* We train multi-lingual models for STT and TTS.  Specifically, I can imagine Language X + English.  This approach would not support the system speaking French and Spanish, for example.  This would allow mixing of languages in the same interaction.

Both of the above seem in striking distance.   Other approaches such as arbitrary, dynamic language detection seem more likely to fail in the near term.


Regardless, this is not on the main development roadmap for quite some time.  At least a year, unless something major changes.

**Comment by Extarys** [comment]
I think your first approach is simpler and I, personally, would be very happy with that.

- Yo Mickey (English)
- Hey Mike (French, shorter for main/prefered language)

**Comment by ChanceNCounter** [comment]
I think this issue could benefit from separate discussions for each of the moving parts:

* Multiple passes at utterances to determine language
* STT (streaming STT determines language ASAP, can't afford to wait)
* TTS (how does it pick a language to reply with?)
* Wake word switching?
* Lingua Franca
* Mycroft config (user/system)
* Language switching intent (tweak settings by voice, or just switch/add languages?)

Also, any solution to this is probably an inherent solution to *switching* the *one* language that Mycroft is using, for folks who don't want a multilingual assistant.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
