### ISSUE TITLE
some functions are too complex

### ISSUE THREAD

**Issue by elopio** [MycroftAI/mycroft-core#19]
Anything with a mccabe number greater than 10 is way too complex.

⟫ flake8 --max-complexity=10 . | grep complex
./mycroft/client/speech/mic.py:106:1: C901 'Recognizer.listen' is too complex (16)
./mycroft/client/speech/recognizer_wrapper.py:59:1: C901 'CerberusGoogleProxy.transcribe' is too complex (11)

Getting the complexity even lower than 10 is great for readability.

**Comment by jdorleans** [comment]
Couldn't agree more. : ) 
We do still have to clean up and improve the code. I'm doing some enhancements for the recognizer (hope to merge soon), but some of those files may require refactoring, which means more care and time. Everybody is welcome to accelerate this process.

**Comment by ryanleesipes** [comment]
@elopio perhaps we can narrow the scope of this by identifying where the most egregious offenders are and targeting them?

**Comment by ryanleesipes** [comment]
Assigning to @jdorleans to review.

**Comment by jdorleans** [comment]
I'm closing this issue since it's something we have to care about daily and its scope is largely applicable for many of our current code. I'll, however, implement a better way to keep tracking and help us to improve issues related to source code quality.
