### ISSUE TITLE
Local Precise models trying to be updated extraneously.

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mycroft-core#1908]
## Be clear about the software, hardware and version you are running
* I'm running a Mark 1
* With version 18.8.1 of the Mycroft software
* With a custom wakeword.

## Try to provide steps that we can use to replicate the Issue
This function: https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/hotword_factory.py#L169 
makes my custom models fail to load pretty reliably.

Log snippet:
```
11:39 PM
15:28:22.661 - mycroft.client.speech.hotword_factory:initialize:281 - ERROR - Could not create hotword. Falling back to default.
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/client/speech/hotword_factory.py", line 269, in initialize
    instance = clazz(hotword, config, lang=lang)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/client/speech/hotword_factory.py", line 140, in __init__
    ).replace('.tar.gz', '.pb')
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/client/speech/hotword_factory.py", line 175, in install_model
    on_download=lambda: LOG.info('Updated precise model')
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/petact/petact.py", line 112, in install_package
    with tarfile.open(data_file) as tar:
  File "/opt/venvs/mycroft-core/lib/python3.4/tarfile.py", line 1553, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully (edited)
```
As this returns an error, it then reverts back to pocketsphinx. 

File exists, is a valid tar.gz, permissions are correct (0666).  

I cut the install_package parts and inserted a silly LOG.info bit instead, and things work.

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

I would expect that if it finds a valid model locally, it would load that.  Instead it's trying to install_package every time it's called.  

## Provide log files or other output to help us see the error

See above.

**Comment by forslund** [comment]
Ok, that doesn't sound too good. I'll ping @MatthewScholefield on this issue as well.

Do you have a config snippet for the setup of the custom wake word as well? I wouldn't think that this code would run if the `'local_model_file'` config variable is set...

**Comment by el-tocino** [comment]
Config for the above issue:

```  "hotwords": {
    "hey mycroft": {
      "module": "athena",
      "phonemes": "AE TH IY N AH",
      "threshold": 1e-25,
      "lang": "en-us",
      "local_model_file": "/etc/mycroft/precise/models/athena.pb"
    }
```

If I change the hotword to athena, as such:
```
"hotwords": {
    "athena": {
      "module": "athena",
      "phonemes": "AE TH IY N AH",
      "threshold": 1e-25,
      "lang": "en-us",
      "local_model_file": "/etc/mycroft/precise/models/athena.pb"
    }
```
Then I get the "precise taking too long to load" message.  Which is also weird.

**Comment by MatthewScholefield** [comment]
The `"module"` parameter actually refers to the wake word module that it uses (ie. "precise" or "pocketsphinx"). And the `local_model_file` only works with `.pb` files. See what happens if you try it like this:
```json
{
    "listener": {
        "wake_word": "athena"
    }
    "hotwords": {
        "athena": {
            "module": "precise",
            "local_model_file": "/etc/.../athena.pb"
        }
    }
}

**Comment by el-tocino** [comment]
Well....that explains a lot.

**Comment by MatthewScholefield** [comment]
We should probably document that somewhere though :)
