### ISSUE TITLE
Add "do not exit on error" flag

### ISSUE THREAD

**Issue by Batcastle** [MycroftAI/mycroft-core#1913]
Running: Mycroft-core Version 18.8.9, using Wake Word "Hey Jarvis"

Issue:
If `apt` throws an error, but otherwise is perfectly fine, `dev_setup.sh` will fail.
This is common with unsigned kernels on machines with Secure Boot.

Have to comment out line 42 in `dev_setup.sh` in order to update Mycroft manually and/or rebuild mimic.

**Comment by forslund** [comment]
Closed by #1914.
