### ISSUE TITLE
remove hardcoded en-us from CLI

### ISSUE THREAD

**Issue by gumulka** [MycroftAI/mycroft-core#1917]
When asking for confirmation with a yes-no question
(ask_yesno in mycroft/skills/core.py) mycroft expects the answer to be either yes or no, independent of the language.

So in any other language other than English, ask yes/no does not work.

## Try to provide steps that we can use to replicate the Issue

  * Set language to any other language other than English.
  * Start an alarm
  * try to cancel the alarm.
  * Answer in your native language to yes/no, instead of yes/no

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

either ask_yesno should translate the native yes/no like (ja/nein), (si/no) to English and return yes/no, or it should return true for yes and false for no.

## Provide log files or other output to help us see the error
Should be attached. Output of
```
cat /var/log/mycroft/skills.log | grep -v urllib3 | grep -v "TimeSkillupdate_display" | grep -v UpdateRemote
```

**Comment by gumulka** [comment]
[logfile.txt](https://github.com/MycroftAI/mycroft-core/files/2710894/logfile.txt)

**Comment by penrods** [comment]
Is \mycroft\res\text\XX-XX\yes.voc and no.voc localized?  Also, from the log it looks like your language is still set to English  -- see all of the "lang": "en-us"

**Comment by penrods** [comment]
Note -- inside the _code_ it will return the values 'yes' for the programming logic, regardless of the localization setting.  That makes writing the code easy, such as

```
   if self.ask_yesno("question") is "yes":
       # handle the 'yes' response, even if the spoken response was "ja" or "si'
```

**Comment by gumulka** [comment]
Thanks for the respond. Did not know about the res/text/XX-XX files. Definitely good to know, but yes, they are localized.

I found out, why there is so much en-us in my logs.
I switched between typing in commands and using the mic, as I was testing some stuff and most of the time it is more convenient to use the command line.

Most plausible reason for my bug above: The text client does not respect the users choice of language.
Found in mycroft/client/text/test_client.py:1261
In function gui_main:

Whenever something is typed on the command line, the GUI Main emits a message to the bus with the language set to "en-us"

Could you either make the command line message lang a variable in the mycroft_cli.conf file, or get it from mycroft.conf?

**Comment by forslund** [comment]
Ah, that's a really good catch. Would explain this quite neatly!

**Comment by gumulka** [comment]
I changed the hardcoded value in the CLI interface for now, but still mycroft does not accept "ja" as a response.
[fixed CLI.txt](https://github.com/MycroftAI/mycroft-core/files/2712313/fixed.CLI.txt)

Tried it again with "Ja" as it could be an upper/lower case problem:
[fixed CLI2.txt](https://github.com/MycroftAI/mycroft-core/files/2712322/fixed.CLI2.txt)
but it still does not seem to work.

Kind regards
Fabian

**Comment by forslund** [comment]
Hmm, I tested in Swedish and for me it works using the cli out of the box without any modifications. Will keep investigating.

**Comment by gumulka** [comment]
Did you try it with the alarm skill?

I will try to set up another environment on my development machine and try it again there with a simpler skill. Maybe it is somewhere else.

**Comment by forslund** [comment]
This was using a simplified case where the only thing the intent handler did was to run the ask_yesno method.

I'll try with the alarm skill as well...

**Comment by domcross** [comment]
NOTE: the wrong "en-us" language tag causes another issue as the wrong normalize-function (`mycroft/util/lang/parse_XX.py`) is called when typing a phrase in `mycroft_cli_client`. 
The english normalize removes article "an" which causes german phrase "schalte das licht an" ("turn the light on") not being recognized by intent parser as the action keyword "an" is missing.
The same phrase spoken is recognized correctly by intent parser as lang-tag is then "de-de".

**Comment by forslund** [comment]
Thanks for identifying that issue as well. Would you like to submit a PR with a fix or do you want me to do it?

**Comment by domcross** [comment]
Is `self.lang` accessible in this context? If yes it is probably sufficent to change line 1259 of `mycroft/client/text/text_client.py`to something like:

`bus.emit(Message("recognizer_loop:utterance", {'utterances': [line.strip()], 'lang': self.lang}))`

Unfortunately I don't have my dev-environment available (and it will take me a few days to get access to it), so I can't test it or create a PR - please go ahead if you have a working solution...

**Comment by forslund** [comment]
Hmm Seems like the cli is only using a cli specific configuration at the moment so it's not easily available...

Settings are basically loaded once in the `load_settings()` function so I'd add code there to load the mycroft config and then store the lang code in a global variable.

**Comment by forslund** [comment]
Had some time on the train and pushed #1925 to address this issue.
