### ISSUE TITLE
American male voice response inaccurate - different readout from CLI console result

### ISSUE THREAD

**Issue by vmajor** [MycroftAI/mycroft-core#1926]
Running: Ubuntu 18.04
Version: dev branch  VersionCheckerSkill - INFO - Current version: [18, 8, 9]
Voice used: American Male (Beta)
Problem: When asking for a forecast, Mycroft gives this response in the CLI:

" Thursday it will be light snow, with a high of 7 and a low of -4"

however, Mycroft American Male reads it as:

" Thursday it will be light snow, with a high of 7 and a low of 4" <-- no MINUS prefix. That's a rather large error

**Comment by forslund** [comment]
Once again a big thank you for reporting the issue. I can't overstate the importance of these reports. We try to be as quick as possible to respond to them, sometimes it takes time to fix other times it's quick (like this one).
