### ISSUE TITLE
Feature request:  Change microphone via CLI

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#1937]
PR #1936 made it fairly easy to select the active microphone.  It should be straightforward to add a mechanism to the CLI that allows picking the mic input, which would be handy in various scenarios.

The code would just need to write to ~/.mycroft/mycroft.conf, updating:
```json
{
   "listener" : {
        "device_name": "xxx"
    }
}
````

**Comment by joshuajaharwood** [comment]
How could we go about enumerating available microphones?

**Comment by krisgesling** [comment]
My first thought would be to look into the devices that get listed by the [current audiotest](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/troubleshooting/audio-troubleshooting#specifying-an-input-device). The code for that can be found under `mycroft-core/mycroft/util/audio_test.py`

In terms of how they're set, I am assuming we don't want to set these as overall system defaults in pulseaudio, particularly for desktop users?

**Comment by forslund** [comment]
Easiest will likely be to use the listener [config](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/configuration/mycroft.conf#L172) (device_name or device_index) to set the port audio input device used by the listener as suggested by @penrods.

The audio_util file also contains a name -> port audio device index function [find_input_device](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/audio_utils.py#L188) which may be leveraged for text input of the device.

**Comment by joshuajaharwood** [comment]
> In terms of how they're set, I am assuming we don't want to set these as overall system defaults in pulseaudio, particularly for desktop users?

For people running more than just Mycroft on one machine, this might be a good idea. It'd make setting up a background audio players like raspotify and mopidy easier. What if we give users the option of applying the changes system-wide, as opposed to just in Mycroft?

**Comment by forslund** [comment]
To me that feels backwards. Better to set global things in the system and set mycroft-specific things in Mycroft.

Doing things systemwide may be another can of worms since the audio system may vary, version, type etc.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
