### ISSUE TITLE
feature: supporting new intent engines

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#1938]
i did some work to make it easy to add new intent engines, logic is based on padatious intent service

new intent engines would be packaged as skills

https://github.com/JarbasAl/mycroft_intent_engines

the base classes could be integrated into mycroft core itself and padatious refactored to use it

the readme is pretty detailed and i included an examples folder

will make a PR when i find some time for it, mostly wanted to flag this for feedback and so i wouldn't forget

to be clear im not suggesting adding more intent engines, just the ability to support them

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
