### ISSUE TITLE
Wolfram should be more concise

### ISSUE THREAD

**Issue by Wolfgange3311999** [MycroftAI/mycroft-core#194]
For instance, when asking "What is a power", it should read only the first definition rather than all 10.

**Comment by ethanaward** [comment]
This is related to a larger issues with parsing Wolfram output as well, since Mycroft frequently gives back responses that don't sound very natural.

**Comment by Wolfgange3311999** [comment]
I don't know if there's a unified solution to them all. However, would it be effective to read a minimum of of certain amount of characters and then stop on the next newline?

**Comment by ethanaward** [comment]
Stopping on a newline would likely help somewhat, especially with the definitions.

**Comment by ethanaward** [comment]
We'll likely want to have some kind of discussion about this to determine how we want Wolfram output formatted.

**Comment by marksev1** [comment]
An idea would be too that one could then trigger to read further with: "Read on."

**Comment by isaacnward** [comment]
Solved by #302.
