### ISSUE TITLE
Rejected custom Wake Word generates an unhandled RuntimeError 

### ISSUE THREAD

**Issue by wsw70** [MycroftAI/mycroft-core#1940]
## Be clear about the software, hardware and version you are running

* I'm running a Picroft
* With version 18.8.10 of the Mycroft software
* With a custom Wake Word 

## Try to provide steps that we can use to replicate the Issue

I wanted to change the standard wake up word and the one I chose (and "phonemized" from other words) was not accepted. This is an inconvenience but I need to further dig why it was not (it i snot a rela word).

Mycroft however dumped a Traceback when refusing this word:

```
12:28:49.991 - mycroft.client.speech.hotword_factory:initialize:288 - WARNING - Could not found find model for dillpenza on precise.
12:28:50.142 - mycroft.client.speech.hotword_factory:initialize:293 - ERROR - Could not create hotword. Falling back to default.
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/client/speech/hotword_factory.py", line 281, in initialize
    instance = clazz(hotword, config, lang=lang)
  File "/home/pi/mycroft-core/mycroft/client/speech/hotword_factory.py", line 85, in __init__
    self.decoder = Decoder(config)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/pocketsphinx/pocketsphinx.py", line 277, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

```

This is not a show stopper as Mycroft fell back on the default word but I guess that the the Traceback is not expected.

**Comment by forslund** [comment]
Thanks for reporting. Can you provide the wakeword and phonemes that results in this runtime error?

We would probably need to detect which phonemes and settings that would make pocketsphinx fall over like this so an example would be great.

**Comment by forslund** [comment]
Ping? Did you have a wake word to try it on?

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
