### ISSUE TITLE
401 responses on /v1/device calls (audio.log)

### ISSUE THREAD

**Issue by wsw70** [MycroftAI/mycroft-core#1941]
## Be clear about the software, hardware and version you are running

* I'm running a Picroft
* With version 18.8.10 of the Mycroft software
* With the standard Wake Word (actually a custom one which is rejected, still investigating why - Mycroft fell back on the standard one)

## Try to provide steps that we can use to replicate the Issue

When looking though `/var/log/mycroft/audio.log` I find sequences of the following calls:

```
13:25:07.988 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/ HTTP/1.1" 301 106
13:25:07.999 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): api.mycroft.ai:80
13:25:08.174 - urllib3.connectionpool - DEBUG - http://api.mycroft.ai:80 "GET /v1/device HTTP/1.1" 302 0
13:25:08.187 - urllib3.connectionpool - DEBUG - Resetting dropped connection: api.mycroft.ai
13:25:08.612 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device HTTP/1.1" 401 77

```
The `401 `on the last call seems to indicate that [the call was not authenticated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401).

**Comment by forslund** [comment]
Hi, thanks for reporting.

These 401 will occur at intervals and should trigger a refresh of access token. Do they persist or is there a short interval with 401's?

**Comment by wsw70** [comment]
@forslund no, the sequence above happens occasionally but (as far as I can tell) there is no further impact. If this is normal (token refresh) then I will close the issue. Thanks.
