### ISSUE TITLE
fasteners module missing - correct run environment for runpy.py?

### ISSUE THREAD

**Issue by wsw70** [MycroftAI/mycroft-core#1942]
## Be clear about the software, hardware and version you are running

* I'm running a Picroft
* With version 18.8.10 of the Mycroft software
* With the standard Wake Word (actually a custom one which is rejected, still investigating why - Mycroft fell back on the standard one)

## Try to provide steps that we can use to replicate the Issue

`/var/log/mycroft/bus.log` and `/var/log/mycroft/skills.log`  start with 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pi/mycroft-core/mycroft/__init__.py", line 17, in <module>
    from mycroft.api import Api
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 26, in <module>
    from mycroft.identity import IdentityManager, identity_lock
  File "/home/pi/mycroft-core/mycroft/identity/__init__.py", line 21, in <module>
    from mycroft.util.combo_lock import ComboLock
  File "/home/pi/mycroft-core/mycroft/util/combo_lock.py", line 16, in <module>
    from fasteners.process_lock import InterProcessLock
ImportError: No module named 'fasteners'
13:19:31.082 - mycroft.configuration.config:load_local:109 - DEBUG - Configuration /home/pi/mycroft-core/mycroft/configuration/mycroft.conf loaded
13:19:31.093 - mycroft.configuration.config:load_local:109 - DEBUG - Configuration /home/pi/mycroft-core/mycroft/configuration/mycroft.conf loaded
(...)

```

On the other hand

```
(.venv) pi@picroft:/var/log/mycroft $ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasteners
>>>
```

On the yet other hand

```
root@picroft:~# python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasteners
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'fasteners'
>>>
```

I do not use virtual environments in Python, but maybe `runpy.py` is started outside the venv where Mycroft lives and therefore uses the modules installed globally (where `fasteners` is absent)?

Note: Mycroft works fine, I do not know it enough yet to measure the impact of this failed initialization

**Comment by forslund** [comment]
As indicated by the `(.venv) ` at the prompt for the first attempt with python you're inside the mycroft venv.

Switching to super user (as in the second case) will load the environment of the root user and thus not be inside the venv.

At some point there was an issue with the first startup after picroft-update would not find fasteners correctly on picroft, I believe it's fixed in the unstable picroft version.

This has probably more to do with that picroft specific script than with mycroft-core. Would you mind moving the issue to https://github.com/MycroftAI/enclosure-picroft?

**Comment by wsw70** [comment]
@forslund thanks for the details. I am moving it right away.

**Comment by wsw70** [comment]
I just realized that this has been already reported (https://github.com/MycroftAI/enclosure-picroft/issues/87)
