### ISSUE TITLE
Building Mycroft using the dev_setup.sh script fails with git pathspec errors when targeting the master branch 

### ISSUE THREAD

**Issue by RusDavies** [MycroftAI/mycroft-core#1946]
## Summary
When attempting to build Mycroft on Linux from the git repos, targeting the stable master branch fails. 

## Software & hardware
* Source from git repo at git@github.com:MycroftAI/mycroft-core.git 
* Commodity PC running Fedora Linux

## Steps to Replicate the Issue
1. Clone the git repo (git clone --depth=1 git@github.com:MycroftAI/mycroft-core.git && cd mycroft-core)
2. Run the dev_setup.sh script (bash dev_setup)
3. Follow the instructions, selecting to use the stable master branch
4. Observe that (3) fails (error: pathspec 'master' did not match any files(s) known to git)
5. Fetch the master branch (git fetch origin master)
6. Observe that (4) pulls data and appears to work
7. Attempt to checkout the master (git checkout master)
6. Observe that (6) fails with the error (error: pathspec 'master' did not match any file(s) known to git)

## Expected outcome
When I use the dev_setup.sh script to build the master branch, as per the README.md, it should build without error.

## Actual outcome
When I use the dev_setup.sh script to build the master branch, as per the README.md, it fails with git pathspec errors. 

## Analysis and Potential Solution
It appears the error occurs because .git/config is overly specific in targeting only the dev branch. 

This can be remedied by changing the lines:
[remote "origin"]
        url = git@github.com:MycroftAI/mycroft-core.git
        fetch = +refs/heads/dev:refs/remotes/origin/dev

to:
[remote "origin"]
        url = git@github.com:MycroftAI/mycroft-core.git
        fetch = +refs/heads/&ast;:refs/remotes/origin/&ast;

With that change, and so long as the master branch is first fetched and checked out, the dev_setup.sh script then works when targeting the master branch. 

## Suggested Action
1. Modify .git/config to allow the master branch to be pulled
2. Update dev_setup.sh to fetch the master branch before attempting to check it out

**Comment by penrods** [comment]
Yeah, that "depth=1" in the instructions shouldn't be there anymore.  I'll correct it...

**Comment by penrods** [comment]
@RusDavies , can you see if this eliminates the issue for you now?  You will need to clear the checkout and run through the process again, but I think it should be clean.  If so, then we can close this one out.
