### ISSUE TITLE
Feature: Add extract_duration method

### ISSUE THREAD

**Issue by ChristopherRogers1991** [MycroftAI/mycroft-core#1959]
The timer skill has an [_extract_duration](https://github.com/MycroftAI/mycroft-timer/blob/4e503621399761b2910068d275b269916359ce5f/__init__.py#L118-L134) method that I think would be useful elsewhere. It should be added to [mycroft.util.parse](https://github.com/MycroftAI/mycroft-core/blob/60d29056783fbe2b7a1741865ed99ed825ae2e03/mycroft/util/parse.py) (alongside things like [extract_datetime](https://github.com/MycroftAI/mycroft-core/blob/60d29056783fbe2b7a1741865ed99ed825ae2e03/mycroft/util/parse.py#L140)).

**Comment by ChristopherRogers1991** [comment]
Note that the function could also be beefed up a bit, to handle things like "half hour," etc.

**Comment by ChristopherRogers1991** [comment]
PR for this is https://github.com/MycroftAI/mycroft-core/pull/1977

**Comment by forslund** [comment]
Resolved by #1977. Closing
