### ISSUE TITLE
Error on fresh picroft install - No such file or directory: '/home/pi/.mycroft/skills/TimeSkill/uuid'

### ISSUE THREAD

**Issue by andlo** [MycroftAI/mycroft-core#1986]
in the log shows:
```
20:43:26.341 - mycroft.skills.settings:_poll_skill_settings:389 - ERROR - Failed to fetch skill settings: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 382, in _poll_skill_settings
    self.initialize_remote_settings()
  File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 156, in initialize_remote_settings
    self.save_skill_settings(skill_settings)
  File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 224, in save_skill_settings
    self._save_uuid(skill_settings['uuid'])
  File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 259, in _save_uuid
    with open(uuid_file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.mycroft/skills/TimeSkill/uuid'
```

Ill suspect that the user alreddy has a timersetting stored on home.mycroft.ai and during initialazation the settings is written to the device. But the skill isnt yet installed and thus there isnt the directory to store the setting in...

**Comment by andlo** [comment]
I think line 259 in settings.pu should be changed from 

```
        with open(uuid_file, 'w') as f:
            f.write(str(uuid))
 ```
to 
```
  try:
            with open(uuid_file, 'w') as f:
                f.write(str(uuid))
        except Exception:
            LOG.exception('Failed to save settings to file ' + uuid_file)
``` 
which would fix that skills initilization breaks if a directory is missing.

**Comment by forslund** [comment]
This is captured by the exception on [L389](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/settings.py#L389) (And the trace is logged).

I'm not sure how allowing code execution to proceed after the uuid-file write failed will work. I'll ping @MatthewScholefield who has more experience in the interactions of the skill settings with the server.

Possibly code that ensure that the path exists could be added as well?

**Comment by andlo** [comment]
Ill agree. Either make sure the path exists or skip if it dosnt. Later when the skill is install the path will be made.

**Comment by andlo** [comment]
Ill think this issue is handled so closing.
