### ISSUE TITLE
`dev_setup.sh` fails when running in non English `LANG` setting

### ISSUE THREAD

**Issue by MaWoe** [MycroftAI/mycroft-core#2037]
## Software, hardware and version
* Git hash: 2daa81d2990e8cc2922e6a4fc7f3286f6b54282d (master)
* Ubuntu 16.04.6 LTS
* Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
* 8 GiB RAM

## Steps to replicate Issue
Run the `dev_setup.sh` with the `LANG` variable other than the default English. Example:

    LANG=de_DE.UTF-8 bash dev_setup.sh

Answer questions with:
* Y (run on master)
* Y (auto update)
* N (skip mimic build)
* N (leave `PATH` variable unchanged)

## Expected condition / deviation from expected condition
Expected: The `dev_setup.sh` script does its jobs.
Deviation: After installing some packages (via Apt and Pip) the script issues an error:

    ./dev_setup.sh: Zeile 388: / 512000: Syntax Fehler: Operator erwartet. (Fehlerverursachendes Zeichen ist »/ 512000«).

Translates to:

    ./dev_setup.sh: Line 388: / 512000: Syntax Error: Expected operator. (Token causing the error: »/ 512000«).

## Proposed solution
Within the installer script set `LANG=C`

**Comment by forslund** [comment]
Thanks for identifying this, it looks like a pretty good solution.
