### ISSUE TITLE
Feature Request: Nice dates (and times)

### ISSUE THREAD

**Issue by LinusS1** [MycroftAI/mycroft-core#2048]
While I was developing a few skills that needed to deal with times I came across the issue of having Mycroft say the date/time. I'm requesting the opposite of `extract_datetime`. So that when I input a date object of today, Mycroft says "today". etc... Also to say **times** a method that takes a time/datetime object and returns something like 5 o clock would be nice.

**Comment by penrods** [comment]
See the nice_*() methods in mycroft.util.format!

https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/format.py#L383

**Comment by LinusS1** [comment]
Perfect! this was exactly what I was looking for. 🎉
