### ISSUE TITLE
Question: Devices working in tandem

### ISSUE THREAD

**Issue by Szalacinski** [MycroftAI/mycroft-core#2051]
Partially related to #2038 

Me and a friend of mine have been working on setting up a Mycroft personal backend, along with a Deepspeech and Mimic server running in a Ubuntu container.  Our eventual goal is to replace all of the other voice assistant devices with a self-run Mycroft installation, thereby centralizing all of the skills (which appear to be local to each Mycroft installation, making it a hassle to install a skill on all of the devices.  Please correct me if I am wrong on this), and reducing the amount of updates and anomalous behavior that would come from having individual SBCs running their own instance.  There are XMOS USB microphone arrays that would be wired on a cable rack that runs throughout the area, and they would run back to a server.  The other path would be if individual devices could work in tandem, and have centralized skills and configurations.

The main questions are:

- Can skills be centralized on a backend server, and can SBCs mostly act as lightweight devices listening for a wake word and then passing back audio to a personal backend that has the skills installed?  This would bypass the need for wiring multiple microphones into a machine, and would be the simplest option for people wishing to set up their own locally-run assistants.

- Can the backend server be smart enough to realize that the user is closer to device A, rather than device B, and play audio back only on device A's speaker?  Could this work even if two microphones were not used with individual SBCs, and were run back to a central location?

**Comment by penrods** [comment]
You just basically described Alexa or Google Home -- they are remote mics doing wakeword, then everything else happens on a server.  So yes, this is possible.

The Mycroft messagebus architecture _can_ support this, at least in theory.  But it isn't an implementation we have pursued.

**Comment by Szalacinski** [comment]
One more question before I close this issue, because my question has mostly been answered:

If I want to write this implementation and push it upstream, what would be the best course of action programming-wise to where the user could enable it if they wanted this style of experience, without interfering with the default implementation?

**Comment by penrods** [comment]
One simplicity of things running on the same device is discovery.  You'll have to build a mechanism to coordinate easily.  Google and Amazon hit the same endpoints from around the world, but I don't think you are proposing that style of centralization.

The messagebus is a simple websocket, but will need some security constructs when you are operating outside of a single device.  So WSS, firewall rules, etc.

Then you will need pieces to launch the proper pieces, distribute config files (since the filesystem isn't shared), etc.  Details like that.
