### ISSUE TITLE
extract_numbers failing for some languages

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2056]
`extract_numbers_generic()` fails for languages that do not support the short_scale and ordinals arguments in their `extractnumber` functions. 

Eg calling:
- `extract_numbers_de()` [calls](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/lang/parse_de.py#L950) `extract_numbers_generic(text, pronounce_number_de, extractnumber_de, short_scale=short_scale, ordinals=ordinals)` 
-  `extract_numbers_generic()` then [attempts to call](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/lang/parse_common.py#L75) `extract_number_de(normalized, short_scale, ordinals)`
- `extract_number_de()` fails as it [only accepts one argument](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/lang/parse_de.py#L82) 'text'

**Comment by ChanceNCounter** [comment]
I took a stab at this, and [kludged a fix](https://github.com/MycroftAI/mycroft-core/commit/a289caf0291829e88250fa54e90732d11f96e494) for the core problem, but it quickly revealed further bizarre behavior.

In English:

```
>>> extract_numbers_generic("two eighteen hundred 34 gold two", \
pronounce_number_en, extractnumber_en)
[1834]
>>> extract_numbers_generic("two eighteen 34 gold two", \
pronounce_number_en, extractnumber_en)
[2, 2, 18, 34]
>>> extract_numbers_generic("two hundred eighteen 34 gold two", \
pronounce_number_en, extractnumber_en)
[234]
```

In German, it fails in equally interesting ways, seemingly related to the presence or absence of the number 1:

```
>>> extract_numbers_generic("eins zwei drei", pronounce_number_de, extractnumber_de)
['3', '2', '1']
>>> extract_numbers_generic("drei ein 417.0 zwei", pronounce_number_de, extractnumber_de)
['1', '1', '3']
>>> extract_numbers_generic("drei eins 417.0 zwei", pronounce_number_de, extractnumber_de)
['2', '7', '4', '1', '1', '3']
>>> extract_numbers_generic("drei 1 417.0 zwei", pronounce_number_de, extractnumber_de)
['2', '7', '4', '1', '1', '3']
>>> extract_numbers_generic("drei 2 417.0 zwei", pronounce_number_de, extractnumber_de)
['417', '2', '2', '3']
```

**Comment by krisgesling** [comment]
Damn... good to lift the carpet and see what's underneath, but damn! 
![rabbit hole](https://media3.giphy.com/media/swtiK9jRfE0zS/giphy.gif?cid=790b76117dc2d680a35a684b089ccb0ce7ca43bb1409511e&rid=giphy.gif)

**Comment by krisgesling** [comment]
No longer part of core, will check in LF refactor.
