### ISSUE TITLE
Picroft Wakeup word and Temperature Error

### ISSUE THREAD

**Issue by rajdpandey** [MycroftAI/mycroft-core#2064]
PIcroft is taking wakeup word again and again even though I am Not Saying it. And It starts Loops of it. And It also Is'nt saying Correct Temperature of place even though i have set the location through web. And When I try to add New skill through web It is Showing Connection Error than Key Error and Etc. on a Loop.

**Comment by krisgesling** [comment]
Closing as per conversation in Chat.mycroft.ai please let us know there if you are still having trouble.

**Comment by rajdpandey** [comment]
Still Having Issues. I have Posted Photos of it.
