### ISSUE TITLE
Standardize music player autoducking 

### ISSUE THREAD

**Issue by retrodaredevil** [MycroftAI/mycroft-core#2085]
I've recently made a skill that plays youtube songs (yes other people have done the same thing) and am pretty satisfied with how the "auto ducking" works. However, it is inconsistent with how different music skills "auto duck". The goal of auto ducking is to pause the music when the user asks Mycroft a question. This isn't too difficult to implement. You just have a register 2 or 4 event handlers, depending on how you do it, and have some state to see if you are in "auto paused" mode. If you look at the pandora or spotify skills, you'll see that their auto ducking both works differently, making them inconsistent.

CommonPlaySkill makes making music skills a lot easier. It looks like it has something useful called AudioService. There really isn't much documentation on how to actually use the AudioService. It just looks like an abstraction for sending messages to the messagebus. It has no actual examples of receiving those messages, or an advantage of sending a message out to the messagebus, then receiving it in another method compared to just calling a method to start the playing of music (which most skills that utilize that mostly do).

CommonPlaySkill really should help handle auto ducking, but it doesn't really look like it was set up for that. I haven't come across a skill that actually uses the AudioService, which looks like it could be a really nice abstraction, if there was documentation on how to use it correctly.

Another thing that CommonPlaySkill should address, is the displaying of track info on the mouth text. This is another thing that it looks like AudioService tries to address. One of the problems with the mouth text is that another skill my want to try to utilize the mouth text which could overwrite a skill that really should have priority over it at that time. I think that somehow abstracting setting the mouth text would be a good thing, so skill authors again, don't have to worry about inconsistencies.

Obviously, I don't think we can refactor or add to CommonPlaySkill as it may break things, but maybe we could create another abstract class that does more than CommonPlaySkill (maybe called AdvancedPlaySkill or something).

I'm curious to know what your thoughts are and if you think that this is necessary.

**Comment by forslund** [comment]
Hi I do agree that the ducking things should be added to the common play infrastructure and I do think this can be made in a backward compatible way. Adding the handlers for these messages, but not requiring the skill creators to provide them, (which isn't necessary if they're using the audioservice to do playback since that handles ducking internally)

I've thought about the track info and in my opinion that should be handled in the playback control skill. this makes it easy to make it future proof for the mark-2 as well. (basically the playback control would handle all visualization).

I do agree that the audioservice could use some more description.
The available documentation we have is the [audioservice api](https://mycroft-core.readthedocs.io/en/master/source/mycroft.html#audioservice-class), there's some info on the [docs site](https://mycroft.ai/documentation/skills/audio-service/). I'd also written an example on the common-play framework using the audioservice. The example skill i built can be found [here](https://github.com/forslund/common-play-tutorial)

**Comment by retrodaredevil** [comment]
OK, that's some pretty nice documentation. The only thing is it looks like AudioService only supports playing URI's. So only local files or files you can download. This means that skills like Pandora and Spotify cannot use the AudioService. I think that should be made more clear in the documentation so skill creators don't try and use the AudioService to create a skill that involves streaming. As of right now, the documentation isn't clear about what the AudioService can be used for. When I first saw it I thought that maybe I should provide my own implementation for AudioService, then I saw that all AudioService does is send messages to the MessageBus for the backend to receive and deal with, which is only useful for skills that need to play URI's.

I feel like there would be a better way to provide auto ducking than just doing the same thing as AudioService is doing. Maybe somehow combine that logic so both CommonPlaySkill and whatever the AudioService backend is.

**Comment by forslund** [comment]
I did have an implementation using PulseAudio's ducking feature which is promising and more general purpose.

You can use local files (technically with file:// but if no :// is in the path it's automatically added)

I will work on updating the docs with more details.

**Comment by retrodaredevil** [comment]
I'd definitely like a link if you have a working example of a general purpose auto ducking, especially if I could implement this in my skill and eventually have other people implement this in the pandora, spotify, etc. skills.

I don't think the docs would need too much work. Just as long as it gets the point across that AudioService is just for local files or URIs.

**Comment by forslund** [comment]
This has been done to some extent as part of the 19.08 release. 
- volume skill handles ducking while listening
- there is the possibility to hook into pulseaudio role-ducking

Closing this issue for now
