### ISSUE TITLE
Error in dev_setup.sh: chown at line 226

### ISSUE THREAD

**Issue by Nemirtingas** [MycroftAI/mycroft-core#2092]
When building a fresh install, just after git clone  and doing bash dev_setup.sh:
At line 226, the chown is wrong as it assumes that the user's group is the same as his name.
My user is different from my group so I changed this line:
        $SUDO chown -R $USER:$USER /opt/mycroft
to
        $SUDO chown -R $USER: /opt/mycroft

which will make chown use the user's primary group on Ubuntu.

**Comment by forslund** [comment]
Thanks for letting us know.

In the other place where we chown we use:
```sh
setup_user=$USER
setup_group=$( id -gn $USER )
```

To determine the correct group. would this work in your case as well?

**Comment by Nemirtingas** [comment]
Yes, it should fix this bug :), thx.
