### ISSUE TITLE
Feature: Allow mycroft-speak and mycroft-say-to take bash pipes

### ISSUE THREAD

**Issue by FruityWelsh** [MycroftAI/mycroft-core#2105]
* I'm running mycroft-core
* With version 19.2.4 of the Mycroft software

Add the ability to | into mycroft-speak and mycroft-say-to to open up scripting options.

**Comment by FruityWelsh** [comment]
Ran into a snag creating a unittest. Mostly I don't know where the unit-tests for the bin/ scripts are.

**Comment by forslund** [comment]
I do not think we have any unittests for the scripts yet.

Since the tests are of the shell scripts would they be unittests or integration tests? Basically can they be run in isolation or is a mycroft instance required?

**Comment by FruityWelsh** [comment]
I guess intergration would be more apt (from my understanding the scripts just send a preconfigured message onto the messagebus).

**Comment by forslund** [comment]
Yeah, that's exactly how they work.

I think adding a directory under the test/integrationtests folder for these would be the best place for them.

**Comment by FruityWelsh** [comment]
So something like:
test_mycroft-speak_bash_pipe
test_mycroft-speak_arg
test_mycroft-say-to_bash_pipe
test_mycroft-say-to_arg

To be honest I also have no idea how to write a test for a bash script that interfaces with python. Would I need to setup a mock messagebus to make sure that the messages are recieved correctly and that mycroft responds corretly?

**Comment by forslund** [comment]
For an integration test it would interact with a running mycroft messagebus.

I'm not certain myself what the best way to do this would be.

Iguesds the test would connect to the messagebus, listen for the speak message. Then launch the script as a subprocess wait a short interval and check that the expected message was received.

A bit complex to do. If you like to submit the change without a test that's ok.Iyt might be better investment of time if I wrote a unittestfor the underlying messagebus send function

**Comment by FruityWelsh** [comment]
Currently this works with discrete messages from the echo command, but does not work with cat or streams of text.

**Comment by forslund** [comment]
For me this works:
```sh
$ echo "hello there" > say.txt
$ cat say.txt 
hello there
$ cat say.txt | ./bin/mycroft-speak
```

**Comment by FruityWelsh** [comment]
That works for me too. 
It seems to be more of an issue with the new line character and the other characters. Maybe we need to filter out special characters?

My testfiles are:
Hello there
General Kenobi

and  the mycroft-say file which has a #, which also fails.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
