### ISSUE TITLE
No matching distribution found for xxhash (from padatious)

### ISSUE THREAD

**Issue by JiaChenwei** [MycroftAI/mycroft-core#2107]
When I install padatious, it seems to need install xxhash, but pip cannot find this pakage.
<pre>Collecting padatious
  Using cached https://files.pythonhosted.org/packages/33/c1/a54ac3f8fe5fac7fc9537beb90576673a660f3da9147e1317adf6e4c3cfb/padatious-0.4.7.tar.gz
Requirement already satisfied: fann2 in /home/jia/anaconda3/envs/mycroft/lib/python3.6/site-packages (from padatious)
Collecting xxhash (from padatious)
<font color="#C4A000">  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by &apos;NewConnectionError(&apos;&lt;pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f82853f28&gt;: Failed to establish a new connection: [Errno 101] Network is unreachable&apos;,)&apos;: /simple/xxhash/</font>
<font color="#C4A000">  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by &apos;NewConnectionError(&apos;&lt;pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f82853eb8&gt;: Failed to establish a new connection: [Errno 101] Network is unreachable&apos;,)&apos;: /simple/xxhash/</font>
<font color="#C4A000">  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by &apos;NewConnectionError(&apos;&lt;pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f82853208&gt;: Failed to establish a new connection: [Errno 101] Network is unreachable&apos;,)&apos;: /simple/xxhash/</font>
<font color="#C4A000">  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by &apos;NewConnectionError(&apos;&lt;pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f82853320&gt;: Failed to establish a new connection: [Errno 101] Network is unreachable&apos;,)&apos;: /simple/xxhash/</font>
<font color="#C4A000">  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by &apos;NewConnectionError(&apos;&lt;pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f828535f8&gt;: Failed to establish a new connection: [Errno 101] Network is unreachable&apos;,)&apos;: /simple/xxhash/</font>
<font color="#CC0000">  Could not find a version that satisfies the requirement xxhash (from padatious) (from versions: )</font>
<font color="#CC0000">No matching distribution found for xxhash (from padatious)</font>
<font color="#C4A000">You are using pip version 9.0.1, however version 19.1 is available.</font>
<font color="#C4A000">You should consider upgrading via the &apos;pip install --upgrade pip&apos; command.</font>
</pre>

**Comment by forslund** [comment]
Hi @JiaChenwei from the error message it seems like a network error hinders the download of the required package.

Can you retry and see if it has fixed itself?

**Comment by forslund** [comment]
Hi, have you got this working or is this still an issue?

**Comment by forslund** [comment]
Since there's been no communication here for almost 2 months I'm closing this issue. If you still have problems with this feel free to reopen the issue, Thanks
