### ISSUE TITLE
extractnumber_en fails with XX%

### ISSUE THREAD

**Issue by ChristopherRogers1991** [MycroftAI/mycroft-core#2110]
extractnumber_en returns `False` when a a number is followed by `%`, e.g. `100%`. The number by itself works correctly.

https://github.com/MycroftAI/mycroft-core/compare/bug/extract_number_percent provides a failing unit test.

**Comment by ChristopherRogers1991** [comment]
Hey @forslund,
Did this get tagged by mistake on https://github.com/MycroftAI/mycroft-core/pull/2411? I'm not sure how that would resolve this. If it does, perhaps we should add the test from the linked branch (https://github.com/MycroftAI/mycroft-core/compare/bug/extract_number_percent)

**Comment by forslund** [comment]
Um.. yes, sorry

**Comment by ChanceNCounter** [comment]
Anybody touch this yet? This works, but it's pretty naive, and I haven't run tests, just threw it together:

```
def extractnumber_en(text, short_scale=True, ordinals=False):
    for word in text.split(" "):
        if word[-1] == "%":
            text = text.replace(word, word.replace("%", " percent"))
    return _extract_number_with_text_en(_tokenize(text),
                                        short_scale, ordinals).value

**Comment by forslund** [comment]
No one has. Feel free to take it on.

A regex might be something to look at as well or a generic replace of % with the empty string while parsing.

**Comment by ChanceNCounter** [comment]
Mmm. That should be performant, I don't know why I bothered trying to avoid it. `text = text.replace("%", "")` seems like all this would need.

**Comment by JarbasAl** [comment]
see https://github.com/MycroftAI/mycroft-core/pull/2413#issuecomment-562376599 , i think this should be handled in tokenize and become ["N", "%"] , replacing will solve the immediate issue, but some other util/language further down the line will have to duplicate code eventually, this is common enough IMHO to be properly handled instead of side stepped in this single method

**Comment by ChanceNCounter** [comment]
You could be right. I'm also concerned about the likelihood that this will screw up math someplace, in that a person trying to perform arithmetic on the output would likely prefer "0.N."
