### ISSUE TITLE
Websocket needs to have origin check disabled for 3rd party connections

### ISSUE THREAD

**Issue by paulscott56** [MycroftAI/mycroft-core#212]
messagebus/service/ws.py needs to have a method to disable cross origin checks in order for 3rd party devices and apps to connect (e.g. the Android client)

This is easily achieved by adding

`` def check_origin(self, origin):
        return True
``

**Comment by joshymcd** [comment]
created PR 215 for this issue

**Comment by ethanaward** [comment]
Addressed by #215.
