### ISSUE TITLE
Fallback to en-us when locale (intent, vocab) not found

### ISSUE THREAD

**Issue by domcross** [MycroftAI/mycroft-core#2120]
When Skill-service starts up it loads all intents that are specified for a skill by looking into folders vocab/intent/locale for the configured language. 

*Problem:* In case a intent/vocab-file is not found the skill is not loaded. 

*Example:* recently the mycroft-stop skill was enhanced with the "reboot" intent. The "reboot.intent" file is currently only available for "en-us". I run Mycroft with `language="de-de"`and get following error:
```
mycroft.skills.core:load_skill:165 - ERROR - Failed to load mycroft-stop.mycroftai 
due to a missing file: Unable to find "reboot.intent"
```
This renders the whole skill unusable for me...

*Suggestion:* when `load_skill`fails to load a intent/vocab-file fall back to "en-us" and try to load the intent again. As in 99.99% of all cases there is a english intent file this will not break the loading of the intent.

**Comment by forslund** [comment]
I agree that this should probably be done. I do think we should keep a mode where it'll error if not all translations are found to make it easy to see which ones aren't 100 % operational.

I started the work on something like this this morning. hopefully a PR soonish :)

**Comment by domcross** [comment]
[This issue](https://github.com/MycroftAI/mycroft-skills/issues/716) from mycroft-skills repo is related.

**Comment by forslund** [comment]
Closed thanks to work by @domcross (probably got tired of waiting for the fix I was doing, I wonder where that branch went)
