### ISSUE TITLE
Mycroft Widget 

### ISSUE THREAD

**Issue by ITCMD** [MycroftAI/mycroft-core#2122]
I'm running the Mycroft-Core (latest version) on KDE Plasma 5.5

After installing the core and attempting to install the Plasma-Mycroft (and rebooting), adding the widget gives this error:

`Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.plasma.mycroftplasmoid/contents/ui/main.qml:32:1: module "QtWebKit" is not installed`

**Comment by forslund** [comment]
This is probably not a mycroft-core issue but I'm not sure where to report this issue either :) I'm pinging @AIIX who's done much of the work on the KDE integration and Plasmoid.

**Comment by AIIX** [comment]
@ITCMD seems you are missing dependencies, please use the latest installer for installing the mycroft widget correctly: https://github.com/AIIX/mycroft-installer/releases

**Comment by forslund** [comment]
@ITCMD are you happy with this answer? Can we close the issue?

**Comment by forslund** [comment]
Since there's been no more communication, I'll close this for now. Feel free to reopen if you still have issues.
