### ISSUE TITLE
Missing url Parameter for MaryTTS constructor

### ISSUE THREAD

**Issue by motom001** [MycroftAI/mycroft-core#2127]
In mycroft latest version v19.2.7. is a parameter url missing for the marytts class constructor (like ibm tts, which has also a RemoteTTS baseclass).

missing parameter url:
https://github.com/MycroftAI/mycroft-core/blob/b0157b46c804bc46533fdcf5a9169a40508a9225/mycroft/tts/mary_tts.py#L31

for example ibm tts:
https://github.com/MycroftAI/mycroft-core/blob/b0157b46c804bc46533fdcf5a9169a40508a9225/mycroft/tts/ibm_tts.py#L25

A following error is the wrong parameter syntax to the base class RemoteTTS
https://github.com/MycroftAI/mycroft-core/blob/b0157b46c804bc46533fdcf5a9169a40508a9225/mycroft/tts/mary_tts.py#L32

better would be a init method like this:
`
    def __init__(self, lang, config, url="http://localhost:59125"):
        super(MaryTTS, self).__init__(lang, config, url, '/process', MaryTTSValidator(self))
`

Sorry for the bad code syntax - i tried my best but it doesn't work :(

**Comment by forslund** [comment]
Solved by #2262. Closing.
