### ISSUE TITLE
Not able to register

### ISSUE THREAD

**Issue by ahcorde** [MycroftAI/mycroft-core#213]
Hi everyone,

I just received Mycroft, but I'm not able to register my device. 

The first time that I submit the 6 digits code, my web-browser redirect me to https://cerberus.mycroft.ai/device, but the list of device is empty. Then when I try to repeat the proccess I always see the message "Failed to pair with device"

I have try to put the URL in the web browser without the button using (checking this JS: https://cerberus.mycroft.ai/js/pairing.js) 
```
https://cerberus.mycroft.ai/devices/register?code=D5EE76. 
```

The first time I recieved:

```
{"status": 200, "message": "Successfully paired with device", "device_id": "0656feea-09f7-4c7b-a4f4-64a14021a596"}
```
But the rest of the time:
```
{"status": 404, "message": "Device not found"}
```
I always see the 6 digits code in the LCD of Mycroft.

I have also updated the device using the script provides in /home/pi. I think the current versión is 0.7.1

**Comment by aatchison** [comment]
Hmm, you might take a look to see if  `/home/mycroft/.mycroft/identityidentity.json` exists, if it does, try deleting that and rebooting the unit, then pair again.

**Comment by aatchison** [comment]
Did you even have any luck with this?

**Comment by ahcorde** [comment]
I have removed this file but now if I execute `top` I'm not able to see mycroft services

**Comment by nrd2001** [comment]
I just received my kit and i'm having the same problem.

**Comment by aatchison** [comment]
Since this is a pretty generic issue, and we know that the process works, I'm closing this now.
