### ISSUE TITLE
gcc 8.3 update with microphone problems?

### ISSUE THREAD

**Issue by vanbreukelingen** [MycroftAI/mycroft-core#2143]
After normal update to gcc 8.3 (9.0 is the actual one, as pip 18.0 should be replaced to pip 19.1 at the collecting part of installation) she stopped taking actions via microphone. When you say "Hey, XXX" the status part on the right left corner stops to smooth and freezes; It has an ALSA issue.

My macine is a AMD Ryzen 2700X with lot's of RAM and the developer branch of the AI on an Arch linux-ck-zen kernel. Investigations via chat.mycroft.ai lead to this writing of the bug issue. 

Taking has never been the problem, but talking to her/him/it - which developer really cares? You are much faster with writing it down then when talking. 

There's no json identity file in my ./mycroft folder.

**Comment by forslund** [comment]
Thanks for reporting do you see any errors in the voice.log file (in /var/log/mycroft)

Was this after rerunning the dev_setup.sh and rebuild of the pyaudio module for some reason?

**Comment by vanbreukelingen** [comment]
now after reboot to

`Linux arch5 5.1.6-1-ck-zen #1 SMP PREEMPT Fri May 31 17:19:58 EDT 2019 x86_64 GNU/Linux
`
she even doesn't talk anymore...

[voice.log](https://github.com/MycroftAI/mycroft-core/files/3243808/voice.log)


should I unpair and repair with ./dev_setup.sh?

**Comment by vanbreukelingen** [comment]
Set up again; having now Marks voice but without possibility to talk; still freezing. When telling "I have now finished booting up" this shows up:

`ALSA lib pcm_pulse.c:752:(pulse_prepare) PulseAudio: Unable to create stream: Bad state

Assertion 'pthread_mutex_destroy(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:83, function pa_mutex_free(). Aborting.
Assertion 'pa_atomic_load(&(s)->_ref) >= 1' failed at pulse/stream.c:320, function pa_stream_unref(). Aborting.`

whata do?

**Comment by forslund** [comment]
Hi sorry for the late reply. This is a tricky issue and I haven't been able to find any report similar to this one...

Do you get the same issue when you run the audiotest

```
./start-mycroft.sh audiotest
```

And does pulseaudio work in other software such as audacity?

It can also be good to try parecord to record a short snippet to verify that is working. `parecord > out.wav` (say something and then hit ctrl+c to stop recording)

I wonder if it could be an issue with a new glibc or something where the c-hooks for pyaudio (used to access the mic) are compiled with the old version and some inconsistency shows up? (Maybe I'm out way over my head here)

**Comment by rekkitcwts** [comment]
I'm not sure if this issue is similar to [this post](https://community.mycroft.ai/t/usb-microphone-randomly-freezes-after-saying-something-to-the-usb-microphone-working-before/6692) on the forums, since both happen to mention pulseaudio and the freezing microphone.

**Comment by forslund** [comment]
Thanks @rekkitcwts 

@vanbreukelingen, Yesterday I noticed an issue on the dev branch where the mic worker thread would throw an exception if you have opted in to sharing wakeword data (See pr #2145) Could be a possible issue as well if you're on the latest dev and have selected opt in on home.mycroft.ai (and the pulseaudio thing is just a red herring)

**Comment by vanbreukelingen** [comment]
`~~~~da/mycroft-core/.venv/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
~~~~oft-core/.venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] `




is what I get now at the beginning.... micro status ok but vulnerable

`~~~skills.settings:_send_settings_meta:311 - ERROR - ('Connection aborted.', OSError(0, 'Error'))`

when talking to her, she reacts just "normall" without any errors, so this should be solved for the moment..

no sound output, but writing ok...

will tell more about it after next reboot.

vulnerablity of binutils older versions at arch forum is to be discussed.

Having another case in the upcoming days to be published, it's a grandmother with hardware so around 60 in human age with a debian based distribution (Peppermint OS with a KDE desktop) as VirtualBox Guest on a freeBSD 13.0 current (really updated, incl. kernel ports and trees) host, not giving me any access to pairing code, with our without curl, uunpaired, paired, again - no change, that they can connected.

**Comment by vanbreukelingen** [comment]
rebooted - works fine for now!
