### ISSUE TITLE
Stoping Picroft to narrate last query

### ISSUE THREAD

**Issue by rajdpandey** [MycroftAI/mycroft-core#2146]
Hi all,

I am using picroft on Raspberry Pi 3B+ and there is an issue I wanted to ask about and how to achieve that.

Example:

User: Hey Mycroft tell me about the Himalayas?
Mycroft: Starts narrating answer.
(Between the Narration)
User asks: Hey Mycroft tell me about America?

Then Mycroft should stop tell me about Himalaya's and should tell me about America.

But right now it first completes whole Himalaya's narration and then starts telling me about America.

I don't want to manually say Hey Mycroft stop.

It should be automatic.

So how can I make this?

**Comment by krisgesling** [comment]
Great, I've transferred this over to mycroft-core. Let us know how the testing goes.

**Comment by rajdpandey** [comment]
Yeah, I am not good with Coding but I am trying to achieve that.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
