### ISSUE TITLE
Can't add new device

### ISSUE THREAD

**Issue by kenken023** [MycroftAI/mycroft-core#2147]
* I'm running a Picroft. With the standard Wake Word

## Steps to reproduce:
1. Setup a new raspberry pi 3 b+ with the picroft image
2. Register the device using the code
3. Returns a server error HTTP Code 500 - Internal Server error

I am trying to setup a new raspberry pi 3 b+ using the picroft image (stable). But at the registration part on the website after I input all the details including the code, it returns an error 500 Internal Server error

**Comment by forslund** [comment]
Hi, thanks for reporting.
Can you post or e-mail a screenshot of the location, wakeword and voice settings you're setting when doing the pairing and the email that's connected to your account (ev. Through a social login service)

**Comment by forslund** [comment]
ping @chrisveilleux and @matheuslima

**Comment by penrods** [comment]
Also, can you retry the pairing?  I'm wondering if this is a transient issue.

**Comment by kenken023** [comment]
Hi @forslund  @penrods 

I am in Singapore. Please see screenshots for more details:

![picroft-1](https://user-images.githubusercontent.com/3609248/59074388-be296c80-88fd-11e9-978a-cb8ecf4e7781.PNG)
![picroft-2](https://user-images.githubusercontent.com/3609248/59074389-be296c80-88fd-11e9-8018-6109b96109f0.PNG)

Now I tried registering a device using USA, I works.

**Comment by krisgesling** [comment]
Singapore doesn't contain any regions (at least in the location list we're using) so there's no ability to then select a city, @matheuslima would this be causing the error on submit?

**Comment by kenken023** [comment]
Is it also possible to have an error handle in the future? Even if there’s an error, it always says successful 😊

Thanks!

**Comment by matheuslima** [comment]
@kenken023 sorry about this issue, we had an issue with our database and we don't have regions and cities for Singapore. That makes you unable to register a device with a location in Singapore. We definitely need to put an error handler to deal with such cases, also we need to fix Singapore in the database.

**Comment by chrisveilleux** [comment]
I manually added a region and city for Singapore.  Please try to pair your device again using these values.

**Comment by forslund** [comment]
Hi @kenken023, have you tried after the recent fixes? How did it go?

**Comment by kenken023** [comment]
It's working now. Thank you so much.

**Comment by duwudi** [comment]
I've been trying with China -> Guangdong -> Shenzhen and had the same issue. Thank God I stumbled on this thread - changed to Hong Kong and paired straight away

**Comment by forslund** [comment]
@duwudi It would be great if you could open an issue in the [selene-backend repo](https://github.com/mycroftai/selene-backend)
