### ISSUE TITLE
Can't get pairing code in a VM

### ISSUE THREAD

**Issue by vanbreukelingen** [MycroftAI/mycroft-core#2148]
On a Dell Vostro 3000 Series I have a freeBSD 13.0 CURRENT host with a Peppermint OS (Debian, 5.0.X) guest, running MyCroft on it. Everything's fine, except that I don't get any pairing code for the device. We already tried the curl command via konsole but it seems MC doesn't recognize the online prescense of the device in the api. Paired, Unpaired, again trying to pair, nothing works. Matheus from the chat told me to open a new issue with this screenshot. 

![Screenshot_20190608_105416](https://user-images.githubusercontent.com/43870491/59144946-564a5300-89dd-11e9-80f1-06e99f5dd4c0.png)
 

Maybe M. doesn't want freeBSD hosts? What'ya think?

**Comment by forslund** [comment]
I wonder if this is similar to an issue I've recently saw...Can you try to remove the `~/.mycroft/identity/identity2.json` file and then start up Mycroft?

**Comment by vanbreukelingen** [comment]
Well,  there's no .json file in the identity folder.

**Comment by forslund** [comment]
Ok, then this is a separate issue. What'sthre response to the input _pair my device_ ?

**Comment by forslund** [comment]
Also from your screenshot it looks like skills are all loading correctly. Which would mean that an internet connection has been found...

This should trigger the pairing skill automatically if no pairing is detected. So either the paired check breaks some how and returns that the device is already paired or the pairing skill fails somehow

**Comment by vanbreukelingen** [comment]
of course, as it is a free-vpn-service, it's a question if they like mycroft at the moment, normally ok, but sometimes slow, no matter if via canada or japan or south korea; the skill-build came without vpn as delta are a bit wired with git clone, are some big .la files, so I decided to download the file from mid-europe, but later during installation process I activated the .ovpn immidiatly - many companies don't like VPN connections at all, although it is a matter of private spehre even when shopping, and as I alsways have troubles with data piratery against machines like me; it's better not to give CC data via the "original" ISP - damn botchecks!

As I already unpaired and tried to repair with the curl command, given both trials - in the VM and on the host - but no matter what you do, it stays disconnect, not getting a pairing code at all. 

Audio setup is another thing, got to integrate via USB attach the micro with camera from the host; where is the ./audio-setup.sh - script like on picroft?, or at least the wipe and a new setup, without cloning again.?

I mean it's a damn hard work to rebuild a clicky-clicky-debian-os to a KDE environment with only 4GB RAM inkl. host, so this why the whole thing becomes slower and slower; kernel is now 5.0.XX, with kde-full package, it's a grandmother and she was 35 years in sklavery at bills drones and now she breathes again with the BSD on it... Like to get an apple maverick on it, too: https://forums.virtualbox.org/viewtopic.php?t=93467&sid=55dc236416c71abb3b54298eadad346b

I mean she had it damn hard and was a present, that's what we get, when our hardware comes back from prost*-bill-gates-windows-10-m$-f* we should probably give it first to gentoo with emerge a.s.o., but no bluetooth, not beiing able to do some SSD, I looked behind the cover. 

When you insert pair my device, nothing happens at all and naturally "could not update configuration as device is not paired" - so no weather, mail, etc. .... 

"american female" doesn't work at all, you'd always to decide for google mimic2 in the api, as otherwise you get Mark. And weather is just in Fahrenheit, although everything is in the api at Celsius. Custom wakewords are still a big problem with the phonetics and the precise load...

Will probably need help with the language spoken in Portugal on the main machine or here on the laptop via VM? Is there a female voice possible in Portoguese?

Maybe it's really the BSD host and I need a special invitation by the MC Holding or something like this :-)

Maybe something remains when you get your pairing code with curl at the server, so it is blocked - gonna write matheus-mycroft a message, they should take care for it, too.

Have a nice weekend!

**Comment by forslund** [comment]
I do believe the main issue is the timeouts, could you get a pairing code using curl? If so I find it weird, maybe the default timeout isn't sufficient for your vpn/configuration?

- audio setup is hosted in the [picroft-repo](https://github.com/MycroftAI/enclosure-picroft/tree/stretch/home/pi)

- American female is an old mimic1 voice and requires a subscription if I recall correctly

- I think you will need to use the google tts to have a female Portuguese, the ones provided by espeak are all male.

Have a nice weekend you too!

**Comment by vanbreukelingen** [comment]
yes, now I'm having a non PrePaid-Card, it shouldn't make any troubles with google - 

if we had enough from the investment fundraising, we could work further on the android version of mycroft, the problem there is the connection via a port on the 192.168.X.X line, what simply doesn't connect. 

gotta play around with the whole MC at the weekend for not beiing bored.

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
