### ISSUE TITLE
Vocab keywords should be full path

### ISSUE THREAD

**Issue by ChristopherRogers1991** [MycroftAI/mycroft-core#2153]
If the vocab folder in a skill contains the following:

```
vocab
   |_en-us
         |_folder1/VocabA.voc
         |_folder2/VocabA.voc
```

whatever is in those two files will be will all be registered under the type `<skill-id>VocabA`.

This is less than ideal, as the two sets of vocab may not be compatible. The workaround of course is to change the names of the files, however, we could support this if we changed [this code](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/skill_data.py#L102-L104) from:
```
            if f.endswith(".voc"):
                vocab_type = to_alnum(skill_id) + splitext(f)[0]
                load_vocab_from_file(join(path, f), vocab_type, bus)
```
to something like:
```
            if f.endswith(".voc"):
                sub_path = join(path, f)[len(basedir):]
                vocab_type = to_alnum(skill_id) + splitext(sub_path)[0]
                load_vocab_from_file(sub_path, vocab_type, bus)
```

the terms could be registered under `<skill-id>folder1/VocabA` and `<skill-id>folder2/VocabA` respectively.

Hit this working on the iot-control-skill. There's a lot of vocab to cover, and some overlaps. Files can be renamed to avoid issues, but I think using the path would be ideal since it would avoid the possibility of a collision altogether, and allows for simple categorization without awkward file names. This would be a breaking change though, so it might be worth a little discussion.

**Comment by forslund** [comment]
I do think this is a good approach and I think this is something that can be implemented despite changing a naming convention IMHO because
- The subfolder feature is not very well known or used and this should generate the same id-s for skills without subfolders
- The generated name is an internal implementation detail of mycroft-core and external code shouldn't rely on the naming here.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
