### ISSUE TITLE
Mycroft repeats last request when starting up

### ISSUE THREAD

**Issue by trekjunky** [MycroftAI/mycroft-core#2155]
OpenSuSE 15.1
I am running mycroft-core version 19 oh 2, release 12

My problem: I have the skill finished booting up running. Right after Mycroft says he is ready, he repeats the last request I made days ago. If I ask him 5 requests, the next time I start him up, he will repeat my last request. How do I stop this?

**Comment by forslund** [comment]
That sounds really weird. mycroft-core doesn't retain any information about what is spoken between startups. I checked the finished-booting skill and it doesn't seem to do anything like that either.

Does this happen even if you reboot the machine between starting Mycroft?

**Comment by trekjunky** [comment]
Yes, I have rebooted several times and Mycroft does it every time I start him up. I paid good money that I donated so that I wouldn't have any problems, but that didn't seem to matter. I wonder what problem I will have when and if this is fixed?

**Comment by forslund** [comment]
Thanks for that piece of information, that rules out cached speech wav-files since they would be flushed at reboot.

Could it be another skill that stores those things? Do you have more third-party skills in addition to the finished-booting skill?

To help us look further into the issue could you perform the following actions:

edit the `mycroft.conf` to enable debugging logs

`nano ~/.mycroft/mycroft.conf`

add a line to set the log level to debugging

` "log_level": "DEBUG"`

this needs to be valid json and can be a bit tricky. If the config hasn't been changed previously it should look like this when done:

```json
{
  "max_allowed_core_version": 19.2,
  "log_level": "DEBUG"
}
```

Since the issue is happening during startup the config editing is necessary, otherwise the debug CLI could perform the log level change during operation.

Then start up mycroft `./start-mycroft.sh all` when it has started ask him to "create a support ticket" and follow the verbal instructions to create a support package. then forward the e-mail that will be sent to your registered e-mail to me ake.forslund[-at-]mycroft.ai

If there are issues with the support skill zip up the `/var/log/mycroft/skills.log` file and send that.

Thank you.

**Comment by trekjunky** [comment]
I had to send you an email directly as my second email explains that I never got the email that Mycroft sent.

**Comment by forslund** [comment]
Thank you for sending the logs, I looked them over and one possibility is the fallback-recommendations skill. It has some code that could be responsible for the repeat after reload...

**Comment by krisgesling** [comment]
@trekjunky can you try uninstalling that Skill and retesting to see if the problem goes away?
You should be able to just say "uninstall recommendations"

**Comment by trekjunky** [comment]
I uninstalled it and ran a test run and the problem went away. I
reinstalled it and ran another test and the problem didn't come back.
Thanks!!!!!

But now I have a question that should be simple enough. In my
troubleshooting I edited the file ~/.mycroft/mycroft.conf and changed the
log level to DEBUG. Now I would like to change it back, BUT I don't
remember what the setting was before. Can you help?

*Cane Kostovski*
www.pc-tamer.com
__________________________________________
“Here, where a thousand
Captains swore grand conquest. . .Tall
Grass their monument.”
― Basho

"Too many people are beacons of light with hate for others...
If only some of that light would shine on them
showing them as they are, NOT as they wish they were!!!!!"
― Cane Kostovski
__________________________________________

**Comment by trekjunky** [comment]
Kris' advice worked. He said to uninstall recommendations and try it. I did
and the problem went away. I reinstalled it and tested again. The problem
did NOT come back. Thanks for your help!!!!

*Cane Kostovski*
www.pc-tamer.com
__________________________________________
“Here, where a thousand
Captains swore grand conquest. . .Tall
Grass their monument.”
― Basho

"Too many people are beacons of light with hate for others...
If only some of that light would shine on them
showing them as they are, NOT as they wish they were!!!!!"
― Cane Kostovski
__________________________________________

**Comment by krisgesling** [comment]
Great! 

I'll still let the developer of that skill know so they can keep an eye out for it and hopefully prevent it from happening again. 

As for switching the log level back, you should be able to just delete that line from your conf file and it will switch back to the default level of 'info'.
Another random tip - in the CLI you can type:
`:log level debug`
or
`:log level info`
to quickly switch log levels. However I don't think these are retained after a reboot.

**Comment by forslund** [comment]
@krisgesling as the issue occured during startup I asked him to set the log level to debug through the config so we'd be guaranteed to catch it.

@trekjunky the default config should look like this:

```json
{
  "max_allowed_core_version": 19.2
}
```

**Comment by trekjunky** [comment]
Thanks Ake!!!!

*Cane Kostovski*
www.pc-tamer.com
__________________________________________
“Here, where a thousand
Captains swore grand conquest. . .Tall
Grass their monument.”
― Basho

"Too many people are beacons of light with hate for others...
If only some of that light would shine on them
showing them as they are, NOT as they wish they were!!!!!"
― Cane Kostovski
__________________________________________

**Comment by LinusS1** [comment]
hi @trekjunky , I'm the developer of that fallback recommendations skill, and I would like to look into this more as I haven't seen something like this. If you could respond to my questions here: 
https://github.com/LinusS1/fallback-recommendations-skill/issues/9#issuecomment-501512086
That would be great, so I can further debug this skill.
