### ISSUE TITLE
error : target not found

### ISSUE THREAD

**Issue by erfanr** [MycroftAI/mycroft-core#2164]
Hi, I am cloned mycroft-core and executed dev_setup.sh on Fedora 30 workstation.
after answering all of questions (no mimic build) i recieve these:
`
warning: database file for 'core' does not exist
error: target not found: git
error: target not found: python
error: target not found: python-pip
error: target not found: python-setuptools
error: target not found: python-virtualenv
error: target not found: python-gobject
error: target not found: python-virtualenvwrapper
error: target not found: libffi
error: target not found: swig
error: target not found: portaudio
error: target not found: mpg123
error: target not found: screen
error: target not found: flac
error: target not found: curl
error: target not found: icu
error: target not found: libjpeg-turbo
error: target not found: base-devel
error: target not found: jq
error: target not found: pulseaudio
error: target not found: pulseaudio-alsa

`

**Comment by el-tocino** [comment]
That looks like a pacman error, not rpm.  Arch or Fedora?  Or is fedora being recognized as fedora?

**Comment by erfanr** [comment]
It's Fedora. But I think it's not recognized.
How should I do it to recognize?
(Sorry for bad English)

**Comment by el-tocino** [comment]
The dev_setup pushes fedora below finding pacman.  Probably easiest step for the moment is to move pacman either out of the path or to a different name temporarily.  This looks like a bug, though, imo, will see if I can write a quick fix otherwise one of the project devs might want to.

**Comment by forslund** [comment]
Indeed it sounds like a bug. The way we determine which installer binary to use is kind of dumb but works in most cases.

Simpler than renaming the binary in the filesystem may be to edit [dev_setup.sh](https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh#L294) and changing `pacman` to `pacman_disabled` which should result in moving on to dnf as well.

To improve the os detection for Fedora could you post the content of `/etc/os-release`

**Comment by erfanr** [comment]
OK. I removed lines from 294 to 303 in dev_setup.sh . And its working now.

**Additional information:**
This is my $PATH variable. There is no pacman here:
`/usr/libexec/python3-sphinx:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/erfan/Downloads/mycroft/mycroft-core/bin:/var/lib/snapd/snap/bin:/home/erfan/dotnet:/home/erfan/dotnet:/home/erfan/dotnet`

and this is my /etc/os-release
NAME=Generic
VERSION="30 (Generic)"
ID=generic
ID_LIKE=fedora
VERSION_ID=30
PRETTY_NAME="Generic 30 (Generic)"
ANSI_COLOR="0;34"
LOGO=generic-logo-icon
CPE_NAME="cpe:/o:generic:generic:30"
HOME_URL="http://www.zombo.com/"
SUPPORT_URL="https://en.wikipedia.org/wiki/Help!_(album)"
BUG_REPORT_URL="https://youtu.be/CSemARaqGqE"
REDHAT_BUGZILLA_PRODUCT="Generic"
REDHAT_BUGZILLA_PRODUCT_VERSION=%{bug_version}
REDHAT_SUPPORT_PRODUCT="Generic"
REDHAT_SUPPORT_PRODUCT_VERSION=%{bug_version}
PRIVACY_POLICY_URL="http://nsa.gov"

(I don't know why NAME is Generic

**Comment by forslund** [comment]
Thanks. After a quick google I think it may be depending on the release-package that's installed... there is release-generic and release-workstation, etc. And it may depend on the type of install you selected when first setting up the OS installation...

Maybe, just googlin'n'guessin' here :)

Anyway I'll try to change up the os detection here.

**Comment by forslund** [comment]
Based of above info (Thanks!) we've updated the Fedora detection. See #2165. Closing this issue for now. If things are still weird feel free to reopen it.
