### ISSUE TITLE
Passive listener

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#218]
There should be a passive mode where Mycroft can respond to queries both before and after the wake word.

**Comment by Wolfgange3311999** [comment]
This relies on the listener being refactored. At the moment it is too huge to effectively expand.

**Comment by aatchison** [comment]
Are we still working on this issue?

**Comment by Wolfgange3311999** [comment]
Not actively but I think it is something to consider for the future. If you'd like we can close this for now.

**Comment by aatchison** [comment]
Thanks, closing
