### ISSUE TITLE
dev-install error on opensuse

### ISSUE THREAD

**Issue by XGWang0** [MycroftAI/mycroft-core#2181]
OS version : opensuse 42.3
Got following error :
"Installing packages...
 Installing packages for OpenSUSE...
Loading repository data...
Reading installed packages...
'autoconf' is already installed.
No update candidate for 'autoconf-2.69-12.49.noarch'. The highest available version is already installed.
'bison' is already installed.
No update candidate for 'bison-2.7-9.43.x86_64'. The highest available version is already installed.
'pkg-config' is already installed.
No update candidate for 'pkg-config-0.28-9.54.x86_64'. The highest available version is already installed.
'automake' is already installed.
No update candidate for 'automake-1.13.4-8.9.noarch'. The highest available version is already installed.
'libjpeg-devel' not found in package names. Trying capabilities.
'swig' is already installed.
No update candidate for 'swig-3.0.10-1.2.x86_64'. The highest available version is already installed.
'libffi-devel' not found in package names. Trying capabilities.
'libffi-devel-gcc5' providing 'libffi-devel' is already installed.
'libfann-devel' not found in package names. Trying capabilities.
No provider of 'libfann-devel' found.
"
There are too many package not found on opensuse standard repor and update repos.

Any ideas?

**Comment by forslund** [comment]
Seems like the only error is missing libfann-devel package ?

I suggest trying to find a package or repo with that package and seeing if it can be found.

OpenSuse was tested using Tumbleweed as far as I can recall, not sure if packaging has changed upstream or if there's a difference between that version and v 42.3?

No one in the core team is running OpenSuse so we'd appreciate it very much if you report back any solution or improvement to the install script.

**Comment by XGWang0** [comment]
Oh..., too many issue for opensuse,
1.I need to add new repo for libfann-devel, the repo can get from http://download.opensuse.org/repositories/devel:/libraries:/c_c++/openSUSE_Leap_42.3/
2.Solve depences issues
3.Update gcc due to low version gcc lacks of some options
4.Comment out pyalsaaudio from requirement.txt, or it will cause compilation issue due mission head file.
5.Install correct version pyalsaaudio via system repos
......
Recommand Tumbleweed

**Comment by forslund** [comment]
Sorry for the late reply. Can this version of OpenSuse be detected and added to the dev_setup.sh do you think?

**Comment by forslund** [comment]
Since there's been no communication for a while I'll close this issue. Feel free to reopen if this is something that still needs work.
