### ISSUE TITLE
Mycroft Build Process improvements

### ISSUE THREAD

**Issue by lyndalopez544** [MycroftAI/mycroft-core#2188]
- Update all dependencies to the latest version, for more compatibility and stability across  systems.
- Make the dev_setup.sh script runnable as root by default as all packaged versions of mycroft have to run it as root.(as a configuration script)

**Comment by forslund** [comment]
You can allow root to run the dev_setup.sh script by passing the running it as `dev_setup.sh --allow-root`. It's however not recommended to run it like this.

**Comment by PureTryOut** [comment]
> Make the dev_setup.sh script runnable as root by default as all packaged versions of mycroft have to run it as root.(as a configuration script)

Packaged versions (assuming distro packaging and probably Pip) _don't_ have to run `dev_setup.sh`. They should install deps with the dependency handling of the package manager in use, not with this script.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
