### ISSUE TITLE
Make start-mycroft.sh independent from dev_setup.sh

### ISSUE THREAD

**Issue by lyndalopez544** [MycroftAI/mycroft-core#2191]
The dev_setup.sh script included in the source release would not function as it requires the directory to be a git repo.

It has to be fixed in order for the source release to be packaged.

**Comment by forslund** [comment]
`dev_setup.sh` is intended as a script to setup the development environment for mycroft-core and isn't intended to be used in a packaging / distribution situation.

**Comment by aurora-of-earth** [comment]
@forslund So why is it included in the master branch and also in the release archives?

**Comment by forslund** [comment]
Basically it's a part of the repo and a tool used during developing that also needs to be under version control. If there is an issue we should be able to go back and setup a development version of any specific version.

What exactly do you want to do with the dev_setup.sh-script? Which parts do you need to run? Would it work if you defined the `IS_TRAVIS` env variable (blocking the interactive part) and supplied the -sm flag to skip cloning/building mimic?

What other git commands are you hitting?

We could possibly split the dev_setup.sh into a couple of subscripts allowing you to do what you wish while still retaining the things fulfilling the dev_setup's original purpose?

**Comment by aurora-of-earth** [comment]
> Basically it's a part of the repo and a tool used during developing that also needs to be under version control. If there is an issue we should be able to go back and setup a development version of any specific version.
> 
> What exactly do you want to do with the dev_setup.sh-script? Which parts do you need to run? Would it work if you defined the `IS_TRAVIS` env variable (blocking the interactive part) and supplied the -sm flag to skip cloning/building mimic?
> 
> What other git commands are you hitting?
> 
> We could possibly split the dev_setup.sh into a couple of subscripts allowing you to do what you wish while still retaining the things fulfilling the dev_setup's original purpose?

The dev_setup.sh is required to be run once before running start-mycroft.sh which is in turn required by bin/mycroft-start; the start-mycroft.sh is essential to start mycroft in a release build.
I've made a pull request with the needed changes.

**Comment by PureTryOut** [comment]
I only just saw this, but I think my #2687 is a better approach to this than #2202 is.

This way usage will be the same as before for people running MyCroft from a git checkout, but in case of distro packaging (in this case meaning `start-mycroft.sh` is installed somewhere on the system as `start-mycroft`, e.g. in `/usr/bin`) stuff like `dev_setup.sh` will not be called.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
