### ISSUE TITLE
Privacy Policy not visible without an account

### ISSUE THREAD

**Issue by ssixty** [MycroftAI/mycroft-core#2194]
on https://mycroft.ai/  the link to https://mycroft.ai/privacy-policy/  redirects me to a login page.

I don't want to register an account before reading the policy.

edit: the Terms of Use link has the same issue.

**Comment by forslund** [comment]
Ping @chrisveilleux

**Comment by forslund** [comment]
Thanks for raising the issue as seen in the previous comment I've pinged Chris who does most of the work on the backend/website

**Comment by chrisveilleux** [comment]
This link is obviously broken.  If you would like to view the privacy policy before I get to fixing it, you can look here: https://mycroft.ai/embed-privacy-policy/

**Comment by chrisveilleux** [comment]
The privacy policy link in the footer has been fixed.  The terms of use link in the footer had the same problem and was also fixed.

**Comment by ssixty** [comment]
Thanks for the link and the changes
