### ISSUE TITLE
Raspberry Pi 4 support?

### ISSUE THREAD

**Issue by flatsiedatsie** [MycroftAI/mycroft-core#2200]
I had a look but I couldn't find it, so I thought I'd ask: how can I install PiCroft on a Raspberry Pi 4?

**Comment by forslund** [comment]
We haven't gotten around to try Mycroft on the Pi-4 yet but the git-clone method detailed in the [Readme](https://github.com/MycroftAI/mycroft-core#getting-started) should work.

**Comment by forslund** [comment]
Got confirmation from @JarbasAl on the chat a while back that the normal git-install of mycroft-core works. But he had some issues with the respeaker and matrix voice hats. But that's likely just a config issue (this is me guessing wildly).

Closing this issue.
