### ISSUE TITLE
Pairing Code to short

### ISSUE THREAD

**Issue by Proxtx** [MycroftAI/mycroft-core#2205]
Register this device with the code 'M' as in Mike. 'L'
    as in London. 'K' as in Kilogram. 'F' as in Fox trot.
    the number Three. 'J' as in Juliet

Only 5 letters

**Comment by penrods** [comment]
What are you running on, hardware wise?  I noticed the AIY was cutting off audio playback prematurely.  If you pull up the CLI via `mycroft-cli-client` command does it show the full code?

**Comment by penrods** [comment]
Wait a minute - there *are* five letters and one number for a total of six characters in the example you gave.  Your code is: MLKF3J

**Comment by Proxtx** [comment]
YES I saw it in the log but it hadn't told me
