### ISSUE TITLE
Allow self-signed certificates on local home server

### ISSUE THREAD

**Issue by flatsiedatsie** [MycroftAI/mycroft-core#2219]
I'm trying to use MyCroft on a Raspberry Pi 4 (buster). I used the console install method.

In the `mycroft.conf` file I then changed the URL of the server to that of the Mycroft Personal Server, which I was [advised to try](https://github.com/MycroftAI/mycroft-core/issues/1605#issuecomment-512780742).

After some adjustments I got the Mycroft Personal Server to run. But then I ran into an issue with the SSL connection.

```
./start-mycroft.sh debug
Already up to date.
Starting all mycroft-core services
Initializing...
Starting cli
12:27:59.603 - mycroft.api:is_paired:514 - WARNING - Could not get device info: SSLError(MaxRetryError('HTTPSConnectionPool(host=\'0.0.0.0\', port=6712): Max retries exceeded with url: /v0.1/device/ (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))
```
Could it be that Mycroft doesn't accept locally issues SSL certificates?

I've [mirrored this issue ](https://github.com/MycroftAI/personal-backend/issues/37)at the Mycroft Personal Server github issue cue, since I assume the author must have found a way around this already.

**Comment by el-tocino** [comment]
You have to add the self signed cert to your local python keystore, then you can make this work.  

There's also let's encrypt, though you have to renew pretty regularly.

**Comment by forslund** [comment]
I don't think this should be something we add to mycroft-core. Seems you can add a certificate to the trusted list manually: [unix.stackexchange.com](https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list)

**Comment by flatsiedatsie** [comment]
You're right.
