### ISSUE TITLE
Tornado 5 support

### ISSUE THREAD

**Issue by toddrme2178** [MycroftAI/mycroft-core#2227]
Currently, this package is locked to Tornado 4.5.3.  Tornado 5.0 was released March 2018, and Tornado 6.0 was released March 2019.  Other packages are beginning to drop support for Tornado 4, and the different versions cannot be installed at the same time, so having this package pinned at 4.5.3 makes it impossible to update other packages.  Is there any chance to get support for tornado 5 at least, and ideally tornado 5 and 6?

**Comment by forslund** [comment]
I'd love to get the server updated to the latest. When we moved to 4.5.3 it was the last version that didn't break our code outright. Some work is required for making the move but I'd love to take the plunge. If you're well versed in Tornado you're welcome to try it out, otherwise I might get some free time the coming weeks to look at it...

**Comment by toddrme2178** [comment]
I don't know Tornado at myself I am afraid.  One issue I just learned is
that Tornado 4 doesn't support Python 3.8 at all, which makes the move a
bit more pressing.

**Comment by forslund** [comment]
Ok, just did a test with the latest Tornado and I don't see the problems I encountered earlier. So it'll may be fine to just bump the version... Will do more tests during the week.

**Comment by j1nx** [comment]
For MycroftOS I´m using 5.1.1 for quit some time now without any issues.

**Comment by forslund** [comment]
After 19.08 is out (tomorrow if all goes well) we'll start moving some packages, including Tornado, to more recent versions.

**Comment by domcross** [comment]
I am on Mycroft 19.8.3 and `mycroft-pip list` returns `tornado 6.0.3` - looks to me like this issue can be closed?

**Comment by forslund** [comment]
Indeed, you are 100% correct. Closing
