### ISSUE TITLE
STT error

### ISSUE THREAD

**Issue by hippyk** [MycroftAI/mycroft-core#2229]
```
14:02:31.289 - __main__:handle_record_begin:36 - INFO - Begin Recording...
14:02:32.524 - mycroft.client.speech.listener:transcribe:231 - ERROR - list index out of range
14:02:32.524 - mycroft.client.speech.listener:transcribe:232 - ERROR - Speech Recognition could not understand audio
```
The frequency of occurrence is often.

**Comment by el-tocino** [comment]
Is it being intentionally triggered or is it false positives?

**Comment by hippyk** [comment]
> Is it being intentionally triggered or is it false positives?

I'm sorry I don't quite understand what you mean. I'm just doing the regular operation.

**Comment by el-tocino** [comment]
Are you saying "Hey mycroft, do something" and it's responding with the log message above?  Or are you not saying anything and it's randomly activating?

**Comment by hippyk** [comment]
> Are you saying "Hey mycroft, do something" and it's responding with the log message above? Or are you not saying anything and it's randomly activating?

The first situation has a probability, and the second is almost certain.

**Comment by el-tocino** [comment]
Are you using a custom wake word or just "hey mycroft"?

**Comment by hippyk** [comment]
> Are you using a custom wake word or just "hey mycroft"?

I send a wake-up signal directly by "touch startListening"

**Comment by el-tocino** [comment]
No idea what that means?

**Comment by hippyk** [comment]
@el-tocino It doesn't seem to have something to do with wake-up.

**Comment by el-tocino** [comment]
Does it here you correctly ever?

**Comment by forslund** [comment]
The error message you're seeing is that the audio recorded doesn't contain any speech that the STT can transcribe.

This usually happen (as @el-tocino points out) when the listening is falsely triggered, i.e. the wake word spotter thinks it hears a "hey mycroft" from some piece of music or similar.

Other possibilities:
- If you trigger by hitting the IPC file and you don't speak directly the listening may timeout and miss your words.
- If there is some mic issue and the audio is missing or quality is very bad this could occur.

The last question by el-tocino is very relevant and I'm also curious to that.

**Comment by hippyk** [comment]
> Does it hear you correctly ever?

Yes, occasionally succeed. And i use Google Voice search to test the microphone and ti is perfectly ok.
@forslund

**Comment by hippyk** [comment]
I just tried five more times, only one failed.

**Comment by krisgesling** [comment]
Hi HippyK,

How are you triggering `startListening` and how often?

If this is not the case, please ignore, however if you are attempting the constant listening idea that you previously mentioned, our API will reject the requests. Using our server as a general STT service is not permitted. We provide this service for free to all users because we believe that everyone should have access to a privacy respecting voice assistant. Any attempts to abuse that service have detrimental impacts on the whole Community.

**Comment by hippyk** [comment]
Now it does look really because it didn't hear what I said. Maybe the first error tip can be optimized.

**Comment by JarbasAl** [comment]
if i understand correctly you are manually creating the listening signal used by speech listener, why are you doing it this way? if you are doing it often (live transcription it seems to be the case) you will run into that all the time

1 - when audio is not understood, this would be most of the time if listening  24/7
2 - when requests are rate limited

if you are doing this please stop, that is not the intended use and hurts the whole community

you should look into streaming STT options, but be warned that is paid by the minute, you will also want to look into VAD detection to avoid sending "silence" to the STT and waste credits

something like Kaldi or deepspeech might be better suited for 24/7 listening if you have the resources to run those

**Comment by el-tocino** [comment]
Try and look into running this locally if you want to do non-stop listening: https://discourse.mozilla.org/t/new-project-deepspeech-websocket-server-client/32554

**Comment by hippyk** [comment]
@JarbasAI @el-tocino Thank you very much for your advice. But this problem doesn't have nothing to do with the way you wake up. Wake up by voice is the same. I just used the command line for convenience, and I didn't wake it up continuously.

**Comment by el-tocino** [comment]
Jarbas explains the error succinctly above.  Without more complete details it will be difficult to provide relevant help.
