### ISSUE TITLE
speak skill

### ISSUE THREAD

**Issue by jasonehines** [MycroftAI/mycroft-core#223]
I created a speak skill. Would you like it in the repository?

**Comment by the7erm** [comment]
@jasonehines I couldn't find the folder, did you forget to push it? 
https://github.com/jasonehines/mycroft-core/tree/speak-skill/mycroft/skills 

What exactly does the speak skill do?  

    Hey mycroft say:<word or phrase>

**Comment by jasonehines** [comment]
@the7erm No. I wasn't sure if it was even wanted in the repository since third party skills folder was announced recently. I have another pull request open too and don't know how to do a separate one.

Yes. you can use speak, say or repeat. I saw someone request it in the forums and I was planning to call it from a bluetooth proximity script to greet the person.

**Comment by ethanaward** [comment]
@jasonehines: Here's how to [create a new PR](https://help.github.com/articles/creating-a-pull-request/). Feel free to do so and we'll take a look at it.

**Comment by isaacnward** [comment]
Looks like this has been solved by #228!
