### ISSUE TITLE
Feature request: Check for AVX instruction set during install

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2232]
As of late last year TensorFlow requires the CPU to support the AVX instruction set. This is therefore required by the Precise wake word engine. 

Currently there are no checks or warnings when installing Mycroft to indicate that this will be a problem. However a number of users have reported Precise failing and in the end it was identified that they were running on older or lower end hardware.

Mycroft could still be used with PocketSphinx as the wake word engine, however it would be better to notify the user such that they are a) aware of the reduced capability; and b) can choose whether or not to continue.

Advanced users may opt to build an older version of TensorFlow (v1.13) from source. 

The simplest method (that I know of) to identify if AVX is supported is to check for avx in the cpuinfo flags eg:
`grep avx /proc/cpuinfo`

### Success criteria
- During installation CPUinfo is checked to confirm AVX support
- If available, installation silently continues
- If unavailable, information is provided to the user and the installation may be aborted
- If the user opts to continue installation, the PocketSphinx listener should be selected.

**Comment by krisgesling** [comment]
Hi Arjangupta,

Thanks for the offer of help! Another Community member has actually submitted PR #2269 for this. It looks like it didn't get linked automatically.

If you are interested in helping out, we definitely appreciate the help. We have a range of [Issues tagged "help wanted"](https://github.com/search?utf8=%E2%9C%93&q=user%3Amycroftai+label%3A%22help+wanted%22+state%3Aopen&type=Issues&ref=advsearch&l=&l=) that might be of interest :grinning:

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
