### ISSUE TITLE
Installing Mycroft may uninstall WINE without notice

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2238]
A [user on the forums reported](https://community.mycroft.ai/t/there-should-be-a-warning-that-mycroft-will-uninstall-wine-and-other-software/6995/2) that by installing Mycroft, their WINE installation and all programs using WINE were uninstalled without warning. Have requested further details about the users system.

This appears to have happened at least once before on Kubuntu 16.04
https://community.mycroft.ai/t/finally-got-it-working/5580
In that instance it seemed that the `portaudio19-dev` package required `libjack0` and thus uninstalled `lib-jack-2-0`.

#### Expected behaviour:
- [ ] Able to install Mycroft without removing other software from the system.
- [ ] If a package must be removed from the system this should provide a warning and require user confirmation with the option to abort the installation process and return the system to its previous state.

**Comment by nickmcgill** [comment]
I installed mycroft today from git, and have found that wine has been removed.
Ubuntu 18.04.3 LTS, mycroft stable.
No changes from the default mycroft setup.

**Comment by krisgesling** [comment]
Hi Nick, 

Apologies that this has happened. It seems to be quite rare, but needs to be addressed as we don't want to cause these unintended changes on a users system.

There are [instructions in our docs](https://mycroft.ai/documentation/linux/#removing-mycroft-for-linux-from-your-system) on removing Mycroft from your system however there's no simple way to roll back the uninstall of packages unfortunately.

**Comment by lu-ka** [comment]
Hi!

Ran into this again, dev_setup tried to nuke some packages because portaudio19-dev conflicted with libjack. Solved it by running a manual

`apt install portaudio19-dev`

which prompted removal of ONLY libjack (and installation of another version of libjack), then re-running dev_setup

**Comment by cinsin** [comment]
This happened to me too.  Under ubuntu19.10 desktop  running "apt install portaudio19-dev" removed wine-staging without warning and wine-staging can not be installed again by apt.  Luckily i have a full backup of system files, after restore "/opt/wine-staging" and "/usr/bin/wine*" wine works again.

please fix this, thanks!

**Comment by krisgesling** [comment]
Hi Cinsin, I'm glad to hear you have a backup. We added the warning to avoid data loss but the broader issue remains. 

we are working on a Snap package for Mycroft. Snaps are a containerized packaging system which amongst other things will take care of this dependency incompatibility and will therefore prevent the conflict and stop other packages being removed unintentionally.

**Comment by able2doit** [comment]
Happened today using Debian 10 (buster).  No idea what has been lost, if anything.

**Comment by ChanceNCounter** [comment]
The following in dev_setup.sh should have caught that:

```bash
function debian_install() {
    APT_PACKAGE_LIST="git python3 python3-dev python3-setuptools libtool \
        libffi-dev libssl-dev autoconf automake bison swig libglib2.0-dev \
        portaudio19-dev mpg123 screen flac curl libicu-dev pkg-config \
        libjpeg-dev libfann-dev build-essential jq pulseaudio \
        pulseaudio-utils"


    if dpkg -V libjack-jackd2-0 > /dev/null 2>&1 && [[ -z ${CI} ]] ; then
        echo "
We have detected that your computer has the libjack-jackd2-0 package installed.
Mycroft requires a conflicting package, and will likely uninstall this package.
On some systems, this can cause other programs to be marked for removal.
Please review the following package changes carefully."
        read -p "Press enter to continue"
        $SUDO apt-get install $APT_PACKAGE_LIST
    else
        $SUDO apt-get install -y $APT_PACKAGE_LIST
    fi
}
```

unless the name of the package changed. Maybe the `-y` should go away.

**Comment by krisgesling** [comment]
Hey @able2doit - very sorry to hear that this happened. Did you get the warning with the package list that Chance highlighted above?
