### ISSUE TITLE
the installation is not working on mint, i have the same problem like in the other posts here

### ISSUE THREAD

**Issue by Z3r0ut** [MycroftAI/mycroft-core#2239]
the installation is not working on mint, i have the same problem like in the other posts here
im reposting it because i didnt see a fix for this in these posts.. Pls help me..

**Comment by krisgesling** [comment]
Hi Z3r0ut, I'm closing this as it seems to be a duplicate of the problems described in #2207

**Comment by forslund** [comment]
@Z3r0ut just letting you know that the fix for Mint supplied by @fermulator has now been merged. Feel free to give it a try!
In your mycroft-core directory run
```
git checkout dev
git pull
```

To pull down the latest changes.
