### ISSUE TITLE
PLS READ FIRST before closing... please

### ISSUE THREAD

**Issue by Z3r0ut** [MycroftAI/mycroft-core#2240]
the installation is not working on mint, i have the same problem like in the other posts here
im reposting it because i didnt see a fix for this in these posts.. Pls help me..

**Comment by el-tocino** [comment]
It's not that people aren't reading your posts, it's that you are posting multiple times about the same issue.  Once is more than enough, and as you've been replied to by gez multiple times about this, you should probably read those responses before trying to start new issues that will be closed.  Opening additional issues just wastes time.  
https://github.com/MycroftAI/mycroft-core/issues/2207#issuecomment-516241616
https://github.com/MycroftAI/mycroft-core/issues/2239#issuecomment-516241837

**Comment by krisgesling** [comment]
Hi Z3r0ut, 
Unfortunately it's not as simple as running an extra command.
Please keep an eye on issue #2207  - when a fix is ready, it will be posted there.
