### ISSUE TITLE
A suggestion from Z3r0ut

### ISSUE THREAD

**Issue by Z3r0ut** [MycroftAI/mycroft-core#2250]
I have an Suggestion,
Add an feature (or as an skill) that can read text (text to speech) for example
I say "Read an funny story" then he searches for a text dokument named "funny story" and reads the content of the text dokument.

And maybe, even read things that stand on a website.

And, if thats even possible, a feature for example when i say "Read this area" the AI creates an area selecting overlay this way a area screenshot tool does, and then the AI reads the text inside the area.

**Comment by krisgesling** [comment]
Hi Z3r0ut,

Some version of this Skill exists such as the [Bedtime Stories Skill](https://market.mycroft.ai/skills/904b3150-06c2-4136-9666-82581d4222c0) however text-to-speech (TTS) is also pretty computationally expensive so we don't offer the ability to use Mycroft as a generic TTS service for documents and websites etc. 

If you were looking to add voice to your own website, then you should checkout [Neongecko](https://neongecko.com/) who build on top of Mycroft.

Finally, I wanted to let you know about our [Community Forums](https://community.mycroft.ai/), this is a much better place to make suggestions, ask questions and develop general ideas. The issues for repo's are intended to be for flagging bugs and specific feature requests that relate to the code within that repo. Often discussions from the Forums will result in a feature request that gets posted here, and then we can look at the technical implementation of that.
