### ISSUE TITLE
dev_setup.sh does not recognize Fedora OS

### ISSUE THREAD

**Issue by guystreeter** [MycroftAI/mycroft-core#2255]
`dev_setup.sh` does not recognize Fedora OS.

```bash
$ cat /etc/os-release 
NAME=Fedora
VERSION="30 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

running dev_setup.sh on Fedora results in:

> Could not find package manager
> Make sure to manually install: git python3 python-setuptools python-venv pygobject libtool libffi libjpg openssl autoconf bison swig glib2.0 portaudio19 mpg123 flac curl fann g++ jq

I expected it to find and use dnf

I looked at the OS matching in dev_setup.sh and I found these tests (among others):

* found_exe yum && os_is centos
* found_exe yum && os_is rhel
* os_is_like fedora

None of these tests will match a Fedora system. I edited the last one to just

`os_is fedora`

and the setup completed successfully. I'm sure this not a complete solution, but I'll leave that to you.

**Comment by forslund** [comment]
This should be resloved now by pr #2257 by @vegerot, closing.
