### ISSUE TITLE
suggestions for cli

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mycroft-core#2259]
A :config or :configuration option, to list/show/point to the running configuration.  Useful for finding odd config bits easily.  

Also handy would be an option to disable audio output when queried from the CLI. (:mute?)  This would theoretically be configurable as not everyone will want it to be quiet.  

Lastly, a less verbose mode would be nice.  Something like a :verbose option perhaps to turn on/off log display.  This would NOT effect mycroft logging, just the display.

**Comment by penrods** [comment]
I'm about done with a standalone mycroft-config utility that does something like this:
```
mycroft-config:  Mycroft configuration manager
usage: mycroft-config [COMMAND] [params]

COMMANDs:
  edit (system|user)                  edit and validate config file
  reload                              instruct services to reload configs
  show (default|remote|system|user)   display the specified setting file
  set <var>                           set the variable (under USER)
  get [var]                           display a particular variable
                                      or all if no 'var' specified
Note: Use jq format for specifying <var>

Examples:
  mycroft-config edit user
  sudo mycroft-config edit system
  mycroft-config show remote
  mycroft-config get
  mycroft-config get enclosure.platform
  mycroft-config set test.subvalue "foo"
```

Does this sound adequate?  It also wouldn't be difficult to add access to this inside the CLI if preferred.

**Comment by el-tocino** [comment]
A most welcome addition indeed.

**Comment by penrods** [comment]
See PR #2290 for the mycroft-config tool
