### ISSUE TITLE
Feature: Add get_selection() to MycroftSkill class

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2276]
A common need for Skill developers is to present a list of options to the user and ask them to make a selection. This is possible using a combination of existing methods, however it requires each developer to work out their own pattern. Adding a standard method will make this easier for developers and provide a more consistent experience for users.

The current method generally involves:
1. Take list of items
2. Generate question dialog using [`join_list()`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.util.format.html?highlight=list#mycroft.util.format.join_list)
3. [`get_response()`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html?highlight=get_response#mycroft.MycroftSkill.get_response) from user
4. validate response checking for:
    - fuzzy match of list item
    - ordinal or number eg "third item", or "number two"
5. return selected item, or execute `on_fail` callback

**Comment by arjangupta** [comment]
Hi, I'm interested in this issue. Has anyone claimed it yet?

**Comment by forslund** [comment]
Not as far as I've heard, go for it!

If you have questions we have a chat at chat.mycroft.ai

**Comment by krisgesling** [comment]
Please do, thanks Arjan :smile:

**Comment by ChanceNCounter** [comment]
Closed by #2302, no?

**Comment by forslund** [comment]
You are quite correct. Closing!
