### ISSUE TITLE
Denial of Service (DoS)

### ISSUE THREAD

**Issue by larrycameron80** [MycroftAI/mycroft-core#2308]
Denial of Service (DoS)
Vulnerable module: tornado
Introduced through: tornado@4.5.3
Detailed paths
Introduced through: MycroftAI/mycroft-core@MycroftAI/mycroft-core#65bc1b9786461b2fafbb5d3dc49047f1d70f86f7 › tornado@4.5.3
Remediation: Upgrade to tornado@5.1.
Overview
tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.

Affected versions of this package are vulnerable to Denial of Service (DoS) attacks due to not enforcing max_size when decompressing compressed zip messages.

**Comment by krisgesling** [comment]
Thanks for flagging this one too. The desire to bump Tornado versions has also been raised in #2227 

Ake has done some testing already, so I anticipate that we'll get to this in the near future. Hopefully we can jump straight to version 6?

**Comment by forslund** [comment]
Tornado has been updated which should resolve this issue. Merging.
