### ISSUE TITLE
Support for Ivona Text To Speach

### ISSUE THREAD

**Issue by prosenkiewicz** [MycroftAI/mycroft-core#2328]
As in title, I'm going to implement support for ivona TTS

**Comment by JarbasAl** [comment]
hey, have a look at this PR that does that https://github.com/MycroftAI/mycroft-core/pull/1550

**Comment by prosenkiewicz** [comment]
hi, well not exactly since the issue you posted is related to pyvona https://github.com/zbears/pyvona which is now depricated. But my implementation is for people who bought ivona binary back in the days. So they are able now to use ivona with mycroft as a deamon which is listening on certain address or simply by using it as comand. 

Anyway my apologies for not describing that as precisely as I should from the start.

**Comment by JarbasAl** [comment]
i was mentioning it exactly because ivona is deprecated, i did not know about the daemon, any way to still get those?

**Comment by prosenkiewicz** [comment]
I don't know if you still can get ivona, since amazon bought IVO software so to get this it is necessary to ask amazon. Nonetheless it was possible before that happend, so there are still people who has it like company I work for and for these people this support might be useful.

**Comment by JarbasAl** [comment]
i agree it should be supported if it exists, i was just curious about using it myself! i like amazon voices

**Comment by prosenkiewicz** [comment]
Not long time ago it was available to download beta version of multiple languages of ivona from google shop and it should still be available to download from some apk mirrors. But I don't know what is the legal status of it for commercial use, for private user it should be fine.

**Comment by JarbasAl** [comment]
my aim was to have a good sounding offline/self hosted voice, i don't want to rely on the cloud (unless it's my cloud!) :) thank you for the tips

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
