### ISSUE TITLE
Add basic testcases for the audioservice interface

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#2332]
Add tests for the [audioservice](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/audioservice.py) interface for skills.

Basically the tests need to create a mock bus and create the audioservice with

```python
bus_mock = Mock()`
as = AudioService(bus_mock)
```

Then do calls against the objects methods and ensure that the expected messages are sent on the mock_bus.

If there are questions just comment here or join [our chat](https://chat.mycroft.ai)!

**Comment by Lawrence4code** [comment]
I'd like to work on this please.

**Comment by krisgesling** [comment]
Awesome, thanks Lawrence.

Let us know if you have any questions :slightly_smiling_face:

**Comment by forslund** [comment]
You're very welcome to take it on! Also since we require a CLA to accept the PR's you might want to sign it right away so you don't need to wait for it later. go to https://mycroft.ai/cla and sign up there. You'll get an e-mail fairly soon.

Many thanks for helping out!

**Comment by bolt25** [comment]
I would like to work on this.
Can anyone help me understand how and where can I start contributing ? 
P.S -I'm new to open source

**Comment by forslund** [comment]
Hi @bolt25, you're very welcome to contribute!

First step would be to follow the install mycroft (linux on your computer or in a virtual machine) and make sure you can run the testcases with

```
source venv-activate.sh
pytest test/unittests/
```

Then you will need to add a new file called `test_audioservice.py` in `test/unittests/skills/` and add create testcases there. (you can see the other files in the folder for reference, the audioservice is fairly standalone and won't require the same amount of weird mocking techniques though, hopefully being much simpler).

Something like this should be the general structure of the tests:

```python
from unittest import TestCase
from unittest.mock import MagicMock


class TestAudioService(TestCase):
    def setUp(self):
        self.bus = MagicMock()
        self.audioservice = AudioService(self.bus)

    def test_play(self):
        self.audioservice.play('http://example.com/file.mp3')
        emitted_message = self.bus.emit.call_arg_list[0][0]
        self.assertEqual(emitted_message.type, 'mycroft.audio.service.play')
        self.assertEqual(emitted_message.data, EXPECTED_DATA) # expected data needs to be figured out and added

    def text_other_test_case(self):
        ...
```
