### ISSUE TITLE
Extract "day after tomorrow" not working

### ISSUE THREAD

**Issue by moritzgloeckl** [MycroftAI/mycroft-core#2333]
Hi,

I'm running the latest docker image, with mycroft-core 18.8.4

In my skill's code I'm using `extract_datetime("day after tomorrow")` (for testing), this leads to the following error:

```
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/skills/core.py", line 736, in wrapper
    handler(message)
  File "/opt/mycroft/skills/my-skill.mycroftai/__init__.py", line 25, in handle_read_tasks_intent
    LOG.error(extract_datetime("day after tomorrow"))
  File "/opt/mycroft/mycroft/util/parse.py", line 170, in extract_datetime
    return extract_datetime_en(text, anchorDate, default_time)
  File "/opt/mycroft/mycroft/util/lang/parse_en.py", line 397, in extract_datetime_en
    not wordPrev[0].isdigit()):
IndexError: string index out of range
```

Has this been fixed already or am I doing something wrong here?

Thanks.

**Comment by ChanceNCounter** [comment]
I'm on it. Pushing a fix and PR now.

**Comment by moritzgloeckl** [comment]
Hi @ChanceNCounter, thanks for fixing this so fast.

**Comment by forslund** [comment]
The fix by @ChanceNCounter has been merged now. Closing this issue.

But @moritzgloeckl the docker project hasn't been maintained for some time so I'm not sure what's the best way for you to update. If you're experienced with docker and want to pick up the project we'd be happy for the help.

**Comment by moritzgloeckl** [comment]
Hi @forslund 

Ok I did not know that it hasn't been maintained - it's working quite well for me, after some minor permission/venv issues. I am somewhat experienced (not a pro though) with docker, so I can take a look if you like.

The reason why I'm using docker is, because it's actually quite nice to develop skills with it. I start the container, attach a volume between my computer and the skills directory. I start the mycroft-cli in debug mode, and develop the skill from PyCharm on my computer. Once I hit save, it immediately reloads the skill and I can just type what I wanted to test, without having to speak to my pi constantly.

This discussion might go beyond this ticket, so we can discuss elsewhere on the chat/forum or something if you like. Then maybe we can chat about what needs to be done Docker-wise.

**Comment by forslund** [comment]
I totally get it. feel free to reach out to me on the chat. The git repo for the docker is over here: https://github.com/MycroftAI/docker-mycroft/
