### ISSUE TITLE
Test cases for CommonPlaySkill

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#2340]
The common play framework requires some tests, currently the logic is [basically untested](https://coveralls.io/builds/25963387/source?filename=mycroft/skills/common_play_skill.py)

Basically a test skill needs to be created inheriting from `CommonPlaySkill`

bind(): ensure super's bind is called and that the `play:query` and `play:start` handlers are created.

__handle_play_query(): ensure the returned confidence level is calculated correctly and that the CPS_query_phrase() method is called.

To make this easier to test we may want to rename the __handle_play_query and __calc_confidence to start with a single underscore...

If assistance is needed contact a dev in our [chat](https://chat.mycroft.ai) or ask questions in the comments of this issue

**Comment by souravsingh** [comment]
@forslund I am interested in working on the issue.How do I start?

**Comment by forslund** [comment]
I would create a file in `tests/unittests/skills` called test_common_play_skill.py

In that file create a common play skill something like

```python
class CommonPlayTest(CommonPlaySkill):
    def CPS_match_query_phrase(self, phrase):
        [...]

    def CPS_start(self, phrase, data):
        [...]

then start writing test cases for that starting with the bind method

example
```python
    def test_bind(self):
        skill = CommonPlayTest()
        bus = Mock()
        skill.bind(bus)

        # Check bus.on called with play:query, play:start
        [...]
```

**Comment by forslund** [comment]
Common play test cases were added in #2459, closing issue.
