### ISSUE TITLE
Add input speech filtering

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mycroft-core#2341]
## Be clear about the software, hardware and version you are running

I'm using Mycroft!

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

Due to (very mild) [security concerns](https://www.theverge.com/2017/9/7/16265906/ultrasound-hack-siri-alexa-google), as well as potential ASR rate improvements, I suggest a low-pass and high-pass filter be added to the speech handler.  

* the low-pass should be enabled by default with a relatively high (15khz) cut off.  
* the high- and low-pass should both be configurable options
* the frequencies for each should be configurable as well
* low-pass filtering alone wouldn't make a big effect on Open Data submitters samples
* if  filters are engaged beyond default, and open data is being collected, should be tagged or log a warning?
* and of course, log any such effects that may be in use.

Other considerations for filtering would be normalizing and [de-noising](https://github.com/Shb742/rnnoise_python).

**Comment by forslund** [comment]
I think we basically have this implicitly at the moment...The default sampling rate is 16000 Hz which should result in a maximum frequency of 8kHz if I remember Nyquist correctly.

**Comment by davidwagnerkc** [comment]
I do not know about making changes to default settings for everybody, but seems like having the El Tocino DeepSpeech special magic mic config available would be something of value to people wanting to get better results from running local ASR models.

**Comment by el-tocino** [comment]
https://github.com/el-tocino/localcroft/blob/master/mycroft-core/mycroft/stt/__init__.py 
probably needs to be updated for current release.  But something to work off of if people are interested.
