### ISSUE TITLE
os_is_like in deb_setup.sh fails when multiple likes are specified

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#2357]
In dev_setup.sh we use the [os_is_like](https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh#L262) function to check the ID_LIKE field in `/etc/os-release`

The function currently only handle single entries like

`ID_LIKE=debian`

but in some cases this may list multiple os's. For example KDE Neon has a field like this

`ID_LIKE="ubuntu debian"`

The function should be updated to handle multiple distributions listed in the ID_LIKE field like above.

**Comment by brennerm** [comment]
Would like to take care of this.

**Comment by forslund** [comment]
Thank you, you're very welcome to tackle it. We require you signing a Contributor License Agreement before we can merge your PR so you might want to start the CLA process directly by going to https://mycroft.ai/cla to reduce the delay after you've submitted the PR and it being merged.
