### ISSUE TITLE
Phillips Hue Skill

### ISSUE THREAD

**Issue by ChristopherRogers1991** [MycroftAI/mycroft-core#238]
Add a skill to control Phillips Hue Lights. Specifically:
- Toggle the lights
- Activate scenes
- Dim
- Change color temp

This is currently underway [here](https://github.com/ChristopherRogers1991/mycroft-core/tree/feature/issues-238). Toggling and scenes are currently supported. Dimming and color temp still to come.

**Comment by ryanleesipes** [comment]
Will try this on Monday.

**Comment by ChristopherRogers1991** [comment]
Dimming and color temp management have been added.

Tests and pep8 are passing - should I open a PR? I'm not sure what the process is for new skills. I saw a few open issues for skills, but haven't seen any that were merged (and it looks like [this roku skill](https://github.com/MycroftAI/mycroft-core/pull/166) was going to be "pop[ped]... out into a third party skill," but I have know idea what that means)

If I should open a PR:
* Should I add requirements to the main requirements.txt, or leave a requirements.txt in my skill's directory?
* Should I just use the same copywrite blob from one of the other files?
* Anything else I should know about or do?

**Comment by aatchison** [comment]
Definitely, that's the best point of discussion for integration into the core. It's encouraged! :)

**Comment by ChristopherRogers1991** [comment]
Just realized I broke a lot of stuff while I was refactoring at 4am this morning (probably a bad idea). Hopefully you didn't try it while it was broken.

I want to add one more intent before opening a PR - should be tonight.

Can someone address the open questions, about whether to include my own requirements.txt file, or add my requirements to the core file, and whether to copy/paste the copywrite blurb from one of the other files?

**Comment by ethanaward** [comment]
@ChristopherRogers1991 At the moment, put the requirements into the core requirements.txt file. That's where they should be for a core skill. We still have yet to work out a good 3P skill system for that, so just put it there for now. 

And yeah, copy the GNU Public License and put it in your file.

**Comment by ChristopherRogers1991** [comment]
Thanks @ethanaward. PR is open. Feel free to rip it to shreds. All feed back is welcome.

**Comment by aatchison** [comment]
Wahoo! @ryanleesipes , you own Phillups Hue lights lol

**Comment by ChristopherRogers1991** [comment]
Looks like the tests failed. I just re-ran locally, and it looks like they pass if I have a local mycroft.ini file (~/.mycroft/mycroft.ini), but failed when I removed that.

I'm assuming that means I need to add the block to the core ini file?

**Comment by ChristopherRogers1991** [comment]
Here's an example stack trace:

    Traceback (most recent call last):                                                                        
      File "/home/chris/Code/mycroft-core/mycroft/skills/core.py", line 88, in load_skill                     
        skill = skill_module.create_skill()                                                                   
      File "/home/chris/Code/mycroft-core/mycroft/skills/phillips_hue/__init__.py", line 274, in create_skill 
        return PhillipsHueSkill()                                                                             
      File "/home/chris/Code/mycroft-core/mycroft/skills/phillips_hue/__init__.py", line 43, in __init__      
        int(self.config.get('brightness_step', 50))                                                           
    AttributeError: 'NoneType' object has no attribute 'get'

**Comment by aatchison** [comment]
You could probably add some default or empty configurations and maybe make it pass without acting if the settings aren't filled in with valid data? Maybe add some exceptions to notify that there is no configuration on invocation?
 I'm not entirely sure.

**Comment by ethanaward** [comment]
@ChristopherRogers1991 Yeah, config stuff needs to be at least empty in the mycroft.ini file, I think. Feel free to also bring up these comments on the PR so that people reviewing it can see your comments in a centralized place.

**Comment by ChristopherRogers1991** [comment]
Ok, they're all passing now.

**Comment by aatchison** [comment]
We now have a skill for Hue in https://github.com/MycroftAI/mycroft-skills
