### ISSUE TITLE
home.mycroft.ai/devices/add redirects to home.mycroft.ai and i am not able to register my new Ubuntu device

### ISSUE THREAD

**Issue by akhiljns** [MycroftAI/mycroft-core#2383]

**Comment by mroettgen** [comment]
This affects me, too.

Ubuntu 19.10  
Happens in Chrome 78.0.3904.97 as well as Firefox 70.0.1  

Console output is:
```
GET https://account.mycroft.ai/api/defaults 502 (Bad Gateway)

ERROR Error: Uncaught (in promise): e: {
  "headers": {"normalizedNames":{},"lazyUpdate":null},
  "status": 502,"statusText":"Bad Gateway",
  "url": "https://account.mycroft.ai/api/defaults",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://account.mycroft.ai/api/defaults: 502 Bad Gateway",
  "error": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.15.5 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n"
}
    at P (polyfills.fe2ee2d4ceefdcd961d7.js:1)
    at P (polyfills.fe2ee2d4ceefdcd961d7.js:1)
    at polyfills.fe2ee2d4ceefdcd961d7.js:1
    at e.invokeTask (polyfills.fe2ee2d4ceefdcd961d7.js:1)
    at Object.onInvokeTask (main.d5bfb4f8cb54f908b0f5.js:1)
    at e.invokeTask (polyfills.fe2ee2d4ceefdcd961d7.js:1)
    at t.runTask (polyfills.fe2ee2d4ceefdcd961d7.js:1)
    at g (polyfills.fe2ee2d4ceefdcd961d7.js:1)
    at t.invokeTask [as invoke] (polyfills.fe2ee2d4ceefdcd961d7.js:1)
    at m (polyfills.fe2ee2d4ceefdcd961d7.js:1)

GET https://account.mycroft.ai/api/preferences net::ERR_ABORTED 502 (Bad Gateway)
```

**Comment by forslund** [comment]
Thanks for reporting, I see this as well.

Going to ping @chrisveilleux who handles most of the infrastucture.

**Comment by akhiljns** [comment]
> This affects me, too.
> 
> Ubuntu 19.10
> Happens in Chrome 78.0.3904.97 as well as Firefox 70.0.1
> 
> Console output is:
> 
> ```
> GET https://account.mycroft.ai/api/defaults 502 (Bad Gateway)
> 
> ERROR Error: Uncaught (in promise): e: {
>   "headers": {"normalizedNames":{},"lazyUpdate":null},
>   "status": 502,"statusText":"Bad Gateway",
>   "url": "https://account.mycroft.ai/api/defaults",
>   "ok": false,
>   "name": "HttpErrorResponse",
>   "message": "Http failure response for https://account.mycroft.ai/api/defaults: 502 Bad Gateway",
>   "error": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.15.5 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
> }
>     at P (polyfills.fe2ee2d4ceefdcd961d7.js:1)
>     at P (polyfills.fe2ee2d4ceefdcd961d7.js:1)
>     at polyfills.fe2ee2d4ceefdcd961d7.js:1
>     at e.invokeTask (polyfills.fe2ee2d4ceefdcd961d7.js:1)
>     at Object.onInvokeTask (main.d5bfb4f8cb54f908b0f5.js:1)
>     at e.invokeTask (polyfills.fe2ee2d4ceefdcd961d7.js:1)
>     at t.runTask (polyfills.fe2ee2d4ceefdcd961d7.js:1)
>     at g (polyfills.fe2ee2d4ceefdcd961d7.js:1)
>     at t.invokeTask [as invoke] (polyfills.fe2ee2d4ceefdcd961d7.js:1)
>     at m (polyfills.fe2ee2d4ceefdcd961d7.js:1)
> 
> GET https://account.mycroft.ai/api/preferences net::ERR_ABORTED 502 (Bad Gateway)
> ```

yep it seems it fails to retrieve account details and accounts.mycroft.ai results in bad gateway error

**Comment by forslund** [comment]
The backend issue has been resolved. The host had been rebooted but the service wasn't restarted automatically.

I'm closing the issue, if the issue remains for you feel free to reopen.

Once more thanks for reporting.

**Comment by krisgesling** [comment]
Hi there, just wanted to close the loop on this.

On Sunday the 10th of November, one of the Mycroft service API endpoints became unavailable,  preventing certain pages from loading correctly. This included the Profile, My Devices and Add Device pages of Home.mycroft.ai. As per our standard incident response process, a [report for this incident](https://docs.google.com/document/d/1c_14fncocbL9cw7wncfwqGK26AfmgeRFPVWuiRfwokI/edit#heading=h.ca8hd315e96j) was created and is available for the Community to review. 

Our engineering team investigated and restored this service in a matter of hours, and all services are now fully functional.

A standard post-incident review is being conducted, and the team has taken immediate actions to reduce the chance of this type of incident reoccurring in the future, as well as to improve automatic recovery if a service does become unresponsive.  

We apologize for those who could not access all of their account information during this time, and appreciate our Communities responsiveness in reporting the issue. The Communities support in identifying and debugging issues assists us in continually improving Mycroft's services.

Thanks
The team at Mycroft AI
