### ISSUE TITLE
Pairing does not work properly on CLI

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#239]
When a user has an unpaired device and uses the voice client, they get prompted to pair their device as soon as they say anything. This runs through the listener, which manually appends `pair my device` to the heard utterances to trigger the pairing process. 

When using the CLI , nothing runs through the listener, so you have to explicitly trigger the pairing process via typing `pair my device`, which isn't necessarily intuitive. Also, if you try to use one of the other Cerberus services, it will tell you that your device is not yet registered but not give you a pairing code.

**Comment by aatchison** [comment]
Thanks ethan
