### ISSUE TITLE
python version redhat

### ISSUE THREAD

**Issue by maxbachmann** [MycroftAI/mycroft-core#2407]
dev_setup.sh currently installs:
```
python34 python34-devel python34-pkgconfig python34-libs
```
on centos/redhat even though python 3.4 was already dropped from mycroft

**Comment by maxbachmann** [comment]
I just tried it in a centos docker container. There it was enough to install
```bash
python3-devel
```
and the other python stuff was installed as dependency. (it installed python3.6 and python3.4 was not even available in the package manager)

**Comment by forslund** [comment]
If you have a change that works, feel free to submit. If you want someone to try it *cschantz* on the mycroft chat was quite involved in testing the last version.

**Comment by maxbachmann** [comment]
for testing on centos the docker container should be enough, however since the same install function is run on redhat, it would be good if someone could test it over there. I will open a PR and ask cschantz to test it.
