### ISSUE TITLE
pocketsphinx custom wake words broken (backend)

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#2417]
https://github.com/MycroftAI/mycroft-core/pull/2395 reverted this https://github.com/MycroftAI/mycroft-core/pull/1062#discussion_r137691072

backend seems to still be setting phonemes under listener, either backend needs update or that pr needs to be reverted

symptoms reported by users in chat:
https://chat.mycroft.ai/community/pl/3uayazg6tbb6pgf5ug6wdetwne
https://chat.mycroft.ai/community/pl/a8hfu5gx5jgcmee3u3rxc5ozza

**Comment by forslund** [comment]
The common issue seem to be that it breaks if the precise dev-mode has been activated:

```
{
  "max_allowed_core_version": 19.8,
  "precise": {
    "model_url": "https://raw.githubusercontent.com/MycroftAI/precise-data/models-dev/{wake_word}.tar.gz",
    "dist_url": "https://github.com/MycroftAI/precise-data/raw/dist/{arch}/latest"
  },
  "hotwords": {
    "hey jarvis": {
      "sensitivity": 0.5,
      "module": "precise"
    }
  }
```

Removing the hotword section here restores the functionality.

My first guess is that the merge of missing parts are incomplete and triggers the issue. The backend needs to be updated but in the meantime we need to fix cores merging. IMHO

**Comment by forslund** [comment]
Also it's unclear where the configuration in question comes from. It looks like the setup that is generated by the configuration skill when precise dev-models are activated.
