### ISSUE TITLE
Build systems for multiple environments, architectures, development state, and packaging methods

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#242]
At the moment build and publish scripts are directly included in mycroft-core. This method has some benefits, but it would be ideal not to tie the packaging process to the code base.

**Comment by krisgesling** [comment]
This is now being tracked and actioned elsewhere eg
https://github.com/MycroftAI/mycroft-devices

If anyone sees this and has ideas for specific changes to be made, please open a new issue describing them.

Thanks
