### ISSUE TITLE
`:log level debug` not working from CLI

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2420]
On a Linux installation in the Mycroft CLI, issuing the `:log level debug` command changes the log level for output to `/var/log/mycroft/*.log` but has no effect on the messages shown in the CLI's log output. 

Tested on Ubuntu 19.10 and Debian 10

**Comment by forslund** [comment]
Can you verify that DEBUG messages aren't filtered? check the ~/.mycroft_cli.conf

**Comment by ChanceNCounter** [comment]
I can confirm that they *are* filtered, and also that changing the log level to debug does not un-filter them.

Is that the intended behavior? I'd expect that filter to be removed (or bypassed) when the user selects debug logging.

**Comment by KathyReid** [comment]
tack så mycket, åke :-) 

```
kathyreid@kathyreid-zenbook-ux533fd:~$ cat .mycroft_cli.conf 
{"filters": ["mouth.viseme", "mouth.display", "mouth.icon", "DEBUG"], "cy_chat_area": 7, "show_last_key": false, "max_log_lines": 5000, "show_meter": true}
```
changing this now gives: 

![Screenshot from 2019-12-09 16-59-24](https://user-images.githubusercontent.com/114158/70411057-4521f200-1aa5-11ea-84a6-70ca3b97000e.png)

What I think is happening here is that the `log level debug` in the CLI _allows_ the logging to the shown in the CLI, but it's suppressed by `mycroft_cli.conf` - that is, the `.conf` file takes precedence.

**Comment by forslund** [comment]
It sort of is intended the filter is separate system for the cli.

That said the DEBUG shouldn't be filtered by [default](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/text/text_client.py#L65). so that's an issue. We could technically forbid the DEBUG to be filtered now since it can now be controlled via the log level.
