### ISSUE TITLE
Language Settings not working

### ISSUE THREAD

**Issue by flozi00** [MycroftAI/mycroft-core#2425]
## Be clear about the software, hardware and version you are running

* I'm running a rapsberrypi 3
* With Mycroft from master branch
* With the standard Wake Word

## Try to provide steps that we can use to replicate the Issue

install mycroft as in the tutortial described
use the command: mycroft-config set lang "de-de"

restart mycroft instance
mycroft is still only working in english and not in german or any other language

**Comment by ChanceNCounter** [comment]
Can you confirm that `~/.mycroft/mycroft.conf` reflects "de-de" as your primary language, as seen [here](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/languages#1-language-setting)?

**Comment by flozi00** [comment]
Yes, it was correct.
I changed the /etc/Mycroft/mycroft.conf manually for the tts and it was still in English too

**Comment by forslund** [comment]
Setting the "lang" to "de-de" should switch you to german dialogs and vocabs. (Tested it here just now and it works)

Then you need to setup a german STT, currently the best option is the google STT and for german TTS you'll need to use the google TTS as well.

Have  you read the documentation on [switching language](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/languages)?

**Comment by flozi00** [comment]
yes, but I didn't configure the stt engine. do I have to do that ? I only changed the lang in Mycroft.conf and the tts in /etc/Mycroft/mycroft.conf.I also have a question, why does every skill have to be translated and the language is not machine translated, so the skill only has to be written in English and translators do the rest

**Comment by forslund** [comment]
The default mycroft STT only handles English currently I'm afraid so it needs to be set up.

It was suggested before to have automatic translations but the quality (in my case Swedish) was not of very good quality.The community submitted translations through translate.mycroft.ai are much better imho. But we could try something that did a first pass automatic and then the community would correct it or something.

**Comment by flozi00** [comment]
Could you provide sample configuration files for the different languages and engines ?

Did you ever heard about deepl ?
It's a German start-up with high data protection and very good translations.
They don't have so much languages but it becomes more.

**Comment by forslund** [comment]
Haven't heard of it but it sounds interesting. will google :)

**Comment by flozi00** [comment]
After complete new setup it is working now.
Closing this issue
