### ISSUE TITLE
AttributeError: '_curses.window' object has no attribute 'get_wch' (with Pyenv & fix included)

### ISSUE THREAD

**Issue by pglombardo** [MycroftAI/mycroft-core#2426]
Running the source from the master branch on an Ubuntu 18.04.3 LTS with [pyenv](https://github.com/pyenv/pyenv/).

All worked well with `dev_setup.sh` and `start_mycroft.sh deebug` until the CLI tried to boot which resulted in:

    AttributeError: '_curses.window' object has no attribute 'get_wch'

After some digging, the fix was to install `libncursesw5-dev` and rebuild the installed Python version via pyenv.  In my case, the steps were:

    sudo apt install libncursesw5-dev
    pyenv install <version>

Now all works well.  This issue can serve as a solution for anyone else that hits this scenario.  You might think about adding a `TROUBLESHOOTING.md` file or a page in the wiki to collect up such fixes.  Otherwise closed issues work well too.

**Comment by forslund** [comment]
We do have a troubleshooting section in the [documentation](https://mycroft-ai.gitbook.io/docs/), it would be great if you'd like to contribute this tip. It can be done using the documentation [github-repo](https://github.com/MycroftAI/documentation)

**Comment by pglombardo** [comment]
Done.  Hope it helps.

**Comment by forslund** [comment]
Thanks! closing this issue now since PR was created.
