### ISSUE TITLE
update responsive voice TTS

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#2434]
integration of responsive voice uses an older version of my package https://github.com/OpenJarbas/py_responsivevoice

we should either pin an older version of the package/log a warning, or update the TTS engine to support all the new voices

**Comment by forslund** [comment]
Maybe we should do both? update it to the current version adding the new voices and pin that?

**Comment by JarbasAl** [comment]
i will look into adding some extra logic in my package to lookup a voice by a named string, this should make it easier to integrate

regarding pinning versions, since this is not a default requirement how would we do that? in the TTS Validator class?

**Comment by JarbasAl** [comment]
i don't think this issue was ever fixed and responsive voice changed quite a bit since

i am closing this since engines are being migrated into plugins and one already exists https://github.com/OpenVoiceOS/ovos-tts-plugin-responsivevoice
