### ISSUE TITLE
Packagebuilds for Archlinux.

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#244]

**Comment by rafamanzo** [comment]
I've come with something primitive at:
* https://gitlab.com/rafamanzo/aur-mycroft-core
* https://aur.archlinux.org/packages/mycroft-core/

It is just the minimal to get it working and probably have many issues for which my system is biased.

I don't have plenty of time to keep it updated, so if someone wants to adopt it, please let me know!

**Comment by aatchison** [comment]
It looks like the mission is accomplished, though it probably needs to be maintained.
