### ISSUE TITLE
Increase in reports of accidental/inexplicable/inappropriate wake word detection

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/mycroft-core#2444]
Sadly, I don't have much more to add *yet*. Still, there have been more reports of apparently random activation over the past few days than I recall seeing over the first several months of my involvement.

I'm not sure it coincided with 19.8.5, but it's definitely the past couple of weeks.

I have myself been experiencing some inexplicable waking, where Mycroft seems to awaken from random sounds that aren't even speech.

Additionally, I've got a directional microphone hooked up to a USB sound card. It produces a whole lot of noise. When that microphone is active, inappropriate activation is constant, and I mean constant. As soon as STT gives up, it activates again.

Off the top of my head, @TheLastProject mentioned something about this, as well as [this](https://chat.mycroft.ai/community/pl/pu6yi4ccgff17k8mfr7q7p1upc) user in chat, a few hours ago. I can't remember which other users mentioned it in chat, but there was at least one; search-fu is failing me.

I'm not sure how to begin debugging this. I dunno if the problem lies in the wake word listener or with core or what.

**Comment by forslund** [comment]
The biggest change was how the hotword engine parameters are loaded, can you verify that the "hey mycroft" wake word is loaded as a precise wake word and verify that precise-engine is launched? Should look like this:

```
$ ps aux | grep precise
ake       3662  0.0  0.0   8496   776 pts/5    S+   09:47   0:00 /home/ake/.mycroft/precise/precise-engine/precise-engine /home/ake/.mycroft/precise/hey-mycroft.pb 2048
ake       3664 32.9  3.3 1295276 133436 pts/5  Sl+  09:47   0:18 /home/ake/.mycroft/precise/precise-engine/precise-engine /home/ake/.mycroft/precise/hey-mycroft.pb 2048
```

**Comment by JarbasAl** [comment]
if this is suddenly happening to many users it is probably config related, either users are screwing up and it falls back to pocketsphinx, or something is wrong when updating from the backend

is this for the "hey mycroft" wake word or custom words?

**Comment by ChanceNCounter** [comment]
Re: Precise, yes and yes.

```
❯ ps aux | grep precise
chance     436  0.0  0.0  10788   760 pts/1    S    15:46   0:00 /home/chance/.mycroft/precise/precise-engine/precise-engine /home/chance/.mycroft/precise/hey-mycroft.pb 2048
chance     439  6.1  0.6 1370208 106840 pts/1  Sl   15:46   0:02 /home/chance/.mycroft/precise/precise-engine/precise-engine /home/chance/.mycroft/precise/hey-mycroft.pb 2048
```

> Edit: In addition noisy mics have in the past been prone to false activations on Precise.

Well, mine are certainly noisy mics! Only one produces *constant* activations, though. I wonder whether others' mics are also noisy.

> And further more there could also be an issue with some mismatching/unsupported sample frequency. Does STT produce valid transcriptions?

It does, though I have to practically put the one mic in my mouth, and STT is the *only* thing that can make out what I'm saying with the other mic. It sure sounds like this is a Precise problem, at least in my case.

@JarbasAl It's Precise, "hey mycroft", and no config changes in ages. Indeed, it happens with the same mic across two different Mycroft builds (both running dev, though)

**Comment by el-tocino** [comment]
Start with the voice log (/var/log/mycroft/voice.log) and ee what it's getting.  Try turning on wake word saving/uploads to capture what's triggering it.

**Comment by ChanceNCounter** [comment]
It's not getting anything. That's the point.

**Comment by el-tocino** [comment]
If it's getting nothing that means it's not getting triggered.

I suppose it's possible your log files aren't getting logged to for some reason, but that would likely be some custom config or local tweaks that have happened to make that so.

**Comment by ChanceNCounter** [comment]
No, I mean, the entire log consists of the trigger. That's it. It's not transcribing anything, there's no reading the log to determine what else it was hearing in context. When I say constant activations, that's no hyperbole. It activates, I deactivate it, it activates again with no delay whatsoever.

**Comment by el-tocino** [comment]
Then turn on wake word saving so you can start hearing what it's triggering on.  That sounds more like a mic issue if it's that often...

**Comment by ChanceNCounter** [comment]
It's definitely a mic problem in my case. I can't speak to the other reports. Still, the question now becomes why static is triggering it.

**Comment by el-tocino** [comment]
You mention above that only one mic does this?  Why haven't you swapped for a mic that doesn't?  What kind of mics are you using?

**Comment by ChanceNCounter** [comment]
My other mic does it sporadically, and I have switched, but it's still static triggering it. Incidentally, I've noticed that the linked report in chat was using PocketSphinx.

**Comment by NeonJarbas** [comment]
cause seems to be network issues, precise update check causes a time out and hotword falls back to pocketsphinx

chat discussion https://chat.mycroft.ai/community/pl/rrskc1zauig6d8py1j3xj58zww

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
