### ISSUE TITLE
Separate build system for Mycroft units.

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#245]

**Comment by junland** [comment]
@aatchison Could you add more context to this issue? I think I have something in mind, but don't know if it's correct or not.

**Comment by aatchison** [comment]
Hello!
From the beginning, we have been targeting the Mycroft unit itself. The core code includes specialized scripts and functions for the unit that aren't necessarily useful on every platform. One example of this is the enclosure client: https://github.com/MycroftAI/mycroft-core/tree/master/mycroft/client/enclosure and the corresponding service that runs on the device: https://github.com/MycroftAI/mycroft-core/blob/master/publish/publish.sh#L104

Also, I am working on snap packages so the device can be run on ubuntu-core. Some parts will be unit specific as well.

**Comment by junland** [comment]
@aatchison Hmmm alright, I could see something like the Open Build Service from OpenSUSE, dunno if it makes packages for alternate archs thou. Also it's prolly out of scope but maybe look at the Yocto Project. It's more for building a embedded Linux distro but it has tools to build and make software and software SDK's for your devices....

**Comment by aatchison** [comment]
Issue resolved.
