### ISSUE TITLE
add config entry for path to save output files

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mycroft-core#2454]
# How to submit an Issue to a Mycroft repository
## Be clear about the software, hardware and version you are running
* I'm running a picroft
* With latest unstable
* With custom Wake Word

## Try to provide steps that we can use to replicate the Issue

Turn on saving of wake words and audio clips (set both of these to "true"):
    "record_wake_words": false,
    "save_utterances": false,

only over here: https://github.com/MycroftAI/mycroft-core/blob/master/mycroft/configuration/mycroft.conf 
does it mention where it saves these to.  
This should be a configurable path, much like the upload URL is, for either/both of these.  Perhaps "default_save_path" or something less awkward.

**Comment by krisgesling** [comment]
Yeah good call.

Would a single configurable path with two sub-directories be sufficient?
- `mycroft_wake_words`
- `mycroft_utterances`

**Comment by el-tocino** [comment]
yeah seems reasonable to me.

**Comment by KathyReid** [comment]
Another thing to consider here is that they would need to be writable by the `mycroft` user, so the directories would need the correct ownership permissions. 

Another thing to consider is that even though saving Wake Words and Utterances is off by default, I could see this potentially filling disk space over time. I've seen several cases where `/var/log/mycroft` contains hundreds of Mb of logs, even with `logrotate`. Do we need to put in place any checks to protect disk space, particularly on the `picroft` or `mark` platforms?

**Comment by el-tocino** [comment]
Since it's off by default and would require direct cli changes, I don't think it should require disk protections.  Turning it on means you've got enough knowledge to get to the system and handle basic stuff.  A warning in the config might be useful by the option. If this is something coming to web config or turned on by default then this would be worth revisiting.  

The permissions issue is another good point, but would be covered in the logs.  Again, though, if they're doing cli level work to get this set they can get to their logs, and should be able to see the issue.

**Comment by JarbasAl** [comment]
permissions would only apply to the mark1/picroft, otherwise we can not assume anything regarding the installs/users, i don't like to make assumptions about how the users are using it, i don't think we should touch permissions at all. 

I might install mycroft as a standalone user, in main user account, or as root. i have done all these at some point

a warning in mark1/picroft docs should be enough
