### ISSUE TITLE
Publish Mycroft on PyPI

### ISSUE THREAD

**Issue by opensource-assist** [MycroftAI/mycroft-core#2457]
It would heavily reduce the installation overhead.

**Comment by krisgesling** [comment]
Hey Aurora, we're looking at the best ways to package Mycroft up at the moment.

Will throw PyPI in the mix of options :)

**Comment by forslund** [comment]
I am positive to this. All our packaging tools uses mycroft-core as a pip package. So the biggest issue is to write the instructions on how to manually install the dependencies.

**Comment by NeonDaniel** [comment]
+1 on this. As far as system dependencies, I believe the docs would only need to include:
```
sudo apt update
          sudo apt install -y gcc libfann-dev swig libssl-dev portaudio19-dev git libpulse-dev
          pip install wheel
          pip install mycroft
```

On a related note, I found it easier to manage updates and dependencies by breaking up core into the separate services and maintaining them independently (https://pypi.org/project/neon-messagebus/, https://pypi.org/project/neon-gui/, https://pypi.org/project/neon-audio/, https://pypi.org/project/neon-speech/)

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
