### ISSUE TITLE
How do i uninstall from Archlinux?

### ISSUE THREAD

**Issue by Merith-TK** [MycroftAI/mycroft-core#2465]
For example: 

* I'm running it on Archlinux
* With version `git` 

## Try to provide steps that we can use to replicate the Issue
I see no way of uninstalling when using a git clone version of the repo

**Comment by krisgesling** [comment]
Hi Merith,

`./dev_setup.sh --clean` should remove all files and directories that Mycroft creates. You can [see the function it triggers here](https://github.com/MycroftAI/mycroft-core/blob/f0caf4255139a991c9ff59e10ae276fd866e9059/dev_setup.sh#L27).

I need to add this to the docs, it's quite new.

**Comment by Merith-TK** [comment]
that worked., thanks
