### ISSUE TITLE
The audioaccuracytest doesn't work

### ISSUE THREAD

**Issue by jugdizh** [MycroftAI/mycroft-core#2466]
I am on master branch of Mycroft. OS is Ubuntu 16.04. I have completed the ./dev-setup.sh process and now I'm running through the tests available via ./start-mycroft.sh

The audioaccuracytest seems to be broken:
```
$ ./start-mycroft.sh audioaccuracytest
Already up-to-date.
Initializing...
Starting audioaccuracytest
/opt/mycroft/.venv/bin/python3: No module named mycroft.audio-accuracy-test.__main__; 'mycroft.audio-accuracy-test' is a package and cannot be directly executed
```

**Comment by forslund** [comment]
Hi,

thanks for pointing this out. Seems like it hasn't been operational for quite some time. I'll make a PR to updated it and get it back into working order.
