### ISSUE TITLE
skill container --dir should be replaced with positional argument

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#247]
Previously the command to start a skill in a container was:

`./start.sh skill_container SKILL_PATH`

Right now the command needs to be supplemented with a `--dir`:

`./start.sh skill_container --dir SKILL_PATH`

this is clunky as the skill directory is generally needed (the default value will seldom work). I believe the old command line should be brought back.

**Comment by ethanaward** [comment]
Fixed by #248
