### ISSUE TITLE
Making the Audio Service work with Strawberry Music Player

### ISSUE THREAD

**Issue by DAMO238** [MycroftAI/mycroft-core#2502]
## Be clear about the software, hardware and version you are running

Arch Linux, latest development version, custom wake word (precise)

## Try to provide steps that we can use to replicate the Issue

1. Install and run strawberry
2. Ask mycroft to stop, pause, play, or any other music control intent

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

Mycroft should hook into the music player and run the appropriate action. However, mycroft is silent and does not do anything. I believe this is because mycroft doesn't know how to deal with strawberry, but I am struggling to understand how the audio service works.

The commands used to control strawberry are as follows:
strawberry [option]

-p play
-t toggle playing
-u pause
-s stop
-q stop after current track
-r previous
-f next

There are more niche uses in the man file for strawberry.

If someone points me in the right direction, I could probably make a pull request to allow integration with strawberry.

**Comment by forslund** [comment]
Strawberry looks like a nice commandline player.

I'll see if I can write a short tutorial on how to create an audio service backend.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
