### ISSUE TITLE
Add a systemd service

### ISSUE THREAD

**Issue by StuartIanNaylor** [MycroftAI/mycroft-core#2513]
My horrid hack that sure more finesse could be provided but as an example

/home/pi/mycroft-core/service-mycroft.sh
```
#!/usr/bin/env bash

DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
DBUS_SESSION_BUS_PID=`cat /run/dbus/pid`
pulseaudio --start
/home/pi/mycroft-core/start-mycroft.sh all
```

sudo systemctl edit --force --full mycroft-start
```
[Unit]
Description = Mycroft core AI
After=dhcpcd.service

[Service]
User=pi
Group=pi
ExecStart = /home/pi/mycroft-core/service-mycroft.sh
ExecStop = /home/pi/mycroft-core/stop-mycroft.sh
Type=oneshot
RemainAfterExit=true

[Install]
WantedBy = multi-user.target
```
sudo systemctl enable mycroft-start
sudo reboot

I just picked a late order service and dhcpcd was last but any late order After=

**Comment by JarbasAl** [comment]
https://github.com/MycroftAI/mycroft-core/pull/2475 and https://github.com/MycroftAI/mycroft-core/issues/346 are about this

**Comment by forslund** [comment]
This repo should basically be implementation-agnostic. We could however setup an examples directory based on the work by  @j1nx. Let's close this issue in favor of the older issue #346 and continue that discussion there.
