### ISSUE TITLE
IBM Watson STT not working

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2516]
The IBM STT interface is not currently working as IBM have changed their authentication mechanism. 

The existing implementation uses the [SpeechRecognition Python package](https://github.com/Uberi/speech_recognition) which has not been updated to use the new API key. 

The simplest fix would be to implement a new StreamingSTT class within Mycroft and not use the SR package for this service.

IBM STT Docs:
https://cloud.ibm.com/apidocs/speech-to-text/speech-to-text

**Comment by forslund** [comment]
It would probably suffice with an even simpler non-streaming version as a stop-gap. wouldn't require many lines of code. (the streaming service which can be a bit tricky)

**Comment by forslund** [comment]
Some guidance for anyone attempting the non-streaming version:
Change the base class to TokenSTT, the user will need to supply the url in the module config

```json
"stt" {
  "ibm": {
    "credential": {
      "token": "API_KEY_FROM_SERVICE"
    },
    "url": "URL_FROM_SERVICE"
  }
```
To authenticate using requests use HTTPBasicAuth('api' self.credential['token']) to authenticate with the service,

the request call becomes something like
```python
response = post(
    self.config['url'] + IBMSTT.ENDPOINT,
    headers={'Content-Type': 'audio/flac'},
    data=audio.get_flac_data(convert_rate=16000),
    auth=HTTPBasicAuth('apikey', self.token))

Then some additional parameters for language and/or model could be added as well.

**Comment by codyreinold** [comment]
I've submitted a PR for this issue--it should be resolved now. Details are in the PR, but essentially moved the functionality from SpeechRecognition and rewrote in Mycroft. Opted for a non-streaming interface to start, simply for simplicity.

If we continue to move away from SpeechRecognition to in-codebase solutions, we can look at streaming at that time. I would imagine usage of IBM Cloud is relatively low at the moment, so I don't think this is a huge priority.
