### ISSUE TITLE
skills not showing in market.mycroft.ai... configurable

### ISSUE THREAD

**Issue by stratus-ss** [MycroftAI/mycroft-core#2518]
## Be clear about the software, hardware and version you are running

I am running Mycroft on Debian buster arm (not picroft) installed from github method.

Tried both the unstable dev build and the stable build using Jarvis wake word

## Try to provide steps that we can use to replicate the Issue

1. Burn the Raspbian Lite image to Micro SD card using Etcher
2. Seat the Micro SD card in the RPi 4
3. Boot raspbian, run the updates
4. reboot
5. git clone https://github.com/MycroftAI/mycroft-core
6. ./dev_setup.sh
7. choose unstable or stable
8. wait for install complete
9. pair device
10. install skill "hey mycroft install spotify skill"

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

I expect based on the documentation that both Spotify and Home Assistant skills would be configurable from https://market.mycroft.ai/skills

## Upload any files to the Issue that will be useful in helping us to investigate
[mycroft_logs.tar.gz](https://github.com/MycroftAI/mycroft-core/files/4397642/mycroft_logs.tar.gz)

**Comment by andlo** [comment]
Hi @stratus-ss 
No - tey are in market for show wat can be installed.

After installation configuration are in the skills section when you are loged in on home.mycroft.ai
Direct link to skills settings here https://account.mycroft.ai/skills

![image](https://user-images.githubusercontent.com/3314671/77832114-eb1c6980-7133-11ea-8adc-9bcce3e7c931.png)

**Comment by stratus-ss** [comment]
Thank you for the quick reply. You are correct this is user error. My confusion is largely because the skills place has a check mark beside some which I assume meant they were installed
