### ISSUE TITLE
can only connect once to gui

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#2525]
im having some weird issue with the GUI websocket

- start mycroft
- gui connects (debug cli GUI)
- kill debug cli
- start debug cli
- gui wont connect again until mycroft enclosure restart

I was making my [own cli GUI](https://gist.github.com/JarbasAl/031f66adcab4ab85824b8caef9576d9d)

enclosure logs bellow
```
2020-04-01 05:00:24.357 | INFO     |  9767 | mycroft.messagebus.client.client:on_open:67 | Connected
2020-04-01 05:00:32.569 | INFO     |  9767 | tornado.access | 101 GET /gui (127.0.0.1) 0.80ms
2020-04-01 05:00:44.081 | INFO     |  9767 | mycroft.client.enclosure.base:callback_disconnect:423 | Disconnecting!
2020-04-01 05:00:44.081 | INFO     |  9767 | mycroft.client.enclosure.base:callback_disconnect:425 | dict_keys(['dummy_10064'])
2020-04-01 05:00:44.082 | INFO     |  9767 | mycroft.client.enclosure.base:callback_disconnect:426 | deleting: dummy_10064
2020-04-01 05:00:51.334 | WARNING  |  9767 | tornado.general | tornado.autoreload started more than once in the same process
```

3 ways to replicate
- if gui is open in debug cli, my gui will not connect
- if gui is open in my script, gui cli will not connect
- if debug cli is restarted, second time gui wont connect 

so i guess the issue can be summed up as only 1 gui can connect, only once

NOTE: cli GUI always prints that it connected, that message is logged before it actually connects, so that needs refactoring

**Comment by forslund** [comment]
This is an issue that originated with the upgrade of tornado.

There is a branch with a workaround at [bugfix/workaround-multi-displays](https://github.com/MycroftAI/mycroft-core/tree/bugfix/workaround-multi-displays)

However it's not the ideal solution since tornado really doesn't like being run in this fashion nowadays. We're currently considering to rewrite the gui bus to be a single connection but isolating the displays by using jwt messages or a similar approach.

**Comment by JarbasAl** [comment]
with the new message targetting mechanism you can even share the existing bus, the GUI is already connected to it anyway

**Comment by forslund** [comment]
The problem we'd like to resolve is the multicast, with targeting anything can still see the messages sent to the individual guis. The original idea with separation on different ports was to make sure different gui's could send things like a password without it being "easy" to listen to. It's a flawed mechanic right now and more obfuscation than an actual solution.

My idea was to setup a http(s) endpoint using tornado where a gui could register id and jwt key. Then connect to the public gui websocket and communicate privately using jwt.

**Comment by JarbasAl** [comment]
with current implementation any GUI needs to connect to the core socket to register, skills send messages to the core socket before those are sent to the GUI socket, which means all GUIs get everything anyway

a big refactor is needed in the whole core, no point in securing the GUI socket if it is still getting all data from core socket

**Comment by AIIX** [comment]
can the workaround fix branch be merged in dev till a better solution is sort out since it seems to work better than the quite broken current implementation in dev ? https://github.com/MycroftAI/mycroft-core/tree/bugfix/workaround-multi-displays

**Comment by forslund** [comment]
@JarbasAI point well made. In the thoughts I had the gui shouldn't connect to the core bus to get the gui bus port at all.

But keeping it even simpler as a start might be good. One possibility could be to still have a separate gui port just for having it open for external connections isolating the most dangerous things, (speech injection etc) on the internal core bus.

@aiix let me add a big todo notice of all the bad things in that solution before I do it.
