### ISSUE TITLE
Pi 2 Model B + Cirrus sound card + Mycroft

### ISSUE THREAD

**Issue by murphyalexandre** [MycroftAI/mycroft-core#254]
Hey,

I'm having some issues with mycroft on my pi 2 and I don't know if this is the place to ask for help. If not, please direct me to where I should ask my questions.

So I have a Cirrus sound card on my Pi and I installed the latest Raspbian (from 2016-05-27) on it with the correct Cirrus driver loaded on boot. Everything is working fine with the sound card, I have only one input and one output for aplay and arecord and both of them are working right out the box.

<img width="508" alt="capture d ecran 2016-06-30 a 14 39 12" src="https://cloud.githubusercontent.com/assets/2568444/16499954/81b78ffe-3ed0-11e6-9252-ac77f4d21fc4.png">

Next thing I did was to try the audiotest. I had some troubles with an old raspbian version and an old Cirrus driver, but now, everything went great, I can hear my voice on the playback.

<img width="563" alt="capture d ecran 2016-06-30 a 14 41 44" src="https://cloud.githubusercontent.com/assets/2568444/16500027/d4404f0e-3ed0-11e6-9d5e-61693c0fec07.png">

The problem is when I try to run Mycroft normally, it simply doesn't work. It just sits there and doesn't hear the wake word.

<img width="963" alt="capture d ecran 2016-06-30 a 14 44 32" src="https://cloud.githubusercontent.com/assets/2568444/16500124/3941f7d6-3ed1-11e6-8a3b-98a424df9645.png">

Running the unittest worked, except some warning saying that the speech recognition couldn't understand the audio. See the [PasteBin](http://pastebin.com/yy6AFanc).

I also tried the audio-accurary-test with a bunch of wav recording with the mic, it worked with the one with multiple keywords in it. It, however, hanged when I tested with a wav of 8000. I don't use that rate in the config, but it might be something interesting to look at.

<img width="742" alt="capture d ecran 2016-06-30 a 14 54 43" src="https://cloud.githubusercontent.com/assets/2568444/16500493/d179c0b4-3ed2-11e6-8951-b7bf95199439.png">

So, I'm here now wondering what to do next. How can I debug this problem of mine? Is there something wrong with my setup?

**Comment by aatchison** [comment]
Did you ever have any luck?

**Comment by murphyalexandre** [comment]
No.

**Comment by aatchison** [comment]
Hmm. You might check out a newer version and let us know. Are you sure it's not a sound card issue? You might try `./start.sh audiotest` instead of those other audio tests.

**Comment by murphyalexandre** [comment]
I would, but I don't have access to the device anymore! Closing it for now.

**Comment by aatchison** [comment]
Thanks, sorry about that.
