### ISSUE TITLE
Wrong installation Dependency Github Path

### ISSUE THREAD

**Issue by UltraBlackLinux** [MycroftAI/mycroft-core#2545]
To make it short: the Installation Script for Arch is wrong:
Instead of: pip install https://github.com/JarbasAJ/py_mplayer/archive/master.zip
It should be: pip install https://github.com/JarbasAI/py_mplayer/archive/master.zip

Pls fix this, i wondered y it didnt work
xD

**Comment by UltraBlackLinux** [comment]
Edit: Changing the path fucks it up, better simply do:
pip install py_mplayer

**Comment by JarbasAl** [comment]
this should be optional and not installed by default

also https://github.com/MycroftAI/py_mplayer fork should be used. I will be archiving my repo. ping me if you need anything done on pypi side.

**Comment by krisgesling** [comment]
As Jarbas said this should be optional not installed by default.

Also if you want the forked version it should be:
```
pip install git+https://github.com/MycroftAI/py_mplayer
```
