### ISSUE TITLE
docker build no response

### ISSUE THREAD

**Issue by dony71** [MycroftAI/mycroft-core#2546]
I try to build docker image for arm64 platform
I get dockerfile from https://hub.docker.com/r/mycroftai/docker-mycroft/dockerfile
It's running until dev_setup.sh execution below, and no response further entering Y or N or y or n
Anybody have similar issue?

================================================
                    Welcome to Mycroft!

This script is designed to make working with Mycroft easy.  During this
first run of dev_setup we will ask you a few questions to help setup
your environment.

Do you want to run on 'master' or against a dev branch?  Unless you are
a developer modifying mycroft-core itself, you should run on the
'master' branch.  It is updated bi-weekly with a stable release.
  Y)es, run on the stable 'master' branch
  N)o, I want to run unstable branches
Choice [Y/N]:

**Comment by dony71** [comment]
btw I'm doing this from ssh terminal

**Comment by forslund** [comment]
Seems like the call to dev_setup.sh is missing the CI environment variable. (having this will skip the interactive part of the dev_setup... Se [here](https://github.com/MycroftAI/docker-mycroft/blob/master/Dockerfile#L17) in the docker repo

**Comment by dony71** [comment]
@forslund : this will build mimic which takes long time on raspberry pi
any better solution?

**Comment by forslund** [comment]
I pushed the arm64 apt package for mimic to the (unofficial) mycroft-desktop repo. See [the issue](https://github.com/MycroftAI/docker-mycroft/issues/62) on the [docker-mycroft](https://github.com/MycroftAI/docker-mycroft/) repo.

Can we close the issue here and continue the discussion over on the docker specific repo?

**Comment by forslund** [comment]
Taking the silence as agreement :) Feel free to reopen.
