### ISSUE TITLE
Voight Kampff should allow setting unit

### ISSUE THREAD

**Issue by TheLastProject** [MycroftAI/mycroft-core#2547]
For https://github.com/TheLastProject/travel-time-skill, I need to be able to test both unit settings.

I could not find any code that allows setting the unit.

Being able to use `Given the unit system is imperial` and `Given the unit system is metric` would be great.

(I also noticed https://mycroft-ai.gitbook.io/docs/skill-development/introduction-1/test-steps#and-but names the text `Given user is located in Paris`, but I can't find any code implementing this either?)

**Comment by TheLastProject** [comment]
Example of what I want to do:

```
Feature: travel-time
  Scenario: Traffic to Berlin
    Given an English speaking user
    Given the unit system is Metric
    Given home is set to Amsterdam
  When the user says "What's the traffic like to Berlin"
  Then mycroft should reply with a dialog from "time.travel.metric"
  Then the reply should contain "from Amsterdam to Berlin by car"
```

I expect this to be equivalent to
```
{
  "utterance": "What's the traffic like to Berlin",
  "intent_type": "time.travel.intent",
  "expected_dialog": "time.travel.metric",
  "expected_response": "It is .* kilometers and .* minutes from Amsterdam to berlin by car",
  "settings": {"home": "Amsterdam"}
}
```
with Mycroft's unit system set to metric as well.

**Comment by forslund** [comment]
Hi, setting the unit (or any global config) is a good suggestion and is possible in the current system I'll make a point to implement a given step for this.

The settings are a bit trickier but that sort of feature is planned for the second stage of Voight Kampff development. Stage 1 was development of a robust integration test to allow pull requests to Mycroft core and it's supporting modules to be thoroughly tested before inclusion. Stage 2 is meant to implement the features in the current skill tester to allow it to mock parts in the same way as the old skill t ester and apply settings, etc.

**Comment by codyreinold** [comment]
I agree with adding to the config abilities and believe there should be a consistent template used as we grow this functionality. Opened issue #2556 to cover this.

**Comment by forslund** [comment]
I'm trying to finalize the PR for this and wonder what the best syntax in the behave file will be.

For the unit specific given I'm using the suggested: `Given the unit system is X`

For generic configuration I wonder if we can use a dot-notation
`Given the config[uration] value for skills.msm.directory is skills`?

**Comment by codyreinold** [comment]
As I recommended in #2556, I would suggest using:

```python3
@given("the skill's {key} is {value}")
def given_skill_config(context, key, value):
```

This aligns with the work I am doing to standardize other language in VK tests. Eg:

``` python3
@given("the user's {key} is {value}")
def given_user_config(context, key, value):
    if key == 'language':
        if value in ['en-us', 'english']:
            context.lang = 'en-us'
            return
        raise ValueError('"{}" is not an allowed language'.format(value))
    raise ValueError('"{}" is not an allowed user configuration ' +
                     'variable'.format(key))
```

**Comment by krisgesling** [comment]
In this instance the measurement system is normally set per user so I'd go with:
`"Given the user's {key} is {value}"`
> Given the user's measurement unit is metric

Could use dot notation, or a simple dictionary to map the natural language `{key}` to the relevant dot notation. This would read better (eg above), but does introduce another step for error. Eg was it "measurement unit", "unit system", "unit of measurement", etc 

A dict like this could be useful for other features, like the Config Skill letting users change or query any of their settings.

**Comment by forslund** [comment]
Sounds like a good idea, Where would this dict be defined?

**Comment by krisgesling** [comment]
`mycroft/res/text/en-us/settings.list`
?

**Comment by codyreinold** [comment]
I agree a key / val file sounds like a good idea.

It probably makes sense to have two different files; one in mycroft-core, which defines defaults, and one located in the skill-specific folder to override / provide skill-specific keywords. This would allow us to write mycroft-core-wide statements (eg: @given("the skill's {key} is {value}")) that could then be easily extensible in all skill tests.

As it stands / without this, a skill creator would be forced to copy the function from mycroft-core into their own specific skill's tests to add a custom given statement.

**Comment by forslund** [comment]
Sounds like a good idea, I'll update my original work to include these features
