### ISSUE TITLE
Fatal bug on the web client

### ISSUE THREAD

**Issue by Dylage** [MycroftAI/mycroft-core#2553]
# Fatal bug on the web client

Hello, I'm encountering a bug when trying to access the web client installed by default on PiCroft.
(The cli-client has no problem and works perfectly at the same moment).

## My config 

* I'm running a Raspberry Pi 3B, with Picroft
* With version 20.2.2 of the Mycroft software
* Client : Mozilla Firefox 75.0 on a Linux machine of the same local network

## Steps to reproduce

1. Start Mycroft (mycroft-start all)
2. Go to the IP adress of the server on port 8181 (http://IPV4_ADRESS:8181/)
3. Get the following traceback error error :

```
Traceback (most recent call last):
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/tornado/web.py", line 1676, in _execute
    result = self.prepare()
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/tornado/web.py", line 2431, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
```

**Comment by forslund** [comment]
Hi, I'm afraid there is no web client installed by default on the Picroft

**Comment by Dylage** [comment]
Hum, I didn't install any and the port was open, so I thought the old project  jcasoft /
Mycroft-Web-Client (or another) had been integrated (since it is using the same port) or something like that.

**Comment by forslund** [comment]
The 8181 port is the websocket connection if you wish to experiment with sending messages to core.

There is a web ui by @TheLastProject here: https://github.com/TheLastProject/mycroft-WebUI
I've played around with a audio interface (REALLY EARLY WORK+ I DON'T KNOW WEB): https://github.com/forslund/mycroft-web-audio-client

**Comment by Dylage** [comment]
Oh, my bad then, I should have read the doc better.
I close and present my apologies for the flood.
(Thank you for the links, I'll watch that).
