### ISSUE TITLE
load_data_files should call load_regex_files

### ISSUE THREAD

**Issue by ChristopherRogers1991** [MycroftAI/mycroft-core#256]
I see that not having `load_data_files` call `load_regex_files` was done on purpose, according to the first comment on https://github.com/MycroftAI/mycroft-core/pull/222, however, it seems strange to have `load_data_files` not load all the data files, so I wanted to open this up for discussion.

The function is currently written as:
```
    def load_data_files(self, root_directory):
        self.init_dialog(root_directory)
        self.load_vocab_files(join(root_directory, 'vocab', self.lang))
```
It seems like it could be:
```
    def load_data_files(self, root_directory):
        self.init_dialog(root_directory)
        self.load_vocab_files(join(root_directory, 'vocab', self.lang))
        regex_path = join(root_directory, 'regex', self.lang)
        if os.path.exists(regex_path):
            self.load_regex_files(regex_path)
```
This should safely load it for the skills that rely on it, without causing harm to the others.

Is there any strong argument for not having `load_data_files` load the regex files in this, or a similar manner?

**Comment by ethanaward** [comment]
I'm fine with making this change. I'll do some tests to make sure it works as intended.
