### ISSUE TITLE
Failed to install Mycroft

### ISSUE THREAD

**Issue by nlpsuge** [MycroftAI/mycroft-core#2561]
Hi,

I use Fedora 32.

I just clone the master branch to my machine. The codes is the latest.

Execute 'bash dev_setup.sh' report those errors:
(Omit successful logs...)
mycroft-core/mimic/bin/mimic: error while loading shared libraries: libicui18n.so.60: cannot open shared object file: No such file or directory
Installing PEP8 check as precommit-hook
dev_setup.sh: line 486: mycroft-core/.venv/lib/python3.8/site-packages/_virtualenv_path_extensions.pth: No such file or directory
dev_setup.sh: line 486: return: can only `return' from a function or sourced script

I believe that installing libicu-devel-60 can resolve partial problems at least, but I can't find a way to install it. The latest of libicui18n.so.60 is libicu-devel-65.1 in repositories.

**Comment by ChanceNCounter** [comment]
I believe that's the same culprit dep as #2511

**Comment by nlpsuge** [comment]
Yes, but it's seems like unsolved and closed.

I run 'bash dev_setup.sh' in Fedora 31 not too long ago, it also reported the same problems.

I used MyCroft last year or the year before the last year, I remember clearly I can use it normally.

**Comment by forslund** [comment]
A related PR may be #2521

Also the error with mimic looks a bit like there exists a prebuilt mimic but linked against an older version of libicui18n, maybe you can delete the folder `mimic` and re-run dev-setup.py

The *return* error looks a bit weird, definitely a bug in handling an error condition. Will look into it as well as why the first part of that line is failing.

**Comment by nlpsuge** [comment]
@fermulator 

I've deleted folder 'mimic' and re-run 'dev_setup.sh'. Failed again. The result reads:

Installing PEP8 check as precommit-hook
./dev_setup.sh: line 486: /mnt/2460B65660B62E84/linuxs/softwares/git-sources/linux/ai/mycroft-core/.venv/lib/python3.8/site-packages/_virtualenv_path_extensions.pth: No such file or directory
./dev_setup.sh: line 486: return: can only `return' from a function or sourced script

**Comment by nlpsuge** [comment]
@fermulator 

I found that the folder 'mycroft-core/.venv/lib/python3.8/' does not exist.

$ ls .venv/lib/
python3.6/

Only the folder 'mycroft-core/.venv/lib/python3.6/' exists.

**Comment by forslund** [comment]
Ok, seems like the mimic issue isn't showing at least.

This may be python 3.8 related. I will do a test here in a bit.

**Comment by forslund** [comment]
Remove the entire .venv folder `rm -rf .venv` and see if that resolves it.

**Comment by forslund** [comment]
Did you have any luck installing after removing the .venv directory?

**Comment by nlpsuge** [comment]
Sorry for replying so late. 

After removing the .venv directory when I re-run multiple times of 'dev_setup.sh', I got this kind of errors:
Installing PEP8 check as precommit-hook
grep: mycroft-core/.venv/lib/python3.8/site-packages/_virtualenv_path_extensions.pth: Permission denied
Adding mycroft-core to virtualenv path
sed: can't read mycroft-core/.venv/lib/python3.8/site-packages/_virtualenv_path_extensions.pth: Permission denied

Checked out the permission of this file:
$ ll mycroft-core/.venv/lib/python3.8/site-packages/_virtualenv_path_extensions.pth
----------. 1 l l 258 May  5 20:41 mycroft-core/.venv/lib/python3.8/site-packages/_virtualenv_path_extensions.pth

My solution was adding permission to the file "mycroft-core/.venv/lib/python3.8/site-packages/_virtualenv_path_extensions.pth":
$ chmod 777 mycroft-core/.venv/lib/python3.8/site-packages/_virtualenv_path_extensions.pth

Then I installed it successfully.

**Comment by ChanceNCounter** [comment]
IMO, you should nuke it and start again. It shouldn't need any fussing with permissions.

I'd run `./dev_setup.sh --clean`, delete the whole repo, clone again, and then run `./dev_setup.sh -p <pythonversion>`, and see if you have a similar experience.

Just my two cents.

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
