### ISSUE TITLE
Pocketsphinx: Fallback to english model if language specific model doesn't exist

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#2563]
When using a pocketsphinx wakeword mycroft tries to load a language specific model. If the model doesn't exist the load fails. ([report on the forums](https://community.mycroft.ai/t/error-switching-wake-word/8644))

This should be handled by using a fallback mechanism, so if no language specific model exists it should log a warning and fallback to using the english model that is included in mycroft-core.

At [L105 in hotword_factory.py](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/hotword_factory.py#L105) a line to set the model to the default en-us should be added.

The code will look something like

```python
        if not exists(model_file):
            LOG.error('PocketSphinx model not found at ' + str(model_file))
            model_file = join(RECOGNIZER_DIR, 'model', 'en-us', 'hmm')
```

**Comment by katridi** [comment]
I can take it
