### ISSUE TITLE
wait_while_speaking() it does not work

### ISSUE THREAD

**Issue by gras64** [MycroftAI/mycroft-core#2579]
I have been having problems with "wait_while_speaking ()" for a while. even on multiple devices. i use espeak as tts. Even if I attach wait = True to speak_dialog there is no waiting and I have to incorporate a time delay into my skills. i import "from mycroft.audio import wait_while_speaking"

**Comment by forslund** [comment]
Thanks for reporting, I compared mimic and espeak and for espeak I can reproduce this issue so there's defintely something that's going wrong there. espeak is not using the newer tts architecture so I'll might try to update it to the more modern version and see if things improve.

**Comment by forslund** [comment]
If you have the possibility to try out #2581, and see if that works better for you I'd love the feedback.
