### ISSUE TITLE
self.remove_fallback(handler) it does not work

### ISSUE THREAD

**Issue by gras64** [MycroftAI/mycroft-core#2586]
i need the remove.fallback function after recording in my wakeword skill. I acted according to instructions https://mycroft-ai.gitbook.io/docs/skill-development/skill-types/fallback-skill. however, I always get the message. "mycroft.skills.fallback_skill:remove_fallback:139 | Could not remove fallback!". the fallback function is retained and is not deactivated. During the skill shutdown, the function is executed, the error message remains and fallback is deactivated.

**Comment by forslund** [comment]
Thanks for reporting, I tested and can confirm that this is a bug.

**Comment by forslund** [comment]
Looks like [self.remove_instance_handlers()](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html#mycroft.FallbackSkill.remove_instance_handlers) should work if you need a quick workaround.

**Comment by gras64** [comment]
thanks for the hint
