### ISSUE TITLE
Mycroft does not work with another input device

### ISSUE THREAD

**Issue by baditaflorin** [MycroftAI/mycroft-core#2602]
# How to submit an Issue to a Mycroft repository

When submitting an Issue to a Mycroft repository, please follow these guidelines to help us help you. 

## Be clear about the software, hardware and version you are running
![image](https://user-images.githubusercontent.com/2330999/83954189-ac9bdd00-a84f-11ea-89ab-4c6adb1976b4.png)

For example: 

* I'm running a Mark 1
* With master version using git clone of the Mycroft software
* With the standard Christopher

## Try to provide steps that we can use to replicate the Issue

For example: 

1. Using the standard microphone the command works. 
2. When I change the microphone to the bluetooth device, it will show the input in the debug, but I do not issue a command. 

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

This is called _object-deviation format_. Specify the object, then the deviation of the object from an expected condition. 

Example 1: 

* When I say "Hey Mycroft, set your eyes to cadet blue", the eyes turn purple instead of blue. 

Example 2: 

* When I say "Hey Mycroft, what time is it in Paris", the time spoken is out by one hour - it's not observing daylight savings time. 

Example 3: 

* When I run `msm default` on my Mark 1, I receive lots of Git 'locked file' errors on the command line. 

## Provide log files or other output to help us see the error

We will normally require log files or other troubleshooting information to assist you with your Issue. 

This [documentation](https://mycroft.ai/documentation/troubleshooting/) explains how to find log files. 

As of version 0.9.10, the [Support Skill](https://github.com/MycroftAI/skill-support) also helps to automate gathering support information. 

Simply say: 

* "Create a support ticket" _or_
* "You're not working!" _or_
* "Send me debug info"

and the Skill will put together a support package which you can email to us. 

## Upload any files to the Issue that will be useful in helping us to investigate

Please ensure you upload any relevant files - such as screenshots - which will aid us investigating.

**Comment by JarbasAl** [comment]
try setting one of these https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/configuration/mycroft.conf#L170

issue is super confusing, if you arent going to follow the template at least delete the defaults, you are obviously not running a mark1

**Comment by baditaflorin** [comment]
Hi Jarbas, I do not know what is a mark1 ...
Thanks for the link. 

I have a laptop running Linux Mint 19.3 where I tried to install Mycroft

**Comment by krisgesling** [comment]
Hi there,

[Mark 1's](https://mycroft.ai/product/mycroft-mark-1/) are our old hardware devices.

Bluetooth devices have been notoriously difficult to get working, but have you had a look at our [Audio Troubleshooting docs](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/troubleshooting/audio-troubleshooting)?

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
