### ISSUE TITLE
command not found: mycroft-config

### ISSUE THREAD

**Issue by baditaflorin** [MycroftAI/mycroft-core#2603]
It is refferenced in the documentation here 
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/troubleshooting/audio-troubleshooting

**Comment by forslund** [comment]
The documentation assumes you've added the core commands to path when running dev_setup.sh.

If you didn't add the mycroft scripts to the path you can run it from the mycroft-core folder via

`./bin/mycroft-config`

**Comment by baditaflorin** [comment]
I was expecting to find all comands, as I selected YES to this.

There are several Mycroft helper commands in the bin folder.  These
can be added to your system PATH, making it simpler to use Mycroft.
Would you like this to be added to your PATH in the .profile?
Choice [Y/N]:  Y - Adding Mycroft commands to your PATH 
Type mycroft-help to see available commands.

The standard location for Mycroft skills is under /opt/mycroft/skills.
For convenience, a soft link has been created called 'skills' which leads
to /opt/mycroft/skills.

**Comment by JarbasAl** [comment]
did you see some error logs during installation? 

you can execute the script directly from ```./bin/mycroft-config``` as @forslund said

**Comment by ChanceNCounter** [comment]
There is also the slim but nonzero possibility that `.profile` isn't being sourced.

**Comment by forslund** [comment]
If it's not being sourced despite you've answered yes then there is an issue.

Skimming the dev_setup.sh script it seems like it would currently require a restart of the terminal window before the added path would be applied. Could that be the issue? Or is it still not working?

Does the explicit invocation of the script work?

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
