### ISSUE TITLE
Suggestion to add 'mycroft-config edit _' to the 'mycroft-start --help' menu.

### ISSUE THREAD

**Issue by auwsom** [MycroftAI/mycroft-core#2604]
Nevermind, found the problem for 'How to exit `mycroft-config edit Default` without leaving stopped job'

**Comment by auwsom** [comment]
also, just a nitpicking suggestion.. to put the 'mycroft-edit' command into the main `mycroft-start --help` menu. I wonder what other commands are not in there?

**Comment by forslund** [comment]
That's weird, for me ctrl+x shuts down the editor correctly when running `mycroft-config edit default`

**Comment by auwsom** [comment]
Thanks @forslund . Youre correct, I found the error on my end. I will retitle so I can leave the suggestions about including `mycroft-config edit _` in the `mycroft-start --help` menu.

**Comment by krisgesling** [comment]
Hey glad you worked it out. 

The items listed in `mycroft-start --help` are specifically for that command but we should certainly add it to the `mycroft-help` list

**Comment by auwsom** [comment]
Just a minor suggestion, but it would really help for those following the
unix paradigm to make a 'mycroft --help' menu. That's the first thing I
tried before having to go to the Documentation. It's less like powershell
commands, but much easier and more simple to get started with.
