### ISSUE TITLE
after deleting github repo and doing git clone the app does not work anymore

### ISSUE THREAD

**Issue by baditaflorin** [MycroftAI/mycroft-core#2605]
OS: Linux mint 
Did the pairing, but still I get this error and nothing works. 
![image](https://user-images.githubusercontent.com/2330999/83955574-d27bae80-a85c-11ea-97ce-a1d67839e938.png)

Log Output:                                                                                                    0-8 of 8
========================================================================================================== mycroft-core 20.2.4 ===
Establishing Mycroft Messagebus connection...
Connected to Messagebus!
~~~~client:emit:121 | Could not send mycroft-date-time.mycroftai:TimeSkillupdate_display message because connection has been closed
~~~~ssagebus.client.client:emit:121 | Could not send mycroft-reminder.mycroftai:reminder message because connection has been closed
 01:14:35.468 | INFO     | 29568 | mycroft.messagebus.client.client:on_open:67 | Connected
 01:14:35.459 | INFO     |   661 | mycroft.messagebus.client.client:on_open:67 | Connected
 01:15:05.061 | WARNING  |   661 | ConfigurationSkill | Impossible to update configuration because device isn't paired
  ^--- NEWEST ---^

**Comment by baditaflorin** [comment]
```01:21:06.433 | WARNING  |   661 | ConfigurationSkill | Impossible to update configuration because device isn't paired
  ^--- NEWEST ---^ 

```

**Comment by baditaflorin** [comment]
pair new device
 >> Thanks but I'm already paired

**Comment by el-tocino** [comment]
Device doesn't think it's paired, ask it "pair my device" and see what happens.

**Comment by adocampo** [comment]
How did you pair your device exactly? Documentation states clearly you need to say "pair my device"
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/basic-commands#pairing

**Comment by krisgesling** [comment]
hey there, if this still isn't working try deleting your identity file and restarting mycroft:
```
~/mycroft-core/stop-mycroft.sh
rm ~/.mycroft/identity/identity2.json
~/mycroft-core/start-mycroft.sh debug
``` 

This will require you to re-pair the device.

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
