### ISSUE TITLE
span install does not work

### ISSUE THREAD

**Issue by baditaflorin** [MycroftAI/mycroft-core#2606]
As per instructions from https://snapcraft.io/mycroft
error: cannot install "Mycroft": invalid instance name: invalid snap name: "Mycroft"

**Comment by baditaflorin** [comment]
snap install mycroft
error: snap "mycroft" is not available on stable but is available to install on the following
       channels:

       candidate  snap install --candidate mycroft
       beta       snap install --beta mycroft
       edge       snap install --edge mycroft

       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info mycroft'.
snap install --candidate mycroft 
error: snap "mycroft" is not available on candidate but is available to install on the following
       channels:

At the end, this command works to install snap install --beta mycroft

**Comment by krisgesling** [comment]
Hey there, thanks for the good suggestions. I've updated the Snap store listing to provide more detail, particularly while the Snap isn't in the Stable channel.
