### ISSUE TITLE
Clean install after removing everything in my system does not even start

### ISSUE THREAD

**Issue by baditaflorin** [MycroftAI/mycroft-core#2607]
Alternatively you can manually remove these files using the following commands:
```
sudo rm -rf /var/log/mycroft # Log files
rm -f /var/tmp/mycroft_web_cache.json # Configuration from Home.mycroft.ai
rm -rf "${TMPDIR:-/tmp}/mycroft" # Temp files
rm -rf "$HOME/.mycroft" # User level configuration
sudo rm -rf /opt/mycroft # Mycroft Skills directory
rm -rf "$HOME/mycroft-core" # Mycroft-core installation
```
Then did the github clone

When I run, I get nothing on Log Output:                                                                            0-3 of 3
================================================================================== mycroft-core 20.2.4 ===
Establishing Mycroft Messagebus connection...
Connected to Messagebus!
  ^--- NEWEST ---^ 

History ===========================================    Log Output Legend ==================== Mic Level ==
 test                                                  DEBUG output
 >> Please wait a moment as I finish booting up.
 5 minutes later

Input (':' for command, Ctrl+C to quit) ==============================

**Comment by gerrywastaken** [comment]
@baditaflorin Why did you close this?
