### ISSUE TITLE
span install does not work after you restart the OS 

### ISSUE THREAD

**Issue by baditaflorin** [MycroftAI/mycroft-core#2609]
$ mycroft                
Traceback (most recent call last):
  File "/home/florin/snap/mycroft/common/venv/bin/mycroft-cli-client", line 5, in <module>
    from mycroft.client.text.__main__ import main
  File "/home/florin/snap/mycroft/common/venv/lib/python3.6/site-packages/mycroft/__init__.py", line 19, in <module>
    from mycroft.skills.context import adds_context, removes_context
  File "/home/florin/snap/mycroft/common/venv/lib/python3.6/site-packages/mycroft/skills/__init__.py", line 21, in <module>
    from .mycroft_skill import (MycroftSkill, intent_handler, intent_file_handler,
  File "/home/florin/snap/mycroft/common/venv/lib/python3.6/site-packages/mycroft/skills/mycroft_skill/__init__.py", line 15, in <module>
    from .mycroft_skill import MycroftSkill
  File "/home/florin/snap/mycroft/common/venv/lib/python3.6/site-packages/mycroft/skills/mycroft_skill/mycroft_skill.py", line 29, in <module>
    from adapt.intent import Intent, IntentBuilder
  File "/home/florin/snap/mycroft/common/venv/lib/python3.6/site-packages/adapt/__init__.py", line 20, in <module>
    __doc__ = codecs.open('README.md', encoding='utf-8', mode='r').read()
  File "/snap/mycroft/current/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: 'README.md'
Stopping all processes...
mycroft-skills: no process found
mycroft-enclosure-client: no process found
mycroft-speech-client: no process found
mycroft-audio: no process found
Stopped
$ ~/mycroft-core   master  sudo mycroft
[sudo] password for florin:       
mkdir: cannot create directory '/run/user/0': Permission denied
tar: precise-engine/libpython3.5m.so.1.0: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/numpy.core.umath.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5i.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse.linalg.isolve._iterative.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.special.specfun.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libbz2.so.1.0: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.spatial._hausdorff.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_lzma.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.special._ufuncs.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._nnls.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5t.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_codecs_iso2022.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5z.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.integrate.vode.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse.csgraph._tools.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.integrate._dop.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libaec-2147abcd.so.0.0.4: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5d.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.utils.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_decimal.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5f.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5a.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/include/python3.5m/pyconfig.h: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/include/python3.5m: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/include: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse._csparsetools.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libncursesw.so.5: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.fftpack._fftpack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.integrate._odepack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libcrypto.so.1.0.0: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/readline.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.integrate._quadpack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libz-a147dcb0.so.1.2.3: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/lib/python3.5/config-3.5m-x86_64-linux-gnu/Makefile: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/lib/python3.5/config-3.5m-x86_64-linux-gnu: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/lib/python3.5: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/lib: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libmpdec.so.2: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_multiprocessing.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_yaml.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.linalg._decomp_update.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.interpolate.dfitpack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/base_library.zip: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py._conv.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5l.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_codecs_kr.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._trlib._trlib.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/numpy.random.mtrand.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/liblzma.so.5: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.fftpack.convolve.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5s.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libstdc++.so.6: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.linalg._flinalg.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5g.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.spatial.qhull.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libreadline.so.6: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libexpat.so.1: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/numpy.fft.fftpack_lite.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_ctypes.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.special._ufuncs_cxx.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse.csgraph._min_spanning_tree.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._slsqp.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libyaml-0.so.2: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/audioop.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/numpy.linalg._umath_linalg.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/termios.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libssl.so.1.0.0: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_codecs_tw.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._cobyla.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libtensorflow_framework.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libhdf5-b253f31d.so.101.1.0: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libhdf5_hl-d68fbc5b.so.100.1.0: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py._errors.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5r.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/mmap.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_hashlib.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.spatial._distance_wrap.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.special._comb.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._group_columns.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse.csgraph._shortest_path.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.spatial.ckdtree.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/numpy.linalg.lapack_lite.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_multibytecodec.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_csv.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._lbfgsb.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse._sparsetools.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._zeros.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libsz-1c7dd0cf.so.2.0.1: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5p.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse.linalg.eigen.arpack._arpack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.linalg.cython_lapack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.ndimage._nd_image.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy._lib._ccallback_c.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.interpolate._ppoly.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.ndimage._ni_label.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libgcc_s.so.1: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/resource.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/numpy.core.multiarray.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse.linalg.dsolve._superlu.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/lib2to3/PatternGrammar.txt: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/lib2to3/Grammar.txt: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/lib2to3: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.integrate.lsoda.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/tensorflow.python.framework.fast_tensor_util.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_pywrap_tensorflow_internal.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py._proxy.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._lsq.givens_elimination.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_ssl.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libz.so.1: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.linalg._solve_toeplitz.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize.minpack2.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_codecs_cn.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.linalg._fblas.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.interpolate.interpnd.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/parser.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize.moduleTNC.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/google.protobuf.pyext._message.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.optimize._minpack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libopenblasp-r0-39a31c03.2.18.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/google.protobuf.internal._api_implementation.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.linalg._flapack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.interpolate._bspl.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py._objects.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.special._ellip_harm_2.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/numpy.core.multiarray_tests.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_opcode.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5ac.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.linalg.cython_blas.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.defs.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5o.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_bz2.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse.csgraph._reordering.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_json.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libgfortran-ed201abd.so.3.0.0: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5ds.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.interpolate._fitpack.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_curses.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/precise-engine: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.sparse.csgraph._traversal.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_codecs_hk.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/scipy.spatial._voronoi.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/_codecs_jp.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/h5py.h5fd.so: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine/libtinfo.so.5: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: precise-engine: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: Exiting with failure status due to previous errors
tar: hey-mycroft.pb: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: hey-mycroft.pb.params: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: Exiting with failure status due to previous errors
No protocol specified
Unable to init server: Could not connect: Connection refused

(yad:14955): Gtk-WARNING **: 04:14:03.357: cannot open display: :0
Creating virtualenv in /root/snap/mycroft/common/venv
No protocol specified
Unable to init server: Could not connect: Connection refused

(yad:14964): Gtk-WARNING **: 04:14:04.884: cannot open display: :0
No protocol specified
Unable to init server: Could not connect: Connection refused

(yad:14968): Gtk-WARNING **: 04:14:05.982: cannot open display: :0
ERROR: Pipe to stdout was broken
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
sed: can't read /root/snap/mycroft/common/venv/lib/python3.?/site-packages/pip/_internal/utils/misc.py: No such file or directory
/snap/mycroft/1078/bin/mycroft-launch: line 69: pip: command not found
No protocol specified
Unable to init server: Could not connect: Connection refused

(yad:14981): Gtk-WARNING **: 04:14:08.984: cannot open display: :0
/snap/mycroft/1078/bin/mycroft-launch: line 92: mycroft-cli-client: command not found
Stopping all processes...
mycroft-skills: no process found
mycroft-enclosure-client: no process found
mycroft-speech-client: no process found
mycroft-audio: no process found
Stopped

**Comment by baditaflorin** [comment]
Tried it again, now getting this error

```
Establishing Mycroft Messagebus connection...
Connected to Messagebus!
 04:17:55.203 | WARNING  | 15569 | mycroft.client.speech.hotword_factory:initialize:418 | Could not found find model for christopher on precise.
 04:17:55.205 | INFO     | 15569 | mycroft.client.speech.hotword_factory:load_module:403 | Loading "christopher" wake word via pocketsphinx
 04:17:55.266 | INFO     | 15569 | mycroft.client.speech.listener:create_wakeup_recognizer:360 | creating stand up word engine
 04:17:55.267 | INFO     | 15569 | mycroft.client.speech.hotword_factory:load_module:403 | Loading "wake up" wake word via pocketsphinx
 04:17:55.292 | INFO     | 15569 | mycroft.messagebus.client.client:on_open:67 | Connected
 04:17:55.828 | INFO     | 15570 | mycroft.skills.msm_wrapper:create_msm:106 | Releasing MSM instantiation lock.
 04:17:55.829 | INFO     | 15570 | mycroft.skills.skill_updater:_log_next_download_time:248 | Next scheduled skill update: 2020-06-07 02:47:21.755018
 04:17:55.830 | INFO     | 15570 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: mycroft-pairing.mycroftai
 04:17:55.839 | INFO     | 15570 | mycroft.skills.settings:get_local_settings:78 | /home/florin/snap/mycroft/1078/.config/mycroft/skills/mycroft-pairing.mycroftai/settings.json
 04:17:55.866 | INFO     | 15570 | mycroft.skills.skill_loader:_communicate_load_status:280 | Skill mycroft-pairing.mycroftai loaded successfully
 04:17:55.868 | INFO     | 15570 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: mycroft-volume.mycroftai
 04:17:55.874 | ERROR    | 15570 | mycroft.skills.skill_loader:_load_skill_source:215 | Failed to load skill: mycroft-volume.mycroftai (ModuleNotFoundError("No module named 'alsaaudio'",))
Traceback (most recent call last):
  File "/home/florin/snap/mycroft/common/venv/lib/python3.6/site-packages/mycroft/skills/skill_loader.py", line 208, in _load_skill_source
    ('.py', 'rb', imp.PY_SOURCE)
  File "/snap/mycroft/current/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/snap/mycroft/current/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/florin/snap/mycroft/1078/../common/mycroft-data/skills/mycroft-volume.mycroftai/__init__.py", line 15, in <module>
    from alsaaudio import Mixer, mixers as alsa_mixers
ModuleNotFoundError: No module named 'alsaaudio'
 04:17:55.880 | ERROR    | 15570 | mycroft.skills.skill_loader:_communicate_load_status:287 | Skill mycroft-volume.mycroftai failed to load
 04:17:56.114 | INFO     | 15570 | mycroft.skills.__main__:_get_pairing_status:92 | Device is paired
 04:17:56.124 | INFO     | 15570 | mycroft.enclosure.display_manager:_write_data:70 | Display Manager is creating /tmp/mycroft/ipc/managers/disp_info
 04:17:56.125 | INFO     | 15570 | mycroft.skills.__main__:_update_device_attributes_on_backend:144 | Sending updated device attributes to the backend...
 04:17:56.943 | INFO     | 15570 | mycroft.skills.skill_manager:_load_on_startup:261 | Loading installed skills...
 04:17:56.949 | INFO     | 15570 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: mycroft-ip.mycroftai
 04:17:57.005 | INFO     | 15570 | mycroft.skills.settings:get_local_settings:78 | /home/florin/snap/mycroft/1078/.config/mycroft/skills/mycroft-ip.mycroftai/settings.json
 04:17:57.044 | INFO     | 15570 | mycroft.skills.skill_loader:_communicate_load_status:280 | Skill mycroft-ip.mycroftai loaded successfully
 04:17:57.056 | INFO     | 15570 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: mycroft-version-checker.mycroftai
 04:17:57.069 | INFO     | 15570 | mycroft.skills.settings:get_local_settings:78 | /home/florin/snap/mycroft/1078/.config/mycroft/skills/mycroft-version-checker.mycroftai/settings.json
 04:17:57.129 | INFO     | 15570 | mycroft.skills.skill_loader:_communicate_load_status:280 | Skill mycroft-version-checker.mycroftai loaded successfully
 04:17:57.130 | INFO     | 15570 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: mycroft-joke.mycroftai
 04:17:57.138 | INFO     | 15570 | mycroft.skills.settings:get_local_settings:78 | /home/florin/snap/mycroft/1078/.config/mycroft/skills/mycroft-joke.mycroftai/settings.json
 04:17:57.187 | INFO     | 15570 | mycroft.skills.skill_loader:_communicate_load_status:280 | Skill mycroft-joke.mycroftai loaded successfully
 04:17:57.188 | INFO     | 15570 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: mycroft-naptime.mycroftai
 04:17:57.197 | INFO     | 15570 | mycroft.skills.settings:get_local_settings:78 | /home/florin/snap/mycroft/1078/.config/mycroft/skills/mycroft-naptime.mycroftai/settings.json
```

**Comment by JarbasAl** [comment]
from your logs in second post install seems to have worked

erros in skill logs seem to be a missing requirement in volume skill, i ran into the same after upgrading to ubuntu 20, but i didnt run into that before in other distros, i guess this used to be a default package

you can run  ```mycroft-pip install pyalsaaudio``` as a workaround meanwhile

i think this issue can be closed

**Comment by forslund** [comment]
Thanks for the detective work @JarbasAI,

also @baditaflorin launching mycroft with sudo might have bad consequences only do that if you're really sure you need it.

**Comment by baditaflorin** [comment]
My aim was to have a working install of the software. From there, I will trace my steps back and do what I need, like protecting the port and other things.
