### ISSUE TITLE
'Emitter' no longer correct and 'Message' not working

### ISSUE THREAD

**Issue by auwsom** [MycroftAI/mycroft-core#2611]
In the messagebus docs (https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-types), self.bus.emit should now be used instead of self.emitter.emit. However, doing so results in the error "NameError: name 'Message' is not defined".

https://community.mycroft.ai/t/stopping-play-wav/6752/8?u=auwsom
https://community.mycroft.ai/t/how-do-i-send-a-message-to-the-messagebus/6354/5

**Comment by auwsom** [comment]
When removing 'Message' the following error is given:
```
File "/media/abc/Iprogs/mycroft-core/mycroft/messagebus/client/client.py", line 118, in emit
    self.client.send(json.dumps(message.__dict__))
AttributeError: 'str' object has no attribute '__dict__'
```

..in 'mycroft-core/mycroft/messagebus/client/client.py", line 118, in emit'

```
    def emit(self, message):
        if not self.connected_event.wait(10):
            if not self.started_running:
                raise ValueError('You must execute run_forever() '
                                 'before emitting messages')
            self.connected_event.wait()

        try:
            if hasattr(message, 'serialize'):
                self.client.send(message.serialize())
            else:
                self.client.send(json.dumps(message.__dict__))
        except WebSocketConnectionClosedException:
            LOG.warning('Could not send {} message because connection '
                        'has been closed'.format(message.msg_type))
```

**Comment by auwsom** [comment]
interesting that mycroft/skills/intent_service_interface.py is currently using "self.bus.emit(Message("register_intent", intent_parser.__dict__))".. so maybe using 'Message' is the correct form?

**Comment by forslund** [comment]
Yes the Message object needs to be imported to be used. If this is missing from the docs raise an issue over in the [mycroft-docs repo](https://github.com/mycroftai/documentation). I also think Mycroft would be happy to accept a PR with an update to the docs :)

**Comment by auwsom** [comment]
https://github.com/MycroftAI/documentation/issues/174

Hopefully, people will find this in search until they change it.. Im not setup for a PR request at the moment and it should be just a Find and Replace All on 'emitter' and 'bus' on this page: https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-types
