### ISSUE TITLE
common play should allow setting track info

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#2614]
When using the common play it should be possible to set track info, currently this is left up to the individual backends

each commonXX framework is likely to know what it is playing, it doesnt make sense for the individual audio services to guess this again (if they can do it at all)

example from my bandcamp skill

```
2020-06-10 22:54:44.254 | DEBUG    | 80137 | BandCampSkill | Bandcamp data: {'track_name': 'Astronaut Problems', 'released': '26 May 2017', 'url': 'https://deadunicorn.bandcamp.com/track/astronaut-problems', 'tags': [], 'album_name': 'Aliens', 'artist': 'Dead Unicorn', 'type': 'track', 'stream': 'https://t4.bcbits.com/stream/dc7e43f1a692bbcd5599e4b9a531ac60/mp3-128/1118755107?p=0&ts=1591912482&t=f65c778b0814d41a0565b3810371608158e466dd&token=1591912482_dea3126e0a57e2e2ad6044341ee2b309f5501bf9'}
2020-06-10 22:54:44.472 | INFO     | 80137 | Playback Control Skill | Audio service status: {'artist': '', 'album': ''}
```

**Comment by forslund** [comment]
To summarize some of the chat from this morning. A WIP implementation for this was used back in November to show trackinfo for spotify / the news, the playback skill could send the current track info to the playback control skill which would visualize the information.

A method `CPS_send_status()` can be called informing the playback skill of what is currently playing. For example see the news skill [here](https://github.com/MycroftAI/skill-npr-news/blob/20.02/__init__.py#L310) and [here](https://github.com/MycroftAI/skill-npr-news/blob/72c6db01ba752b05998c3865856e6fca46891737/__init__.py#L344)

I'll post a PR with that implementation in the CommonPlaybackSkill for further discussion of what info should be included.

There's then some things needed in the playback control skill to use this information in a good way

**Comment by JarbasAl** [comment]
@forslund i meant it should be populated here https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/audio/services/__init__.py#L135

what you said works for gui, but the point would be to have the info available for any skill that requests it. your approach would work if we add some listeners to the audio services for the same message

**Comment by forslund** [comment]
That was my thought as the continuation of this.

An alternative could  could also add an optional third in the tuple sent to the play / queue to use as track info...

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
