### ISSUE TITLE
Local Pairing

### ISSUE THREAD

**Issue by hughesjs** [MycroftAI/mycroft-core#2615]
Reading through the documentation, it seems as though you need to pair to home.mycroft.ai to use some features.

To me, requiring this connection seems to be the antithesis of what Mycroft is trying to achieve, the decoupling of AI Assistance from centralised servers like those at Google and Amazon.

As such, is there any way to store this information locally (perhaps just a config file on the host) and if not, could this be added as an option?

**Comment by forslund** [comment]
You can do some things to run entirely local
1. Setup [selene](https://github.com/MycroftAI/selene-backend) locally. The home.mycroft.ai software is open source and can be setup locally (maybe not on the same pi as Mycroft but somewhere on the network) it can then be setup with all keys required for Wolfram alpha or weather services.

2. Run Mycroft without backend. This should (TM) work. You'd need to black list the mycroft-pairing and mycroft-configuration skills and setup your own STT (either a remote of your choice or somethng like Deepspeech) then add keys to skills to allow them to run without using the home.mycroft.ai passthrough.

However as I've understood it, the idea with home.mycroft.ai is to offer a simple solution for fairly good privacy. The STT calls are anonymized, you have access to the source code and can verify that if you don't opt-in the data isn't stored etc.

**Comment by JarbasAl** [comment]
check https://github.com/JarbasSkills/skill-mock-backend

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues. 

Or reopen this issue if you feel this should not have been closed.

Thanks
