### ISSUE TITLE
Support Skill Registration with entry-points

### ISSUE THREAD

**Issue by Cadair** [MycroftAI/mycroft-core#262]
Python's entry points system allows packages to specify an entry point on installation and then another package or script can query all the installed packages that have registered to that entry point.

The upshot of this is that if I write a third party skill and set a entry point specified by Mycroft core in my skills setup.py file, Mycroft can auto-detect my skill and any other skills registered against the entry point.

For a more through introduction see this: http://docs.pylonsproject.org/projects/pylons-webframework/en/latest/advanced_pylons/entry_points_and_plugins.html 

As far as I am aware this is the best way for Mycroft to handle third party skills that can then have their own release cycle and make use of all of Python's packaging machinery.

**Comment by aatchison** [comment]
This is very interesting, and as we are moving closer to a skills delivery system, we should keep this in mind.

**Comment by krisgesling** [comment]
Went a different direction with Skill registration in the end. 

Closing.
