### ISSUE TITLE
License  questions

### ISSUE THREAD

**Issue by corus87** [MycroftAI/mycroft-core#2620]
Hello, 
since you have done a great job with the speak recognition I wonder am I allowed to use part of your [recognizer code](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/mic.py) in another open source project? 

The relevant code I would use, would be [here](https://github.com/corus87/kalliope/blob/new_speech_recognizer/kalliope/stt/SpeechRecognizer.py)

Thanks.

**Comment by krisgesling** [comment]
Hey there, 

You are absolutely free to use code from mycroft-core under the Apache 2.0 license. Here's a really quick overview of what that means: https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29

As you've done, you need to keep the copyright and license information with any code you are using. 
You also need to make it clear if any changes have been made to this code. In my opinion, this can be a short statement after the license info that changes have been made, and the git history documents what those changes are.
As this repo doesn't have a NOTICE file, this is not required.

Of course if there are any improvements you make that you think would benefit the broader project, we welcome PRs!
