### ISSUE TITLE
Central Issue for porting to windows

### ISSUE THREAD

**Issue by NoamDev** [MycroftAI/mycroft-core#2627]
This a central issue for discussions about porting Mycroft to windows.
cc @el-tocino

**Comment by NoamDev** [comment]
- fann2 installation is very difficult to install on windows, I think we should fork fann2, build wheels and release them. This has been done very successfully in https://www.lfd.uci.edu/~gohlke/pythonlibs/#fann2.

- PyAudio can be installed with python 3.6.

- Paths in [mycroft/configuration/mycroft.conf](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/configuration/mycroft.conf) are not windows compatible. Should we create another configuration file for windows?

**Comment by NoamDev** [comment]
I installed the fann2 from the link above (actually though pipwin).
Then tried to move on, I changed the paths in the configuration, replace '~' with %USERPROFILE% and `opt/` with %APPDATA%.
After that I ran `python -m mycroft.messagebus.service`.
I had to replace '/tmp' somewhere with a cross-platform equivalent.
Now I found that SIGKILL is unix specific and in windows it should be done a little differently, but since process killing doesn't sound important as long as everything works as expected, I removed it for now.
message bus seem to work.

**Comment by forslund** [comment]
Nice!

Shouldn't `~` work?

```python
>>> from os.path import expanduser
>>> expanduser('~/hello')
'C:\\Users\\afxxu3/hello'
>>>
```

**Comment by NoamDev** [comment]
Oh cool! I wasn't aware to that.

**Comment by NoamDev** [comment]
windows does not like to connect to 0.0.0.0 (though listening is not a problem)
so the config should be changed here to 127.0.0.1

**Comment by NoamDev** [comment]
Oh, a problem, maybe.
python didn't understand %appdata% and %userprofile% and instead created directories with those names....
I can change the second to ~, for now, I'll change the first to something harmless.

**Comment by forslund** [comment]
Haven't tried this but maybe the code should be updated to use [os.path.expandvars](https://docs.python.org/2/library/os.path.html#os.path.expandvars) as well as expanduser. at some point.

**Comment by NoamDev** [comment]
Is there a way to disable some skills?
Deleting them just cause them to be re-dowbloaded.

**Comment by forslund** [comment]
You can add them to the list of [blacklisted_skills](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/configuration/mycroft.conf#L117)

**Comment by NoamDev** [comment]
Thanks, that's enough for me.
I had to also add os.path.normpath in skill loader, but it works.

**Comment by NoamDev** [comment]
Do you know of windows builds of mimic? Some binary releases?
I have a ubuntu dual-boot, so I'm technically able to cross-compile, but I'd prefer to save the time...

**Comment by NoamDev** [comment]
Btw, I have skills service up and runing now:)

**Comment by forslund** [comment]
No mimic windows exe pre-built I'm afraid. You can skip local mimic for the time being and use the Mimic2 (American Male selection on home.mycroft.ai)

**Comment by NoamDev** [comment]
But I can't pare it since the code should be spoken...
Is there another way of getting a pairing code?

**Comment by forslund** [comment]
It will be written in the log output. Look for `Pairing code: <CODE>`

**Comment by NoamDev** [comment]
Wait, I'll try anyway.
Maybe ot writes it too.

**Comment by NoamDev** [comment]
After some workarounds with curses, I have text interface.
However, I can't pair, right after function handle_pairing is finished the pairing-skill is being removed..
```
2020-07-01 18:18:31.521 | INFO     |  7856 | mycroft.skills.padatious_service:train:102 | Training complete.
2020-07-01 18:18:31.528 | INFO     |  7856 | mycroft.skills.padatious_service:train:106 | Mycroft is all loaded and ready to roll!
2020-07-01 18:18:31.733 | INFO     |  7856 | mycroft.skills.skill_manager:_unload_removed_skills:322 | removing mycroft-pairing.mycroftai
2020-07-01 18:18:31.770 | INFO     |  7856 | mycroft.skills.skill_loader:_execute_instance_shutdown:147 | Skill mycroft-pairing.mycroftai shut down successfully
2020-07-01 18:18:31.773 | INFO     |  7856 | mycroft.skills.skill_manager:_unload_removed_skills:322 | removing mycroft-volume.mycroftai

```
So the pairing code though retrieved, is never spoken, and even if print it, there's no one left to listen, as the skill is being removed.

**Comment by forslund** [comment]
There's probably some issue in the code checking if a skill has been deleted. Check this method, if something is too isn't adding up: https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/skill_manager.py#L313

**Comment by NoamDev** [comment]
Well, it somehow got solved. 🤷‍♂️

**Comment by ChanceNCounter** [comment]
I applaud the effort and apparent progress, but I figure I should nevertheless paste the counterargument from chat:

> it's dependency hell for days. the nature of python on windows means that many stories end in, "just isn't gonna work cross-platform like that."
>
> WSL is a promising solution, because it provides the necessary compatibility layer between headless *nixware and Windows itself. however, it's still at a stage where they really don't want you to dick with windows from within WSL, apart from launching programs, and i've discovered several times that you can trigger opaque, generic BSODs when you try.
>
> i'm convinced at this point that the best way forward for a windows port is to wait until system control via WSL is more thoroughly supported, and less prone to crashes. if you don't try to control the system, mycroft already runs almost-natively under WSL, if you install pulseaudio on windows.

> it may be possible to create a windows-native message bus listener, run mycroft itself under WSL, and write a whole separate windows client that responds to the message bus. i haven't pursued that because it's such a clunky solution. be great for you and for me, but for consumers? yeesh.

On the other hand, I am **very** optimistic about Mycroft under WSL, assuming WSL catches up. Right now, everything works out of the box with WSL+PulseAudio. You just can't do any system control tasks, launching programs, stuff like that. Just caching directory contents in a skill has caused bluescreens. But, if all you wanna do is interact with Mycroft, Q&A skills, control IoT devices, things like that, WSL will do fine.

**Comment by ChanceNCounter** [comment]
Oh, and, naturally, no X = no GUI =P but Jarbas' TUI works well.

**Comment by NoamDev** [comment]
@ChanceNCounter 
It's not gonna be easy, but I believe it has to be done that way.

**Comment by NoamDev** [comment]
I don't understand why if audio service loads services like vlc, it uses the audio utils instead..
When does it use the audio services?

**Comment by forslund** [comment]
It's made to be a pluggable system for different audio libraries to perform audio playback. This is used for example by skills playing news or a playlist of media.

These are loaded as they are available and none is a hard requirement. the "simple" uses the basic playback commandlines defined in the configuration (starting on [L53](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/configuration/mycroft.conf#L53)). And can be overridden in any of the system or user configurations.

VLC will be used if it is installed since it offers better handling than the "simple" systems, etc.

These services aren't needed for speech or anything I wouldn't focus on them in the beginning. Finding replacement commandline applications to use to render speech (play_wav and play_mp3 in the configuration)

**Comment by NoamDev** [comment]
Ok, for now I use ffplay. It's nice:)
Do you think it's time to fork and start coding?

**Comment by forslund** [comment]
Haven't you already? ;)

**Comment by NoamDev** [comment]
Is there anything holy with the fann2 version? Why not use 1.1.2?

**Comment by NoamDev** [comment]
Ok, I started to make it more organized, beginning with requirements installation.
I created this pr to allow you participate.

**Comment by krisgesling** [comment]
Hey, got your CLA Thanks!

In terms of requirement versions. Most of the time it's what was latest and working at the time the code was committed. As this code regularly gets pushed out to many thousands of devices we keep the dependency versions very specific. We update periodically, but particularly if there is an issue, security update, or a new feature is available that we need.

In saying that a relaxed dependency environment variable recently got added which you might be interested in:
https://github.com/MycroftAI/mycroft-core/pull/2562

**Comment by NoamDev** [comment]
The PR current code works with messagebus and skills.
(However it currently uses an unofficial build of fann2, we should fork and build one for ourselves.)

The next thing is the text client, it depends on curses which does not support windows.
The way I see it we have 2 options:
- use an unofficial build from http://www.lfd.uci.edu/~gohlke/pythonlibs/ (I don't think we should do that, and we don't have the source code to build by ourselves)
- to migrate to UniCurses. A cross-platform library with api very similiar to curses (it wraps curses in the case of linux).

Unless you there's a better solution, can any one take migrating to UniCurses on himself?  
I already forked it from sourceforge here:
https://github.com/NoamDev/pyunicurses.

**Comment by cgohlke** [comment]
> use an unofficial build from http://www.lfd.uci.edu/~gohlke/pythonlibs/ (I don't think we should do that, and we don't have the source code to build by ourselves)

The source code is available on that site and there are forks available on [PyPI](https://pypi.org/project/windows-curses/) and [GitHub](https://github.com/zephyrproject-rtos/windows-curses)

**Comment by NoamDev** [comment]
Nice to meet you here 😊

**Comment by forslund** [comment]
Awesome progress, gonna try getting it running this weekend and see if I can provide a mimic executable for you.

For fann2, We do have a fork here: https://github.com/MycroftAI/fann2-update, it has some fixes for multi-arch issues on linux. We never pushed a package since it was mainly I who had issues with it...

Maybe the windows fixes can be added to that?

**Comment by NoamDev** [comment]
I think the best way would be to publish wheels for fann2 on pypl. As windows does not come with swig and cmake. @cgohlke did you have to make changes to the code? May we request your help in case we have a problem in doing so?

**Comment by cgohlke** [comment]
> did you have to make changes to the code?

I used my own setup.py to also compile the FANN-2.2.0 library source and ran swig manually. E.g. this might work:

```patch
diff --git a/setup.py b/setup.py
index 37af7c7..5c478b4 100755
--- a/setup.py
+++ b/setup.py
@@ -88,8 +88,12 @@ def build_swig():
     swig_cmd = [swig_bin, '-c++', '-python', 'fann2/fann2.i']
     subprocess.Popen(swig_cmd).wait()

-if "sdist" not in sys.argv:
-    build_swig()
+#if "sdist" not in sys.argv:
+#    build_swig()
+
+srcdir = "../FANN-2.2.0-Source/src/"
+sources = [srcdir+src for src in
+               ('fann.c', 'fann_cascade.c', 'fann_error.c', 'fann_io.c', 'fann_train.c', 'fann_train_data.c')]

 setup(
     name=NAME,
@@ -120,11 +124,12 @@ setup(
     include_package_data=True,
     packages=find_packages(),
     py_modules=['fann2.libfann'],
-    ext_modules=[Extension('fann2._libfann', ['fann2/fann2_wrap.cxx'],
-                           include_dirs=['./include',
-                                         '../include', 'include'],
-                           libraries=['doublefann'],
-                           define_macros=[("SWIG_COMPILE", None)]
+    ext_modules=[Extension('fann2._libfann', ['fann2/fann2_wrap.cxx'] + sources,
+                           include_dirs=['./include', srcdir+'include', '../include', 'include'],
+                           #libraries=['doublefann'],
+                           define_macros=[("SWIG_COMPILE", None),
+                                          ("WIN32", None),
+                                          ("FANN_NO_DLL", None)]
                           ),
                 ]
 )
```

```
swig.exe -c++ -python -I..\FANN-2.2.0-Source\src\include  fann2\fann2.i
```

**Comment by NoamDev** [comment]
Assuming all checks pass now, we have text client working (using windows-curses).
During my work, I noticed Ctrl+C did not trigger a SIGINT handler..
At least not while curses was running.
We should make sure one day that it doesn't influence other places where we subscribe to SIGINT, like the mycroft.lock module.

**Comment by NoamDev** [comment]
We now have audio as well, though my lightweight windows setup won't install mimic1. 
For now, you have to use the text client and set up pairing first. Then you can configure it to use mimic 2 in https://home.mycroft.ai.
Also, for now, ffplay is used as the command-line audio player.
Are there built-in windows alternatives?
Alternatively, when we have a proper installer it can install ffplay too. (65 MB).
If anyone tries this, I'd like to hear whether yo think ffplay is a proper alternative to what's used in linux.
One last thing, mimic2 sometimes times out. Because there is not mimic to fallback to, it'll log stack traces and it won't answer you, but won't crash.

**Comment by NoamDev** [comment]
> For fann2, We do have a fork here: https://github.com/MycroftAI/fann2-update, it has some fixes for multi-arch issues on linux. We never pushed a package since it was mainly I who had issues with it...
> 
> Maybe the windows fixes can be added to that? 

We need to build wheels, can we have a ci with a  windows machine?

**Comment by krisgesling** [comment]
Yeah if we're going to have a Windows release then we definitely need CI setup for it. 

TBH I don't want to invest too much time in doing that until we've ironed out the bugs and can get a Windows version running manually. It does sound like you are making some excellent progress though!

Are you using the changes suggested by cgohlke to compile your own currently?

**Comment by NoamDev** [comment]
I was able to compile fann2 according to cgohlke's insturctions. Though I haven't tested it with mycroft yet.
About pushing it to https://github.com/MycroftAI/fann2-update, this setup is windows only, so.. it would mean @forslund won't be able to use it for his own problem. Anyway, I think it's best to create another fork named fann2-windows.
I'll create one, with an installation script as well.

**Comment by NoamDev** [comment]
You can now install fann2-windows using `pip install git+https://github.com/NoamDev/fann2-windows.git`
**on a windows machine** that has swig in its path. I didn't bother making it cross-platform.
There is some dead code in setup.py.. and package details should also change, I guess. But it's not very important right now.
I still need to make sure it works with mycroft, maybe later.

**Comment by NoamDev** [comment]
if I understand correctly the only dependent of fann2 is padatious. Is padatious on by default? If not, I'm not sure how to verify whether my installation actually works.

**Comment by krisgesling** [comment]
Ah I should update that - both Adapt and Padatious are available by default

**Comment by krisgesling** [comment]
Just had to go check, but asking Mycroft "how are you" should use Padatious

**Comment by NoamDev** [comment]
I checked now, it works:)
I commited my changes, so now the pr does not depend anymore on cgholke's builds. Only pypl and my git repo (for now).

**Comment by NoamDev** [comment]
@forslund Have you tried producing mimic builds?

**Comment by krisgesling** [comment]
I think I'm going to buy my first Windows key in about 15 years because of this :smile:

**Comment by NoamDev** [comment]
😂 I PMed you about that.

**Comment by NoamDev** [comment]
I built mimic using wsl. But beacuse mycroft is looking for file named 'mimic' and not 'mimic.exe'.
I'll try to change it so that in windows it'll look for mimic.exe and then see if it works.

**Comment by NoamDev** [comment]
I did so, and now it works.
In addition to mimic1 executable releases, we also need precise releases. I already opened an issue there MycroftAI/mycroft-precise#163.
How do you even build precise linux executables? There doesn't even seem to be anything but python there anyway, and setup.sh only calls setup.py after a few preparations..

**Comment by forslund** [comment]
@NoamDev Sorry didn't quite get around to it yet. I've had limited time in front of the computer these past weeks.

**Comment by NoamDev** [comment]
@forslund That's ok, if you need help with cross-compiling tell me:)

**Comment by forslund** [comment]
@NoamDev I've built a static binary of mimic for windows and added to the latest mimic-release: Direct link: https://github.com/MycroftAI/mimic1/releases/download/1.3.0.1/mimic_windows_amd64.zip

Works for me(TM) but let me know if there are issues with using it.

**Comment by NoamDev** [comment]
How can I force it to use mimic1 specifically without unpairing/disconnecting network?

**Comment by NoamDev** [comment]
@MatthewScholefield
I saw that you're the one who tagged the precise releases.
How do you build them?

**Comment by MatthewScholefield** [comment]
@NoamDev I run [./build.sh](https://github.com/MycroftAI/mycroft-precise/blob/dev/build.sh) in the repo.

**Comment by krisgesling** [comment]
> How can I force it to use mimic1 specifically without unpairing/disconnecting network?

Select British Male as the voice, this is Mimic 1.
AKA "ap" in the config which stands for "Alan Pope"

**Comment by NoamDev** [comment]
>I run [./build.sh](https://github.com/MycroftAI/mycroft-precise/blob/dev/build.sh) in the repo.
Thanks!
I see it uses pyinstaller which does not support cross-compiling.
So I think the first step towards windows build is a setup file for windows.
Then, we can use pyinstaller the same way.
That means the build process should be done on a windows machine.
Do you think the setup file should be batch or powershell? powershell is much more convenient, but I'm afraid wine does not support powershell out of the box.
Or maybe use py2exe?

**Comment by NoamDev** [comment]
@forslund 
your mimic executable works very well!
i'd change my win-setup so that it'll download and unpack this.

**Comment by NoamDev** [comment]
Because of multiple edits, I'll clarify about precise:
to compile precise we use pyinstaller
in order to compile to windows one should either:

1. use a windows machine

2.  use wine

wine does not support powershell out of the box meaning if we use wine we have to use batch scripts.
What's wrong with batch? In gentle words I don't like batch, it's ugly.

So, the question is: Are you OK with building precise for windows on a windows machine?
please say yes 😅

**Comment by ChanceNCounter** [comment]
I think there are two ways of looking at that. On the one hand, it makes sense to build on the target platform. On the other hand, it makes sense to ensure that all builds can be performed by the same machines, and I can't see too many people migrating *from* Linux *to* Windows =P

IMO, it comes down to how committed you are to maintaining the Windows build. If there's a reasonable chance that it might become abandonware, I think its best shot at attracting a new maintainer would be cross-compilation, so suffer through the batfile. If you expect you'll be doing it for the foreseeable future, do it however's easiest for you. I wouldn't wish a batfile on my worst enemy.

The biggest danger in packaging a FOSS project for an unsupported platform is not that you'll do it wrong. It's that you'll do it wrong *and nobody else knows how to fix it*. That ends with really irate users looking for help where none exists 😛 you haven't lived until you've seen somebody throw a fit at a dev team over an unofficial package they found in the Arch **U**ser Repository!

So I'd base the decision entirely on whether you think you'll still be maintaining the build in a year.

**Comment by NoamDev** [comment]
@ChanceNCounter Thanks!
I'm indeed not planning to maintain that forever, so I'll work a little more to make it cross-compilable (have I just made the word up?)
Batch, here we come!

**Comment by NoamDev** [comment]
Hmm, I can use python sometimes, instead. This would both more easy and maintainable.

**Comment by NoamDev** [comment]
I created windows precise build script and have built windows precise tars 🥳
I still have to make sure it actuallt works, but hay, we are one step ahead!

**Comment by NoamDev** [comment]
How can I run the tests on precise executable?

**Comment by MatthewScholefield** [comment]
```
pip3 install pytest
pytest
```

**Comment by NoamDev** [comment]
inside or outside the venv?

**Comment by MatthewScholefield** [comment]
Inside

**Comment by NoamDev** [comment]
As you can see in the issue, releasing a new pyache version is required.

**Comment by forslund** [comment]
I'm away camping for a couple of days, in case Kris hasn't verified and prepped the release I can look at the pyache release this weekend and do a release (Kris permitting)

**Comment by NoamDev** [comment]
> 
> 
> I'm away camping for a couple of days, in case Kris hasn't verified and prepped the release I can look at the pyache release this weekend and do a release (Kris permitting)
@forslund sure, enjoy yourself!

**Comment by NoamDev** [comment]
Amm, what's up with that?
@krisgesling already opened a PR, but a review is needed.

**Comment by NoamDev** [comment]
I feel confused. why precise has so many places to list its requirements?
requirements.txt, requirements/prod.txt and setup.py has its own independent list of requirements..
setup.py doesn't actually use the above txt files if I understand correctly, it doesn't use find_packages or something like that..
and so, build.sh in its turn doesn't use them.
Am I missing anything?

**Comment by forslund** [comment]
Seems like some merge has gone wrong there, the requirements.txt shouldn't be needed (replaced by the `requirements/prod.txt`) (and the setup.py should be changed to reference that one)

As far as I know the short list in the setup.py is the list of packages actually needed for building the executable.

Maybe my [gist](https://gist.github.com/forslund/b3679508d849efb8e48eda8d04c91f23) for building the bundle on Arm64 Linux could be of use, though windows is likely quite different so probably not.

Something that's good to know is that Python 3.8 and precise doesn't work.

**Comment by NoamDev** [comment]
I need to make sure astor's data files get included, astor (a requirement of tensorflow) now uses a file named VERSION.
Ideally, I would add to the spec file:
```
a.datas += collect_data_files('astor', subdir=None, include_py_files=False)
```
But the spec tamplate is used for building many scripts and I worry that not all of them use tensorflow..
So is there a reason to worry? If so, is it possible to include those data files only when needed?

**Comment by NoamDev** [comment]
Hey all, took me a while but I adapted precise for windows support :)
MycroftAI/mycroft-precise#180

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
