### ISSUE TITLE
Make mycroft-core an installable python package

### ISSUE THREAD

**Issue by Cadair** [MycroftAI/mycroft-core#263]
Is there a reason(s) why mycroft-core is not packaged in the python fashion and then looks for things like mimic in the standard system path?

**Comment by clusterfudge** [comment]
There are a number of dependencies that don't package well, or shouldn't be packaged as part of mycroft. For example, mimic has no python components, so making a pip package for it doesn't make a lot of sense. The pocketsphinx-python bindings (and available pip packages) don't work in a virtualenv, as they have native dependencies on pocketsphinx and sphinxbase that don't come in with the python lib. 

Python (via pip) doesn't have a good story for native dependencies, and native package managers (which we would use deb) have packages that are out of date and out of our control.

**Comment by Cadair** [comment]
My background is in scientific python, so I am fully aware of the limitations of pip when it comes to packaging compiled dependencies. 

I am not suggesting that Mycroft start using pip etc as their primary distribution / installation method, but it would still be nice to make it possible to install Mycroft core as a python package, if you assume the binary dependencies are taken care of (in the correct paths).

My main reason for asking this is that I would like to build a conda package for Mycroft (and all binary deps) http://conda.pydata.org/docs/ as it's my primary way of interacting with Python packaging and it is designed to fix all the issues that you nicely described with standard python packaging, with scientific Python in mind).

**Comment by clusterfudge** [comment]
I suppose depending on what it is you're trying to do, there are some subsets of mycroft that can be installed (even today, maybe?) that can suit your purposes.

The mycroft-skills-sdk (documentation lost, will find) is just the skills service, and can attach to a remote mycroft (or just a messagebus service). It is (I believe) pure python2.7. Adapt, the intent determination framework that Mycroft uses (in it's intent skill) is also pure python, and it works in py2 and py3. The speech clients are really the big barrier to mycroft packaging nicely, but I think you're right to call out that a) they don't need to be part of mycroft-core, and b) a mycroft-core package would be nice.

**Comment by ethanaward** [comment]
Yeah, parts of the team were having a discussion earlier about what exactly should be in mycroft-core. We were talking about it from the perspective of stripping down the skills to an essential few that should be needed on anything running mycroft, rather than having a lot of extraneous ones for various tasks.

**Comment by XayOn** [comment]
I don't think handling system-wide deps apart is that much a problem.

You could ask users to create virtualenvs with --system-site-packages and then just install deps via apt.

If current apt packages are outdated for this, setting up a debian repo or a PPA should probably do the trick, plus, having that it'd be easy to create a metapackage depending on all mycroft system deps, thus making a simple three-steps install process:

- Add the apt repo
- Install mycroft-deps package
- Install mycroft with pip

**Comment by forslund** [comment]
Hi longtime no comment here :) Right now it actually is pip installable. However it's not released on pypi and there's a separate issue for that. Closing this one for now
