### ISSUE TITLE
Documentation does not match implementation

### ISSUE THREAD

**Issue by NoamDev** [MycroftAI/mycroft-core#2630]
The documentation says the file is being deleted, well it is not.
Also the documentation says SIGTERM signal is sent, but actually SIGKILL is sent.
Given that the code works (I guess), I think the documentation is the one requiring change.
https://github.com/MycroftAI/mycroft-core/blob/aca6a18c5f408480d1c129d33f2522e7f0c35802/mycroft/lock/__init__.py#L129-L147

**Comment by NoamDev** [comment]
The PR current code works with messagebus and skills.
(However it currently uses an unofficial build of fann2, we should fork and build one for ourselves.)

The next thing is the text client, it depends on curses which does not support windows.
The way I see it we have 2 options:
- use an unofficial build from http://www.lfd.uci.edu/~gohlke/pythonlibs/ (I don't think we should do that, and we don't have the source code to build by ourselves)
- to migrate to UniCurses. A cross-platform library with api very similiar to curses (it wraps curses in the case of linux).

Unless you there's a better solution, can any one take migrating to unocurses on himself?  
I already forked it from sourceforge here:
https://github.com/NoamDev/pyunicurses.

**Comment by krisgesling** [comment]
Nice spotting, if you want to create a PR updating those comments it would be very helpful, and you'll forever get the kudos for fixing it up :)

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
