### ISSUE TITLE
mycroft-stock: failed with Exception('Skill has been disabled by Mycroft')

### ISSUE THREAD

**Issue by fermulator** [MycroftAI/mycroft-core#2631]
## Be clear about the software, hardware and version you are running

For example: 

* I'm running picroft
* With version `20.2.4` of the Mycroft software
* With the standard Wake Word

## Try to provide steps that we can use to replicate the Issue

1. follow picroft installation instructions
2. on startup, we get these errors about a disabled skill 

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

I wouldn't expect something as core as "mycroft-stock" to fail to load on a user's system;  Nor for it to be disabled?  This isn't a marketplace skill that the user installs afaik.

Here's the logs:
```
mycroft.skills.skill_loader:_create_skill_instance:231 | Skill __init__ failed with Exception('Skill has been disabled by Mycroft
```
```
 14:05:55.969 | INFO     |   633 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: mycroft-stock.mycroftai
 14:05:56.015 | INFO     |   633 | mycroft.skills.settings:get_local_settings:78 | /opt/mycroft/skills/mycroft-stock.mycroftai/settings.json
 14:05:56.021 | ERROR    |   633 | mycroft.skills.skill_loader:_create_skill_instance:231 | Skill __init__ failed with Exception('Skill has been disabled by Mycroft')
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/skill_loader.py", line 228, in _create_skill_instance
    self.instance = skill_module.create_skill()
  File "/opt/mycroft/skills/mycroft-stock.mycroftai/__init__.py", line 127, in create_skill
    return StockSkill()
  File "/opt/mycroft/skills/mycroft-stock.mycroftai/__init__.py", line 87, in __init__
    raise Exception('Skill has been disabled by Mycroft')
Exception: Skill has been disabled by Mycroft
 14:05:56.027 | ERROR    |   633 | mycroft.skills.skill_loader:_communicate_load_status:287 | Skill mycroft-stock.mycroftai failed to load

```

'tis here
```
(.venv) pi@picroft:~ $ msm list  | grep stock
INFO - building SkillEntry objects for all skills
INFO - building SkillEntry objects for all skills
INFO - invalidating skills cache
mycroft-stock	[installed]
```

**Comment by fermulator** [comment]
w/ some help from the Mattermost dev channel, looks like https://github.com/MycroftAI/skill-stock/issues/31 is to blame here

**Comment by fermulator** [comment]
from a "mycroft-core" perspective; maybe we should be stack trace dumping into the logs when a skill is specifically disabled for a valid reason? would also be good if the mycroft devs were able to include a brief "reason" and "ticket reference" to track so that anyone looking at the logs can immediately understand what's going on

**Comment by krisgesling** [comment]
Yeah the intention was to quickly disable this while we got another service stood up. 

We've always used free services for this as it's not a highly used Skill, however the intention now is to provide a proxy to the paid FMP API as discussed in the linked issue above. This requires some updates on the Selene backend, and switching the Skill itself to their new API syntax.

If you have any specific wording suggestion for changing the current log message then I'm happy to switch it out.

**Comment by fermulator** [comment]
per discussion, a message like:
> "The <skill-name> skill has been disabled due to <reason>, for further information see <link/ref>."

**Comment by krisgesling** [comment]
https://github.com/MycroftAI/skill-stock/pull/32

**Comment by fermulator** [comment]
'twas merged via https://github.com/MycroftAI/skill-stock/commit/7d61ac88ce5557e9f26503611d10d771c1f73e7d

**Comment by fermulator** [comment]
being delivered into marketplace by @krisgesling via https://github.com/MycroftAI/mycroft-skills/pull/1415
