### ISSUE TITLE
py2cairo location has moved

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mycroft-core#264]
this breaks install-pygtk.sh
Current url:
https://cairographics.org/releases/py2cairo-1.10.0.tar.bz2
New url:
https://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2

**Comment by ethanaward** [comment]
Both of these links work to download the tar for me.

**Comment by el-tocino** [comment]
Interesting.  Today they work for me as well.  Two days ago the insecure url was returning an error indicating that it had been updated to the secure url as the tar file.  Will close, then.

**Comment by jdorleans** [comment]
Thx for the feedback guys
