### ISSUE TITLE
extract_datetime() returns 8 AM results in utterance where no time specification was made 

### ISSUE THREAD

**Issue by emphasize** [MycroftAI/mycroft-core#2647]
Found this while reworking the skill-reminder. While processing non timed reminder there is a safeguard mechanism to check [extract_datetime](https://github.com/MycroftAI/mycroft-core/blob/a6cb0c5258dbc34e7f80daf50ed751c87a40c61e/mycroft/util/parse.py#L145) in ["the case where padatious misses the time/date"](https://github.com/MycroftAI/skill-reminder/blob/b8dc13ec00bb0feb361deb58fd71080e98ed1325/__init__.py#L251) with the result of returning 8 AM and blocking the non timed reminder alltogether. (tested in german language. Phrase: "Erinnere mich an Meeting"; changed the vocab locally and tested it also with "Erinnere mich Meeting" with no difference)

This may be an issue in various skills so i dump it here.

**Comment by forslund** [comment]
Seems to be a german (or non-english) issue in lingua franca:

Mycroft calls:
```python
from mycroft.util.parse import extract_datetime
>>> print(extract_datetime('Remind me of the meeting', lang='en-us'))
None
>>> print(extract_datetime('Remind me of the meeting', lang='de-de'))
[datetime.datetime(2020, 8, 5, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Europe/Stockholm')), 'remind me of the meeting']
```

Lingua franca calls:
```python
>>> from lingua_franca.parse import extract_datetime
>>> print(extract_datetime('Remind me of the meeting', lang='en-us'))
None
>>> print(extract_datetime('Remind me of the meeting', lang='de-de'))
[datetime.datetime(2020, 8, 5, 0, 0, tzinfo=tzlocal()), 'remind me of the meeting']
```

May be good to move the issue there or raise an issue there to make sure it's noted there as well.

**Comment by krisgesling** [comment]
Fixed in Lingua Franca
