### ISSUE TITLE
skill keep reloading indefinitely if there are files with a future date

### ISSUE THREAD

**Issue by notmart** [MycroftAI/mycroft-core#2656]
due to a temporary problem in my system, i ended up with a skill with __init.py modification time set in the future. this caused that skill to constantly be reloaded my mycroft core, and unloaded just after the loading was complted. took some hours of debug to understand this was actually the problem.

perhaps skills with files with modification date from the future should just be stopped from loading and have a debug log about it?

**Comment by forslund** [comment]
Maybe a max(read timestamp, current timestamp) could be used as a sanity filter?
