### ISSUE TITLE
extend common play - audiobooks / podcasts / video / games

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#2658]
We should add support for media types under common play, it currently assumes "play X" is always about music, but it could be video or audiobooks, at very least the trigger phrase needs to be expanded to handle other use cases, which can also be used for media type detection (but wont be enough)

Apologies for the messy issue, instead of rewriting all the info bellow i thought it would be easier to screenshot the chat

![Image Pasted at 2020-8-12 21-38](https://user-images.githubusercontent.com/33701864/90065934-e9b79c00-dce4-11ea-984e-d9e32362e4c7.png)
![Image Pasted at 2020-8-12 21-328](https://user-images.githubusercontent.com/33701864/90065948-ede3b980-dce4-11ea-8b83-9b552a0ffe59.png)

![2020-08-12_21-56](https://user-images.githubusercontent.com/33701864/90067247-ba099380-dce6-11ea-85d0-f886c27d14a4.png)

![2020-08-12_21-54](https://user-images.githubusercontent.com/33701864/90067089-83337d80-dce6-11ea-861d-fd5c7e9f8fdb.png)
![2020-08-12_21-55](https://user-images.githubusercontent.com/33701864/90067095-862e6e00-dce6-11ea-8ae0-20b95eed3fb7.png)

![image](https://user-images.githubusercontent.com/33701864/90067330-dc9bac80-dce6-11ea-9877-f6152d85bb45.png)

**Comment by krisgesling** [comment]
Hey Jarbas, good discussion already, thanks for getting it going.

The other big area that I see coming up (particularly with the GUI) are "playing" games. They can use Padatious intents to closely match their game name but is it worth allowing them to respond to the `CPS_match_query_phrase` with a media type of `game`?

**Comment by AIIX** [comment]
Hey so I got down to working on adding a video type to playback skill that can support "Video" media type GUI side, It isn't exactly clear as to how the video type is supposed to be handled as currently at least on the "Audio"' type Mycroft Internally manages playback but for GUI video side, video playback will be managed by an component in the user interface so I believe it would be nice to discuss the structure of the data CPS will provide GUI and GUI needs to send back to playback skill
