### ISSUE TITLE
Two errors with the latest 20.02.5 (probably Python3.8 related)

### ISSUE THREAD

**Issue by j1nx** [MycroftAI/mycroft-core#2676]
With the latest dev version I got the following two errors.

**Audio.error.log:**

Traceback (most recent call last):
  File "/usr/bin/mycroft-audio", line 11, in <module>
    load_entry_point('mycroft-core==20.2.5', 'console_scripts', 'mycroft-audio')()
  File "/usr/lib/python3.8/site-packages/mycroft/audio/__main__.py", line 69, in main
    audio.shutdown()
  File "/usr/lib/python3.8/site-packages/mycroft/audio/audioservice.py", line 466, in shutdown
    self.bus.remove('mycroft.audio.service.play', self._play)
  File "/usr/lib/python3.8/site-packages/mycroft/messagebus/client/client.py", line 213, in remove
    self.emitter.remove_listener(event_name, func)
  File "/usr/lib/python3.8/site-packages/pyee/_base.py", line 136, in remove_listener
    self._events[event].pop(f)
KeyError: <bound method AudioService._play of <mycroft.audio.audioservice.AudioService object at 0x7fa7c8b970>>

**skills.error.log**

Traceback (most recent call last):
  File "/usr/bin/mycroft-skills", line 11, in <module>
    load_entry_point('mycroft-core==20.2.5', 'console_scripts', 'mycroft-skills')()
  File "/usr/lib/python3.8/site-packages/mycroft/skills/__main__.py", line 206, in main
    skill_manager = _initialize_skill_manager(bus)
TypeError: _initialize_skill_manager() missing 1 required positional argument: 'watchdog'

The second is most likely because of my own requested service hooks ;)

If I understand it correctly, Python3.8 is a bit more picky on stuff. I know, Python3.8 is not yet officially supported, but as most recent distro already have it included I report them here.

**Comment by forslund** [comment]
The skills error is a missing argument when skills_manager wasn't initialized the first time due to a Msm error (Msm cache likely not on the system and no internet available). Not the fault of your hooks.

The thing in audio I can't really reproduce here. But will try on my Ubuntu focal system as well with python 3.8.

**Comment by j1nx** [comment]
Ah ok, sounds plausible as my boot currently is way to fast and the internet is not yet fully up when Mycroft is. Will dig into it some more.

**Comment by forslund** [comment]
You should be able to work around it by restarting the skill service once after the internet connection has been established. msm should then cache things and it should work on all later starts.

**Comment by forslund** [comment]
Also in your audio log is there any errors/exceptions before the one in the shutdown() it looks like it hasn't registered the audioservice handlers and is failing to remove them.

**Comment by j1nx** [comment]
New flash and only the skill error at first boot. Not the audio one. Believe it is a timing issue. 

Could also be a time/date issue as mycroft boots and start very fast, internet is not even fully set up, which also means the time has not yet been synced. Git checkouts will therefor also fail because of the SSL certificates not been valid because of it.

Leave it for now. Will do some testing in delaying the start a bit first.

**Comment by j1nx** [comment]
Can't reproduce the audio error anymore. Must have been a timing issue where things were not fully ready as of yet when starting mycroft audio services.

So closing this issue for now.
