### ISSUE TITLE
fatal error building mimic from dev_setup.py

### ISSUE THREAD

**Issue by vorpalhex** [MycroftAI/mycroft-core#2694]
I encountered and found a workaround for the following issue, posting for visibility (and in case anyone else has the same issue). 

Ubuntu 19.04 on Arm64 (Raspberry Pi 4 with 2gb of ram, `Linux mycroft 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`). Running dev_setup.py set to build mimic hit the following:

```
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_12_params.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_17_durmodel.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_17_mcep_trees.lo
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[1]: *** [Makefile:4069: lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_01_params.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/local/lib/mycroft/mimic'
make: *** [Makefile:4320: all-recursive] Error 1
```

Re-running the script resulted in the same error in the same place. Resolution was to cd into the mimic folder and build/install directly - I believe that the issue may be with the script wrapper instead of mimic itself based on that.

Resolution steps:

```
cd mimic
./configure
make clean
make build
make check
sudo make install
```

After that the dev_setup.py script worked as expected.

**Comment by forslund** [comment]
That is likely a out of memory issue. The dev_setup.sh tries to calculate maximum number of CPU cores to use when building to improve speed. There's a [PR](https://github.com/MycroftAI/mycroft-core/pull/2382) that for these architectures locks the number of cores to 1 for these architectures. Perhaps it should be merged if it solves the issue for you?

**Comment by vorpalhex** [comment]
Yeah, I suspect that's the culprit. Will drop a comment on that PR linking back to this issue.

**Comment by mocallins** [comment]
I tried the suggested build steps, didn't help.

  CC       lang/cmu_us_slt/libttsmimic_lang_cmu_us_slt_la-cmu_us_slt_spamf0_accent_params.lo
  CC       lang/cmu_us_slt/libttsmimic_lang_cmu_us_slt_la-cmu_us_slt_spamf0_phrase.lo
  CCLD     libttsmimic_lang_cmu_us_slt.la
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_01_mcep_trees.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_01_params.lo
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[1]: *** [Makefile:4072: lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_01_params.lo] Error 1
make[1]: Leaving directory '/home/pi/build/mycroft-core/mimic'
make: *** [Makefile:4323: check-recursive] Error 1
