### ISSUE TITLE
Unable to clone repo 

### ISSUE THREAD

**Issue by damorosodaragona** [MycroftAI/mycroft-core#2696]
* I'm running on the last version of VirtualBox (v.6.1.12) on 
* With version 18.04.5 of Ubuntu Server

To replicate:
1. Install VirtualBox 6.1.12 on Win10 (latest update)
2.  Create a VM with Ubuntu Server 18.04.5 

When i try to clone mycroft-repo on Ubuntu Server 18.04.5 (but on Ubuntu Desktop 18.04 is the same) i got the error in the images attached. 

![image](https://user-images.githubusercontent.com/15249587/93468105-c63cce00-f8ee-11ea-9866-d13c9a083cb7.png)

![image](https://user-images.githubusercontent.com/15249587/93468984-1cf6d780-f8f0-11ea-9f57-2cbb49f7fbda.png)

**Comment by krisgesling** [comment]
Hey there, I haven't seen this one before. 

Just to confirm, my understanding is that these are freshly installed Ubuntu images.

How much memory did you allocate to the VM? 

You could try:
```
git clone --depth=1 --no-single-branch https://github.com/mycroftai/mycroft-core
```

**Comment by damorosodaragona** [comment]
I allocate 4gb RAM and around 15gb of virtual hard disk.
I tried your suggestion but didn't work:  
![image](https://user-images.githubusercontent.com/15249587/93590539-fb105a00-f9ae-11ea-98b5-6a8144b74042.png)

**Comment by krisgesling** [comment]
Hey, thanks for the update. If you've resolved it for now, I'll close this issue given it's not an issue in mycroft-core itself.

If others run into the same thing then we can investigate further.
