### ISSUE TITLE
Extract existing audioservices, STT and TTS engines for new plugin system

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2701]
As we are moving to a new [plugin system for audioservices, STT and TTS engines](https://github.com/MycroftAI/mycroft-core/pull/2594) we need to create a plugin for each of the services that will no longer be included by default in core.

Examples are provided in the PR #2594 

We also need to explore the best ways to surface the available plugins. Most likely an extension of the Selene Marketplace.

**Comment by krisgesling** [comment]
Once optional modules are removed from core, this `log.error` should be changed to an `exception` as per this thread:
https://github.com/MycroftAI/mycroft-core/pull/2594/files#r462482743

**Comment by krisgesling** [comment]
New TTS services in #3024 and #3032

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
