### ISSUE TITLE
Allow skills to require specific languages

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/mycroft-core#2703]
In a future update, Lingua Franca will not load English (or any) parsers and formatters by default. Rather, LF will expect Mycroft to specify which language(s) should be loaded. This should facilitate modularity, and might also save on memory, if a bunch of new languages are added.

However, there are two scenarios in which a skill might want functions from a specific language, regardless of the user's STT and TTS choices:

1) A skill that hasn't been localized will expect access to the author's language (usually English)
2) A skill that pertains to a particular place, culture or language might need to operate on the relevant language

Toward that end, it would be helpful if skills could specify any language or languages they might require to function.

**Comment by krisgesling** [comment]
Hey, that makes sense. Are you thinking a new optional attribute in a Skills `manifest.yml`?
```yaml
dependencies:
  # Require the availability of a specific human language
  language:
    - it-it
```

**Comment by JarbasAl** [comment]
at the intent level a skill should also be aware if something is not available (not localized yet) to configured language

related https://github.com/MycroftAI/mycroft-core/pull/1111

**Comment by ChanceNCounter** [comment]
I think `manifest.yml` is a sensible place for it, to be sure. `MycroftSkill` would then simply call `lingua_franca.load_language(...)`. It can fire blind, no need to check if it's loaded already. LF will do that.

**Comment by ChanceNCounter** [comment]
On the other hand, it might be good to support a distinction between "requires all of these languages" and "requires at least one of these languages."

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
