### ISSUE TITLE
Listener refactor

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#272]
The listener should be separated into separate modules and much probably put into its own file. This will help with making unit tests.

**Comment by FruityWelsh** [comment]
Is this still on list to do? 
Is listener.py in the speech module not separated enough for unit tests, or is there further isolation that needs to occur?

**Comment by MatthewScholefield** [comment]
This is super old. Probably not relevant anymore since it's split up decently well now.
