### ISSUE TITLE
Prep: LF 0.3.0 will require addition to test runner

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/mycroft-core#2723]
Lingua Franca 0.3.0 will not load languages by default (see also: #2703). Hence, `bin/mycroft-skill-testrunner` will need to make sure a test's language is loaded.

This is trivial by either of two routes:

`lingua_franca.load_language(str: lang_code)` before starting a particular language's test suite, or
`lingua_franca.set_default_lang(str: lang_code)` to ensure the language is loaded, and make it LF's default. This way, it would support the omission of the `lang` parameter within localized test files. The latter only works if tests are run consecutively, rather than in order, or they'll clobber each other's invocations of `set_default_lang()`.

**Comment by ChanceNCounter** [comment]
This would need to be done simultaneously with the LF integration, and not before, because (obviously) those functions are not yet available.

**Comment by ChanceNCounter** [comment]
I've just realized, "run consecutively rather than in order" is the most meaningless of typos =P

Testing by setting the default language will only work if tests are run *consecutively* rather than *concurrently or in parallel*. Unittest and pytest, by default, run tests in a manner which *I* certainly can't predict, and getting them to run tests *in* order is challenging (and would be a big hassle for new devs.) I have no idea how VK does it, but when I tried to test Lingua Franca that way, like I said, the tests clobbered each other's `set_default_lang()` calls.

In LF, I solved this by spamming a function in the test file I called `unload_all_languages()` 👅 but that's not necessary here, just important to note that `load_language(...); call_function(data, lang=lang_code)` will be more reliable *within tests* than `set_default_lang(...); call_function(data)`

**Comment by ChanceNCounter** [comment]
aaaand I should further point out *that* only happens *within test files*. LF's test suite is able to set default languages *per file* with no problems. It's files that contain multiple calls to `set_default_lang()`, within different tests, that have problems.

End of nitpick.

**Comment by ChanceNCounter** [comment]
If Mycroft-core goes straight to LF 0.4, there's an antipattern available (👅) that *should* (hopefully) obviate this problem:

`lingua_franca.config.load_langs_on_demand = True` will do some nonsense that's intended only (and specifically) for situations in which the implementation doesn't know ahead of time what languages it will need to invoke. This trades performance - *presently* consisting of a whole lot of negligible calls - for convenience. It can increase *or* decrease heap size, depending on how often LF functions are called on unloaded languages. I don't think it will be a problem for the test runner. I just wish people didn't know it existed 😉

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
