### ISSUE TITLE
Replacing hard coded /tmp/ for some instances in the code

### ISSUE THREAD

**Issue by dzekem** [MycroftAI/mycroft-core#2727]
# /tmp/ has been hard coded in some instances

This will be replaced with https://docs.python.org/3/library/tempfile.html which has been well implemented in some instances in the code.

**Comment by forslund** [comment]
Agreed, I thought we'd been better regarding this but you're right it's very much needed!

**Comment by spencerkee** [comment]
Hello, any chance you could assign the issue to me?
