### ISSUE TITLE
 Failed to find intent. 

### ISSUE THREAD

**Issue by weathon** [MycroftAI/mycroft-core#2730]
I am running the latest stable version of Mycroft.
If I start with ```debug``` it will have an error that " Failed to find intent. "
but if I start with cli it works fine

**Comment by krisgesling** [comment]
Hi there, can I clarify in one instance you run:
```
mycroft-start debug
```
and in the other you run
```
mycroft-start all
mycroft-cli-client
```
and with the first method you get an error that it failed to find intent. 

What utterances do you say that returns the error? I presume it is for anything you say?

Can you also give some more detail on how you're running Mycroft? Picroft, Git install on Linux, Docker, Snap, installed from a Linux distro like Manjaro, other?

**Comment by weathon** [comment]
It gave me the error for everything I said. And now the debug is also working. I think it might be just when I run debug it is not ready and when I run CLI it is ready to use. Is it true that after I start it I have to wait for tenish minutes? I am ruing it on a Ubuntu Laptop, with i3 CPU, build and run from git repo.

**Comment by joshua-montgomery** [comment]
It used to be true that there was a bunch of setup on boot, but the guys
trimmed a lot of that away.  It SHOULDNT take 10 min to stand up the
services, but I'm not saying it ISNT taking that long.

Any ideas where the delay is?

--

*Joshua Montgomery |* Founder *|* *Mycroft AI*
300 E 39th Street, Ste 4I, Kansas City, MO 64111
p 785-840-6155 <7858406155> *| *joshua.montgomery@mycroft.ai
https://mycroft.ai <http://mycroft.ai/>

**Comment by forslund** [comment]
First startup it downloads and install all skills after that it should be quicker. less than 30 seconds on my desktop.

Would be interesting if you could post your `skills.log` found under `/var/log/mycroft`

**Comment by weathon** [comment]
Thank you guys, it is working now.
(On my raspberry, the first boot is more than an hour)
