### ISSUE TITLE
Skill Settings does not works

### ISSUE THREAD

**Issue by damorosodaragona** [MycroftAI/mycroft-core#2733]
Hi, 
i have a skill and i need to save some information. 
I have some issues:
1. Following the guide, i create a settingsmeta.json file in the root directory of my Skill. 
This is the content of my settingsmeta.json file:
```
{
    "skillMetadata": {
        "sections": [
            {
                "name": "Bookmarks",
                "fields": [
                    {
                        "name": "bookmark",
                        "type": "text",
                        "label": "my bookmarks",
                        "value": "1.2.a"
                    }
                ]
            }
        ]
    }
}
```

Now when i use `self.bookmark = self.settings.get('bookmark')` in `initialize()` method i always obtain `None`.
If i try to use `self.log.info(self.settings)` this is what i got: `{'__mycroft_skill_firstrun': False}`

---------

2. If i delete `settingsmeta.json` and if i just use `self.settings['bookmark'] = ""` then using `self.log.info(self.settings)` i got: `{'__mycroft_skill_firstrun': False, 'bookmark': ""}` and this is maybe is ok, the informations are stored in the file `settings.json` in `.config\mycroft\skill-name` folder, but i can't understand how use ` settingsmeta.json`.

----------

3. But in both cases if I try to use `Given user's saved story is true` in a feature named `featurename.feature` creating a file `featurename.config.json` with this content:
```
{
    "saved story": {
      "true": {
          "bookmark": "1.2.a"
        }
    }
}
```
this patch is not applied, so the test not pass.

--------

How can i fix all this issues?
What i'm doing wrong?
If i can't use `settingsmeta.json` file is ok, but i need to patch the value of the skill configuration to test all the possible scenarios,

**Comment by forslund** [comment]
Hi settingsmeta is used for the websettings and will currently not populate with the defaults until the first fetch from home.mycroft.ai if I recall this correctly which may take a minute or so after first install.

I don't know the implementation of `The given user's saved story is true` so I can be off here, but the second part seems like you're trying to set the mycroft global configuration (not the skill's settings). I believe currently there's no good way to patch skill settings in the voight kampff tests.

There is an [issue for improving the test suite](https://github.com/MycroftAI/mycroft-core/issues/2633)

**Comment by krisgesling** [comment]
Hey there, 

I'd also add that you can provide a default value within the Skill code itself eg:
```python
self.bookmark = self.settings.get('bookmark', '1.2.a')
```

This is a feature of the `.get` method, not specific to Mycroft. If there is no value for "bookmark" it will instead return the second argument.

As Ake mentioned there is a separate feature request issue open for patching a Skill settings in VK.

So I'm going to close this issue for now. Please jump into the forums or the ~Skills channel on Mycroft Chat if you have further questions about using settings.
