### ISSUE TITLE
relative imports

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#2751]
a pattern across the code base is doing ```from . import XXX```

relative imports are less readable, and cause issues when running mycroft a certain way

You could argue this is a dev issue and call it wontfix, but for me this is very annoying. I use pycharm and run each service (bus/audio/skills/etc.) independently, depending on my workdir i can't launch some of these modules. I find this very annoying and my first step when making a new PR is editing these imports

audio service
![image](https://user-images.githubusercontent.com/33701864/98446877-c0a67c00-2118-11eb-9f95-696f8b4ceb69.png)

skills
![image](https://user-images.githubusercontent.com/33701864/98447089-221b1a80-211a-11eb-8e00-1f9003caec0e.png)

can we please drop this pattern for dev convinience and better readability?

**Comment by forslund** [comment]
I personally think it's more readable since I become directly aware if it's something from the module I'm working with something external.

I don't see those errors myself very often but if it's real annoyance for many developers making the readability worse for developer convenience should be considered. For me readability would take precedence but I don't really suffer from the issues this brings so I'm definitely biased :)

**Comment by JarbasAl** [comment]
regardless of readability an import that fails depending on workdir should be avoided if possible IMHO

**Comment by JarbasAl** [comment]
Absolute imports. From PEP 8:

Relative imports for intra-package imports are highly discouraged. Always use the absolute package path for all imports. Even now that PEP 328 [7] is fully implemented in Python 2.5, its style of explicit relative imports is actively discouraged; absolute imports are more portable and usually more readable.

**Comment by krisgesling** [comment]
I was hoping that link would state that one way was better than the other with a million up votes. It's never the way :(

So to clarify, the current use of relative imports will always work if you launch it using the module name eg:
```shell
python -m mycroft.skills
```
but if trying to launch the `__main__.py` directly it can/will fail?

And if we switch every relative import with the absolute, then both will always work?

**Comment by JarbasAl** [comment]
yes, absolute imports will always work

currently if we launch a ```___main___.py``` it will fail as shown above

works everywhere seems a better choice to me, and in general explicit is better than implicit. Seems an obvious change to me.....

**Comment by krisgesling** [comment]
It's probably just what I've seen the most, but personally I find the explicit relative imports useful in indicating that they are being imported from within that module as opposed to being sourced externally.

I also find it interesting that people argue absolute imports are more portable. If I move a whole section of code that uses relative imports and move it elsewhere, it should work exactly the same. If it was using absolute imports they would by definition need to be updated.

This really feels like a developer preference issue.
