### ISSUE TITLE
adjusting for ambient noise at a safer time

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#2754]
in [listen method of speech client](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/mic.py#L703) it says

```
# Every time a new 'listen()' request begins, reset the threshold
# used for silence detection.  This is as good of a reset point as
# any, as we expect the user and Mycroft to not be talking.
# NOTE: adjust_for_ambient_noise() doc claims it will stop early if
#       speech is detected, but there is no code to actually do that.
self.adjust_for_ambient_noise(source, 1.0)
LOG.debug("Waiting for wake word...")
```

however since this method is async from the actual STT processing, it means it might adjust for ambient noise just as TTS is starting

a better place for this would be right before the STT processing step, like i did in [hivemind-voice-satellite](https://github.com/OpenJarbas/HiveMind-voice-sat/blob/master/mycroft_voice_satellite/speech/mic.py#L631)

```
# Every time a 'listen' request ends, reset the threshold used for
# silence detection.
# This is as good of a reset point as any, as we expect the user to
# have stopped talking and Mycroft to not be talking yet
# NOTE: adjust_for_ambient_noise() doc claims it will stop early if
#       speech is detected, but there is no code to actually do that.
self.adjust_for_ambient_noise(source, 1.0)
return audio_data
```
PR coming soon

**Comment by krisgesling** [comment]
I assume this was to eliminate the start listening beep particularly on a Mark 1. So as long as you test on that you should be safe.

**Comment by JarbasAl** [comment]
this is somewhat unrelated to the beeping sound, the playback of the sound mutes the mic either way

What this does impact is the parameters used for voice activity detection, since the current implementation considers ambient noise:
- the user speech
- the muted mic during beep sound
- just on time before user starts to speak

by moving it to the new proposed place the ambient noise will be adjusted right after the user stops speaking (recording for STT stopped) and before mycroft is speaking (STT processing didn't start yet)

**Comment by forslund** [comment]
Isn't it in direct series?
1. Adjust for ambient
2. Wait for wakeword
3. record utterance
4. Jump to 1

So would be directly after STT recording completes?

**Comment by JarbasAl** [comment]
no, it is async, audio is put into a queue for STT to handle, and immediately adjusts for ambient noise

**Comment by JarbasAl** [comment]
closing due to brain fart, this will block for 1 second, not a good change

**Comment by penrods** [comment]
Tossing in my $0.02, I believe my intention was to to have this occur after the silence gap at the end of a STT session.  This seemed like the time when you could most reliably expect it to be "quiet".  It's been a while, so other things may have changed assumptions that once allowed this to behave in a way that matches that intention.

**Comment by penrods** [comment]
I might also be completely wrong in my recollections.  :)

**Comment by JarbasAl** [comment]
@penrods yep thats clearly the intention, but the response times have gone down meanwhile, since that step takes 1 second it means TTS might have started already, but i havent figured out a better place for it....

**Comment by penrods** [comment]
It would be ideal if some of the quiet at the end of the utterance could be included in the adjustment sample. If I recall, a 0.4 second response was considered "human like", so the sample should probably fit in that window or close.
