### ISSUE TITLE
Improvement for utils and AudioRecordSkill

### ISSUE THREAD

**Issue by jcasoft** [MycroftAI/mycroft-core#276]
improvement for utils and AudioRecordSkill
include another parameter in mycroft.ini
device = "plughw:0,0"  #Select PCM by name
and modify:
mycroft/util/**init**.py
line 40 with new parameter
def record(file_path, duration, rate, channels, device):
...... ["arecord", "-r", str(rate), "-c", str(channels), "-d", str(duration), "-D", device, file_path]

modify later:
mycroft/skills/audio_record/**init**.py
add after line 34
    self.device = self.config.get('device')
and modify line 82
    self.record_process = record(self.file_path, self.duration, self.rate, self.channls, self.device)

**Comment by ethanaward** [comment]
Have you tested this to make sure it works? If so, submit a PR with these changes.

**Comment by aatchison** [comment]
Closing to age and perhaps relevance.
