### ISSUE TITLE
Integrate new Azure Cognitive Services (TTS)

### ISSUE THREAD

**Issue by dalgwen** [MycroftAI/mycroft-core#2760]
**Is your feature request related to a problem? Please describe.**
As a french user, I cannot use mimic. I used to rely upon google TTS, which is kind of a hack and can break anytime (and by the way, it is broken now). I search some reliable and free (or with free plan) TTS engine, and the best I found is IMHO Azure.
I didn't manage to make the current Bing integration working. And anyway, it seems Bing TTS is end of life / outdated, replaced by Azure TSS.

**Describe the solution you'd like**
Include new Azure Cognitive Services (TTS)

**Describe alternatives you've considered**
Bing, Google TTS, Watson

**Additional context**
I will provide a pull request

**Comment by marvin-w** [comment]
For Google TTS follow https://github.com/MycroftAI/mycroft-core/pull/2763

**Comment by dalgwen** [comment]
Azure TTS as a plugin is now available on Pypi.
(the new plugin system requires the current dev branch)
