### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by diabsiniman** [MycroftAI/mycroft-core#2768]
Trying to install on ubuntu 20.04

(im not very good at this, without step by step instructions, im basically lost)

following instructions, as instructed, and then this error comes up :

pulseaudio-utils is already the newest version (1:13.99.1-1ubuntu3.8).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1842k  100 1842k    0     0  2103k      0 --:--:-- --:--:-- --:--:-- 2100k
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pip==20.0.2 (from versions: none)
ERROR: No matching distribution found for pip==20.0.2
Failed to set up virtualenv for mycroft, exiting setup.

your help would be appreciated

**Comment by krisgesling** [comment]
Hi there, is this a standard Ubuntu 20.04? Are you using Anaconda or similar?

Otherwise I'd check your system date as this can also cause SSL failures.

You can tell pip to ignore SSL but I'd strongly discourage that.

**Comment by diabsiniman** [comment]
> Hi there, is this a standard Ubuntu 20.04? 
Yes, though i have been running and using it for a few months before i did this install, i also had a small minecraft server running from it for a while, but have since stopped that, beyond that, i just use this for my normal day to day operations (email, word processing, printing of documents, zoom meetings)

>Are you using Anaconda or similar?
i havent a clue, as stated before, im not a very good linux user, once i have something installed and working, i forget about every thing else i did to get it to work, i have no documentation to track my changes and packages, and without step by step instructions, for the most part, i havent a clue what i am doing (i did do a redhat course back in 2002, but i failed that, and most of the stuff i learned i have forgotten) 
> 
> Otherwise I'd check your system date as this can also cause SSL failures.
my system date is set to update from a local (country) ntp server (i hope i did that right). regardless, the time and date seem to be working fine, without having to be reset or anything (i havent had any other time or ntp related issues)

> 
> You can tell pip to ignore SSL but I'd strongly discourage that.
i tried that, and it still didnt install (was the first fix i tried before posting here, this i did undo before posting as i am sure running a machine without ssl causes no end of trouble)

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
