### ISSUE TITLE
No Sound Kubuntu Plasma 5

### ISSUE THREAD

**Issue by trekjunky** [MycroftAI/mycroft-core#277]
I've run build and dev setups without a hitch. The QTApplication runs, but there is no sound. Please help...I have since switched to Kubuntu. Same issue

**Comment by swilso793** [comment]
Do you have the pulseaudio packages installed in your system?
If yes, try `pulseaudio -D` before running mycroft. If that doesn't work download pavucontrol(`sudo apt-get install pavucontrol`) and see what's happening in a nice gui.

**Comment by aatchison** [comment]
Any luck here? I'd like to close this O/S specific issue and also understand if your issue was fixed :)

**Comment by swilso793** [comment]
Im guessing he fixed it, because he didn't answer and i had the same problem that was fixed by running `pulseaudio -D`

**Comment by trekjunky** [comment]
Issue solved. You can close this issue.
