### ISSUE TITLE
Mycroft fails to start on Manjaro

### ISSUE THREAD

**Issue by 1Maxnet1** [MycroftAI/mycroft-core#2770]
**Describe the bug**
Starting Mycroft on Manjaro Linux after installing it in the official way, results in errors and warnings.

**To Reproduce**
1. Go to https://github.com/MycroftAI/mycroft-core
2. Copy the steps from the Installation guide and run them in your terminal.
3. Answer all the Questions asked at the Installation
4. run ~/mycroft-core/start-mycroft.sh debug

**Expected behavior**
The CLI-Interface should show up.

**Log files**
[audio.log](https://github.com/MycroftAI/mycroft-core/files/5621446/audio.log)
[bus.log](https://github.com/MycroftAI/mycroft-core/files/5621447/bus.log)
[enclosure.log](https://github.com/MycroftAI/mycroft-core/files/5621448/enclosure.log)
[skills.log](https://github.com/MycroftAI/mycroft-core/files/5621449/skills.log)
[voice.log](https://github.com/MycroftAI/mycroft-core/files/5621450/voice.log)

![Screeeenshot3](https://user-images.githubusercontent.com/24827631/100719991-ab420c00-33bd-11eb-88da-bc1697705a71.png)
![Screenshot](https://user-images.githubusercontent.com/24827631/100719997-abdaa280-33bd-11eb-93a5-729cc4574ad1.png)
![Screenshot2](https://user-images.githubusercontent.com/24827631/100719999-ac733900-33bd-11eb-89ec-fd8c429b0729.png)

**Environment (please complete the following information):**
 - Device type: Desktop
 - OS: Manjaro
 - Mycroft-core version: 20.08.0

**Additional context**
I used to see the same problem with the AUR-package and the official Manjaro package. Reported the error there too, but as it happens with the git installation method too, I report it here too.

**Comment by goldyfruit** [comment]
Did you install it as `root` or as a simple user?

In you `bus.log` I can see some `permission denied`.
```
PermissionError: [Errno 13] Permission denied: '/tmp/mycroft/service.pid'
```

**Comment by JackPala** [comment]
I had the same issue, I did a chmod -R 777 on the directory that contains the files in question, this is certainly not the best way, but it worked for me

**Comment by 1Maxnet1** [comment]
> Did you install it as `root` or as a simple user?
> 
> In you `bus.log` I can see some `permission denied`.
> 
> ```
> PermissionError: [Errno 13] Permission denied: '/tmp/mycroft/service.pid'
> ```

How to install as root or user ? I did simply run the commands as they are described in the readme. So I guess as user, not as root, although it asked for my password in the installation script.

**Comment by ivvil** [comment]
> How to install as root or user?
I tried to run `bash dev_setup.sh` as root, but it error-ed saying that it shouldn't be run as root, I have the same problem with arch, and also had problems with the AUR package, maybe it left some files it doesn't like?

**Comment by goldyfruit** [comment]
Does you `/tmp` is mounted separately than `/`? If yes could you please paste the output of the command below?
```
$ mount | grep /tmp
```

**Comment by ivvil** [comment]
> Does you /tmp is mounted separately than /?

If you are asking if  I have a separate partition for `/tmp` no, i don't.

The output of `mount | grep /tmp`:
`tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=409600,inode64)`

**Comment by goldyfruit** [comment]
Are you able to create a directory in `/tmp` as a simple user?
```
$ mkdir /tmp/mycroft
$ touch /tmp/mycroft/service.pid
```

**Comment by ivvil** [comment]
The file `/tmp/mycroft` already exists in `/tmp` and also `/tmp/mycroft/service.pid` if i do `touch /tmp/mycroft/service.pid
` It gives me an error but the file already exists. I have tried to make `/tmp/test` and it works, it also lets me touch a file into it

**Comment by goldyfruit** [comment]
> The file `/tmp/mycroft` already exists in `/tmp` and also `/tmp/mycroft/service.pid` if i do `touch /tmp/mycroft/service.pid ` It gives me an error but the file already exists. I have tried to make `/tmp/test` and it works, it also lets me touch a file into it

Could you please paste the output of this:
```
$ ls -ld /tmp/mycroft
```

**Comment by ivvil** [comment]
Restarting now fixed it, maybe the /tmp files where left from the AUR installation and the new installation couldn't erase them?

**Comment by goldyfruit** [comment]
Yeah that was my though, that `/tmp/mycroft` was created by `root`, during the reboot `/tmp` is flushed so the directory and the rest of the files have been cleared.

**Comment by ChanceNCounter** [comment]
Couple clarifying questions, as I'm a Manjaro user and I see this is still open. It's not a direct comparison, though, because my build almost certainly predates yours.

@1Maxnet1 @JackPala had you guys also tried the Manjaro or AUR packages first, before doing a git install? Both of those packages are unreliable, and the Manjaro package has never worked; they don't come from MycroftAI. I wouldn't be surprised if they left artifacts.

**Comment by 1Maxnet1** [comment]
> Couple clarifying questions, as I'm a Manjaro user and I see this is still open. It's not a direct comparison, though, because my build almost certainly predates yours.
> 
> @1Maxnet1 @JackPala had you guys also tried the Manjaro or AUR packages first, before doing a git install? Both of those packages are unreliable, and the Manjaro package has never worked; they don't come from MycroftAI. I wouldn't be surprised if they left artifacts.

Yes i tried the packages. Manjaro as well as AUR. Can I somehow clear the artifacts?

**Comment by ChanceNCounter** [comment]
Well, to judge by the above logs, I'd make sure `/tmp/mycroft` and `/var/tmp/mycroft*` are all gone. Also `/var/log/mycroft` and `/opt/mycroft/` for good measure. I don't know off-hand what else those packages might have created that would interfere with a git install, but future error messages will tell.

**Comment by 1Maxnet1** [comment]
> Well, to judge by the above logs, I'd make sure `/tmp/mycroft` and `/var/tmp/mycroft*` are all gone. Also `/var/log/mycroft` and `/opt/mycroft/` for good measure. I don't know off-hand what else those packages might have created that would interfere with a git install, but future error messages will tell.

I deleted all those directories and files, you mentioned, but but the situation did not changed, same things are happening when running mycroft.

```
$ ./start-mycroft.sh debug
Hinweis: Es wird davon abgeraten zu Pullen, ohne anzugeben, wie mit abweichenden
Hinweis: Branches umgegangen werden soll. Sie können diese Nachricht unterdrücken,
Hinweis: indem Sie einen der folgenden Befehle ausführen, bevor der nächste Pull
Hinweis: ausgeführt wird:
Hinweis: 
Hinweis:   git config pull.rebase false  # Merge (Standard-Strategie)
Hinweis:   git config pull.rebase true   # Rebase
Hinweis:   git config pull.ff only       # ausschließlich Vorspulen
Hinweis: 
Hinweis: Sie können statt "git config" auch "git config --global" nutzen, um
Hinweis: einen Standard für alle Repositories festzulegen. Sie können auch die
Hinweis: Option --rebase, --no-rebase oder --ff-only auf der Kommandozeile nutzen,
Hinweis: um das konfigurierte Standardverhalten pro Aufruf zu überschreiben.
Bereits aktuell.
Starting all mycroft-core services
Initializing...
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting background service audio
Starting background service voice
Starting background service enclosure
Starting cli
2021-02-24 14:33:```01.759 | ERROR    | 46775 | mycroft.configuration.config:__init__:146 | RequestException fetching remote location: 
2021-02-24 14:33:01.788 | ERROR    | 46775 | mycroft.configuration.config:__init__:166 | Failed to fetch remote configuration: AttributeError("'str' object has no attribute 'items'")
Traceback (most recent call last):
  File "/home/maxb/mycroft-core/mycroft/configuration/config.py", line 155, in __init__
    translate_remote(config, setting)
  File "/home/maxb/mycroft-core/mycroft/configuration/config.py", line 50, in translate_remote
    for k, v in setting.items():
AttributeError: 'str' object has no attribute 'items'
2021-02-24 14:33:01.878 | WARNING  | 46775 | mycroft.util.file_utils:ensure_directory_exists:252 | Failed to create: /tmp/mycroft/ipc
2021-02-24 14:33:01.879 | INFO     | 46775 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
```

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
