### ISSUE TITLE
Space in Folder name: warning when starting mycroft-core

### ISSUE THREAD

**Issue by Jomosoto** [MycroftAI/mycroft-core#2789]
**Describe the bug**
When I start mycroft-core with "bash start-mycroft.sh", I get a warning that the folder "home/pi/Programm" doesn't exists and mycroft isn't startet. The folder is actually named: "Programm Daten". It seems like spaces in folder names cause problems.

![grafik](https://user-images.githubusercontent.com/40580158/103411831-5b986100-4b72-11eb-8a7a-90a43f7ecab1.png)

**To Reproduce**
1. Install mycroft core in a path, that contains a folder with a space in the name
2. Make the setup with "bash dev_setup.sh"
3. Start mycroft-core with "bash start-mycroft.sh"
4. Get the Warning. (See screenshot)

**Expected behavior**
Mycroft should start without this warning.

**Environment (please complete the following information):**
 - Device type: Raspberry Pi 3 B+
 - OS: Raspberry Pi OS (02.12.2020)
 - Mycroft-core version: 20.8.0

**Comment by forslund** [comment]
Thanks for reporting this. I think the issue you're seeing will be resolved when PR #2686 is merged. it contains a fix making sure the path on this line is handled correctly.

**Comment by mark-z-r** [comment]
@Jomosoto, PR #2686 has been merged, is this still happening.

**Comment by forslund** [comment]
Since a fix for this has been merged and there's been no reply for over a week I'm closing this issue. If there's still a problem please reopen the issue. Thanks!
