### ISSUE TITLE
Allow skills to send more information than the utterance to the messagebus

### ISSUE THREAD

**Issue by joshymcd** [MycroftAI/mycroft-core#279]
Currently skills send their 'utterance' to the message bus but with no extra information.
there should be a way to allow skills to send extra information so custom UI's can display the data whichever way it feels fit.
e.g the wiki skill should/could be able to send the URL to the wiki page it is getting its information from:
`{'Title': 'Ubuntu (operating system)', 'URL': 'https://en.wikipedia.org/wiki/Ubuntu_(operating_system)'}`
or the weather skill should be able to send structured information e.g 
`{'High': 30, 'Low': '20', 'Unit': 'Celsius' }`

**Comment by joshymcd** [comment]
Created PR #280 for this issue

**Comment by krisgesling** [comment]
Closing very old issue.

Worth noting, we now have a defined range of [Message types](https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-types#) along with the ability for custom messages namespaced to the Skill. 

This also ties into the new GUI framework.
