### ISSUE TITLE
Add Filesystem docstrings to docs build

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2798]
**Is your feature request related to a problem? Please describe.**
Currently our technical documentation for the `MycroftSkill` class includes very limited documentation for `self.file_system`:
https://mycroft-core.readthedocs.io/en/master/source/mycroft.html#mycroft.MycroftSkill.file_system

This makes it harder to discover and understand - even knowing it's there I struggle to find it sometimes.

**Describe the solution you'd like**
The docstrings in the [Filesystem class](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/filesystem/__init__.py) actually already exist just need to add these to the export.

**Comment by forslund** [comment]
Closing this since #2805 has been merged
