### ISSUE TITLE
Fallback skills v2

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-core#2806]
This is more of an initial discussion.

## Background
The intent service is currently parsing a list of different sources to determine a handler of the intent. The standard way it's handled is that the individual service return a match tuple which is then used at the end of `handle_utterance()` to trigger the specific intent handler. This is what `AdaptService` and `PadataiousService`. However Fallback can't currently follow this structure since it will execute the fallback handler if it can, making it an odd little duckling.

## Suggestion
I suggest a "FallbackSkillV2" class which has the fallback check and execution split up:

```python
class FallbackSkillV2:
    def can_answer(self, utterance, lang):
        """Check if the skill can answer the particular question.


        Arguments:
            utterance (str): text to parse
            lang (str) : lang code
        Returns:
            (bool) True if skill can handle the query
        """

    def answer(self, utterance, lang):
        """Performs the actual skill actions such as speak the answer."""
```

The skill would still have a priority to select between multiple matching fallbacks.

Both the `can_answer()` and `answer()` methods would be registered to be called over the message bus. (some code in the baseclass or a decorator would make these automatic similar to the intent_handler decorator)

So the `FallbackService` would send out a message and all fallbacks would answer whether they can answer the utterance, the best answer would be returned to the `IntentService`. The intent service would then if Adapt or Padatious couldn't answer the query use the skill reported by the `FallbackService`.

## Pros for this approach
- Makes it possible to do the fallback checks in parallell
- Will work in the same way as the other intent services
- Can simplify the `handle_utterance()` method
- Makes it possible to encapsulate Fallback skills in a separate process if we in the future wants to utilize cgroups, filesystem permissions, etc per skill.
- Would be needed for a disambiguation system

## Cons
- Not at all compatible with the current fallback system and would have to live in parallell with the existing approach making the code slightly more complex for a time.

Edit: After @JarbasAI suggestion this could probably be made backwards compatible.

**Comment by JarbasAl** [comment]
this sounds like duplicating common query logic.

i would say instead of returning a confidence the skill just returns True or False, and selection is still made by using the priority mechanism

this also makes it backwards compat in a way, if we make the default return True (can answer) then old skills just keep on working.

**Comment by forslund** [comment]
Yes, we could definitely go with just having a true / false answer. I did intend to keep the priority concept, will add that in clear text. The confidence was mainly an idea to replace the common query skill with a native system. but I'll scale that back to True / False

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
