### ISSUE TITLE
Add a global method to cancel all interactive / non interactive dialogs

### ISSUE THREAD

**Issue by AIIX** [MycroftAI/mycroft-core#2810]
**Is your feature request related to a problem? Please describe.**
There seems to be no method available for cancelling a non interactive dialog self.dialog or interactive dialog self.get_response or self.ask_yesno dialog

Case problem scenario:
- A page is displayed with information that users can interact with via button or speech, 
- The interaction leads to displaying another non related information page by the skill 
- In speech interaction context a skill author can ask for a response via self.get_response or any other interactive method, on receiving input from the user the author will display a second page. 
- On gui button interaction if a user clicks the button before the self.get_response method is completed the second page is displayed, but here the self.get_response method from the previous intent/interaction/page is still active and is being spoken on a totally new page with no way available to cancel the previous interaction. 

**Describe the solution you'd like**
Allow skill authors to decide when they would like the speech interaction and spoken dialogs to cancel programmatically via following methods 
- self.cancel_all_dialogs() (which cancels any/all pending non spoken / being currently spoken  or interactive dialogs from the specific skill that requested them) 
- self.cancel_dialog("some-dialog")  (which cancels a specific dialog from the specific skill that requested it)

**Comment by JarbasAl** [comment]
the problems goes deeper than that, if you make an intent with an infinite loop and dont handle it in stop it will keep going forever, if you cancel a dialog and the intent just starts another one you still have a problem


i recall some bug reports with the fairy tale reading skill about this exact issue, mycroft needs a mechanism to kill execution of random arbitrary code from skills

check my solution here https://github.com/OpenVoiceOS/ovos_utils/pull/34

**Comment by krisgesling** [comment]
Hey, thanks for writing this up. Very much agree that it's something we need to address.

It seems like there may be two sides of this that we may want to handle separately - the audible speech output, and the Skill process. From that come a range of possible user stories:
1. As a User, I can interrupt what Mycroft is saying. 
    - In this all I care about is stopping the audible speech output, so that I can speak another utterance, or just stop Mycroft talking.
2. As a User, I can stop a Skill from continuing what it's doing.
3. As a Skill Developer, I can stop dialog being spoken that was initiated by my Skill. 
4. As a Skill Developer, I can prevent Mycroft speaking while my Skill is active.
    - This one will need some discussion - it feels like there are likely negative consequences here - eg what about reminder notifications.
5. As a Skill Developer, I can kill an existing handler within my Skill.
    - This one feels strange, the existence of this issue probably points to a different problem. Eg we fixed the Fairy Tale Skill so users could say stop and it would end after that sentence. 
6. As a Release Manager, I can stop the execution of any Skill.
    - Under what conditions? 
7. As a Release Manager, I can set a maximum allowable execution time for intents, at which point the process will be stopped.  

Interested to hear your thoughts, or whether this is veering off into a completely different direction.

**Comment by AIIX** [comment]
> * As a Skill Developer, I can stop dialog being spoken that was initiated by my Skill.
> 
> * As a Skill Developer, I can prevent Mycroft speaking while my Skill is active.
>   
>   * This one will need some discussion - it feels like there are likely negative consequences here - eg what about reminder notifications.
> 
> * As a Skill Developer, I can kill an existing handler within my Skill.
>   
>   * This one feels strange, the existence of this issue probably points to a different problem. Eg we fixed the Fairy Tale Skill so users could say stop and it would end after that sentence.

I think this issue does cover at least some scenarios above, but I would like to stress immediately on the GUI direction/side because as a skill developer working on implementing both GUI and VUI I find that without having those methods available it becomes very difficult to develop a consistent experience and sync where authors can programmatically stop dialogs and speech when pages change or new content is displayed.

Rest of the user stories make sense, but they could be probably solved separately because they touch different cases.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
