### ISSUE TITLE
Allow overridden converse methods to accept emitted messages

### ISSUE THREAD

**Issue by NeonAndrii** [MycroftAI/mycroft-core#2812]
**Is your feature request related to a problem? Please describe.**
Passing a message to converse() would make it possible to contribute more complex skills to the project (sometimes, raw utterances are not enough). This changes cannot be simply implementer in an overridden skill converse() since this method is called by the SkillManager.

**Describe the solution you'd like**
In SkillManager.handle_converse_request(), add a function signature check to pass either an overridden converse or the default one.

**Describe alternatives you've considered**
Digging through the message stack directly in skill.converse() but that requires more complex changes.

**Additional context**
This feature is awaiting for a PR review.

**Comment by JarbasAl** [comment]
this is a good addition, it will also be useful to add converse support for the [HiveMind](https://github.com/JarbasHiveMind)

**Comment by NeonDaniel** [comment]
This also allows converse methods to utilize message context the same way a matched intent would, i.e. a skill method called on intent match can be called in the same way from converse.

**Comment by ChanceNCounter** [comment]
> a skill method called on intent match can be called in the same way from converse.

Welcome addition indeed.

**Comment by krisgesling** [comment]
Hey there, sounds like there's already a bit of interest here. 

I'm interested in the use case you have for it. Can you describe a little more how it would be used?

**Comment by JarbasAl** [comment]
the message object can contain arbitrary data, eg, using a hivemind bridge might for example include username or email, or info about it having been translated, or any other kinda of user preference

instead of passing utterances, lang, pass the full data to converse

**Comment by krisgesling** [comment]
Yeah at the moment I'm struggling to come up with a reason why the whole message wasn't passed along to begin with. Seems much cleaner and easier...
