### ISSUE TITLE
The enclosure sometimes resets rather than talking

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#282]
I've encountered messages sent through the enclosure client to the Arduino in the reverse of the expected order. For instance, at times when talking multiple times rather than resetting when finished and talking immediately again for the next phrase to be spoken it sends the talk command _followed by_ the reset command. Two possible explanations follow:
- When writing to `/dev/ttyACM0` message sent close together get mixed up
- Since there are many asynchronous parts of the python code the `audio_output_end` event happens after the `audio_output_begin` of the next audio.

Edit: I've verified it is not the first proposed explanation as from the python end the `mouth.reset` and `mouth.talk` are often switched.

**Comment by aatchison** [comment]
This references another code base and is the enclosure client now behaves quite differently, including the addition of visemes.
