### ISSUE TITLE
Test environment/config for voight-kampff testunner

### ISSUE THREAD

**Issue by J-Priebe** [MycroftAI/mycroft-core#2833]
**Is your feature request related to a problem? Please describe.**
It should be possible to write tests for skills with persistent state (in particular, a database) in a dedicated test environment. To the best of my knowledge after some poking around, there is no tell within a skill that it is being run in a test. Per #2633 it should soon be possible to override specific skill settings within a specific test, but IMO:
- The appropriate usage of #2633 is to test the skill's behavior as it is affected by different settings.
- It's both cumbersome and dangerous to mandate a "this is a test" step to each test, or risk messing up production data
- There should be a more fundamental overarching way to configure a skill for a test environment.

**Describe the solution you'd like**
A config file which specifically is only applied during tests. Long term an environment a la `dotenv` or Django Settings that is conceptually distinct from config would be cool for more complex skills, but a very simple default `test.conf` file like
```
{
    "test": true,
    "tts": {
        "module": "dummy"
     }
}
```
would go a long way.

**Describe alternatives you've considered**
I haven't been able to find alternatives, short of simply omitting all but the most trivial tests from my db-backed skill. There seems to be relics of `test_envs` in the old intent-based testing module, but I can't find anything for vk.

**Additional context**
PR from ToDo skill where I initially ran into this issue:
https://github.com/MycroftAI/mycroft-skills/pull/1473

**Comment by krisgesling** [comment]
Thanks for writing this up James!

@chrisveilleux just making sure you see this.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
