### ISSUE TITLE
Suggestion: Semi-deprecate ask_yesno (retain it for backwards compat)

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/mycroft-core#2835]
Some confusion took place in chat due to the fact that `ask_yesno()` returns a string "yes" or "no", rather than a bool; this hit a skill dev working in German and was very disorienting for them.

From a language support perspective, I'm inclined to agree. The decision to return a string was before my time, but Ake suggests it was a consensus thing. Fair enough, but it's an idiosyncratic barrier for skill devs whose code targets a language other than English.

(Also, imo, most hardcoded confirmation prompts return bools, so this one should, too...)

Even in a major version, changing the return type of an outward-facing function would be unacceptable, but it's possible to shove it in a bool with a different name.

```python3
def ask_confirm(self, ...):
    ...
    return a_bool_if_you_please

def ask_yesno(self, ...):
    warn(DeprecationWarning("yadda yadda bool time, retained for backward compat"))
    return "yes" if self.ask_confirm(...) else "no"

**Comment by penrods** [comment]
Perhaps consider creating something like an Enum, e.g. Reply.YES and Reply.NO.  With a little bit of class magic you could probably override the __str__ and __eq__ methods to make it backwards compatible with older:

```
if ask_yesno(...) == "yes":
   do whatever
```

but encourage new development of:
```
if ask_yesno(...) == Reply.YES:
   do whatever
```

The ask_yesno() doesn't really work well with truly only returning Yes or No answers because humans aren't well behaved.  You get interactions like this:
```
MYCROFT:  Would you like ketchup on your burger?
HUMAN: Actually, make it a hotdog instead.
```

If that only returned YES/NO then you end up with a voice agent that says:
```
MYCROFT:  Would you like ketchup on your burger?
HUMAN: Actually, make it a hotdog instead.
MYCROFT:  I'm sorry, I didn't understand that.  Would you like ketchup on your burger?
HUMAN: I said a hotdog, you ninny.
MYCROFT:  I'm sorry, I didn't understand that.  Would you like ketchup on your burger?
HUMAN: <walks away muttering about stupid technology>
```

Making a function that implys there will always be one of exactly two responses leads developers into creating fragile interactions.

That's my $0.02, at least.

**Comment by krisgesling** [comment]
For me I think the difference here is whether you look at `ask_yesno()` as a "confirmation prompt". 

The `ask_yesno()` can be used more broadly as it returns either, "yes", "no" or the entire utterance. So in it's current form, it will always return a String. 

If anything I would want to extend it to return the utterance whether or not it detects a "yes/no" response. Could even return an object:
```
{
  "yes": Bool,
  "no": Bool,
  "utterance": Str
}
```

The benefit of having both the "yes/no" and the utterance is that we could handle more natural responses to those prompts like:
> Mycroft: "Do you want to install Dice Skill"
> User: "No, I meant the Mice Skill"

```
response = self.ask_yesno(dialog)
if response['yes']:
    self.perform_action()
else:
   new_action = self.parse_response(response['utterance'])
```


I can also see the benefit in an `ask_confirm()` that is focused on that specific use case when you just want to confirm something or not.

**Comment by krisgesling** [comment]
lol beat me to it Steve!

**Comment by JarbasAl** [comment]
`get_response` is meant for the general use case, `ask_yesno` has always (AFAIK) been meant for confirmation , and there is also `ask_selection`. so while i agree with @penrods rationale, that kind of usage is just a mistake from the skill developer. 

also note there are actually 3 return values, `"yes", "no", None`

```python
result = self.ask_yesno(...)
if result is None:
    # here you should handle the use case pointed out by steve-penrod
    pass
elif result == "yes":
    pass
elif result == "no":
    pass
```

a good skill will check for `None` and handle it gracefully (user didnt answer / said something unexpected), `"yes"` and `"no"` mean exactly that, user agreed or disagreed with prompt.

My suggestion is to simply make this `True`/`False`/`None`, the strings are the messy non obvious part.

This will also simplify the logic in the cases where False/None do not need to be differentiated 

```python
if self.ask_yesno(...):
    pass
else:
    pass
```

**Comment by krisgesling** [comment]
Yeah your right sorry, `None` is also a return value. So really it is:
- `"yes"` - vocab matched with `yes.voc`
- `"no"` - vocab matched with `no.voc`
- `utterance` - user responded but no yes or no found
- `None` - user did not respond

**Comment by JarbasAl** [comment]
PR opened, i went with @ChanceNCounter suggestion, but did not deprecate the old ask_yesno

Returning the full utterance can be very useful to avoid a follow up call to get_response, so i think it makes sense to have a different method for the boolean use case.

But maybe this issue could stay open to discuss a refactoring of ask_yesno, it still doesn't feel right to return the english strings. I'm inclined to go with @penrods suggestions of an Enum and some subclassing magic to make it backwards compatible. 

NOTE: you can subclass an enum from str, but str needs to come first!
```python
class UserReply(str, Enum):
    YES = "yes"
    NO = "no"
```
handling of None and user utterances doesn't quite fit this paradigm either, but comparisons with the Enum would still work

```python
result = self.ask_yesno(...)
if result == UserReply.YES:
    pass
elif result == UserReply.NO:
    pass
else:
    # here you should handle the use case pointed out by steve-penrod
    pass
```

**Comment by krisgesling** [comment]
Hey thanks for that.

For my own learning, I'm interested in the benefits of the Enum here. Why is it better than a simple String in this context?

I guess it enforces some consistency that might reduce errors down the road.

Is it that a string of "yes" is easy to interpret as "the human being verbally responded with 'yes'", whilst the Enum is clearly a representation in code, even though it's still in English?

Or that you can more easily override the `UserReply` class with a localized variant?

**Comment by penrods** [comment]
Yep, you got it.  It is to make it clear that the response UserReply.YES or UserReply.NO is the same in every language.    A German programmer might wonder if they should write `if self.ask_yesno() == "ja"` when the want to support a non-English language.  The enum reinforces that it isn't really a literal "yes" string.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
