### ISSUE TITLE
mycroft: setup.py, mycroft.service,mycroft-cli-client and everything else is a dumpster fire

### ISSUE THREAD

**Issue by warw1zard** [MycroftAI/mycroft-core#2836]
**Describe the bug**
trying to setup mycroftAI brings up bug after bug after bug
`mycroft-cli-client` has a` RuntimeError: Unable to release an unacquired lock`
`mycroft.service` `chef : a password is required ; TTY=unknown ; PWD=/home/chef/mycroft-core ; USER=root ; COMMAND=/bin/true`

**To Reproduce**
the linux machine is a lenovo laptop running linux mint 20 has was installed on january of 2021 (kind of a fresh install as of febuary)
i downloaded the source from your github and tried running `setup.py` from the `terminal` first as a normal user, then tried `root`. to no avail
put `mycroft.service` in its folder where your "run mycroft on boot" document told me to put it, ran it, let it do its thing only to find out these errors when checking status
i had my IT son help me install and setup the program

**Expected behavior**
setup should work properly/normal as expected and allow you to set it up
`mycroft.service` should do as intended and allow you to use mycroft with no problems
mycroft should ask for password when required
my son should be happy that it works and not having 13 year old psychological distress over helping his father set it up (had to give him a break in order to make sure he doesn't instantly `kernel panic`) 

**Log files**
log file from voice.log  [voice.log](https://github.com/MycroftAI/mycroft-core/files/5969002/voice.log)
log file from enclosure.log [enclosure.log](https://github.com/MycroftAI/mycroft-core/files/5968956/enclosure.log)
log file from skills.log [skills.log](https://github.com/MycroftAI/mycroft-core/files/5968960/skills.log)
log file from bus.log [bus.log](https://github.com/MycroftAI/mycroft-core/files/5968992/bus.log)
log file from audio.log [audio.log](https://github.com/MycroftAI/mycroft-core/files/5968998/audio.log)
trying to execute setup.py[setup python.txt](https://github.com/MycroftAI/mycroft-core/files/5969039/setup.python.txt)
starting the service needed for mycroft [service mycroft.txt](https://github.com/MycroftAI/mycroft-core/files/5969052/service.mycroft.txt)
trying out all of the other commands[other commands.txt](https://github.com/MycroftAI/mycroft-core/files/5969059/other.commands.txt)

**Environment:**
 - Device type: [lenovo ideapad 3, Intel© Pentium© CPU 6405U @ 2.40GHz × 2, 128.2 GB drive, 3.6 GiB ram]
 - OS: [Linux Mint 20 Cinnamon, cinnamon version 4.6.7, kernal 5.4.0-65-generic]
 - Mycroft-core version: [e.g. 20.08]
 - Other versions: [e.g. Adapt v0.3.7]

**Additional context**
pythons "os" libary nonexistant even though linux mint supports python

**Comment by krisgesling** [comment]
Hi there, 

As you've found, Mycroft is not setup well for non-development desktop purposes at the moment. The pull request I've linked above is intended to provide the ability to use `setup.py` in the way that most people would expect. 

Currently the recommended installation path for Linux is outlined here:
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/linux#installing-via-git-clone

**Comment by PureTryOut** [comment]
I agree, current setup ain't great. I'm working on fixing that though as Kris already mentioned :wink: 
Once the linked PR is merged, `python3 setup.py install` will do as expected.

As for `mycroft.service` (for anyone else looking, found [here](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/linux#start-mycroft-on-boot), that seems to be Picroft specific. It will at least need some modifying once my PR is in, I'll make sure to make the relevant documentation changes.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
