### ISSUE TITLE
A Skills stop method should not be called after shutdown

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2846]
**Is your feature request related to a problem? Please describe.**
Currently, when a Skill is shutting down it calls the `shutdown()` method, and then the `stop()` method. 

The `stop()` method is intended to stop actions being performed by the Skill, and will be called if a user says "Hey Mycroft, stop". Hence it likely relies upon the Skill itself to execute properly. 

Good example is closing closing DB connections. The `shutdown` method is the logical place for this, however if the stop method relies on that connection, it will fail when called after shutdown.

**Describe the solution you'd like**
At the very least `stop()` should probably get called before `shutdown()`, rather than after.

However I can imagine scenarios where you don't want the action to stop just because the Skill is shutting down. I wonder if we should not call `stop` at all during Skill shutdown and leave it up to the Skill to call `stop()` in their `shutdown()` method if that's the behaviour they want?

**Additional context**
[Raised in Chat here.](https://chat.mycroft.ai/community/pl/jtqwzqc1s3ghpj677papwbznmy)

@penrods - pinging for your advice given this may have been done intentionally for a reason.

**Comment by forslund** [comment]
The point in doing the user shutdown first in the `default_shutdown()` is to make sure it has access to all events, settings etc. that the skill creator has setup. I.E, it's in full normal run state. After the default shutdown code is run to safely remove all things that are setup in the background.

The stop is however questionable, I think the idea of calling the stop method is that the `stop()` method is implemented more often than the `shutdown()` to gracefully stop skill operation. `shutdown()` should only need to be implemented _if_ there are long term processes / states that need to be taken care of.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
