### ISSUE TITLE
Consistently update configuration attributes in all services

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2859]
**Is your feature request related to a problem? Please describe.**
Currently different parts of mycroft-core utilize the Mycroft configuration in different ways. Many classes are not setup to cleanly and automatically update when a configuration change is made. This can cause many things not to behave as expected. 

**Describe the solution you'd like**
There should be a common and consistent method for consuming the configuration, as well as doing anything necessary to utilize a modified configuration.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
