### ISSUE TITLE
"Hey MyCroft" used instead of alternate wake word selected

### ISSUE THREAD

**Issue by chrisamow** [MycroftAI/mycroft-core#2864]
**Describe the bug**
"Hey Jarvis" was selected as the wake word during device pairing
Device only responds to "Hey MyCroft"

**To Reproduce**
Run the docker version of MyCroft on linux mint
Pair the device and select "Hey Jarvis" as the wake word
Speak "Hey Jarvis" nothing happens
Speak "Hey MyCroft"  "Who was Abraham Lincoln?" - the device speaks/reads the response

**Expected behavior**
I expect "Hey Jarvis" to initiate recognition the way "Hey MyCroft" does

**Log files**
I'm not home right now, but I can submit these later if helpful.

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: [e.g. Raspberry Pi, Mark 1, desktop]
 - OS: [e.g. Ubuntu, Picroft]
 - Mycroft-core version: [e.g. 20.08]
 - Other versions: [e.g. Adapt v0.3.7]

**Additional context**

Please think carefully about whether you have modified anything in Mycroft's code or configuration files.  If so, can you reproduce this on a clean installation of Mycroft? Many "bugs" turn out to be non-standard configuration errors.

**Comment by krisgesling** [comment]
Hey there, thanks for flagging this. I'm assuming you are using a Mark II Dev Kit?

If so it will be fixed by https://github.com/MycroftAI/mycroft-core/pull/2861

**Comment by chrisamow** [comment]
> Hey there, thanks for flagging this. I'm assuming you are using a Mark II Dev Kit?
> 
> If so it will be fixed by #2861

Hi Kris - thanks for following up.  It is using the docker image on linux mint - I guessed that it wouldn't only affect docker though - that does sound similar to that PR...

**Comment by krisgesling** [comment]
Hmmm, the specific issue there is that a hotword configuration exists in `/etc/mycroft/mycroft.conf` which overrides the remote configuration from home.mycroft.ai

So have a look for that, it will be something like:
```
  "listener": {
    "wake_word": "hey mycroft"
  },
```

If that's not there, then it's a different issue

**Comment by chrisamow** [comment]
oh, running a shell on the mycroft docker instance...  there is not even a /etc/mycroft/ directory
there is one at /opt/mycroft/mycroft/configuration/mycroft.conf
but I'm not sure if that is active - that entry above is in there along with a bunch of other listener configuration

**Comment by krisgesling** [comment]
That's the default entry. There are four levels that you can read more on here:
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/mycroft-conf

The other override is the user config at `~/.mycroft/mycroft.conf`

Is this the [docker-mycroft container](https://github.com/MycroftAI/docker-mycroft) on DockerHub?

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
