### ISSUE TITLE
Extract STT and TTS base classes to packaged modules

### ISSUE THREAD

**Issue by NeonDaniel** [MycroftAI/mycroft-core#2874]
**Is your feature request related to a problem? Please describe.**
STT and TTS plugins currently override base classes in `mycroft-core`. This requires plugins to be developed and used in an environment that includes all of `mycroft-core` and makes it more difficult to unit test plugins during development. This is a feature request that helps plugin developers better test STT/TTS engines available for use with `mycroft-core`

**Describe the solution you'd like**
Extracting the base classes to separate modules would allow them to be imported individually in plugin classes. Configuration could be passed when objects are created or else read from default locations.

**Describe alternatives you've considered**
There is currently support for this via ovos_utils (https://github.com/OpenVoiceOS/ovos_utils/blob/dev/ovos_utils/plugins/stt.py). Integrating this or something equivalent into the official Mycroft Core would allow developers to utilize an imported STT/TTS base class without worrying about future compatibility with mycroft core changes.

**Additional context**
This would be a similar concept as is being looked at for the messagebus-client here: #2863

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
