### ISSUE TITLE
mycroft.conf silently overwritten

### ISSUE THREAD

**Issue by david-morris** [MycroftAI/mycroft-core#2880]
**Describe the bug**
When there's an error in mycroft.conf, it is silently overwritten.  This is bad because user settings should not be permanently deleted without consent. Instead, logs and/or the output of mycroft-start should show the error.

**To Reproduce**
Try the following mycroft.conf:
```
{
  "max_allowed_core_version": 20.8,
  "listener": {
    "wake_word": "Lazarus",
    "device_name": "default"
    "energy_ratio": 1.5
  },
  "hotwords": {
    "Lazarus": {
      "module": "pocketsphinx",
      "phonemes": "L AE Z ER AH S .",
    }
  }
}
```

Note the missing comma after "default" and incorrect use of the energy ratio parameter.

After running mycroft-start restart all, it is overwritten with the following:

```
{
  "max_allowed_core_version": 20.8
}
```

**Expected behavior**
One of the following:
"Mycroft failed to start because of an error in mycroft.conf."

or

The config file is copied to `mycroft.conf.old` (or `mycroft.conf.old.1`, etc.) and `mycroft.conf` is overwritten with the following:
```
# The previous mycroft.conf contained errors and was moved to mycroft.conf.old.
{
  "max_allowed_core_version": 20.8
}
```

**Comment by david-morris** [comment]
Unable to reproduce.

**Comment by david-morris** [comment]
I can't reproduce this with the given steps, but it keeps happening.  I don't think I understand what is causing this.

**Comment by ChanceNCounter** [comment]
What platform are you running/how did you install?

**Comment by david-morris** [comment]
I am running on lubuntu; I installed by cloning into the repo and building (on master, not dev).

**Comment by el-tocino** [comment]
Which mycroft.conf did you adjust?  Was this before or after pairing?

**Comment by forslund** [comment]
This can occur if the json in the config file is invalid. If that's the case it will be read as if empty and when the version skill writes it's info it will be overwritten without the original content

**Comment by krisgesling** [comment]
It's strongly recommended to use `mycroft-config edit user` rather than directly editing the file. This will validate your json when you save and exit thereby catching any errors. 

But would be better if we didn't nuke someones config if they do edit it directly and have an error as many people do this.

**Comment by david-morris** [comment]
I'll start doing that, thanks. I had no idea, since I had scrolled past the part of the wake word article where it mentioned `mycroft-config edit user`.

Maybe it it would be a good idea to add that tip (with the reasoning that it will validate the json) as a comment to the top of the config file?

I also agree that it would be better not to nuke the config. Editors are always a charged subject.

**Comment by forslund** [comment]
PR #2881 should handle the case with ill-formatted json

**Comment by sparky-vision** [comment]
> It's strongly recommended to use `mycroft-config edit user` rather than directly editing the file. This will validate your json when you save and exit thereby catching any errors.
> 
> But would be better if we didn't nuke someones config if they do edit it directly and have an error as many people do this.

I recently ran into this bug, but I _was_ using mycroft-config edit user. It somehow validated and _then_ overwrote.

I wish I knew how to reproduce that, because I'm sure it would be fantastically useful. But I can report - anecdotally - that it did do the validation and saved the file, then overwrote part of it. (It left part of a chunk.)
