### ISSUE TITLE
Padatious Entity files not respected

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2885]
**Describe the bug**
Registering an entity file for a padatious intent does not seem to restrict the entities that will be accepted

**To Reproduce**
1. Install this test Skill: https://github.com/krisgesling/test-padatious-entity-files-skill
2. Say "test the red entity file" > should respond "detected red"
3. Say "test the wrong entity file" > will respond "detected wrong" however "wrong" is not included in the `type.entity` file.

**Expected behavior**
If an entity file has been registered, Padatious intents should only match if a known entity is present.

**Context**
Filing in mycroft-core as I don't believe Padatious has been updated in a long time so assuming the issue may be related to a more recent change in core.

EDIT: Please double check my example Skills code to make sure this is a genuine issue.

**Comment by emphasize** [comment]
cant reproduce (updated dev). Localized the skill to de-de
12:34:14.851 | INFO     |  3126 | TestPadatiousEntityFiles | {'type': 'rote', 'utterance': 'teste die rote entity datei'}
-- Gefunden rote

**Comment by krisgesling** [comment]
My bad - the `initialize()` method is misspelled meaning it never gets called and doesn't register the entity file...

Sorry all!
