### ISSUE TITLE
Adding last spoken sentence

### ISSUE THREAD

**Issue by hanzala123** [MycroftAI/mycroft-core#2889]
I made an assistant using aiml and now i have switched to mycroft. However one feature i miss is the ability to re speak what was said last. This is a very useful feature especially when one is using headphones or is busy doing something else and missed what was said.

i used a variable in the txt2wav.py file called prevline which stores the last sentence.

**Comment by ChanceNCounter** [comment]
This isn't on the marketplace yet, but you can install it with msm:

https://github.com/MycroftAI/skill-repeat-interactions

**Comment by JarbasAl** [comment]
alternatively

https://github.com/JarbasSkills/skill-parrot

**Comment by hanzala123** [comment]
Thank you so much 
@ChanceNCounter  and @JarbasAl

**Comment by hanzala123** [comment]
@ChanceNCounter  i was trying to install the skills with msm but couldn't. Either no match or too many matches. Could you help me with the exact command

**Comment by ChanceNCounter** [comment]
`msm install [full url to git repository]` should do it. Make sure you copy and paste the link, and not its name. Just the name only works when the skill is published.

**Comment by hanzala123** [comment]
@ChanceNCounter thank you
