### ISSUE TITLE
Create consistent and universal skill_name and skill_id

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2891]
**Is your feature request related to a problem? Please describe.**
There are currently multiple ways that a single Skill is referred to eg HelloWorldSkill vs hello-world-skill vs hello-world-skill.mycroftai etc.

This has been discussed in multiple places but I couldn't see an open issue for it. Here is a placeholder and coming together point which can also link to items being blocked by the need for this to be resolved.

**Describe the solution you'd like**
_Add detail_

**Describe alternatives you've considered**
_Add detail_

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
