### ISSUE TITLE
Move nice_duration completely to Lingua Franca

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2896]
**Context**
This is a companion issue to:
https://github.com/MycroftAI/lingua-franca/issues/26

The issue got raised again in:
https://github.com/MycroftAI/mycroft-core/pull/2890

**Description**
Currently mycroft-core has it's own version of `nice_duration()` that is not fully compatible with the version in Lingua Franca (LF). It is even importing a private LF method in order to implement it's modified `nice_duration()`.
`nice_duration_dt()` doesn't exist in LF.

These should be removed from mycroft-core in favour of Lingua Franca's implementation. This may require updates to LF, and/or deprecation of the current method signature in core.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
