### ISSUE TITLE
USB Microphone does not work after removing and reattaching

### ISSUE THREAD

**Issue by AZAZ78** [MycroftAI/mycroft-core#2904]
**Describe the bug**
I use a Jabra USB Microphone/Speaker combi at a Picroft. If i remove the USB device and attach it again it does not work until i restart Mycroft services.

**To Reproduce**
1. Set up a working Picorft installation with a USB Mic/Speaker
2. Remove the USB device
3. Reattach again
4. Nothing is recognized any more

**Expected behavior**
It continues working like before.

**Log files**
No logs

**Environment (please complete the following information):**
 - Device type: Raspberry Pi 4
 - OS: Picroft
 - Mycroft-core version: 20.08
 
**Additional context**
no additional data

**Comment by krisgesling** [comment]
Hi Azaz, 

I'd take a guess that the Pulse configuration is pointing at a card number as these are assigned dynamically - hence when you remove the mic and plug it back in it can get a new card number. 

Have you tried specifying the Jabra as your input device by name as described here:
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/troubleshooting/audio-troubleshooting#specifying-an-input-device

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
