### ISSUE TITLE
msm_wrapper.py tries to "from msm import...", but msm is deprecated

### ISSUE THREAD

**Issue by yoe** [MycroftAI/mycroft-core#2911]
I'm working on packaging this code for Debian. As part of this, I'm looking at also packaging all the dependencies. I do this by iterating over

- Do an attempted build for mycroft-core (this fails because a python library is not available)
- Either install the library (if it exists), or whip up a package (by way of [dh-make](https://packages.debian.org/dh-make) ), and install that
- Do another attempted build

etc, until it succeeds.

I've now reached the point where it tries to run something that imports `mycroft/skills/msm_wrapper.py`, which contains

    from msm import MycroftSkillsManager, SkillRepo

which requires the "msm" module from https://github.com/MycroftAI/msm -- but that redirects to signify that the package is now deprecated, and there is an "about" message to that extent, too.

While it's possible to package deprecated code, I would prefer not to do that if at all possible. As such, it would be nice if mycroft-core were to either stop trying to import from the deprecated module, or if it were modified so that at least msm_wrapper won't fail if the module is not available.

**Comment by ChanceNCounter** [comment]
Hi. I am a community member whose opinions do not represent anyone else's positions. Please do not package Mycroft. There are a ton of community packages and they are all abandonware. People install them thinking they're official, or at least up to date, and then they come to chat and get angry at MycroftAI and the community for something we can't fix.

**Comment by ChanceNCounter** [comment]
I shouldn't say "all." The Alpine package's maintainer is active. But the AUR package, the Manjaro package, a number of abortive containers floating around GitHub, and that's off the top of my head. Lots of angry would-be users.

**Comment by yoe** [comment]
You're assuming I'm going to package something and then abandon it. Ignoring the fact that that's pretty rude, I have a 20 year [track record](https://qa.debian.org/developer.php?login=wouter) in Debian that should hopefully show I'm not going to do that.

That being said, this issue is about mycroft-core using deprecated code. That issue stands. If you still think it should not be packaged given what I said above, can we discuss that somewhere more appropriate? Thanks.

**Comment by ChanceNCounter** [comment]
I'm sorry you took such immediate offense, but as for venue... whatever you say? This is the first place you've broached it where I've been subscribed. If you'd rather continue the discussion at the relevant channel on MycroftAI's Mattermost server, by all means, let's do that. Others will surely chime in.

**Comment by forslund** [comment]
@yoe The msm module is proveded by mycroft-skills-manager. On [pypi](https://pypi.org/project/msm/0.8.9/) and on [github](https://github.com/mycroftai/mycroft-skills-manager)

The repo you link is the old bash-based msm and not the python implementation.

**Comment by yoe** [comment]
Whoops, okay, that explains that :)

Thanks for clarifying.
