### ISSUE TITLE
source venv-activate.sh unable to run

### ISSUE THREAD

**Issue by Xanaxus** [MycroftAI/mycroft-core#2918]
**Describe the bug**
Expected end of the statement, but found an incomplete token

**To Reproduce**
1. Go to 'mycroft-core' file via terminal
2. run 'source venv-activate.sh'
```
source venv-activate.sh
venv-activate.sh (line 30): Expected end of the statement, but found an incomplete token
            "-q"|"--quiet" )
                           ^
from sourcing file venv-activate.sh
source: Error while reading file “venv-activate.sh”'
```
**Expected behavior**
execute the script

**Environment (please complete the following information):**
 - Device type: Laptop
 - OS: Manjaro KDE
 - Mycroft-core version: 21.2
 

**Additional context**

Please think carefully about whether you have modified anything in Mycroft's code or configuration files.  If so, can you reproduce this on a clean installation of Mycroft? Many "bugs" turn out to be non-standard configuration errors.

**Comment by krisgesling** [comment]
Hey there, 

Did you install Mycroft by cloning the repo or from somewhere else?

Can you run the following and post the output
```
cd mycroft-core
git status
```
This should confirm which branch your on and whether anything has been modified.

Failing that, what shell do you use - maybe it doesn't like case statements?

from mycroft-core directory you can also run:
```
source .venv/bin/activate
```

**Comment by forslund** [comment]
Also it may be interesting to know what shell you're running, eg. bash, zsh or something else. Can be found through `echo $SHELL`

**Comment by Xanaxus** [comment]
Hey it was an issue with the shell, I was using the FISH shell. 

This was the output of the git status
```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by forslund** [comment]
Fish handles things a bit differently than bash, sh and zsh I'm not sure we can make the file sourceable from fish. (My best guess from some quick googling).

The equivalent action of running `source venv-activate.sh` can be performed for fish using `source .venv/bin/activate.fish` alternatively there seem to be a fish plugin for sourcing bash files called bass that could be used....

more of work-arounds than solutions...we could add a venv-activate.fish for use with the fish shell...
