### ISSUE TITLE
Custom name

### ISSUE THREAD

**Issue by grepwood** [MycroftAI/mycroft-core#2919]
If I install mycroft on a device, I'd like to refer to it by a different name than Mycroft when talking to it.

Is that possible?

**Comment by penrods** [comment]
Possible?  Yes.  Easy?  No.

For now you would have to train your own machine learning model to recognize "Hey Bob" or whatever.  So unless you want to dig in to that, you'll have to live with "Hey Mycroft" for now.

**Comment by krisgesling** [comment]
Hey there, we have some documentation around this at:
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/wake-word

If you have recordings or are willing to put the work into collecting them (and provide them under an open license), then members of our community may be willing to train a wake word model for you:
https://community.mycroft.ai/t/custom-wakewords-r-us/7077
