### ISSUE TITLE
tts discarding path

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#2929]
the latest cache refactor introduced an issue in TTS handling, 

a file path is requested, but TTS engines return the path where the file was actually created, mycroft is discarding this path and using the originally requested path instead, meaning the file might not exist when playback starts

issue introduced in https://github.com/MycroftAI/mycroft-core/pull/2853

proposed fix: https://github.com/HelloChatterbox/HolmesV/pull/60

**Comment by krisgesling** [comment]
Yeah I can see the argument that the `get_tts()` method returns a file path, so why aren't we using it. However I'm also wondering why the TTS engine is writing the files to a different path than was requested?

This feels like it was an unintentional breaking change as we previously used the return path. Perhaps we revert to use the returned path, but deprecate it and switch to the requested path in the next major release. Unless there's a reason why each specific TTS engine needs to define where the files reside?
