### ISSUE TITLE
Remove configuration of TTS file extension

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2935]
**Is your feature request related to a problem? Please describe.**
TTS engines are currently configured to use a specific file extension. The only reason for this seems to be to determine which command should be used to play the file. If that's the case, we can detect it rather than have an extra configuration value.

This limits TTS engines to a single file type whilst some engines have an option for different types eg Polly.

**Describe the solution you'd like**
Rather than configure this and pass a value around, we should be able to detect the file type when we need to - ie when playing the audio file itself. 

The only exception would be if the file path does not include a file extension for some reason.

**Additional context**
Split from #2929

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
