### ISSUE TITLE
log files are bigger than 8MB

### ISSUE THREAD

**Issue by Olzeke51** [MycroftAI/mycroft-core#2941]
**Describe the bug**
my 'Skill.log is 11MB - 

**To Reproduce**
run your system for a long time ?? longer than 'latest' releases
.'

**Expected behavior**
I read somewhere that log files would be replaced at 8MB size

**Log files**  edited - added files July 04, 00:03 UTC
[big_files.tar.gz](https://github.com/MycroftAI/mycroft-core/files/6759194/big_files.tar.gz)

**Environment (please complete the following information):**
 - Device type: Mark ][ DEV-kit
 - OS: default Ubuntu
 - Mycroft-core version:21.02
 - Other versions: latest 07-03

**Additional context**
Correct me / close this if I am under the wrong conception/information

**Comment by PureTryOut** [comment]
There is nothing in MyCroft that removes/replaces/reduces those logs. There is just a single line in the startup script that makes logs go there, [clickety click](https://github.com/MycroftAI/mycroft-core/blob/dev/start-mycroft.sh#L141), and it only uses a simple shell redirection to do so.

**Comment by JarbasAl** [comment]
I've had a device run out of disk space because of this (id say it took at least 1 year, probably more)

I now rotate my logs https://github.com/OpenVoiceOS/ovos_utils/blob/dev/ovos_utils/log.py

**Comment by krisgesling** [comment]
yeah I'll at the very least add log rotation to the Mark II, but we should consider how this is handled universally

@PureTryOut as a distro manager, would your preference be for a central Mycroft policy or to handle it at the system level?

**Comment by PureTryOut** [comment]
For system services I'd expect the service manager to handle it. MyCroft however is not a system service, at least not on regular desktops, but a user service and at least for non-systemd systems there is no way to handle such things outside of the program. So my personal preference would be MyCroft handling it itself.

**Comment by ChanceNCounter** [comment]
https://docs.python.org/3/library/logging.handlers.html#baserotatinghandler?

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
