### ISSUE TITLE
Support for speech dispatcher as tts backend

### ISSUE THREAD

**Issue by lw64** [MycroftAI/mycroft-core#2953]

**Comment by krisgesling** [comment]
Hi there, support for SpdSay aka Speech Dispatcher is already available, checkout the docs here for details on how to configure Mycroft to use that for TTS:
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/tts-engine#spdsay

**Comment by lw64** [comment]
thank you.
