### ISSUE TITLE
Create .profile_mycroft in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by ajr-dev** [MycroftAI/mycroft-core#2969]
I have `$XDG_CONFIG_HOME` set to `$HOME/cloud/config` and I want `.profile_mycroft`to go in `$XDG_CONFIG_HOME/mycroft/profile` but it is created in the home directory instead. So I've changed it's location to the one I want, but as it says that the file may be replaced in future the reference I've written to it will miss any changes made to the file when it's generated in `$HOME` again.

**Comment by PureTryOut** [comment]
Note that #2802 is getting rid of that file completely, and it's part of a larger effort of mine to make the entirety of MyCroft follow the XDG Base Directory Specification.

**Comment by ajr-dev** [comment]
Oh, perfect.
