### ISSUE TITLE
Fail to install packages on arch

### ISSUE THREAD

**Issue by ajr-dev** [MycroftAI/mycroft-core#2973]
I had to replace `yes | sudo pacman -S ...` for `sudo pacman -S --noconfirm --needed`. Because it was failing to install the packages on arch linux.

**Comment by krisgesling** [comment]
Hey there, can I check where you are referring to?

Our `dev_setup.sh` already seems to be using those two flags: 
https://github.com/MycroftAI/mycroft-core/blob/61cbaa71cddba2547682a3eb84bb715abf24e517/dev_setup.sh#L374

**Comment by ajr-dev** [comment]
Sorry, it was this was on the gui.
