### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Arndorferd** [MycroftAI/mycroft-core#2981]
**Describe the bug**
Error code and stops listen to further commands

**To Reproduce**
Ask it something,  last was listen to mpr in record was supposed to be listen to npr.
It froze and wouldnt listen to other commands
Gave error code

**Expected behavior**
Should handle the exception and tell me it doesnt understand

**Log files**
 23:27:28.533 | ERROR    |   738 | mycroft.client.speech.listener:transcribe:239 | list index out of range
~~~~|   738 | mycroft.client.speech.listener:transcribe:240 | Speech Recognition could not understand audi
  ^--- NEWEST ---^ 

**Environment (please complete the following information):**
 - Device type: Raspberry Pi 4
 - OS: Picroft
 - Mycroft-core version: 21.2.0

**Additional context**
Seems like its getting an exception because its not understanding and then it breaks rather than the exception being handled, and saying that it doesnt understand it throws this error

**Comment by ChanceNCounter** [comment]
Gonna need *way* more of the log file. Everything from the line that says "Traceback:" down.

**Comment by Arndorferd** [comment]
Not sure what log file this is just on mycroft-cli-client output, voice.log has a similar amount of data with just

2021-08-21 00:00:08.145 | ERROR    |   703 | mycroft.client.speech.listener:transcribe:239 | list index out of range
2021-08-21 00:00:08.148 | ERROR    |   703 | mycroft.client.speech.listener:transcribe:240 | Speech Recognition could not understand audio

and no errors surrounding

**Comment by Arndorferd** [comment]
there is no "Traceback:"

**Comment by ChanceNCounter** [comment]
How about `skills.log`?

**Comment by Arndorferd** [comment]
No errors in skills.log

**Comment by forslund** [comment]
That error occurs when the STT returns no response if I remember correctly. I.e Mycroft is invoked with "hey mycroft" but then nothing is said afterwards.

Not really an error but the case should be handled better

**Comment by ChanceNCounter** [comment]
Yeah, but then :skull:, which is different.

**Comment by forslund** [comment]
Ah yes definitely.

**Comment by Arndorferd** [comment]
Well as someone who does a lot of bug reporting for open source, false lead warnings and errors need to be handled so that its easier for people to report real issues.

**Comment by JarbasAl** [comment]
didnt @ken-mycroft mention fixing this issue some time back in chat?

**Comment by krisgesling** [comment]
Yeah it's on the list to fix up - fully agree that false warnings make things harder so even if it's not "failing" as such, we still want to squish it.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
