### ISSUE TITLE
Asks how long of a timer on random questions

### ISSUE THREAD

**Issue by Arndorferd** [MycroftAI/mycroft-core#2982]
**Describe the bug**
Random questions ask me to set a timer rather than saying it doesn't know or an answer that makes sense

**To Reproduce**
Ask mycroft: Are you a cat
Response: How long of a timer
Ask mycroft: Are you a bear
Response: How long of a timer

**Expected behavior**
Mycroft should respond that it does not understand or respond with an answer

**Log files**

Voice.log

> 2021-08-21 03:45:13.895 | INFO     |   703 | __main__:handle_wakeword:71 | Wakeword Detected: hey mycroft
> 2021-08-21 03:45:14.400 | INFO     |   703 | __main__:handle_record_begin:41 | Begin Recording...
> 2021-08-21 03:45:16.971 | INFO     |   703 | __main__:handle_record_end:49 | End Recording...
> 2021-08-21 03:45:17.625 | INFO     |   703 | __main__:handle_utterance:76 | Utterance: ['are you a cat']
> 2021-08-21 03:45:20.700 | INFO     |   703 | __main__:handle_record_begin:41 | Begin Recording...
> 2021-08-21 03:45:23.842 | INFO     |   703 | __main__:handle_record_end:49 | End Recording...
> 2021-08-21 03:45:24.696 | ERROR    |   703 | mycroft.client.speech.listener:transcribe:239 | list index out of range
> 2021-08-21 03:45:24.700 | ERROR    |   703 | mycroft.client.speech.listener:transcribe:240 | Speech Recognition could not understand audio
> 2021-08-21 03:45:26.640 | INFO     |   703 | __main__:handle_record_begin:41 | Begin Recording...
> 2021-08-21 03:45:32.034 | INFO     |   703 | __main__:handle_record_end:49 | End Recording...
> 2021-08-21 03:45:33.052 | ERROR    |   703 | mycroft.client.speech.listener:transcribe:239 | list index out of range
> 2021-08-21 03:45:33.054 | ERROR    |   703 | mycroft.client.speech.listener:transcribe:240 | Speech Recognition could not understand audio
> 2021-08-21 03:45:40.037 | INFO     |   703 | __main__:handle_wakeword:71 | Wakeword Detected: hey mycroft
> 2021-08-21 03:45:40.510 | INFO     |   703 | __main__:handle_record_begin:41 | Begin Recording...
> 2021-08-21 03:45:42.831 | INFO     |   703 | __main__:handle_record_end:49 | End Recording...
> 2021-08-21 03:45:43.381 | INFO     |   703 | __main__:handle_utterance:76 | Utterance: ['stop']
> 2021-08-21 03:50:22.642 | INFO     |   703 | mycroft.session:get:74 | New Session Start: 57692dc9-007d-4c64-ac9c-e4d24e4c7398
> 2021-08-21 03:50:22.644 | INFO     |   703 | __main__:handle_wakeword:71 | Wakeword Detected: hey mycroft
> 2021-08-21 03:50:23.096 | INFO     |   703 | __main__:handle_record_begin:41 | Begin Recording...
> 2021-08-21 03:50:24.899 | INFO     |   703 | __main__:handle_record_end:49 | End Recording...
> 2021-08-21 03:50:25.520 | INFO     |   703 | __main__:handle_utterance:76 | Utterance: ['are you a bear']
> 2021-08-21 03:50:28.571 | INFO     |   703 | __main__:handle_record_begin:41 | Begin Recording...
> 2021-08-21 03:50:34.525 | INFO     |   703 | __main__:handle_record_end:49 | End Recording...
> 2021-08-21 03:50:35.683 | ERROR    |   703 | mycroft.client.speech.listener:transcribe:239 | list index out of range
> 2021-08-21 03:50:35.684 | ERROR    |   703 | mycroft.client.speech.listener:transcribe:240 | Speech Recognition could not understand audio
> 2021-08-21 03:50:37.587 | INFO     |   703 | __main__:handle_record_begin:41 | Begin Recording...
> 2021-08-21 03:50:40.729 | INFO     |   703 | __main__:handle_record_end:49 | End Recording...
> 2021-08-21 03:50:41.651 | ERROR    |   703 | mycroft.clien

t.speech.listener:transcribe:239 | list index out of range

Audio.log

> 2021-08-21 03:45:18.812 | INFO     |   700 | mycroft.audio.speech:mute_and_speak:127 | Speak: How long of a timer?
> 2021-08-21 03:45:18.814 | INFO     |   700 | mycroft.tts.tts:_get_sentence_from_cache:392 | Found 1db9ce8c25e4c98f15de609813128fb8.wav in TTS cache
> 2021-08-21 03:45:24.740 | INFO     |   700 | mycroft.audio.speech:mute_and_speak:127 | Speak: How long of a timer?
> 2021-08-21 03:45:24.747 | INFO     |   700 | mycroft.tts.tts:_get_sentence_from_cache:392 | Found 1db9ce8c25e4c98f15de609813128fb8.wav in TTS cache
> 2021-08-21 03:50:26.729 | INFO     |   700 | mycroft.audio.speech:mute_and_speak:127 | Speak: How long of a timer?
> 2021-08-21 03:50:26.731 | INFO     |   700 | mycroft.tts.tts:_get_sentence_from_cache:392 | Found 1db9ce8c25e4c98f15de609813128fb8.wav in TTS cache
> 2021-08-21 03:50:35.713 | INFO     |   700 | mycroft.audio.speech:mute_and_speak:127 | Speak: How long of a timer?

**Environment (please complete the following information):**
-     Device type: Raspberry Pi 4
-     OS: Picroft
-     Mycroft-core version: 21.2.0

**Additional context**

May be related to my [previous issue](https://github.com/MycroftAI/mycroft-core/issues/2981) and I have been having an issue with a lack of responsiveness to the wake word from time to time after commands, which might also be related.

**Comment by krisgesling** [comment]
Hey, there's a big update to the Timer Skill on it's way.

If you want to try it out early you can say something like:
"install beta timer skill" 

or do a git pull on the skill:
```
cd /opt/mycroft/skills/mycroft-timer.mycroftai
git pull
```
Both of these should give you the latest version from the repo, rather than the version in the Marketplace.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
