### ISSUE TITLE
Mycroft First Start Up CLI Error

### ISSUE THREAD

**Issue by STORP-Inc** [MycroftAI/mycroft-core#2983]
This is the error when I do ./start-mycroft.sh cli

Initializing...
./start-mycroft.sh: line 83: /home/lamentis/mycroft-core/.venv/bin/activate: No such file or directory
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
./start-mycroft.sh: line 141: /var/log/mycroft/bus.log: No such file or directory
Starting background service skills
./start-mycroft.sh: line 141: /var/log/mycroft/skills.log: No such file or directory
Starting cli
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/lamentis/mycroft-core/mycroft/__init__.py", line 18, in <module>
    from mycroft.messagebus.message import Message
  File "/home/lamentis/mycroft-core/mycroft/messagebus/__init__.py", line 14, in <module>
    from .client.client import MessageBusClient
  File "/home/lamentis/mycroft-core/mycroft/messagebus/client/__init__.py", line 15, in <module>
    from .client import MessageWaiter, MessageBusClient
  File "/home/lamentis/mycroft-core/mycroft/messagebus/client/client.py", line 16, in <module>
    from mycroft_bus_client import MessageBusClient as _MessageBusClient
ModuleNotFoundError: No module named 'mycroft_bus_client'

**Environment (please complete the following information):**
 - Device type: HP Windows 10 Laptop
 - OS: Kali Linux WSL
 - Mycroft-core version: 21.2.0 (The Latest one)

How do I fix it?

**Comment by forslund** [comment]
Hi, it looks like the mycroft venv wasn't created. It's likely that the dev-setup.sh didn't complete since it doesn't have any handling for kali linux

**Comment by krisgesling** [comment]
I'd also warn that we don't test anything on WSL. There are people in the community that use it, so it's certainly possible, but you may run into issues particularly with audio.

As this isn't a supported platform I'm going to close this issue. However if you want to try and do a manual setup, you could ask for help on the [Community Forums](community.mycroft.ai/) or in the [Windows channel on Mycroft Chat](https://chat.mycroft.ai/community/channels/windows).
