### ISSUE TITLE
Create unit tests for mic.py with more audio files to test

### ISSUE THREAD

**Issue by Wolfgange3311999** [MycroftAI/mycroft-core#30]
This should feed a set of recordings into the `listen` method and verify that in each one the wakeword is correctly detected.

To best simulate real-world situations it might be necessary to have a period of white noise or minimal background noise before the voice comes into the recording.

**Comment by ryanleesipes** [comment]
Yes. Agreed 100%! I've been working on recording these! We'll get them in
some kind of file repo.

On Sun, May 22, 2016, 9:53 PM Matthew D. Scholefield <
notifications@github.com> wrote:

> This should feed a set of recordings into the listen method and verify
> that in each one the wakeword is correctly detected.
>
> To best simulate real-world situations it might be necessary to have a
> period of white noise or minimal background noise before the voice comes
> into the recording.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MycroftAI/mycroft-core/issues/30>
>
-- 
Ryan Sipes
CTO, Mycroft A.I.
https://mycroft.ai
785-979-6091

**Comment by ryanleesipes** [comment]
@ethanaward pair with @aatchison to show you how to record these, then pair with me to get specifics on what the recordings should contain.

**Comment by isaacnward** [comment]
This is the same issue as #219, which is on its way to getting merged.
