### ISSUE TITLE
when setting "record_wake_words": true, every wav file is missing the HEY part of HEY MYCROFT

### ISSUE THREAD

**Issue by cooljimy84** [MycroftAI/mycroft-core#3006]
**Describe the bug**
The saved wav files in /tmp/mycroft_wake_words/ only have the MYCROFT part of the trigger. For example my wake word is still hey mycroft, but when i listen to the saved wav files all i hear is "MYCROFT" or the last part of HEY and then mycroft.

**To Reproduce**
1. enabled the record wake words options (i had to enable in the /opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/configuration/mycroft.conf as my config was being overwritten or ignored)

**Expected behavior**
the full saved wav of "HEY MYCROFT" so i can use these to better train the wake word.

**Log files**
If possible, add log files from `/var/log/mycroft/` to help explain your problem.

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: mark 1
 - OS: mark1
 - Mycroft-core version: 21.2.1
 - Other versions: enclosure version 1.4.2

**Comment by cooljimy84** [comment]
[logs.zip](https://github.com/MycroftAI/mycroft-core/files/7265049/logs.zip)
logs attached

**Comment by krisgesling** [comment]
Hey there, 

Have you changed any other setting besides enabling the save attribute?

Make sure the `hotwords.{your_hotword}.phonemes` attribute is set as this is used to calculate how long the wake word is likely to be. You can also tweak that further by setting the average `listener.phoneme_duration`.

If your config was being overwritten then it's highly likely that there was a syntax error in there. If you're editing the conf files directly I'd suggest validating the contents first. DDG has a super simple tool for this: 
https://duckduckgo.com/?t=ffab&q=json+validator&ia=answer

If you still have trouble can you post the complete contents of any `mycroft.conf` files you've edited?

**Comment by cooljimy84** [comment]
Your right I had an config, error. Managed to sort it out and then changed the file back to stock.

Just got the following in the mycroft.conf
{
  "max_allowed_core_version": 21.2
}
{
  "listener":{
    "record_wake_words":true
  }
}

I'll try adding/tweaking the two options you have mentioned and report back.

**Comment by cooljimy84** [comment]
So i change my mycroft.conf to the follow.
```
{
  "listener":{
    "record_wake_words":true,
    "phoneme_duration": 240
  },
   "hotwords":{
     "hey mycroft":{
       "module":"precise",
       "phonemes":"HH EY . M AY K R AO F T"
    }
  }
}
```

If i speak "Hey mycroft" really quick the recording sounds like "Ay mycroft" if i speak at a normal speed it just saves "mycroft" both files are 25.4KB (the same as if the phoneme duration was 120) evening upping to 512 the clip is too short and 25.4KB

**Comment by cooljimy84** [comment]
Kool, as i said "tinfoil hat"

I'll hold off putting my custom training on my mk1 as the mic is different from my laptop and doesn't respond to the wake word very well with the differences.

**Comment by fsa317** [comment]
I think I found the issue.  The expected durations of the wake work is calculated in hotword_factory.py and appears to use the length of the actual phrase not the phoneme.  It does use `phoneme_duration` config on your wake word, but due to a bug it is expecting that config in "hot_words" and not "hotwords":

```
config = Configuration.get().get("hot_words", {})
```

I'm going to see if I can add a fix (never done it before).  Here's my PR - https://github.com/MycroftAI/mycroft-core/pull/3088

**Comment by jessecooper** [comment]
This still seems to have issues with one word wake words like `jarvis`. I still only get a blank file.
