### ISSUE TITLE
[Request] Let the validator (get_response) drive the response return value

### ISSUE THREAD

**Issue by emphasize** [MycroftAI/mycroft-core#3007]
By now you validate the response - lets say you require a number in the response - and if so, you return the response.

So - to give an example - if someone says: "The second title", the return (if validated) is "The second title"
In this context you would require to `extract_number` in the validator to validate the answer is inside the boundaries,
but - depending on your code - would need to do it again outside the `get_response` call.

code example:
_here the validator excepts a number, sentence containing a number or a fitting song name -> int_

```python
song = message.data.get("song", False)
if not song:
        num = self.get_response("ask.specific.song",
                                validator=self.validate_specific_song,
                                on_fail="nothing.found", num_retries=1)
...
def validate_specific_song(self, response):
        # is response a number or contains a number?
        num = extract_number(response)
        # fuzzy match additionally (song name contains a number?)
        matches = [fuzzy_match(response, item["name"])
                   for item in self.songs.playlist]
        best = max(matches)
        if best > 0.5:
            num = matches.index(best)
        # if not affirmative, dont ask again
        if self.voc_match(response, "no"):
            num = 1
        return num if isinstance(num, int) and \
            num <= len(self.songs.playlist) else False
```
I think it would be in favour of slim code if instead of `response` core returns `validator(response)`

core code: [#](https://github.com/MycroftAI/mycroft-core/blob/2a6bb90c9f673b9ff569945e885bb42cd7814354/mycroft/skills/mycroft_skill/mycroft_skill.py#L527)

```python
#new
else:
        validated = validator(response)
        if validated:
              return response if validated == True else validated

        # catch user saying 'cancel'
        if is_cancel(response):
              return None
```
_changed original, see_ [#](https://github.com/MycroftAI/mycroft-core/issues/3007#issuecomment-936084909)

If one requires the original utterance, just pass response (or whatever is set) in the validator

**Comment by JarbasAl** [comment]
unrelated to the validator proposal, but for your specific example i recommend you look into

```python
    def ask_selection(self, options, dialog='',
                      data=None, min_conf=0.65, numeric=False):
        """Read options, ask dialog question and wait for an answer.
        This automatically deals with fuzzy matching and selection by number
        e.g.
        * "first option"
        * "last option"
        * "second option"
        * "option number four"
        Args:
              options (list): list of options to present user
              dialog (str): a dialog id or string to read AFTER all options
              data (dict): Data used to render the dialog
              min_conf (float): minimum confidence for fuzzy match, if not
                                reached return None
              numeric (bool): speak options as a numeric menu
        Returns:
              string: list element selected by user, or None
        """
 ```

**Comment by emphasize** [comment]
@offtopic
Thanks, but both not fitting the use case. Imagine an album with 20 title spoken to you.
In most cases you know the media you're playing, ie the options are known.
If necessary i might add {playlistcount} to the initial dialog, to tell the max number.

The point is you use a validator to narrow down the response options. It would make sense if you pass that and not require a do-over.

**Comment by krisgesling** [comment]
Hey, this is something that has bugged me as well and your proposal sounds pretty good to me personally.

If a validator explicitly returned `True` (not a "truthy value"), would it be better to return the entire utterance? 
If you were only interested in an affirmative response then I'd assume you would use `ask_yesno()` or similar - but this might be a bad assumption to make.

**Comment by emphasize** [comment]
Not exactly following, but you wouldn't need `True` in `if validated:`
And you are not reusing the validator return value later in the code (would have to check `is True` anyway)

If the original response is wanted one can `return response` in the validator

I'm exactly advocating the "truthy value" since you could do multiple things at once in/with the validator and not sort things out later (again).
(Like in the example given _"validator excepts a number, sentence containing a number, a fitting song name or a not affirmative answer"_ and in this case spits out a track number ... or None)

**Comment by krisgesling** [comment]
I was thinking partly about backwards compatibility because making this change will break anything that currently uses the validator function and returns a boolean, so something like:
```python
return False or None   # validation failed
return True            # validation succeeded - returns whole utterance - matches current behaviour
return truthy_value    # validation succeeded - returns truthy_value
```

**Comment by emphasize** [comment]
Gotcha (in the case of returning True in the face of backwards compatability).

Tested it on a repl and the `False or None` scenario is the same in the former and the new code - it cancels out `get_response` with `None` depending on `num_retries`. (Or one could say `or None` is neglectable). 

so
```python
validated = validator(response)
if validated:
        return response if validated is True else validated
```
should cover all the bases

**Comment by krisgesling** [comment]
Yeah I think that works - at least it does in my head.

Interested if anyone else has opinions on this proposal?
 :+1: Hell yeah
 :-1: No way
 :bulb: I like the idea but not sure about the implementation
 :shrug: Don't really understand or not sure what I think

**Comment by emphasize** [comment]
Just realized that the order validate/is_cancel have to be reversed in order to catch cancel consistently (with the changes; yet it would make more sense even without)

```
else:
        # catch user saying 'cancel'
        if is_cancel(response):
              return None

        validated = validator(response)
        if validated:
              return response if validated == True else validated
```

**Comment by emphasize** [comment]
*cough* HELL YEAH! Should i write a PR to push this?

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
