### ISSUE TITLE
MycroftSkill.acknowledge() plays a sound when a context.destination other than itself is targeted

### ISSUE THREAD

**Issue by iointerrupt** [MycroftAI/mycroft-core#3009]
While working on a skill that uses the MycroftSkill.acknowledge() function for a successful requests, a sound is played from the speaker even when a different destination is targeted.  Wondering whether it should do that or should it be up to the skill to handle it.

**Comment by krisgesling** [comment]
Hey there, the message destination isn't currently used in stock Mycroft-core. So an `acknowledge()` tone is going to play on the device running Mycroft. You'd need to look at something like [HiveMind](https://github.com/JarbasHiveMind/HiveMind-core/) to route audio back to a different speaker satellite.

If I've misunderstood, please re-open.
