### ISSUE TITLE
Possible race condition in SkillGUI class when removing a screen

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#3013]
**Describe the bug**
There have been multiple reports of unexpected behaviour when removing pages from a GUI namespace.

Most recently in the Pairing Skill:
https://github.com/MycroftAI/skill-pairing/pull/71#discussion_r730012240

As it's beyond the scope of the Pairing Skill it's been moved here.

**To Reproduce**
Run the GUI stress tester Skill: [skills-gui-stress-test.aiix.zip](https://github.com/MycroftAI/skill-pairing/files/7356577/skills-gui-stress-test.aiix.zip)

To run the test: "run stress test one"

**Expected behavior**
Adding and removing pages should operate consistently and be performed in the order in which they are requested.

**Comment by forslund** [comment]
Was this resolved through #3022?

**Comment by krisgesling** [comment]
Not sure, I haven't tested it deeply yet.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
