### ISSUE TITLE
Switch virtual/libffi to dev-libs/libffi

### ISSUE THREAD

**Issue by rooky-c3bo** [MycroftAI/mycroft-core#3026]
Please replace `virtual/libffi` with `dev-libs/libffi`.
See Gentoo [bug](https://bugs.gentoo.org/699796).
https://github.com/MycroftAI/mycroft-core/blob/ea157598d70581dcaca719e19a2de76e880f76ed/dev_setup.sh#L401

**Comment by krisgesling** [comment]
Hey @rooky-c3bo thanks for pointing that out.

If you'd like to make a pull request and change the line yourself, we warmly welcome new contributors!

For any contributions we do require you to sign a Contributor License Agreement (CLA). The is to protect yourself, the project, and users of Mycroft technologies. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license. This is also a one-time thing, and then you are able to contribute to any Mycroft repository.

You will also be added to [our list of excellent human beings](https://github.com/MycroftAI/contributors)!

Please visit https://mycroft.ai/cla to initiate this one-time signing.

If you haven't contributed to open source before we have a [contributing guide](https://github.com/MycroftAI/mycroft-core/blob/ea157598d70581dcaca719e19a2de76e880f76ed/.github/CONTRIBUTING.md) that can help you get started.

**Comment by rooky-c3bo** [comment]
Hi @krisgesling, you're welcome.

Yes I'd like to make a pull request and already did.
Hopefully my [request](https://github.com/MycroftAI/mycroft-core/pull/3039) is done right so far?
