### ISSUE TITLE
remote config overriding system config

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-core#3029]
bug described here https://community.mycroft.ai/t/remote-conf-overriding-all-other-conf/11476 

this was discussed but consensus not reached https://github.com/MycroftAI/mycroft-core/pull/2861

i was under the impression this was considered an unwanted change, at least without some extra changes accompanying the order change

**Comment by krisgesling** [comment]
Yeah this must be a bug, as no changes have been made on the config order, either in mainline or [in the feature/mark-2 branch](https://github.com/MycroftAI/mycroft-core/blob/feature/mark-2/mycroft/configuration/config.py#L207).

**Comment by JarbasAl** [comment]
I think it was introduced in the XDG PR for configs

**Comment by forslund** [comment]
Yeah, looks like the order was swapped and remote was added before the old /etc/mycroft/mycroft.conf
