### ISSUE TITLE
New Hotword Detector : EfficientWord-Net (Feature Request)

### ISSUE THREAD

**Issue by TheSeriousProgrammer** [MycroftAI/mycroft-core#3034]
Hi , I developed a new hotword detector named EfficientWord-Net , it works on One-Shot Learning
Very similar to face recognition . One needs to provide just a few positive samples of the hotword
to make it start detecting hotwords

Just like Google Assistant's hotword detector, the engine performs the best when samples are
directly collected form the target user

Hope the it will be of help to Mycroft

Github Repo : https://github.com/Ant-Brain/EfficientWord-Net

**Comment by ChanceNCounter** [comment]
Seems to be missing a license.

**Comment by TheSeriousProgrammer** [comment]
My bad, just now added the license file Apache License 2.0

**Comment by goldyfruit** [comment]
That's nice, you should try to write a PR to connect your hotword detector as a plugin.

**Comment by NeonDaniel** [comment]
Thanks to @JarbasAl for this one here: https://github.com/NeonGeckoCom/neon_ww_plugin_efnet

**Comment by TheSeriousProgrammer** [comment]
> Thanks to @JarbasAl for this one here: https://github.com/NeonGeckoCom/neon_ww_plugin_efnet
> 

This looks neat ! Will try to create a wakeowrd for mycroft and make a PR

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
