### ISSUE TITLE
Fresh install dev_setup.sh  permissions problem ManjaroArch

### ISSUE THREAD

**Issue by PeterKW** [MycroftAI/mycroft-core#3035]
I've just tried to install Mycroft, but I think there is a permissions problem somewhere. I'm not quite certain what permissions to change and wanted to double check. Does having this error mean that the permissions on my root '/' are incorrect? What should they be?

```
/usr/share/mycroft-core  ./dev_setup.sh     
...
The standard location for Mycroft skills is under /opt/mycroft/skills.
ln: failed to create symbolic link 'skills': Permission denied
```

```
 /opt/mycroft  tree                                                                               
.
└── skills

1 directory, 0 files
 /opt/mycroft  ls -al                                                                                 
total 0
drwxr-xr-x 1 p p  12 Nov 12 22:04 .
drwxr-xr-x 1 root      root      350 Nov 12 21:58 ..
drwxr-xr-x 1 p p  0 Nov 12 22:04 skills
```

![image](https://user-images.githubusercontent.com/13779157/141540229-dbfeef2c-ad35-47e4-a38d-541c01be3211.png)

**Comment by ChanceNCounter** [comment]
I think it's `/usr/share/mycroft-core` where you're encountering the permissions problem.

**Comment by PureTryOut** [comment]
It is. `dev_setup.sh` is not meant to be ran from a root-owned folder, instead it's meant to be ran from the git directory which should've been cloned to somewhere in the home folder. The error you're getting means it failed to link `/opt/mycroft/skills` to `$PWD/skills` (which it does for developing convenience) which makes sense, as `/usr/share/mycroft-core` is (I assume) owned by root and you don't run the script as root (and neither should you!).

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
