### ISSUE TITLE
Google TTS terms of service note

### ISSUE THREAD

**Issue by fquirin** [MycroftAI/mycroft-core#3056]
I was just browsing the TTS page and saw that you have Google TTS via Google translate as option.
I had this discussion a few times now, but I really think we (the open-assistant community) should remove support for this "service"! Here are a few reasons why:
- Googles terms of service actually prohibit usage for other purposes than translate on their page, so legally its a dark-gray area
- Its a hack and can break anytime
- Text sent to the service will most definitely be analyzed by Google
- Due to it's quality, speed and easy integration it actually is contra productive for the development of open-source alternatives because it suggests that TTS is a solved problem in open-source voice assistants

Now I understand why you want to offer support for this but at the very least you should add a **fat disclaimer** to the docs page, so people know that this cannot (ever!) be used in any other environment as your private, non-public experimental builds!

Anyway I've heard we might see a Mimic 3 soon? :grin: 

Keep up the good work,
Florian / [SEPIA](https://sepia-framework.github.io/)

**Comment by JarbasAl** [comment]
Duplicated issue https://github.com/MycroftAI/mycroft-core/issues/2972

I suppose docs need updating, there has been a major release since the option was removed from backend, might be a good time to drop support in core completely

**Comment by fquirin** [comment]
:slightly_smiling_face:  :ok_hand:

**Comment by krisgesling** [comment]
Hey, thanks for the nudge - I've added the warning from the module to the docs page. 

We will be extracting all of these modules from core at some point. Those that we think are valuable we'll create official plugins for, but for many it will be up to the community as to whether someone wants to create and maintain a plugin for it.

I think your spot-on that there are a number of great open source TTS options available now. So I can't really see gTTS continuing to be supported in any official capacity.
