### ISSUE TITLE
Add Speech-to-Text backend for coqui-STT

### ISSUE THREAD

**Issue by lw64** [MycroftAI/mycroft-core#3062]
It seems to me, that the coqui-STT project has reached a point, where it can be used as a backend. There are lots of languages available, and the performance is also very good: "it is running in realtime on a raspberry pi 4 core".

It has also the capability of streaming speech recognition, but as far as I know, that is not yet supported/used anywhere else.

I don't know if a server like for the deepspeech backend, or direct usage of coqui-STT's python bindings is better.

**Comment by el-tocino** [comment]
There's a move to plugin format for the voice services, and this should be one of the supported types soon.

**Comment by JRMeyer** [comment]
Coqui STT would be a straight-forward drop-in replacement for DeepSpeech, because the APIs are nearly identical :D

also - the latest English model from Coqui STT is much more accurate than the old DeepSpeech model

**Comment by hslr4** [comment]
I'm running Coqui STT on my Picroft as described [here](https://gitlab.mi.hdm-stuttgart.de/heisler/stt-coqui-server) (as a REST API the same way DeepSpeech is currently integrated into Mycroft).
I needed it to quickly work somehow so it might not be the best solution but maybe it is helpful anyway for someone planning to do it right.

**Comment by lw64** [comment]
@hslr4 maybe you could create a pull request for the integration into mycroft?

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
