### ISSUE TITLE
bash dev_setup.sh --clean does not remove skills symlink

### ISSUE THREAD

**Issue by trammell** [MycroftAI/mycroft-core#3084]
**Describe the bug**
`--clean` option is advertised as "Remove files and folders created by this script"

**To Reproduce**

Following the instructions at <https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/linux#installing-via-git-clone>:

1. `bash dev_setup.sh`
2. `bash dev_setup.sh --clean`
3. `ls -l`

**Expected behavior**
`skills` symlink should not be present

**Environment (please complete the following information):**
- Device type: Linux desktop
- OS: Debian 11.2, 5.10.92 x86_64 kernel
- Mycroft-core version: commit 8051e4e1

**Additional context**
Just a newbie trying to get Mycroft working.

**Comment by krisgesling** [comment]
Hey there, thanks for logging this. 

I'd agree - it's a symlink created by the script so it should get removed.
