### ISSUE TITLE
Missing native packages on documentation

### ISSUE THREAD

**Issue by Eibriel** [MycroftAI/mycroft-core#31]
The following _native packages_ are also needed (Xubuntu 14.04):
- libffi-dev
- libssl-dev

**Comment by Dark5ide** [comment]
Also on Ubuntu 16.04.

I suggest adding _libffi-dev_ and _libssl-dev_ in **build_host_setup.sh**. After that we can change the documentation like this : 

- run **build_host_setup.sh**
- run **dev_setup.sh**

**Comment by ryanleesipes** [comment]
@jdorleans @aatchison, can one of you check on this? And if it is needed - include it in README and on the docs site.
