### ISSUE TITLE
Allows skill to dynamically define intents or entities

### ISSUE THREAD

**Issue by zeronounours** [MycroftAI/mycroft-core#3100]
**Is your feature request related to a problem? Please describe.**
Some skills my require dynamic definition of padatious entities to prevent matching requests intented for other skills.
See https://github.com/MycroftAI/skill-homeassistant/issues/64 and https://github.com/MycroftAI/skill-homeassistant/issues/104

It can currently be done with file within resource directories, but it is not a clean solution.

**Describe the solution you'd like**
New methods should be implemented to dynamically load new entities or intents in padatious with any wanted name. For instance:
```python
   def register_entity_file_as(self, filename, name):
```

**Describe alternatives you've considered**
Currently skill-homeassistant provides absolute path to a temporary file to `MycroftSkill.register_entity_file()`. This method may be updated to only use as name the base name of the file and not the full path.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
