### ISSUE TITLE
Full support of systems with libjack-jackd2-0 package e.g. Ubuntu Studio

### ISSUE THREAD

**Issue by succeedmr123** [MycroftAI/mycroft-core#3102]
**Is your feature request related to a problem? Please describe.**

-It is extra bad that respectable systems like Ubuntu Studio which ARE already audio and multimedia optimized for low-latency AV IO -  along the lines of specialized functions Mycroft offers - can not use the Mycroft -core package because Mycroft currently can not operate with distros' key component  - libjack-jackd2-0 package , which is not supported i.e. on Ubuntu Studio 20.04 LTS Mycroft need to install the "wrong" libjack package  that will break the whole distro - fully uninstall loads of key system libraries from distros made specifically for low latency multimedia, (operation under os with advanced linux sound arhitecture, and not basic legacy sound architecture for latency as many other apps  is very desirable feat for Mycroft as well - win-win)

**Describe the solution you'd like**

.. Therefore, a full compatibility with libjack-jackd2-0 package is key so that special latency and audiovisual distros like Ubuntu Studio may function as a platform for Mycroft

**Describe alternatives you've considered**

Alternatives? It is obvious what is necessary: to adjust Mycroft to work fully with libjack-jackd2-0 package, pulse-ALSA bridges, all of that without any glitch.

**Additional context**

 All the other software on Ubuntu Studio or even Kubuntu+Studio repo installed (second way of installing Studio functionality to Ubuntu) -  has zero problems working with advanced audio systems as they are set up into a distro. Of course, the req is due to distro can not be adjusted as libjack-jackd2-0 package is KEY library to the whole distro - would fully break the distro.

Hence a req for improvement of Mycroft in that regard.

Tech data:  if you press enter after libjack incompatibility message, here is what is libjack-jackd2-0  package reconfig soluton;

The following additional packages will be installed:
  libfann2 libout123-0 libportaudiocpp0 libsyn123-0 swig4.0
Suggested packages:
  libfann-doc nas oss4-base portaudio19-doc swig-doc swig-examples swig4.0-examples swig4.0-doc
The following NEW packages will be installed:
  libfann-dev libfann2 libout123-0 libportaudiocpp0 libsyn123-0 mpg123 portaudio19-dev swig swig4.0
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 1673 kB of archives.
After this operation, 8269 kB of additional disk space will be used.
Do you want to continue? [Y/n] 

- In this specific case on Ubuntu-Studio 22.04 LTS - I do not see that libjack-jackd2-0 will be uninstalled. But, reading that it will pollute the system based on Jack-ALS-PulseAudio bridges with OSS - I can not do that, unacceptable. ALSA-Jack is the best Linux has to offer currently, with Pipewire or PulseAudio as second best as much as I can tell from what I see here. therefore the req for Enhancement.

- On previous platform Ubuntu Studio 20.04 LTS it caused catastrophic uninstall request of half of the key system libs. Hence noticing the dangers here.

Conclusion: insofar it looks unusable for at least a year due to the way it relies on the technologies that are not used in better audio subsystem on Linux for pro audio, therefore urgent note here as it is a long overdue.

If testing or patching necessary, am availble -  Mycroft working on advanced linux sound architecture is sa worthwile goal and am willing to help making it happen. thanks in advance

**Comment by succeedmr123** [comment]
Third iteration od power-user analysis:

For Ubuntu studio 22.04 LTS:

checked all the libs to be installed and their function

only portaudio was slightly calling for caution... looking up in ubuntu package description.. seems it may work along ALSA

installing..

Problem is unsolvable in Ubuntu Studio 20.04 LTS advanced audio system platform still.

**Comment by krisgesling** [comment]
Hi there, thanks for submitting this issue. 

It is something that we are working to simplify and in the long-term have supported releases for major platforms like the Ubuntu family of distros.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
