### ISSUE TITLE
An error occurred while processing a request in Time Skill

### ISSUE THREAD

**Issue by mike99mac** [MycroftAI/mycroft-core#3107]
**Describe the bug**
I said "Hey Mycroft ... what time is it" and got the time, but also got the subject error message.  Here's the traceback:

 09:42:05.676 | ERROR    | 55371 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:923 | An error occurred while processing a request in Time Skill
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-date-time.mycroftai/__init__.py", line 412, in handle_query_time
    self.display(self.get_display_current_time(location))
  File "/opt/mycroft/skills/mycroft-date-time.mycroftai/__init__.py", line 272, in display
    self.display_gui(display_time)
  File "/opt/mycroft/skills/mycroft-date-time.mycroftai/__init__.py", line 332, in display_gui
    self.gui.clear()
  File "/home/pi/mycroft-core/mycroft/enclosure/gui.py", line 129, in clear
    self.skill.bus.emit(Message("gui.clear.namespace",
AttributeError: 'NoneType' object has no attribute 'bus'

**To Reproduce**
1. start 'mycroft-start debug'
2. : log level debug
3. say "Hey Mycroft ... what time is it"
4. You should see the error
What is weird is that this was not happening yesterday.  Has any code been updated in the last 24 hours or so? (It is 10:00 EST on 23 May 2022) 

**Expected behavior**
No error message, just the current time

**Log files**
I could provide more if needed 

**Environment (please complete the following information):**
 - Device type:  Raspberry Pi 4 4GB
 - OS: Ubuntu Server
 - Mycroft-core version: Not sure how to query version - I built with stable not development.
 - Other versions: can be provided

**Additional context**
I have been learning to build skills but have not modified any other source files.

**Comment by krisgesling** [comment]
Hey Mike, 

Thanks for raising a ticket. I think the most likely situation is that there's something in the Skill shutdown/reload logic.

If you still have the same version of the Skill installed can you run: 
```
cd /opt/mycroft/skills/mycroft-date-time.mycroftai/
git rev-parse HEAD
```
This will give you a commit hash and will tell us exactly which version is running.

Thanks

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo

**Comment by mike99mac** [comment]
Fare ye well Mycroft ...
