### ISSUE TITLE
Cannot install Mycroft-Core on Fedora 34 Linux because of error: '~/libttsmimic.la' is not a valid libtool archive

### ISSUE THREAD

**Issue by NamesNetworkNic** [MycroftAI/mycroft-core#3115]
I am on a HP laptop running Fedora 34, running the latest version of Mycroft-Core (I am literally in the install process right now).

I have followed the steps given to me from [this page](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/linux) to attempt to install Mycroft, with the minor change of installing to a folder of my choice instead of home. 

.
When running the bash script dev_setup.sh, with the modifier --allow-root (it would not run at all without root as permissions to various folders were denied, and I thought it would take too long to manually correct that), I get this error:

```
  CCLD     libttsmimic.la
  CCLD     libttsmimic_lang_usenglish.la
/usr/bin/sed: can't read Programs/mycroft-core/mimic/libttsmimic.la: No such file or directory
libtool:   error: 'Programs/mycroft-core/mimic/libttsmimic.la' is not a valid libtool archive
make[1]: *** [Makefile:2651: libttsmimic_lang_usenglish.la] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/NamesNetworkNic/Misc Folders/Manually Installed Programs/mycroft-core/mimic'
make: *** [Makefile:4320: all-recursive] Error 1
```
I cut that to the last few lines, [here's the full log.](https://github.com/MycroftAI/mycroft-core/files/8893835/log.txt)

.
I have looked up this error both generally and here on Github and have found nothing on it.
I also attempted an offered quick fix for a [different but similar at a glance error](https://github.com/MycroftAI/mycroft-core/issues/822) adding "CORES=1" to the script, to no effect.

I don't know what to do from here, please tell me how to proceed.

.
Is this because I installed to a folder of my choice instead of home?
Is this because I run the script with root?

I am completely lost here.

.
xo - Nicolete Lovejoy

**Comment by forslund** [comment]
Hi, I'll try to recreate the mimic issue. From the output it looks like there may be an issue with the space in the directory name.

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
