### ISSUE TITLE
Common Play framework interacts weird with active timer

### ISSUE THREAD

**Issue by osheroff** [MycroftAI/mycroft-core#3123]
**Describe the bug**
With a running timer, starting to play a song with the CPS asks "do you want to stop the running timer"?  This line: https://github.com/MycroftAI/mycroft-core/blob/1b67bf33e08541c34c331e7980ce0d6b4bc9c708/mycroft/skills/common_play_skill.py#L163 emits a "mycroft.stop" event, which is interpreted by the timer skill as intending to stop the timer.

**To Reproduce**
1. "Start a timer for 5 minutes"
2. "Play songs by Tom Waits on Spotify"

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
