### ISSUE TITLE
mycroft-config using deprecated --tempfile when falling back to nano

### ISSUE THREAD

**Issue by smokejohn** [MycroftAI/mycroft-core#3124]
**Describe the bug**
In the case where mycroft-config tries to use nano because sensible-editor is not available on the system it uses the deprecated --tempfile parameter which newer versions of nano don't recognize anymore.

**To Reproduce**
1. Fresh install ArchLinuxARM-rpi-armv7-latest or any system without sensible-editor and nano >= 5.0
2. mycroft-config edit user
3. nano doesn't start and prints error about unrecognized option

```
nano: unrecognized option '--tempfile'
Type 'nano -h' for a list of available options.
Configuration unchanged.
```

**Expected behavior**
Open mycroft config with nano without erroring out.

**Fix**
- replace deprecated --tempfile with --saveonexit
- https://www.nano-editor.org/news.php (was deprecated and changed on July 29, 2020)

**Environment:**
 - Device type: Raspberry PI 3b
 - OS: ArchLinuxARM-rpi-armv7-latest
 - Mycroft-core version: [21, 2, 2]

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
