### ISSUE TITLE
If mycroft home is blocked then dont try to pair

### ISSUE THREAD

**Issue by kingpinzs** [MycroftAI/mycroft-core#3125]
**Describe the bug**

**To Reproduce**
1. block home.mycroft.ai
2. try to use mycroft
3. get pair my device

Cause 
https://github.com/MycroftAI/mycroft-core/blob/eb97bb339e506143ba40c162d09c66139c651315/mycroft/stt/__init__.py#L300
`    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except HTTPError as e:
            if e.response.status_code == 401:
                LOG.warning('Access Denied at mycroft.ai')
                # phrase to start the pairing process
                return 'pair my device'`

**Expected behavior**
allowed to use mycroft with out some skills

**Comment by JarbasAl** [comment]
you may want to look at https://github.com/OpenVoiceOS/OVOS-local-backend

mycroft-core does not work without the servers, but you can point the config to a "fake" server

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
