### ISSUE TITLE
ERROR 15894 | mycroft.client.speech.listener:transcribe:239 | list index out of range

### ISSUE THREAD

**Issue by justinsanjp** [MycroftAI/mycroft-core#3127]
11:15:29.359 | ERROR    | 15894 | mycroft.client.speech.listener:transcribe:239 | list index out of range
 11:15:29.360 | ERROR    | 15894 | mycroft.client.speech.listener:transcribe:240 | Speech Recognition could not understand audio

**Comment by krisgesling** [comment]
Hi there, this means that the speech to text service could not extract anything from the audio that was sent. 

It might be from a false activation - eg no one was actually speaking to the device, or if you get it a lot there might be an issue with your microphone.

If it might be a mic issue, I'd suggest checking out our [Audio Troubleshooting Guide](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/troubleshooting/audio-troubleshooting). You can also configure Mycroft to keep the audio recordings that it sends to the STT service which can help to debug things like this. Here's the setting to do that: https://github.com/MycroftAI/mycroft-core/blob/master/mycroft/configuration/mycroft.conf#L174

More broadly, I think we should make the error message more descriptive. `list index out of range` really sounds like a bug in the software.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
