### ISSUE TITLE
Broken PWD in start-mycroft.sh

### ISSUE THREAD

**Issue by Tony763** [MycroftAI/mycroft-core#3137]
Hi commit 56ceb80179a79dfb294f0b3eecdc6612642964c1 break function of `start-mycroft.sh`. 

As pointed by @emphasize, when `mycroft-start` is called, `SOURCE="$0"` will point to `/srv/mycroft-core/bin` and thus break function as everything is run in incorrect directory. If `start-mycroft.sh` is used directly, it works.

The main indicator is: `Please update dependencies by running ./dev_setup.sh again.`

Even if `dev_setup.sh` run again, the message won't go away.

Under hood,  `start-mycroft.sh` try to check MD5 from `.installed` but it is not found (no user alert about missing file)

@krisgesling This is why GitHub Actions stopped working in Home Assistant skill.

```
Autoupdate: false
cat: .installed: No such file or directory
/srv/mycroft-core/bin
Please update dependencies by running ./dev_setup.sh again.
```

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
