### ISSUE TITLE
latest picroft install stuck in CLI "please wait a moment as I finish......."

### ISSUE THREAD

**Issue by geetee24** [MycroftAI/mycroft-core#3141]
install picroft on rpi 4.
at point where docs say the cli should show the reg code, instead, after waiting 20 minutes and speaking to picroft, it STILL SAYS 

 Please wait a moment as I finish booting up.

what is broken?

help please?

core 21.2.2

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
