### ISSUE TITLE
Unsupported locale setting with debug

### ISSUE THREAD

**Issue by FQQD** [MycroftAI/mycroft-core#3145]
**Describe the bug**
On my raspberry pi 2b, when i run ./start-mycroft debug, i get the following error:
`pi@raspi2b:~/mycroft-core $ ./start-mycroft.sh debug
Already up to date.
Starting all mycroft-core services
Initializing...
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting background service audio
Starting background service voice
Starting background service enclosure
Starting cli
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/mycroft-core/mycroft/client/text/__main__.py", line 21, in <module>
    from .text_client import (
  File "/home/pi/mycroft-core/mycroft/client/text/text_client.py", line 40, in <module>
    locale.setlocale(locale.LC_ALL, "")  # Set LC_ALL to user default
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting`

**To Reproduce**
1. Do ./start-mycroft debug
2. See error in logs

**Expected behavior**
Starting the debug

**Environment (please complete the following information):**
 - Device type: Raspberry Pi 2 Model B Rev 1.1
 - OS: Raspbian GNU/Linux 10 (buster) armv7l
 - Mycroft-core version: just downloaded from main github today

**Comment by FQQD** [comment]
imma close it, since no one else seems to have the issue or care about it and i just dont use mycroft

**Comment by JarbasAl** [comment]
you may want to look into OVOS/Neon

https://community.mycroft.ai/t/faq-ovos-neon-and-the-future-of-the-mycroft-voice-assistant/
