### ISSUE TITLE
unmet dependencies error on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by XracerX** [MycroftAI/mycroft-core#3146]
**Describe the bug**
when running bash dev_setup.sh

it errors out

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libicu-dev : Depends: libicu70 (= 70.1-2) but 70.1-2ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.

$ dpkg -l | grep libicu
ii  libicu70:amd64                                              70.1-2ubuntu1                           amd64        International Components for Unicode

**To Reproduce**

bash dev_setup.sh

**Expected behavior**

No error.

**Log files**

/var/log/mycroft# cat setup.log 
 Y - using 'master' branch 
 Y - update automatically 
 Y - Mimic will be built 
 Y - Adding Mycroft commands to your PATH 
Will install PEP8 pre-commit hook...
Interactive portion complete, now installing dependencies...
Installing packages for Debian/Ubuntu/Mint...

**Environment (please complete the following information):**
 - Device type: desktop
 - OS: ubuntu 22.04.1 LTS
 - Mycroft-core version: git master version
 

**Additional context**
nope

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
