### ISSUE TITLE
The start/end_listening sounds should be called with the pulse media.role=phone to enable ducking

### ISSUE THREAD

**Issue by Ramblurr** [MycroftAI/mycroft-core#3148]
**Describe the bug**

When pulse ducking is enabled, the background audio is only ducked when TTS audio is played. But I think the start and end listening sounds  should also be ducked

**To Reproduce**
1. Enable ducking
2. Say "Hey Mycroft.."

Result: The start_listening sound is played, but the existing background music/audio is not ducked.

**Expected behavior**

Play the start/end_listening audio files with the proper pulse audio environment to enable ducking (`media.role=phone`)

**Log files**
If possible, add log files from `/var/log/mycroft/` to help explain your problem.

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: RPI 4 
 - OS: Raspbian
 - Mycroft-core version: ab242a2c821553e6ecde0fa656f3be0331aef738

**Comment by krisgesling** [comment]
I did not know this existed. Nice suggestion!

**Comment by forslund** [comment]
That's a good idea. I wonder if we should create a helper function, `play_audio_and_duck()` (or something) to streamline the experience a bit compared to creating the environment at each call site.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
