### ISSUE TITLE
installation in other debian-related os

### ISSUE THREAD

**Issue by luca-vercelli** [MycroftAI/mycroft-core#3149]
The `./dev_setup.sh` fails under Peppermint, with the error: `Could not find package manager`. I think this also happens with many other non-common Debian-based os'.

This happens because the function `install_deps()` looks for specific os names:

    if os_is_like debian || os_is debian || os_is_like ubuntu || os_is ubuntu || os_is linuxmint

why not just search for apt-get tool? 

    if found_exe apt-get

**Comment by forslund** [comment]
As I recall there were issues with non-debian os's that included apt (or had the possibility to add apt) without it being the primary package manager causing issues. So we couldn't just look at if apt existed on the system.

But maybe that could be added as a fallback? If no supported os was detected check for the specific package managers and try it?

**Comment by MarkMLl** [comment]
Are we talking about apt or the older (but I believe more comprehensive) apt-get here?

**Comment by luca-vercelli** [comment]
The installer uses apt-get, not apt:

https://github.com/MycroftAI/mycroft-core/blob/ab242a2c821553e6ecde0fa656f3be0331aef738/dev_setup.sh#L375

**Comment by luca-vercelli** [comment]
I suggest to add a fallback after all the other `if ` conditions failed, something like 

    [...]
    elif found_exe apt-get
        echo "$GREEN Installing packages for other Debian-related distro...$RESET" | tee -a /var/log/mycroft/setup.log
        debian_install

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
