### ISSUE TITLE
Google Cloud Streaming STT not working

### ISSUE THREAD

**Issue by ipernjakovic** [MycroftAI/mycroft-core#3150]
If you try to use Google Cloud Streaming STT as per documentation:
`mycroft-pip install google-cloud-speech`
pip will install version 2.x in which apparently they removed types and enums, thus breaking the functionality in mycroft. 
In order for Google Cloud Streaming STT to work, the version has to be 1.3.4, at least until the relevant code is rewritten.
So:
`mycroft-pip install google-cloud-speech==1.3.4`

Works perfectly with 1.3.4.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
