### ISSUE TITLE
Mycroft-core broken on Debian testing/sid "Bookworm"

### ISSUE THREAD

**Issue by MarkMLl** [MycroftAI/mycroft-core#3151]
**Describe the bug**
Recurrence of `ModuleNotFoundError: No module named 'requests'` error on latest (non-stable) Debian.

**To Reproduce**
```
$ ./start-mycroft.sh debug
Already up to date.
Starting all mycroft-core services
Initializing...
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting background service audio
Starting background service voice
Starting background service enclosure
Starting cli
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/local/mycroft-core/mycroft/__init__.py", line 17, in <module>
    from mycroft.api import Api
  File "/usr/local/mycroft-core/mycroft/api/__init__.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
**Expected behavior**
Mycroft should start without error. This was working until a few days ago, but has presumably been borked by a recent Debian change.

**Log files**
I have the logfiles from `/var/log/mycroft/` but they are large since I've been trying to characterise a wakeword problem.

**Environment (please complete the following information):**
 - Device type: x86_64 PC, no AVX2.
 - OS: Debian testing/sid "Bookworm"
 - Mycroft-core version: start-mycroft.sh doesn't produce useful output in response to the --version option.
 - Other versions:

**Additional context**
Mycroft is definitely unchanged (unless it's tried updating itself as a part of the failed startup), but Debian is updated regularly since this is a "bleeding edge" system... I'd rather not do anything to break the underlying OS.

**Comment by forslund** [comment]
Did you get any error when running the dev_setup.sh script to set up the mycroft requirements and venv?

**Comment by MarkMLl** [comment]
No. It installed without problems other than that the computer doesn't have AVX2 and Pocket Sphinx appears erratic.

Operation was OK until I checked a couple of days ago, intending to raise the Pocket Sphinx issue on the forum.

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
