### ISSUE TITLE
interface with chat gpt

### ISSUE THREAD

**Issue by NicTanghe** [MycroftAI/mycroft-core#3152]
interface with chat gpt

this whould enable the epitome especially if you can get chatgpt to structure output as readable instruction set.

and have microft respond to errors by asking chatgpt what to do first and then getting back to the user.

**Comment by JarbasAl** [comment]
a roadmap for this here https://github.com/OpenVoiceOS/ovos-core/issues/297

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
