### ISSUE TITLE
Install of latest master branch uninstalls Gnome desktop environment without warning.

### ISSUE THREAD

**Issue by JOH451** [MycroftAI/mycroft-core#3155]
**Describe the bug**

Host system is Debian 12 Bookworm with Gnome 43 desktop environment. Installing latest master branch causes the Gnome DE to be removed while installing dependencies.

**To Reproduce**

Install standard Debian 12 Bookworm with Gnome 43 DE.
Apply latest Debian updates.
Install latest Mycroft AI master branch using standard instructions.

Gnome 43 is uninstalled during installation of dependencies.

**Expected behavior**

Should not happen. Uninstalling a major component of the system without warning is unacceptable.

**Log files**

Terminal session to the point where dependency installation failed.

steve@debian12:~$ git clone https://github.com/MycroftAI/mycroft-core.git
Cloning into 'mycroft-core'...
remote: Enumerating objects: 556412, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 556412 (delta 0), reused 1 (delta 0), pack-reused 556411
Receiving objects: 100% (556412/556412), 117.32 MiB | 8.84 MiB/s, done.
Resolving deltas: 100% (545742/545742), done.
steve@debian12:~$ cd mycroft-core
steve@debian12:~/mycroft-core$ bash dev_setup.sh
Creating /var/log/mycroft/ directory
[sudo] password for steve: 

                    Welcome to Mycroft!  

This script is designed to make working with Mycroft easy.  During this
first run of dev_setup we will ask you a few questions to help setup
your environment.

Do you want to run on 'master' or against a dev branch?  Unless you are
a developer modifying mycroft-core itself, you should run on the
'master' branch.  It is updated bi-weekly with a stable release.
  Y)es, run on the stable 'master' branch
  N)o, I want to run unstable branches
Choice [Y/N]:  Y - using 'master' branch 
branch 'master' set up to track 'origin/master'.
Switched to a new branch 'master'

Mycroft is actively developed and constantly evolving.  It is recommended
that you update regularly.  Would you like to automatically update
whenever launching Mycroft?  This is highly recommended, especially for
those running against the 'master' branch.
  Y)es, automatically check for updates
  N)o, I will be responsible for keeping Mycroft updated.
Choice [Y/N]:  Y - update automatically 

Mycroft uses its Mimic technology to speak to you.  Mimic can run both
locally and from a server.  The local Mimic is more robotic, but always
available regardless of network connectivity.  It will act as a fallback
if unable to contact the Mimic server.

However, building the local Mimic is time consuming -- it can take hours
on slower machines.  This can be skipped, but Mycroft will be unable to
talk if you lose network connectivity.  Would you like to build Mimic
locally?
Choice [Y/N]:  N - skip Mimic build 

There are several Mycroft helper commands in the bin folder.  These
can be added to your system PATH, making it simpler to use Mycroft.
Would you like this to be added to your PATH in the .profile?
Choice [Y/N]:  Y - Adding Mycroft commands to your PATH 
Type mycroft-help to see available commands.

The standard location for Mycroft skills is under /opt/mycroft/skills.
This script will create that folder for you.  This requires sudo
permission and might ask you for a password...
Created!
For convenience, a soft link has been created called 'skills' which leads
to /opt/mycroft/skills.

(Developer) Do you want to automatically check code-style when submitting code.
If unsure answer yes.

Choice [Y/N]: Will install PEP8 pre-commit hook...

Interactive portion complete, now installing dependencies...

Installing packages...
 Installing packages for Debian/Ubuntu/Mint...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.39.2-1.1).
python3 is already the newest version (3.11.2-1+b1).
python3 set to manually installed.
python3-dev is already the newest version (3.11.2-1+b1).
python3-dev set to manually installed.
python3-setuptools is already the newest version (66.1.1-1).
python3-setuptools set to manually installed.
libtool is already the newest version (2.4.7-5).
libtool set to manually installed.
libffi-dev is already the newest version (3.4.4-1).
libffi-dev set to manually installed.
libssl-dev is already the newest version (3.0.9-1).
libssl-dev set to manually installed.
autoconf is already the newest version (2.71-3).
autoconf set to manually installed.
automake is already the newest version (1:1.16.5-1.3).
automake set to manually installed.
libglib2.0-dev is already the newest version (2.74.6-2).
curl is already the newest version (7.88.1-10+deb12u1).
libicu-dev is already the newest version (72.1-3).
libicu-dev set to manually installed.
pkg-config is already the newest version (1.8.1-1).
pkg-config set to manually installed.
libjpeg-dev is already the newest version (1:2.1.5-2).
libjpeg-dev set to manually installed.
build-essential is already the newest version (12.9).
build-essential set to manually installed.
jq is already the newest version (1.6-2.1).
jq set to manually installed.
The following additional packages will be installed:
  libasound2-dev libfann2 libjack-jackd2-dev libout123-0 libportaudiocpp0
  libpulsedsp libsyn123-0 swig4.0
Suggested packages:
  bison-doc libasound2-doc libfann-doc jackd nas oss-compat oss4-base
  portaudio19-doc pavumeter pavucontrol paprefs byobu | screenie | iselect
  swig-doc swig-examples swig4.0-examples swig4.0-doc
The following packages will be REMOVED:
  gnome gnome-core pipewire-alsa pipewire-audio task-gnome-desktop
The following NEW packages will be installed:
  bison flac libasound2-dev libfann-dev libfann2 libjack-jackd2-dev
  libout123-0 libportaudiocpp0 libpulsedsp libsyn123-0 mpg123 portaudio19-dev
  pulseaudio pulseaudio-utils screen swig swig4.0
0 upgraded, 17 newly installed, 5 to remove and 2 not upgraded.
Need to get 5705 kB of archives.
After this operation, 21.1 MB of additional disk space will be used.
Get:1 http://ftp.uk.debian.org/debian bookworm/main amd64 libpulsedsp amd64 16.1+dfsg1-2+b1 [36.8 kB]
Get:2 http://ftp.uk.debian.org/debian bookworm/main amd64 pulseaudio-utils amd64 16.1+dfsg1-2+b1 [88.8 kB]
Get:3 http://ftp.uk.debian.org/debian bookworm/main amd64 pulseaudio amd64 16.1+dfsg1-2+b1 [1174 kB]
Get:4 http://ftp.uk.debian.org/debian bookworm/main amd64 bison amd64 2:3.8.2+dfsg-1+b1 [1175 kB]
Get:5 http://ftp.uk.debian.org/debian bookworm/main amd64 flac amd64 1.4.2+ds-2 [166 kB]
Get:6 http://ftp.uk.debian.org/debian bookworm/main amd64 libasound2-dev amd64 1.2.8-1+b1 [110 kB]
Get:7 http://ftp.uk.debian.org/debian bookworm/main amd64 libfann2 amd64 2.2.0+ds-8 [61.7 kB]
Get:8 http://ftp.uk.debian.org/debian bookworm/main amd64 libfann-dev amd64 2.2.0+ds-8 [90.2 kB]
Get:9 http://ftp.uk.debian.org/debian bookworm/main amd64 libjack-jackd2-dev amd64 1.9.21~dfsg-3 [59.7 kB]
Get:10 http://ftp.uk.debian.org/debian bookworm/main amd64 libout123-0 amd64 1.31.2-1 [28.4 kB]
Get:11 http://ftp.uk.debian.org/debian bookworm/main amd64 libportaudiocpp0 amd64 19.6.0-1.2 [19.9 kB]
Get:12 http://ftp.uk.debian.org/debian bookworm/main amd64 libsyn123-0 amd64 1.31.2-1 [86.1 kB]
Get:13 http://ftp.uk.debian.org/debian bookworm/main amd64 mpg123 amd64 1.31.2-1 [202 kB]
Get:14 http://ftp.uk.debian.org/debian bookworm/main amd64 portaudio19-dev amd64 19.6.0-1.2 [108 kB]
Get:15 http://ftp.uk.debian.org/debian bookworm/main amd64 screen amd64 4.9.0-4 [591 kB]
Get:16 http://ftp.uk.debian.org/debian bookworm/main amd64 swig4.0 amd64 4.1.0-0.2 [1388 kB]
Get:17 http://ftp.uk.debian.org/debian bookworm/main amd64 swig all 4.1.0-0.2 [321 kB]
Fetched 5705 kB in 1s (7406 kB/s)
(Reading database ... 438214 files and directories currently installed.)
Removing gnome (1:43+1) ...
Removing task-gnome-desktop (3.73) ...
Removing gnome-core (1:43+1) ...
Selecting previously unselected package libpulsedsp:amd64.
(Reading database ... 438201 files and directories currently installed.)
Preparing to unpack .../libpulsedsp_16.1+dfsg1-2+b1_amd64.deb ...
Unpacking libpulsedsp:amd64 (16.1+dfsg1-2+b1) ...
Selecting previously unselected package pulseaudio-utils.
Preparing to unpack .../pulseaudio-utils_16.1+dfsg1-2+b1_amd64.deb ...
Unpacking pulseaudio-utils (16.1+dfsg1-2+b1) ...
dpkg: pipewire-audio: dependency problems, but removing anyway as you requested:
 gnome-settings-daemon depends on pipewire-audio | pulseaudio; however:
  Package pipewire-audio is to be removed.
  Package pulseaudio is not installed.

(Reading database ... 438248 files and directories currently installed.)
Removing pipewire-audio (0.3.65-3) ...
Removing pipewire-alsa:amd64 (0.3.65-3) ...
Selecting previously unselected package pulseaudio.
(Reading database ... 438236 files and directories currently installed.)
Preparing to unpack .../00-pulseaudio_16.1+dfsg1-2+b1_amd64.deb ...
Unpacking pulseaudio (16.1+dfsg1-2+b1) ...
Selecting previously unselected package bison.
Preparing to unpack .../01-bison_2%3a3.8.2+dfsg-1+b1_amd64.deb ...
Unpacking bison (2:3.8.2+dfsg-1+b1) ...
Selecting previously unselected package flac.
Preparing to unpack .../02-flac_1.4.2+ds-2_amd64.deb ...
Unpacking flac (1.4.2+ds-2) ...
Selecting previously unselected package libasound2-dev:amd64.
Preparing to unpack .../03-libasound2-dev_1.2.8-1+b1_amd64.deb ...
Unpacking libasound2-dev:amd64 (1.2.8-1+b1) ...
Selecting previously unselected package libfann2:amd64.
Preparing to unpack .../04-libfann2_2.2.0+ds-8_amd64.deb ...
Unpacking libfann2:amd64 (2.2.0+ds-8) ...
Selecting previously unselected package libfann-dev:amd64.
Preparing to unpack .../05-libfann-dev_2.2.0+ds-8_amd64.deb ...
Unpacking libfann-dev:amd64 (2.2.0+ds-8) ...
Selecting previously unselected package libjack-jackd2-dev:amd64.
Preparing to unpack .../06-libjack-jackd2-dev_1.9.21~dfsg-3_amd64.deb ...
Unpacking libjack-jackd2-dev:amd64 (1.9.21~dfsg-3) ...
Selecting previously unselected package libout123-0:amd64.
Preparing to unpack .../07-libout123-0_1.31.2-1_amd64.deb ...
Unpacking libout123-0:amd64 (1.31.2-1) ...
Selecting previously unselected package libportaudiocpp0:amd64.
Preparing to unpack .../08-libportaudiocpp0_19.6.0-1.2_amd64.deb ...
Unpacking libportaudiocpp0:amd64 (19.6.0-1.2) ...
Selecting previously unselected package libsyn123-0:amd64.
Preparing to unpack .../09-libsyn123-0_1.31.2-1_amd64.deb ...
Unpacking libsyn123-0:amd64 (1.31.2-1) ...
Selecting previously unselected package mpg123.
Preparing to unpack .../10-mpg123_1.31.2-1_amd64.deb ...
Unpacking mpg123 (1.31.2-1) ...
Selecting previously unselected package portaudio19-dev:amd64.
Preparing to unpack .../11-portaudio19-dev_19.6.0-1.2_amd64.deb ...
Unpacking portaudio19-dev:amd64 (19.6.0-1.2) ...
Selecting previously unselected package screen.
Preparing to unpack .../12-screen_4.9.0-4_amd64.deb ...
Unpacking screen (4.9.0-4) ...
Selecting previously unselected package swig4.0.
Preparing to unpack .../13-swig4.0_4.1.0-0.2_amd64.deb ...
Unpacking swig4.0 (4.1.0-0.2) ...
Selecting previously unselected package swig.
Preparing to unpack .../14-swig_4.1.0-0.2_all.deb ...
Unpacking swig (4.1.0-0.2) ...
Setting up libpulsedsp:amd64 (16.1+dfsg1-2+b1) ...
Setting up screen (4.9.0-4) ...
Setting up libjack-jackd2-dev:amd64 (1.9.21~dfsg-3) ...
Setting up libout123-0:amd64 (1.31.2-1) ...
Setting up libportaudiocpp0:amd64 (19.6.0-1.2) ...
Setting up libsyn123-0:amd64 (1.31.2-1) ...
Setting up flac (1.4.2+ds-2) ...
Setting up pulseaudio-utils (16.1+dfsg1-2+b1) ...
Setting up bison (2:3.8.2+dfsg-1+b1) ...
update-alternatives: using /usr/bin/bison.yacc to provide /usr/bin/yacc (yacc) in auto mode
Setting up swig4.0 (4.1.0-0.2) ...
Setting up libasound2-dev:amd64 (1.2.8-1+b1) ...
Setting up libfann2:amd64 (2.2.0+ds-8) ...
Setting up libfann-dev:amd64 (2.2.0+ds-8) ...
Setting up swig (4.1.0-0.2) ...
Setting up pulseaudio (16.1+dfsg1-2+b1) ...
Created symlink /etc/systemd/user/default.target.wants/pulseaudio.service → /usr/lib/systemd/user/pulseaudio.service.
Created symlink /etc/systemd/user/sockets.target.wants/pulseaudio.socket → /usr/lib/systemd/user/pulseaudio.socket.
Setting up mpg123 (1.31.2-1) ...
update-alternatives: using /usr/bin/mpg123.bin to provide /usr/bin/mpg123 (mpg123) in auto mode
update-alternatives: using /usr/bin/mpg123.bin to provide /usr/bin/mp3-decoder (mp3-decoder) in auto mode
Setting up portaudio19-dev:amd64 (19.6.0-1.2) ...
Processing triggers for debianutils (5.7-0.4) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for libc-bin (2.36-9+deb12u1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for dbus (1.14.8-2~deb12u1) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2544k  100 2544k    0     0  6897k      0 --:--:-- --:--:-- --:--:-- 6914k
Collecting pip==20.0.2
  Downloading pip-20.0.2-py2.py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 1.7 MB/s eta 0:00:00
Collecting setuptools
  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl.metadata
  Downloading setuptools-68.1.2-py3-none-any.whl.metadata (6.2 kB)
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
  Downloading wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
Downloading setuptools-68.1.2-py3-none-any.whl (805 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 805.1/805.1 kB 886.5 kB/s eta 0:00:00
Downloading wheel-0.41.2-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 320.9 kB/s eta 0:00:00
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-20.0.2 setuptools-68.1.2 wheel-0.41.2

[notice] A new release of pip is available: 20.0.2 -> 23.2.1
[notice] To update, run: python3 -m pip install --upgrade pip
Installing PEP8 check as precommit-hook
Adding mycroft-core to virtualenv path
Collecting requests<2.26.0,>=2.20.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 166 kB/s 
Collecting gTTS<2.3.0,>=2.2.2
  Downloading gTTS-2.2.4-py3-none-any.whl (26 kB)
Collecting PyAudio==0.2.11
  Downloading PyAudio-0.2.11.tar.gz (37 kB)
Collecting pyee==8.1.0
  Downloading pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting SpeechRecognition==3.8.1
  Downloading SpeechRecognition-3.8.1-py2.py3-none-any.whl (32.8 MB)
     |████████████████████████████████| 32.8 MB 8.8 kB/s 
Collecting tornado~=6.1
  Downloading tornado-6.3.3-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
     |████████████████████████████████| 427 kB 41.6 MB/s 
Collecting websocket-client~=1.2.1
  Downloading websocket_client-1.2.3-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 79 kB/s 
Collecting requests-futures==0.9.5
  Downloading requests-futures-0.9.5.tar.gz (5.3 kB)
Collecting pyserial==3.0
  Downloading pyserial-3.0.tar.gz (133 kB)
     |████████████████████████████████| 133 kB 5.5 MB/s 
Collecting psutil==5.6.6
  Downloading psutil-5.6.6.tar.gz (447 kB)
     |████████████████████████████████| 447 kB 9.0 MB/s 
Collecting pocketsphinx==0.1.0
  Downloading pocketsphinx-0.1.0.tar.gz (503 kB)
     |████████████████████████████████| 503 kB 3.8 MB/s 
Collecting inflection==0.3.1
  Downloading inflection-0.3.1.tar.gz (8.7 kB)
Collecting pillow==8.3.2
  Downloading Pillow-8.3.2.tar.gz (48.8 MB)
     |████████████████████████████████| 48.8 MB 26 kB/s 
Collecting python-dateutil==2.6.0
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194 kB)
     |████████████████████████████████| 194 kB 5.8 MB/s 
Collecting fasteners==0.14.1
  Downloading fasteners-0.14.1-py2.py3-none-any.whl (20 kB)
Collecting PyYAML==5.4
  Downloading PyYAML-5.4.tar.gz (174 kB)
     |████████████████████████████████| 174 kB 28.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/steve/mycroft-core/.venv/bin/python3 /home/steve/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpie_t64j4
       cwd: /tmp/pip-install-8ryni9_p/PyYAML
  Complete output (68 lines):
  /tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!
  
          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.
  
          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.
  
          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************
  
  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/steve/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/steve/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/steve/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 319, in run
      self.find_sources()
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
      mm.run()
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 549, in run
      self.add_defaults()
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 201, in get_source_files
    File "/tmp/pip-build-env-gic5t0t5/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/steve/mycroft-core/.venv/bin/python3 /home/steve/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpie_t64j4 Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 23.2.1 is available.
You should consider upgrading via the '/home/steve/mycroft-core/.venv/bin/python3 -m pip install --upgrade pip' command.
Warning: Failed to install required dependencies. Continue? y/N

**Environment (please complete the following information):**

 - Device type: Dell Optiplex 7010 Desktop
 - OS: Debian 12 Bookworm
 - Mycroft-core version: 21.2.2
 - Other versions: Gnome 43, VirtualBox 7.04

**Additional context**

Fortunately this was a test of the installer using a virtualbox. So a snapshot was restored with no permanent damage.

This worked perfectly okay with the same Mycroft-core version and Debian 11 Bullseye.

I have not studied this extensively but the problem seems to be the requirement for pulseaudio. This conflicts with pipewire-audio which is a dependency of gnome core which is in turn a dependency of gnome itself. There are a number of reports on the internet of this problem with Debian Bookworm. In effect pulseaudio is not compatible with Debian 12 Bookworm when using the default Gnome 43 desktop environment.

That suggests that Mycroft itself is not compatible with a default Debian 12 install. This needs to be highlighted rather than ripping out Gnome without warning or ability to stop it.

Apologies for the terminal log formatting. It was perfectly okay when cut and pasted.

**Comment by TimMensch** [comment]
This fails similarly on Ubuntu 22.04.3.

**Comment by TimMensch** [comment]
Update: Workaround for me was to follow the instructions here:

https://github.com/yaml/pyyaml/issues/736

I make no comment on the Gnome desktop environment issue: I'm just pointing out that if you modify `dev_setup.sh` to have this around line 554, you can successfully install PyYAML:

```bash
echo 'Cython < 3.0' > /tmp/constraint.txt
PIP_CONSTRAINT=/tmp/constraint.txt pip wheel PyYAML==5.4.1

# install required python modules
if ! PIP_CONSTRAINT=/tmp/constraint.txt pip install -r requirements/requirements.txt ; then
    echo 'Warning: Failed to install required dependencies. Continue? y/N'
    read -n1 continue
    if [[ $continue != 'y' ]] ; then
        exit 1
    fi
fi
```

I'm not sure if I need to run `pip` an extra time, but the above code is what worked for me as a workaround.

**Comment by saanvik** [comment]
@TimMensch's solution worked for me.

**Comment by JarbasAl** [comment]
I strongly recommend you move to either OVOS or Neon, mycroft-core is abandonware

https://community.mycroft.ai/t/faq-ovos-neon-and-the-future-of-the-mycroft-voice-assistant/13496

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
