### ISSUE TITLE
Installation on macOS 12.6.6 errors

### ISSUE THREAD

**Issue by mikkimichaelis** [MycroftAI/mycroft-core#3157]
execution of dev_setup.sh produces the following

./dev_setup.sh: line 161: read: -N: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]

Removing -N1 from the script allows execution. However /proc/cpuinfo is not found prompting to use PocketSphinx with a Y/N question.  Pressing Y does nothing.

**To Reproduce**
1. clone repo
2. excute bash ./dev_setup.sh
3. edit dev_setup.sh and remove invalid parameters
4. excute bash ./dev_setup.sh press Y

**Environment (please complete the following information):**
 - Device type: MacBook Pro
 - OS: MacOS 12.6.6
 - Mycroft-core version: repo pull

Thank you for your help, I'm excited to give this a try.

**Comment by ChanceNCounter** [comment]
Well, I have bad news, and then I have good news.

The bad news is, MycroftAI is effectively dead. The good news is, that's left a nonprofit fork in charge of the ecosystem. [Here's](https://community.mycroft.ai/t/faq-ovos-neon-and-the-future-of-the-mycroft-voice-assistant/13496?u=chancencounter) a FAQ from the Mycroft forums, and [here](https://www.youtube.com/watch?v=jKpBW3Xvmxg) is a video of our Assistant running natively on Mac...

...which the old Mycroft never could.

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
