### ISSUE TITLE
./dev_setup.sh problem

### ISSUE THREAD

**Issue by Krsth** [MycroftAI/mycroft-core#3164]
My problem is that after downloading mycroft, even if I run the ./dev_setup.sh file and install it, it wants to run ./dev_setup.sh again to run mycroft. 

I'm using linux penguin in chromebook 

That's a codes 

fatihgztk@penguin:~/mycroft-core$ ./start-mycroft.sh all
Please update dependencies by running ./dev_setup.sh again.
fatihgztk@penguin:~/mycroft-core$ ./dev_setup.sh 

                    Welcome to Mycroft!  

This script is designed to make working with Mycroft easy.  During this
first run of dev_setup we will ask you a few questions to help setup
your environment.

Do you want to run on 'master' or against a dev branch?  Unless you are
a developer modifying mycroft-core itself, you should run on the
'master' branch.  It is updated bi-weekly with a stable release.
  Y)es, run on the stable 'master' branch
  N)o, I want to run unstable branches
Choice [Y/N]: tee: /var/log/mycroft/setup.log: Permission denied
 Y - using 'master' branch 
fatihgztk@penguin:~/mycroft-core$ ./start-mycroft.sh all
Please update dependencies by running ./dev_setup.sh again.
fatihgztk@penguin:~/mycroft-core$

**Comment by JarbasAl** [comment]
hello, mycroftAI is dead, and has been for quite some time now, there is no support or updates coming

you might be interested in OpenVoiceOS, a non-profit foundation that forked Mycroft and continued development [openvoiceos.org](https://openvoiceos.org/)

**Comment by forslund** [comment]
Closing PR since we're archiving the repo
