### ISSUE TITLE
Two ideas that come from my personal use case.

### ISSUE THREAD

**Issue by swilso793** [MycroftAI/mycroft-core#317]
1. Maybe Mycroft should first check the defined words from skills. Example: if i say pause and i have defined pause in my third party skills I would almost always want him to understand pause rather than paws or pauls.
2. I don't really like falling back to the wolfram Alpha skill cause it does that mostly when it doesn't understand me. I can always trigger it through it's keyword.

Any suggestions/ideas?

**Comment by Wolfgange3311999** [comment]
So do you think for the second one that Wolfram should only be activated when you say something like `search for the roots of x squared plus three equals zero on Wolfram`?

**Comment by swilso793** [comment]
That sound a bit clunky. What about saying: what can you tell me about blabla for wolfram vs. search about blabla for google?

**Comment by Wolfgange3311999** [comment]
@swilso793 That might do provided we get a Google skill working. My only concern is that the difference is so subtle and arbitrary that it might confuse new users. Although we already do that with the Wikipedia skill (with the phrase `tell me about`).

**Comment by swilso793** [comment]
I tried putting a `return` call right at the first line of the `handle_fallback` function in the `__init__.py` of the WoframAlpha skill and it's awesome. If you have the screens open you don't really need the feedback and it speeds up development by a lot.

**Comment by chrisl8** [comment]
I have to agree on this one. I find two annoying things happening with the WolframAlpha fallback:
1. If I say something "human" like "Hi" or "Good morning", it will go to WolframAlpha  which has some human like interaction. It will say things like, "Hello, human".
Then mycroft sticks "<utterance> is" on the front of it and says, "Hello. is Hello, human."
You can try it with lots of things like "goodbye", "hi", and others.
It makes it feel really clunky when it says, "Hello. is Hello, human." when somebody tries being "silly" with the interface, which I find happens a lot.

2. If mycroft fails miserably at STT, which happens a bit, I get a dump of random data. For instance, for some reason asking about the weather is often interpreted as some city name, like "Oklahoma City", which causes it to start dumping lots of facts about Oklahoma City. This is funny a few times, but eventually I just want it to shut up and tell me it didn't understand me and try again.

**Comment by Wolfgange3311999** [comment]
This brings up a good point slightly unrelated: Perphaps Mycroft should ignore any STT with a confidence lower than a certain value. If I remember correctly, Google gives some level of confidence attached to each proposed transcription. Provided they aren't normalized so that they all add up to `1.0`, that can be used to filter out such occurances. As for the first one, if anything I think it might make more sense to disable the fallback mode in Wolfram and instead make it a skill that uses the regex in EnglishQuestionParser as the vocab.

**Comment by aatchison** [comment]
This issue was resolved a while back.
