### ISSUE TITLE
Mycroft should indicate when it has finished starting.

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#320]
We need Mycroft to indicate when all services are started.

**Comment by Wolfgange3311999** [comment]
We probably don't want him to speak something like "Hello" every time he boots up, especially for those who run Mycroft on something other than a unit. So I would think we'd want a boot up animation for the display and perhaps a short sound when the services finish starting.

**Comment by isaacnward** [comment]
Mycroft now indicates when it is finished starting!

(only on the unit, though)

#335 and #336 are responsible for it
