### ISSUE TITLE
Mycroft should indicate when there is no internet connection.,

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#321]
Since an internet connection is required, we need to know if there is one at any given time.

**Comment by grahamreeds** [comment]
Is it required?

I am not planning on mine being anything more than a home automation
controller.

While finding out what capital city is the highest above sea level is
interesting there is a whole lot you can do inside the network.

GR

**Comment by ethanaward** [comment]
Yeah, it requires an internet connection to use the STT services.

**Comment by grahamreeds** [comment]
How much processing power does STT need? Is there an open source library
that does the same locally?

GR

**Comment by matueranet** [comment]
@ethanaward It might be wise to do a check towards more than only 8.8.8.8 for internet connectivity. If for some reason that Google DNS server is down all Mycroft devices would report they have no internet connectivity. 8.8.4.4 is the secondary DNS server, it seems unlikely that both would be down at the same time, you could do a second check if 8.8.8.8 seems to be down.

**Comment by aatchison** [comment]
How are we on this one @ethanaward ?
