### ISSUE TITLE
Hard Coded Enclosure Code Hangs on Stock Pi 3

### ISSUE THREAD

**Issue by robocoder99** [MycroftAI/mycroft-core#343]
On my Pi 3 with Raspbian Jessie Lite (stock installation) the voice task will hang up after the connection to the message bus with the inclusion of this particular line of code. Never reaches "Waiting for wake word". 

Additionally, this line has the command and the device hard coded rather than using the inbuilt enclosure API. 

This issue has been confirmed on at least one other stock Raspberry Pi 3 running Raspbian Jessie.

https://github.com/MycroftAI/mycroft-core/blob/master/mycroft/client/speech/main.py#L127

**Comment by aatchison** [comment]
Let me know if this works okay for you.
https://github.com/MycroftAI/mycroft-core/pull/344

**Comment by aatchison** [comment]
We should add a value to the configuration file to set unit = True or something similar. That way, product specific features can be enabled or disabled if they can't be separated.

**Comment by aatchison** [comment]
We have addressed this in the latest release.
