### ISSUE TITLE
Fail to register with given code

### ISSUE THREAD

**Issue by Mr5hanMan** [MycroftAI/mycroft-core#345]
I've installed and followed the instruction: https://docs.mycroft.ai/development/cerberus

When I say, "Mycroft, let's register my device" it gives me a code, but when I put it into https://cerberus.mycroft.ai/register

a Pop up occurs saying it has failed.

Any help would be great. Running on Ubuntu 16.0, using Google Chrome browser.

**Comment by aatchison** [comment]
Hello! 
Are you sure that it's the correct code? Sometimes it can be hard to hear. You can check the output of the speech client and read it there as well.

**Comment by movprojects** [comment]
This appears to be an open issue everyone runs into. i fought with it last night on my first install

I fixed my 'failed to register device' by 

1- stopping the mycroft service. ./mycroft.sh stop
2- clear any cookies on the browser set by the cerbus.mycrost.ai server
3- restart mycroft service ./mycroft.sh start
4- also try to do the above and reboot ubuntu or device

**Comment by aatchison** [comment]
I'm really baffled as to why this is happening. Thanks for the cookie info!

**Comment by aatchison** [comment]
This issue doesn't seem to be affecting everyone, closing.

**Comment by Mr5hanMan** [comment]
Resolved this issue, apologies for delayed response. Thanks.

**Comment by aatchison** [comment]
No problem.
