### ISSUE TITLE
[Enhancement]  Client/Device ID in messagebus messages

### ISSUE THREAD

**Issue by joshymcd** [MycroftAI/mycroft-core#347]
My idea (not sure if its already been done) is to have the option of passing in some sort of device or client ID (Could be anything and user definable e.g. a mac address) to the messagebus when making queries, then that id is sent back with every response linked to that message.
This would mean you could have one mycroft server running and clients (such as the android app) can connect to the messagebus and ignore any messages not using its own ID 

Im fine to start working on this as a PR but any comments and guidance would be appreciated 

Josh

**Comment by forslund** [comment]
This has been added by @JarbasAI, closing this issue.
