### ISSUE TITLE
Visemes overwrite screen display

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#358]
On https://github.com/MycroftAI/mycroft-core/pull/357, the mouth animations overwrite the display in cases where the Skill has already placed some information on the display.  For example the stock, spelling or weather skills.

**Comment by isaacnward** [comment]
Does this happen immediately when Mycroft starts saying the information that's getting displayed (as in, the image appears for a split second, then gets overwritten)? If so, I think it's an issue with the mouth listener functionality in enclosure.py. The `__register_mouth_events` and `__remove_mouth_events` methods need to be updated to turn viseme display on and off.

**Comment by penrods** [comment]
This has been corrected in the enclosure code partially.  There is still an issue when the menu is open, so I'm leaving this open for now.

**Comment by aatchison** [comment]
How are we doing here?

**Comment by penrods** [comment]
The latest version of the enclosure code prevents this from happening.  No mycroft-core changes necessary.
