### ISSUE TITLE
Fails if python3 is default

### ISSUE THREAD

**Issue by ParkerMc** [MycroftAI/mycroft-core#360]
In arch python 3 is default you can easy make this change my changing any thing like `python  file name here` to `python  file name here` and `pip install ` to `pip2 install ` this should work on all systems and in the arch install file change stuff like `sudo pacman -S python-pip` to `sudo pacman -S python2-pip` if you need me to test any thing let me know.

**Comment by aatchison** [comment]
Thanks
https://github.com/MycroftAI/mycroft-core/blob/master/dev_setup.sh
Do you think we could check in the dev_setup.sh ?  The virtual env should install python 2.7 right? I added a flag for that. Are you saying that we should replace pip with pip2 in that script
? Feel free to edit the arch build setup script if you like.

**Comment by ParkerMc** [comment]
Sorry I guess I have not been clear. Bow I see how the part I was confused by works. Would you like me to just make the changes and make a pull request?

**Comment by aatchison** [comment]
Sure, make as many PRs as you like. I don't currently run arch on any of my machines, so I wouldn't be able to test that.

**Comment by ParkerMc** [comment]
Fixed with #359 sorry I did not think it would auto add the new commits to the pull request.
