### ISSUE TITLE
Allow for non-speach events

### ISSUE THREAD

**Issue by chrisl8** [MycroftAI/mycroft-core#361]
I would like to be able to put messages onto the bus and "flag" them in some way that will prevent the TTS engine from saying them when the skill emits the "speak" message.

I have in mind that the message could include a "source" key that tracks where the message came from, and the TTS engine will ignore messages with this flag set.

This would allow sending queries to MyCroft via SMS, web, or any other source and picking the result up off of the message bus without MyCroft speaking the answers out loud into the room when the source was not the microphone.

Unfortunately, it seems like none of the data from the original message is preserved through the skill process. The skill simply emits a "speak" message without copying any of the data from the original message into it. It appears to be non-trivial to change this.

**Comment by forslund** [comment]
This can be done now (thanks to @JarbasAI) by using setting the target of an interaction to something other than "audio" allowing for precisely this sort of thing. Closing this issue.
