### ISSUE TITLE
Internet connection check fails when tls is blocked by network

### ISSUE THREAD

**Issue by clccmh** [MycroftAI/mycroft-core#363]
Just as the title says. I am behind a weird firewall on a university network. Every command fails with the response "This device is not connected to the internet"  This is an issue with the connection check. When I edit "client/speech/listener.py", and just remove the check, Mycroft, can process voice commands just fine. I'm not sure if there is a better way to check network connections, but if there is, let me know, and I would be happy to implement it.

**Comment by aatchison** [comment]
Interesting, thanks for creating an issue! We will keep it in mind, and feel free to make changes and a PR if you wish.

**Comment by ethanaward** [comment]
One possible fix that comes to mind is have it not fail when connected to the Internet, just speak. That would still provide the feedback while getting around this issue.

**Comment by aatchison** [comment]
Thanks, I will review your PR

**Comment by clccmh** [comment]
Due to network changes, I can no longer test this issue.
