### ISSUE TITLE
Privacy - Google API

### ISSUE THREAD

**Issue by jsmith000** [MycroftAI/mycroft-core#369]
Heya,

A quick question. How is this supposed to respect my privacy while using Google's API?..

Thank you!

**Comment by penrods** [comment]
Mainly because Google has no information associated with you when we use their APIs.  From their perspective, all requests are coming from "Mycroft".  They have no way to break those out and tie them back to your web browsing history, emails, browser cookies, etc.  Make sense?

**Comment by jsmith000** [comment]
Kind of but still not good enough for me :)

Thank you for the answer though. Waiting for a full open source solution which won't rely on 3rd party services.
