### ISSUE TITLE
dev_setup.sh never ends installing (It eventually did, after several hours)

### ISSUE THREAD

**Issue by sinameraji** [MycroftAI/mycroft-core#371]
When I run dev_setup.sh in terminal, after a while this is what I see:

`ar: `u' modifier ignored since `D' is the default (see `U')
a - cmu_us_slt.o
a - cmu_us_slt_cg_single_mcep_trees.o
a - cmu_us_slt_cg.o
a - cmu_us_slt_cg_single_params.o
a - cmu_us_slt_cg_durmodel.o
a - cmu_us_slt_cg_phonestate.o
a - cmu_us_slt_cg_f0_trees.o
a - cmu_us_slt_spamf0_accent.o
a - cmu_us_slt_spamf0_phrase.o
a - cmu_us_slt_spamf0_accent_params.o

When I try ./start.sh voice I get this error:
Exception: Mimic is not installed. Make sure install-mimic.sh ran properly.

I added install-mimic.sh to dev_setup.sh and still the same thing happens.
How can I get it working?

**Comment by forslund** [comment]
The `ar: u' modifier ignored since D' is the default (seeU')` warning is normal.

The voices takes a long time to build. `cmu_us_slt` shouldn't cause too long wait max a couple of minutes.

**Comment by sinameraji** [comment]
@forslund My macbook gets hot, fan running at 100% and battery life is almost 50% of what it is in OSx. (dualboot ubuntu/osx). 
Do you think installing on virtual machine might help?

**Comment by forslund** [comment]
I don't think a virtual machine would help. The total build time for all voices will probably be a couple of hours, but the files that'll require time will be the `vid_gb_ap_*` files. The other voices (`cmu_us_*`) shouldn't take more than a couple of minutes for each file.

**Comment by ncouture** [comment]
The dev_setup.sh took well over 5 hours to complete on an RPI3 running Ubuntu 16.04 in my case.

Has anyone been cross compiling from x86?

**Comment by sinameraji** [comment]
Yeah I waited for it and it finally completed after several hours!!
Ubuntu is really overheating my macbook and I'm considering dedicating a **Raspberry Pi** to mycroft maybe. 
Is that a good idea?

**Comment by forslund** [comment]
@ncouture the travis CI system cross compiles for Raspberry Pi. Check out https://github.com/MycroftAI/mimic/blob/development/run_testsuite.sh#L159 for how it's done there.
