### ISSUE TITLE
dev_setup.sh ignores WORKON_HOME when VIRTUALENV_ROOT is unset

### ISSUE THREAD

**Issue by ncouture** [MycroftAI/mycroft-core#372]
Working with a shell configured to use virtualenv via virtualenvwrapper may result in the creation of a new virtualenv root directory.

For example if WORKON_HOME is set to $HOME/projects, executing dev_setup.sh will create the $HOME/.virtualenv and use it as the location for the "mycroft" virtual environment.

Since virtualenv's documentation does not describe the use of the VIRTUALENV_ROOT variable, I would like to suggest evaluating if WORKON_HOME is not empty before using VIRTUALENV_ROOT, in which case its value becomes used over VIRTUALENV_ROOT's default.

**Comment by aatchison** [comment]
Interesting. We didn't account for those that might have their own
virtualenvs set up.

**Comment by ncouture** [comment]
@jdorleans this issue has not been close automatically despite the "closes #372" comment in my original commit.
