### ISSUE TITLE
Pairing does not end cleanly

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#373]
The pairing process continues to show the registration code after the pairing completes.  Perhaps this is a non-issue with the new backend server/process?

**Comment by aatchison** [comment]
Perhaps we should just clear the screen after a successful pair. Now that we have the pairing skill, Mycroft knows when he has been activated. I think it would only be a matter of sending a request to the enclosure client to clear the screen.

**Comment by ethanaward** [comment]
Resolved by pairing changes.
