### ISSUE TITLE
review dependencies for update candidates

### ISSUE THREAD

**Issue by ncouture** [MycroftAI/mycroft-core#379]
It seems like the dependencies listed in requirements.txt were never updated, except on a case-by-case basis when some of them failed to provide expected functionality.

As newer versions of Mycroft's dependencies may provide bug fixes and different improvements, I would like to suggest considering running CI against the latest versions the dependencies.

Does anyone have more knowledge on the current state of requirements.txt or thoughts on how (at least some) dependencies could be continually updated to latest providing that CI does not raise issues using them?

**Comment by aatchison** [comment]
This is a good question. I think that we might need better unit test coverage in order to let CI handle it. Any ideas?

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
