### ISSUE TITLE
Write docs on mycroft development environment goals

### ISSUE THREAD

**Issue by clusterfudge** [MycroftAI/mycroft-core#38]
Specifically, why sudo shouldn't be necessary, and why sudo is (in general) bad. This keeps coming up. #32

**Comment by Cliabhach** [comment]
Does it make sense to make our scripts warn heavily, possibly error out, if run in a privileged environment?

**Comment by clusterfudge** [comment]
YES

**Comment by ryanleesipes** [comment]
@Cliabhach Big points for a PR that contains this :smile:

**Comment by Cliabhach** [comment]
I've got a basic snippet:

```
if [ "$(id -u)" == "0" ]; then
  echo "Do not run this script ($0) as root."
  exit 13
fi
```

We've got 2 solutions, I think. We could put this at the top of each file, or place it in one common file that we `source` when necessary. I'm assuming the latter is preferable?

**Comment by clusterfudge** [comment]
Ha! I didn't see this, and implemented almost the exact same thing :+1: 

I have this as well as "sandbox your dependencies" rant coming in with a PR.
