### ISSUE TITLE
On the Cerberus page: Premium subscribers still prompted to subscribe.

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#39]
We need to check for description status before we display the premium subscription proposition.

**Comment by ryanleesipes** [comment]
Not sure who to assign this to, @senseiner @jdorleans ? I assume Jonathan, but not sure.

**Comment by ryanleesipes** [comment]
Once again assigning to @ethanaward

**Comment by ryanleesipes** [comment]
Currently in QA in another repo, closing.
