### ISSUE TITLE
ALSA Music Playback, Device Release & Blocking

### ISSUE THREAD

**Issue by joshua-montgomery** [MycroftAI/mycroft-core#394]
When playing back music using Pianobar the process grabs the device and won't share.

If you adjust the volume or Mimic renders sound while Pianobar is playing, the audio is cached and isn't played until Pianobar releases the hardware device (which happens between songs).

When the hardware device is released, the sound plays, but Pianobar (which is between songs remember) tries to grab the hardware again and fails.

This behavior stops Pianobar playback and hangs the process.  We need to give better thought to how to share the audio hardware / software so that the device can play more than one sound at a time.  Alternatively we need to drop incoming requests for the audio hardware into /dev/null until the process that has it locked out is done with it.

**Comment by joshuajaharwood** [comment]
I've had the same issue - running raspotify and Mycroft at the same time has been a nightmare. I may be able to chalk some of that frustration up to Seeed's drivers overwriting my asound.conf with garbage, though.

**Comment by forslund** [comment]
Using raspotify together with mycroft shouldn't be an issue. Are you using Pulseaudio or just alsa?

**Comment by joshuajaharwood** [comment]
> Using raspotify together with mycroft shouldn't be an issue. Are you using Pulseaudio or just alsa?

Both. Raspotify only works when set to use hw:0,1 though; It also only supports ALSA currently.

**Comment by forslund** [comment]
Hmm, that's weird, I've used raspotify without hardcoding the alsa device...Even if alsa is the only supported backend pulseaudio's alsa plugin should handle it...though if a specific device is set it won't...

Gonna verify that things work as I think before making any more recommendations...

**Comment by forslund** [comment]
Ok tried on my Mark-1 librespot / raspotify is started with the same user as Mycroft using the alsa backend without device specified. Mycroft uses the default `paplay` command to play audio.

This works and mycroft can talk over the spotify music.

**Comment by joshuajaharwood** [comment]
> Running raspotify on the raspotify user causes issues as pulseaudio is by default single user.

That must be it - I'm using the default Raspbian package which sets it up as the raspotify user. Thanks for the heads up!

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
