### ISSUE TITLE
Reset Password from Faceplate

### ISSUE THREAD

**Issue by joshua-montgomery** [MycroftAI/mycroft-core#399]
Lets impliment a new feature that lets you reset the pi user password from the faceplate.

Select "Reset Password" and the faceplate displays it ( while Mycroft says it out loud ).  Then call the passwd feature.  Also: can someone please check to make sure that - if the root account has a login shell - that the password is randomized on first-boot.

Use only non-ambiguous characters. ( NOT 0OI1 etc.)

**Comment by krisgesling** [comment]
Closing in favor of referenced issue in Mark 1 enclosure repo.
