### ISSUE TITLE
Codebase is not PEP8 compliant

### ISSUE THREAD

**Issue by ikeydoherty** [MycroftAI/mycroft-core#4]
To better suit collaboration (and clean code) the codebase should be entirely PEP8 compliant.

`autopep8` might be the saving grace for the initial step here. A test should also be added, perhaps
as part of Travis CI. Might want to add pipe exit code checking here.

`find . -name "*.py"` | xargs pep8

This is a subtask of issue #2

**Comment by elopio** [comment]
pep8 is so much fun ^_^
I'll be back with a PR.

**Comment by ryanleesipes** [comment]
Thank you @elopio!
