### ISSUE TITLE
Mismatch between `oh` and `zero` when pairing

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#401]
When pairing, Mycroft will say `oh` when pronouncing the number 0, which leads to errors when attempting to enter the pairing code.

**Comment by akacipher** [comment]
Yeah that is the mimic issue or more accurately I'll bet on the voice you are using, some people use to say 
letter 'o' when they actually mean zero. For now try different voice or change the TTS engine, this worked for me.

**Comment by aatchison** [comment]
Merged, closing
