### ISSUE TITLE
Update License.md and file headers to Apache 2.0

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#403]
This is in reference to:
https://github.com/MycroftAI/mycroft-core/pull/400

**Comment by Cliabhach** [comment]
Cross references to associated PRs:
#404 
#405

**Comment by aatchison** [comment]
@penrods, shall I close this issue, or does it require further discussion?

**Comment by penrods** [comment]
Keep it open, we need to change the licensing around the interfaces that are needed by Skill writers (the Skill API) to GPLv3 with Classpath Exception.  See an in-depth discussion of my reasoning at:
http://softwareengineering.stackexchange.com/questions/119436/what-does-gpl-with-classpath-exception-mean-in-practice/326325#326325
And don't just take my word for it, the LGPL is legally ambiguous outside of C:
http://stackoverflow.com/questions/8580223/using-python-module-on-lgpl-license-in-commercial-product
Maybe LGPL with Python would hold up in court, but why would we make a company that wants to use Mycroft risk it?


It is going to be a little work making the license change as the exact set of files to include in this isn't clean, and I need to verify that everyone who has contributed to them agrees.  Sean Fitzgerald was on board with it when we discussed a little while back.  Here is a list of classes utilized by existing Skills -- i.e. things that likely should contain the Exception.

	from adapt.intent import IntentBuilder
	from adapt.tools.text.tokenizer import EnglishTokenizer
	from adapt.engine import IntentDeterminationEngine

	from mycroft.messagebus.message import Message
	from mycroft.pairing.client import DevicePairingClient
	from mycroft.skills.core import MycroftSkill
	from mycroft.skills.scheduled_skills import ScheduledCRUDSkill
	from mycroft.util.log import getLogger
	from mycroft.util import play_mp3
	from mycroft.configuration import ConfigurationManager

	from mycroft.identity import IdentityManager

**Comment by forslund** [comment]
I consider this one complete (since #1128). Closing.
