### ISSUE TITLE
third party skills directory

### ISSUE THREAD

**Issue by BongoEADGC6** [MycroftAI/mycroft-core#407]
Previously there was a setting for "third_party_skills_dir" in mycroft.ini.

Recently, the setting has been removed as it recognizes the new mycroft.conf config file. 

Is there a way to work on skills in an outside directory again?

Thanks

**Comment by aatchison** [comment]
I believe that you can do it here
https://github.com/MycroftAI/mycroft-core/blob/master/mycroft/configuration/mycroft.conf#L8

**Comment by BongoEADGC6** [comment]
I tried to change that setting and still get nothing. I've also placed my previously working skill into the ~/.mycroft/skills directory and it doesn't recognize it. Has something changed in the newest merge that broke that third party skills directory?

**Comment by penrods** [comment]
My recommendation for Skills is here:

THIRD_PARTY_SKILLS_DIR = "/opt/mycroft/skills"

Regardless of what user is running Mycroft, that should work.

**Comment by BongoEADGC6** [comment]
Looks like I've found my error with my skill.

~/.mycroft/skills works just fine. I had an error due to the new API. Works like a charm now!

**Comment by aatchison** [comment]
Wahoo!

**Comment by jdorleans** [comment]
Good to know!!
