### ISSUE TITLE
Not registering with home.mycroft.ai

### ISSUE THREAD

**Issue by bengjerstad** [MycroftAI/mycroft-core#408]
I am having the same problem as [this user](https://community.mycroft.ai/t/how-t-register-device-on-https-home-mycroft-ai/1095).

Every time I type my code into the Registration Code box on https://home.mycroft.ai/#/device/add?_k=XXXXX, it says "Code doesn't look right. Check for typos." I have double checked the code from the log, but it is not working. When I stop and start the services, it will give me a new code, but the new code never works either.

**Comment by bengjerstad** [comment]
I just re-cloned the repo and reinstalled, because I noticed that I had a .ini config file instead of a .conf file. 

It worked this time, so I guess the code I was using a few days ago was before the API switch.

**Comment by jdorleans** [comment]
Thx a lot for the feedback... keep it going!!
