### ISSUE TITLE
install_pygtk.sh cd: too many arguments

### ISSUE THREAD

**Issue by JenteA** [MycroftAI/mycroft-core#410]
When running ./dev_setup.sh on Arch Linux the script gives an error when wanting to run script install_pygtk.sh 
line 72 cd: too many arguments
line 73 ./configure file or directory doesn't exist
make: *** No targets given and no Makefile found.  Quit.
make: *** There is no rule to make target Install.  Quit.

**Comment by af7567** [comment]
I just got this same error on Slackware.  The problem is that the script downloads pygtk to pygtk.tar.bz2, extracts it, and then tries to cd to pygtk* which expands to "cd pygtk.tar.bz2 pygtk-2.24.0"

I changed install-pygtk.sh
```
70        curl 'https://pypi.python.org/packages/source/P/PyGTK/pygtk-2.24.0.tar.bz2' > 'pygtk.tar.bz2'
71        tar -xvf pygtk.tar.bz2
72        (   cd pygtk*
73            ./configure --prefix=$VIRTUAL_ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$VIRTUAL_ENV/lib/pkgconfig

```

to

```
70        curl 'https://pypi.python.org/packages/source/P/PyGTK/pygtk-2.24.0.tar.bz2' > 'pygtk.tar.bz2'
71        tar -xvf pygtk.tar.bz2
72        rm pygtk.tar.bz2
73        (   cd pygtk*
74            ./configure --prefix=$VIRTUAL_ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$VIRTUAL_ENV/lib/pkgconfig

```

and trying again

**Comment by Hadjimina** [comment]
Can confirm that simply adding `rm pygtk.tar.bz2` in mycroft-core/scripts/install-pygtk.sh works. pygobject & py2cairo both worked on my system without adding this fix.

**Comment by JenteA** [comment]
It works thank you but I now do get another error
![test-1](https://cloud.githubusercontent.com/assets/14938500/21362393/7feb1bf0-c6e8-11e6-96f3-ed6bdc7369b6.jpg)

**Comment by aatchison** [comment]
I believe this issues is fixed. Re-open if otherwise.

https://github.com/MycroftAI/mycroft-core/pull/432
