### ISSUE TITLE
Pip easy_install requires sudo in dev_setup.sh

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#414]
I'm not sure when this changed, but I'm having problems using the dev setup script without sudo on a Raspbian image. `sudo easy_install pip` is working, but I wonder if it's necessary.

> ./dev_setup.sh 
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-2699.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by jdorleans** [comment]
That's weird... shouldn't the dir be `/usr/bin/python`? Could you try that instead?

**Comment by aatchison** [comment]
It seems that we are installing pip several times, once in the build hosts setup, once in the dev_setup, and they don't play well together.

**Comment by clusterfudge** [comment]
easy_install is used to install pip at a fixed version inside the virtualenv. If easy_install is complaining that it needs permissions to install/upgrade pip, that means that the bash session inside dev_setup is not currently operating within the virtualenv. Either virtualenv was not properly installed by build_host_setup, the virtualenv failed to create for some reason, or the virtualenv failed to activate for some reason. 

We absolutely should not change the easy_install command to use sudo, and should fix the underlying cause instead.

**Comment by aatchison** [comment]
Awesome, thank you.

**Comment by lszyba1** [comment]
Was this ever fixed? 
Debian Stable still has this same issue.
Both Dev and master.
I really don't feel comfortable if the script is installing thigs in base computer. Is there a reason it needs sudo?

Thanks
Lucas

**Comment by MatthewScholefield** [comment]
@lszyba1 A lot has changed since this issue was initially created. If you are experiencing something similar, create a new issue so we can get more details on what's not working.
