### ISSUE TITLE
Pep8 errors fail travis.

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#417]
>  pep8 mycroft
mycroft/__version__.py:1:8: E225 missing whitespace around operator
mycroft/version/__init__.py:33:80: E501 line too long (83 > 79 characters)
mycroft/version/__init__.py:38:80: E501 line too long (89 > 79 characters)
mycroft/skills/core.py:142:21: E127 continuation line over-indented for visual indent
mycroft/skills/configuration/__init__.py:57:80: E501 line too long (95 > 79 characters)
mycroft/skills/wolfram_alpha/__init__.py:182:39: E128 continuation line under-indented for visual indent

**Comment by ethanaward** [comment]
Fixed.
