### ISSUE TITLE
Pairing issue

### ISSUE THREAD

**Issue by jswalls110** [MycroftAI/mycroft-core#428]
I have setup Mycroft on a RPi 3.

I am trying to pair it and I keep getting the message
"The code doesn't look right. Check for typos."

It is a 4 digit code. It includes an "Oh". I have tried 0 and O. I have tried upper and lower case. I have tried the old pairing site. I have tried for 2 days with 3 different codes, rebooted 4-5 times.

No good.

Help!

**Comment by jswalls110** [comment]
Just found another post about apt packages have to use cerberus. 

2 different codes have now told me Failed to pair device.

**Comment by jswalls110** [comment]
BTW your docs say Mycroft utters a 6 digit code.

I've only ever gotten 4 digits.

**Comment by jdorleans** [comment]
The pairing code are 6 alpha numeric and upper case characters

**Comment by jswalls110** [comment]
I now see that when looking at the skills log.

But mycroft is only uttering 4 in all instances.

**Comment by jswalls110** [comment]
Even when I enter the code as seen in the log it tells me it is wrong.

**Comment by jswalls110** [comment]
FINALLY home.mycroft.ai has registered me. But I had to read the code off the log not hear it.

**Comment by jdorleans** [comment]
Notice that the log is not precise regarding the code itself. I bet you are typing periods and spaces. They are not acceptable. Remove any period and space.

**Comment by jswalls110** [comment]
I am an IT guy so I know about dots and spaces.
I am just saying that what is said by the front end (4 digits) is not what is seen in the log (6 digits).
I never would have noticed if I hadn't gone back and reread the docs.

**Comment by jdorleans** [comment]
@jswalls110 agreed. It would be really helpful if you could share some of the logs you were seing so it helps us to track any possible issue or improve it in case of misleading.

**Comment by jswalls110** [comment]
Here you are.
Some examples:
I heard 8WUA. Log says:  S. 8. W. 5. U. A
I heard AKLF. Log says: 8. E. K. L. P. F
I heard 4YYA. Log says: G. 4. Y. 5. Y. A
I heard: b3ij. Log says: B. B. 3. F. I. J
And so one. Some times it prompted me and I was busy so I didn't try.
[mycroft-skills.zip](https://github.com/MycroftAI/mycroft-core/files/666725/mycroft-skills.zip)
