### ISSUE TITLE
Sanitizing of pairing codes

### ISSUE THREAD

**Issue by seanfitzgeraldsc** [MycroftAI/mycroft-core#429]
per #428 , @jdorleans indicates that the web ui will accept invalid pairing codes. Users trying to fetch the codes from their device logs will enter them as logged (including spacing and punctuation intended for TTS). Converting them (either in the web UI or on server side receipt) to strip non-alphanumeric characters and validate expected code length would provide a better user experience and higher pairing success rate.

**Comment by jdorleans** [comment]
Thx for the suggestion @seanfitzgeraldsc. We're doing exactly that. It is coming this next release in the end of the week.

**Comment by aatchison** [comment]
We should be good here.
