### ISSUE TITLE
Conflict between new and old system over identity.json

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#434]
Pairing codes are different for Cerberus and Home, but they both use the same identity.json.  So if you are switching back and forth from old to new (e.g. debugging a Skill) you have to go back to re-pair every time.

I think using a different file for the new code will fix this,  e.g. "identity2.json"

**Comment by aatchison** [comment]
https://github.com/MycroftAI/mycroft-core/pull/435
