### ISSUE TITLE
Mycroft configuration file: mycroft.ini not generated

### ISSUE THREAD

**Issue by jcasoft** [MycroftAI/mycroft-core#44]
Mycroft configuration file: mycroft.ini not generated
    /etc/mycroft/mycroft.ini
    $HOME/.mycroft/mycroft.ini

**Comment by ryanleesipes** [comment]
After pairing with Cerberus, do you see these appear?

**Comment by ryanleesipes** [comment]
By jove, he's right. Where are our settings stored! :smiley: @aatchison, @jdorleans ? Let's make sure to update documentation @ethanaward to reflect what happens once the device is paired and your config is pulled down.

**Comment by jcasoft** [comment]
Hello Ryan, i install a fresh copy of raspberry jessie 1.9.1 on a Pi2 on June 6, the Mycroft configuration file mycroft.ini not generated on /etc/mycroft/mycroft.ini or
$HOME/.mycroft/mycroft.ini. But i create manually mycroft.ini with some parameters.
The FLAC conversion utility has not been installed on requirements, but i installed manually (**sudo apt-get install flac**)
The jack_control and pulseaudio not start automatically, but i run 
**jack_control start
pulseaudio --start**

On my Pi2 configuration i use audio jack 3.5 port  with powered speaker  and USB Microphone, and create a file /etc/modprobe.d/alsa-base.conf with the next parameters:

options snd_usb_audio index=0
options snd_bcm2835 index=1

options ssnd slots=snd-usb-audio, snd-bcm2835

**and all working OK for test**

**Comment by seanfitzgeraldsc** [comment]
It's not expected for these files to be generated. They are consumed if they exist.
