### ISSUE TITLE
Weather skill ignores temperature units

### ISSUE THREAD

**Issue by markwmuller** [MycroftAI/mycroft-core#441]
Hi
I'm unsure if I'm missing something obvious, by I'd like Mycroft to give me the temperature in celsius. There's a setting in mycroft.conf, "WeatherSkill":"temperature" which by default is set to "fahrenheit". 

I've tried changing it to "celsius" and "centigrade", but without success. I know my conf file is read, because I've successfully updated the location. 

The "api_key" is currently empty in the conf -- is this perhaps why it's being ignored?

**Comment by markwmuller** [comment]
Sorry, false alarm. It works fine.

**Comment by aatchison** [comment]
No apologies needed, thanks for the feedback!
