### ISSUE TITLE
Add scheduled triggering of skills (events)

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-core#445]
Please add time and date scheduled triggering of skills. 

For example the "Report" skill (when it will be available), which would give a nice morning digest to the user, that it could be set to trigger every morning at a specific time (workdays, weekdays) etc.

**Comment by aatchison** [comment]
This is a good idea!

**Comment by augustnmonteiro** [comment]
@marksev1 we have the schedule skill that you can extend and set a time to execute a action inside your skill
