### ISSUE TITLE
Wifi setup process broken in release 0.8

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#457]
The wifi setup process is broken in release 0.8

**Comment by aatchison** [comment]
Want to hotfix?

**Comment by penrods** [comment]
Let's just roll it out with this Thursday's release

**Comment by penrods** [comment]
I "slipstreamed" this into the same link.  So if you download it again you'll get this fix now.  Also, the next update will automatically be downloaded and applied if you have a working Picroft installation that is already online.

**Comment by nmaas87** [comment]
@penrods Thank you very much, I will try it again next week, I could not install Picroft as the Wifi Setup did not work :)
