### ISSUE TITLE
Fallback handling needs cleaned up

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#495]
The fallback Wolfram handling needs some attention:
* The "perhaps you meant..." has Never been a useful suggestion
* If possible, responses should be parsed and formatted in a friendlier way.  E.g. asking 
      How tall is the Great Wall of China
  responds with the correct but very stilted:
       Great Wall, height : 30 feet (national rank: 89th, world rank: 2045th)
* Only "question" statements should hit Wolfram.  For example, if it hears me say:
       sneezed again
  it looks that up and responds with the useless:
        sneezed (English word) : 1, n

**Comment by forslund** [comment]
I believe all these points have all been handled so: Closing, if you believe one or more of these are still an issue feel free to reopen this issue.
