### ISSUE TITLE
On the profile page of the cerberus website, the save button shows no message

### ISSUE THREAD

**Issue by elopio** [MycroftAI/mycroft-core#5]
When I update my profile and cerberus and hit save, nothing seems to happen. The profile seems to be updated properly because when I refresh the page it has the new values, but no message is shown.

Steps to reproduce:
Go to https://cerberus.mycroft.ai/profile
Edit the location field
Click the Save button

**Comment by aatchison** [comment]
Thanks! This is a known bug that we are busy resolving as we speak.

**Comment by ryanleesipes** [comment]
Currently in QA in another repo, closing.
