### ISSUE TITLE
Remove helloworld skill from Mycroft-Core

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-core#500]
Removing the helloworld skill from mycroft-core aids in the getting-started experience for developers. We can move the example code to the mycroft-skills repository.

Instead, we can create a hello skill that just responds to hello and how are you prompts.

**Comment by penrods** [comment]
Let's call it GreetingsSkill.  It can handle all the social pleasantries.  I used to cover:

["hello", "hi there", "good night", "howdy", "good afternoon", "good evening", "good morning"]
["thank you", "thanks"]

The first batch would respond differently at different times.  Early in the day could generate "good morning", between 3:00 and 5:00 would be "good afternoon", and later would be "good evening".  Otherewise it was a variant of "hello" ('hi', 'hello', 'how are you', etc).  All easy stuff, but made it feel a little less stiff.

**Comment by chrison999** [comment]
I created a fairly simple skill enabling Mycroft to respond to these greetings:

- Good morning
- Good afternoon
- Good evening
- Good night

Take a look here:  https://github.com/chrison999/mycroft-skill-lets-talk

**Comment by augustnmonteiro** [comment]
All skills were removed, now have a repo for each skill

**Comment by moridin1138** [comment]
@kfezer @augustnmonteiro 
The docs need to be updated.  Links to the HelloWorld skill are broken on pages like:
https://docs.mycroft.ai/skill.creation/creating-first-skill
and
https://docs.mycroft.ai/skill.creation

**Comment by kfezer** [comment]
Thanks, creating issue over there!
