### ISSUE TITLE
audio stopped working

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#519]
hi, just made an update from github for mycroft-core, running in a few problems

2017-02-15 19:06:05,753 - CLIClient - INFO - Speak: Here is this hour's news from NPR.
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/
Playing MPEG stream 1 of 1: tts.wav ...

MPEG 1.0 L I cbr37 44100 stereo
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

Note: Illegal Audio-MPEG-Header 0x04000000 at offset 344.
Note: Trying to resync...
Note: Skipped 42 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x03000200 at offset 426.
Note: Trying to resync...
Note: Skipped 44 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x01000400 at offset 510.
Note: Trying to resync...
Note: Skipped 58 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x03000000 at offset 608.
Note: Trying to resync...
Note: Skipped 182 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0xfeff0000 at offset 830.
Note: Trying to resync...
Note: Skipped 4 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0xfffffdff at offset 874.
Note: Trying to resync...
Note: Skipped 6 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0xfcfffbff at offset 920.
Note: Trying to resync...
Note: Skipped 6 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr38 44100 stereo
Note: Illegal Audio-MPEG-Header 0xff000000 at offset 967.
Note: Trying to resync...
Note: Skipped 43 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x01000100 at offset 1050.
Note: Trying to resync...
Note: Skipped 12 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0xfefffeff at offset 1102.
Note: Trying to resync...
Note: Skipped 14 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr38 44100 stereo
Note: Illegal Audio-MPEG-Header 0x00060003 at offset 1157.
Note: Trying to resync...
Note: Skipped 193 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x00000300 at offset 1390.
Note: Trying to resync...
Note: Skipped 36 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

Note: Illegal Audio-MPEG-Header 0x0000feff at offset 1506.
Note: Trying to resync...
Note: Skipped 36 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x00000200 at offset 1582.
Note: Trying to resync...
Note: Skipped 12 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x01000300 at offset 1634.
Note: Trying to resync...
Note: Skipped 70 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 1744.
Note: Trying to resync...
Note: Skipped 10 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0xffffffff at offset 1794.
Note: Trying to resync...
Note: Skipped 2 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x00000100 at offset 1836.
Note: Trying to resync...
Note: Skipped 14 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x02000300 at offset 1890.
Note: Trying to resync...
Note: Skipped 30 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

MPEG 1.0 L I cbr37 44100 stereo
Note: Illegal Audio-MPEG-Header 0x02000000 at offset 1960.
Note: Trying to resync...
Note: Skipped 46 bytes in input.
[src/libmpg123/layer1.c:30] error: Illegal bit allocation value.
[src/libmpg123/layer1.c:171] error: Aborting layer I decoding after step one.

also on all speak events

**Comment by JarbasAI** [comment]
reverting https://github.com/MycroftAI/mycroft-core/pull/514 is a temporary workaround

**Comment by kfezer** [comment]
Sorry, that was my fault.

**Comment by penrods** [comment]
A copy/paste typo ended up sending WAV audio to the MP3 player.

**Comment by kfezer** [comment]
Should be fixed in the latest release, so closing this. Thanks
