### ISSUE TITLE
Unnecessary request to pair after connecting to new network

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#523]
After following these steps, a Mycroft Mark 1 that is already paired will prompt the user to connect to home.mycroft.ai to pair.  But upon reboot, it pairs fine.

1) Pair a device on one wireless network X
2) Shut it down and move it or disable the network X
3) Power the up the device, follow the wifi-setup process.
4) Say "Hey Mycroft, what time is it?"   You will be prompted to pair.

**Comment by forslund** [comment]
I do believe this has been resolved. Closing the issue. Feel free to reopen if it still occurs.
