### ISSUE TITLE
No list of dependencies, nor clear build instructions

### ISSUE THREAD

**Issue by TheNeikos** [MycroftAI/mycroft-core#53]
A basic README should have at least these:

Clear (and distribution agnostic, for gnu/linux at least) install steps to get to a basic working status.
This missing right now (might be incomplete):
- Explicit list of external dependencies
- List of out of tree dependencies (`adapt-parser` is not on pip for example)
- A clear version statement for Python. Using it is fine and dandy, but is it 2 or 3?

An example of what one should do and what one should expect to happen. Right now you say:

> run `./start.sh service`

Sure, but why? And what does it do? What should I expect? Etc...

Looks promising but still some way to go!

**Comment by ryanleesipes** [comment]
Agreed! Thanks for the feedback, I'll see what I can do!

**Comment by ryanleesipes** [comment]
@ethanaward added this to the docs site. I've assigned him to include this in the README.

**Comment by ethanaward** [comment]
This should be fixed by #82.

**Comment by ryanleesipes** [comment]
Going to split these up into more targeted issues. Thanks for the feedback @TheNeikos
