### ISSUE TITLE
Normalize text before intent parsing

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#530]
Text should be "normalized" before intent parsing.  This simplifies the rules needed by Adapt.  Normalization includes several things:
* Removing articles ("a", "an", "the")
* Expanding contractions (e.g. "what's the time" becomes "what is time")

Normalization is a language-specific operation, so it accepts the lang code of the transcription.  The default is assumed to be "en-us".

**Comment by kfezer** [comment]
We did it.
