### ISSUE TITLE
fresh new installation

### ISSUE THREAD

**Issue by danieledema** [MycroftAI/mycroft-core#532]
Hello everyone,
I just installed Mycroft-core from the aur package and tried to run it with the `mycroft.sh` script.
I had the error `Invalid identifier` for the `verify-start` function.

My system is configured with fish as the main shell.
To solve the problem I just changed all the `-` character used in the variables and function names with `_` and now the error disappeared.
For instance, `verify-start` became `verify_start`.

Hoping it would be useful,
thank you,
Daniele

**Comment by aatchison** [comment]
Thank you! I've not checked out the fish shell yet.

**Comment by forslund** [comment]
The mycroft.sh script has been replaced with start-mycroft.sh and I did a quick test with fish under debian and it seems to run fine now.

Closing this issue.
