### ISSUE TITLE
broadcom

### ISSUE THREAD

**Issue by SlickD** [MycroftAI/mycroft-core#534]
After a smooth install I tried to bring Mycroft's voice into play and, after closely watching the error list such as not being able to access CMU plus the inability to find the BCM2835 card, I realized I am running the new BCM2837 on Pi 3, a 64-bit, not 32-bit processor.
Any resolution to this problem?
Also explains why your offerings, like Mark I, are based on Pi 2.
Thanks
Dennis

**Comment by penrods** [comment]
Actually, the Mark I does use a Pi 3.  But it also uses a custom board, basically our own soundcard.

However I use the Picroft image on a generic Pi3 all the time.  How did you install -- with the Picroft image, using apt-get mycroft-core, or pulling down from Github?

**Comment by SlickD** [comment]
used git clone https:github.com/MycroftAI/mycroft-core.git
Just going by the first page of “Getting Started” on the website. How do I get at Picroft image? Will try using apt-get mycroft-core. Where are both located.
Further question: I am also running a WDlabs 375 Gb usb hard drive on my Pi 3. Is that a complication?
Last, I read where future plans are to incorporate vision. Are you considering using “OpenCV”?
Thanks for the super response. Look forward to next mail.
As a curiosity, I have Mycroft shut down and as I’m typing this mail on main computer, Mycroft’s voice pops up on the speaker for Pi. Thinking of writing to Rod Serling on that one.
Dennis Kazar (SlickD)

**Comment by SlickD** [comment]
Found Picroft image but it’s done in Raspbian Lite (Wheezy). Will try the apt-get.
I get the feeling my Pi drive may be complicating things since everything I find for Mycroft is intended for an SD card. The Pi drive comes with a 4 Gb SD card and Raspbian, I think, after a build, may be on the drive.
Dennis

**Comment by forslund** [comment]
Hi, hope this worked for you. Since there's been no communication for a couple of years I'm closing this issue. :)
