### ISSUE TITLE
Apt package cli 

### ISSUE THREAD

**Issue by BongoEADGC6** [MycroftAI/mycroft-core#545]
Where can I access the mycroft-cli from the apt package install?

**Comment by kfezer** [comment]
You should be able to do it through the mycroft-cli-client in terminal.

For now, you might need to switch user to 'mycroft'
https://community.mycroft.ai/t/can-not-work-out-if-mycroft-is-running/1383/2?u=karl

**Comment by BongoEADGC6** [comment]
What I do this it loads but I get no feedback.

**Comment by kfezer** [comment]
You mean you get no response in the cli?

**Comment by BongoEADGC6** [comment]
Thats correct. All services are running. I can speak to it, but when I load `mycroft-cli-client --quiet` it just go to the next line.

`mycroft@xxxx:~$ mycroft-cli-client --quiet`
`mycroft@xxxx:~$`

**Comment by kfezer** [comment]
Ok, that's what mine's doing too. Thanks for confirming.

**Comment by penrods** [comment]
The --quiet is no longer supported.  There is a --simple that skips the curses interface, but that's it.
