### ISSUE TITLE
way to de-register intents

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#553]
in some cases it would be helpful to be able to de-register intents

use case example:

this would also allow intents to only execute if you give a sequence of orders, intent 1 registers intent 2 
intent 2 registers intent 3, if intent 2 not executed intent 2 is de-registered after a timer

continuous conversation use-case https://community.mycroft.ai/t/keep-skill-active-and-store-input-variables/1447/3?u=jarbas_ai

**Comment by JarbasAI** [comment]
seems to work: 

https://github.com/JarbasAI/mycroft---konami-code

personal taste changes, return instead of break, more logs

    def enable_intent(self, intent_name):
        """Reenable a registered intent"""
        for (name, intent, handler) in self.registered_intents:
            if name == intent_name:
                self.registered_intents.remove((name, intent, handler))
                intent.name = name
                self.register_intent(intent, None)
                self.log.info("Enabling Intent " + name)
                return
        self.log.error("Could not Re-enable Intent " + intent_name)

**Comment by augustnmonteiro** [comment]
Hi,

you can use self.disable_intent(name)

thank you!
