### ISSUE TITLE
enhancement - Continuous listening (wakeword on / off)

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#555]
sometimes it is useful to not need wakeword for a while, a flag that could be set trough a control skill to handle this would be welcome, continous listening could also be a general feature, but i do like the configuration control trough intents

Parrot / Dictation Skill: mycroft speaks/writes back everything, every pause we have to say "hey mycroft" very annoying, 

Missing Parameter Requests: "Hey mycroft, play", "play what music?", "hey mycroft, johnny cash" , 

Continuous conversation in general sounds unnatural

Suggestions:
- intents to control this flag, skills can then call this when needed (maybe a convenience function can be added to base skill, for me i'm happy to just emit the intent message)
- when off continuous listening maybe processing last utterance on every 1 or 2 seconds silence periods?

**Comment by redrussianarmy** [comment]
I agree with @JarbasAI . Is there any development related to this issue?

**Comment by JarbasAl** [comment]
the speak method now allows listening after the utterance is spoken, in addition we have a get_response and ask_selection method. We can also manually trigger listening at any time. I consider this issue resolved

**Comment by krisgesling** [comment]
Yeah, as described we now have a range of methods that didn't exist before.

We won't be adding "continuous listening" in the sense of transcribing continuously. So closing the issue.
