### ISSUE TITLE
Mycroft should stop TTS

### ISSUE THREAD

**Issue by jdorleans** [MycroftAI/mycroft-core#56]
Mycroft should be able to stop any TTS engine by voice or button pressing. This task depends on #55.

**Comment by aatchison** [comment]
This issue is particularly encumbered by
https://github.com/MycroftAI/mycroft-core/issues/57

**Comment by ryanleesipes** [comment]
We should get the button press working again.

**Comment by jdorleans** [comment]
@ryanleesipes the current knowing problem we have with the button is related to the hardware. @aatchison thinks it might be caused by a wrong position of the cables that connects the encoder to the arduino. My unit has this problem and I'll try to fix it by switching the cable position during this weekend.

**Comment by ryanleesipes** [comment]
Until you get that fixed, perhaps you could coordinate with @isaacnward to test it on a "good" unit.

**Comment by ryanleesipes** [comment]
So close! It looks like @isaacnward might have a solution started this week. **fingers crossed**

**Comment by ryanleesipes** [comment]
Looks like at this point, if I'm not mistaken, we need to build this into each of the existing skills (to kill Mimic), I guess we can do that via the "stop" function?

**Comment by ryanleesipes** [comment]
Also @jdorleans - @isaacnward fixed our encoder issue.

**Comment by isaacnward** [comment]
The encoder's working now, but there are still two things standing in the way of this issue getting fixed: the lack of stop functionality in existing skills (which I can work on if needed), and the slow response time described in MycroftAI/enclosure#7 (which is a pretty large problem, but I'll be prioritizing it this week).

**Comment by ryanleesipes** [comment]
Alright, let's close this and get a different issue popped up to implement stop functionality into existing skills.

**Comment by jdorleans** [comment]
Guys, this task is about dealing with TTS stop feature. It requires migrating the kill function from inside the core Enclosure to the TTS engines and then stopping any related TTS process properly. 
This task is not about fixing the hardware encoder issue nor stopping skills.

**Comment by isaacnward** [comment]
Solved by #308.
