### ISSUE TITLE
Wolfram Alpha skill breaks if not loaded last

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-core#564]
After chatting with @augustnmonteiro , we need to load the skill last so that it works correctly. 

It might be able to be fixed in the WA skill, so this could be a first thing to try.

**Comment by forslund** [comment]
I think this is not an issue anymore so I'm closing it. If you still consider this to be a problem feel free to reopen. (Also, Hi Karl how's life?)
