### ISSUE TITLE
Echo cancelation in software 

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#57]
In order for the "Mycroft stop" voice command to function while playing audio or TTS, he needs to be able to hear himself over his own speaker. We have  been playing with some pulse audio plugins that might do the job, but the unfortunate facts are:
1. We have to way to manipulate pulse audio streams, sinks, and sources.
2. If I remember correctly, portaudio doesn't play nice with the pulse microphone source.
3. This might cause a lot of overhead.
4. Cross platform compatibility issues.

**Comment by ryanleesipes** [comment]
We'll narrow the scope of this to pertaining to the unit only (unless we can do this in a settings-respecting way on the desktop).

**Comment by the7erm** [comment]
I was playing around with pulse audio echo cancellation the other day.  The cancellation itself seems to work pretty good. 

```
$ pacmd 
Welcome to PulseAudio! Use "help" for usage information.
>>> load-module module-echo-cancel
```

From there you have to open `pavucontrol` and select `Built in analog stereo (echo cancellation ....)` for all your `Playback` sources - you'll have to catch mycroft while he's speaking on the `Playback` tab - weather is good for this - and on the `Recording` you'll also have to set the source.

My biggest gripe about echo cancellation is it really lowers the audio levels.  I'm not sure what it does on a low power device like a pi.  The vu meter doesn't go up very high in comparison.  I'd say it's about 50%~75% of the volume vs without the echo cancellation.

To test how good of a job echo cancellation was doing I opened up audacity and recorded a track from the mic.  Overall ... pretty dang good.

Erm

**Comment by the7erm** [comment]
I guess I should also mention I had some music playing and being piped through echo cancellation during the process as well.

**Comment by forslund** [comment]
I have had good results with this as well. It can be somewhat automated:
```sh
pactl load-module module-echo-cancel source_name=echosource sink_name=echosink
pactl set-default-sink echosink
pactl set-default-source echosource
```
These lines can be run in the terminal and will create and select the echo cancelled source and sink. The lines could also be included in the pulsaudio configuration.

**Comment by aatchison** [comment]
I wonder if we couldn't create a utility for this?

**Comment by universecoder** [comment]
Hi! I would like to create this utility. I am a newbie when it comes to open source, could you guide me?

**Comment by krisgesling** [comment]
Closing in favor of #1478
