### ISSUE TITLE
During Pairing Prompt, Mycroft should read URL with "dot" where periods are present

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core#58]
During Pairing Prompt, Mycroft should read URL with "dot" where periods are present. Currently he just does a break between the different parts of the URL and also does not read "ai" as "A, I" as he should.

**Comment by ryanleesipes** [comment]
@jdorleans, @clusterfudge  I can't find in the code where it reads out "cerberus.mycroft.ai" - can you point me at the right place?

**Comment by Cliabhach** [comment]
@ryanleesipes I think that would be https://github.com/MycroftAI/mycroft-core/blob/master/mycroft/skills/cerberus_config/__init__.py#L41 , https://github.com/MycroftAI/mycroft-core/blob/bdcd8582aa4938102a90d73bc389f10b272975da/mycroft/skills/weather/__init__.py#L135 , possibly elsewhere.

**Comment by ryanleesipes** [comment]
Giving this to @jdorleans

**Comment by Wolfgange3311999** [comment]
Should anything with a period and no space be read as "dot"? For instance, what about right before speaking with mimic, regex replace "([^,. ]).([^,. ])" with "$1 dot $2"?

**Comment by ryanleesipes** [comment]
@Wolfgange3311999 yes, I think that would be good.

**Comment by ryanleesipes** [comment]
@Wolfgange3311999 do you have any idea of how to make this happen? If so I can reassign this to you.

**Comment by jdorleans** [comment]
Guys, let's not change that behaviour in `mimic`. The char . must be a real pause, that's the way it is on a natural language. That said, there is a simpler way of solving that problem. I'll fix that.

**Comment by Cliabhach** [comment]
@jdorleans: we should probably add something to the docs about when to use phonetic spelling (like 'dot') in spoken text.

**Comment by jdorleans** [comment]
@Cliabhach you're right. We do still have much information to add on our docs and some of them are not very easy to identify until they appear as an issue. I'll take care of some of them and add on our docs.

**Comment by ryanleesipes** [comment]
#91 has been Merged, closing this issue. However, I do think we may want to move to using "dot" in Mimic for instances when there aren't spaces between words/numbers on both sides of a period.
