### ISSUE TITLE
How to change wake word

### ISSUE THREAD

**Issue by disheet** [MycroftAI/mycroft-core#590]
how can i change wake word from HEY MYCROFT to some other word?

**Comment by matueranet** [comment]
This is explained in the docs: https://docs.mycroft.ai/installing.and.running/FAQ First item in the FAQ.

**Comment by kfezer** [comment]
I'm going to close this if that answers your question, disheet.

**Comment by disheet** [comment]
hello sir,

How can i adjust the threshold value for  "HEY NOVA" wake word. Is there
any way to predict threshold value or we have to experiment.

thanks

**Comment by kfezer** [comment]
You would have to experiment. I would recommending leaving it the same as it was by default without doing the experimentation. The CLI might help with that, but I know we had some issues with the numbers, so it might vary from machine to machine.
