### ISSUE TITLE
Question: Start Mycroft service with systemd?

### ISSUE THREAD

**Issue by stardiviner** [MycroftAI/mycroft-core#592]
I installed Mycroft and KDE Plasma Plasmoid applet for mycroft from [Arch Linux AUR 1](https://aur.archlinux.org/packages/mycroft-core) and [Arch Linux AUR 2](https://aur.archlinux.org/packages/plasma5-applets-mycroft-git).

**Comment by kfezer** [comment]
Hey there, 

I'm sorry, I don't understand the question, is this a bug or a feature request?
Generally, we like using issues to show bugs and enhancement to the code, not answering questions. The best place for that is going to be the forums:
https://community.mycroft.ai/
or slack:
https://mycroft-ai-slack-invite.herokuapp.com/

I'm going to close this issue for now.
