### ISSUE TITLE
Repeats the answer 

### ISSUE THREAD

**Issue by kashyap32** [MycroftAI/mycroft-core#597]
I am using Picroft Image. If I run python say_commands.py 'what time is it' Mycroft gives the same answer two times, is this something that I am doing it wrong or what?

**Comment by aatchison** [comment]
Hmm, Would you mind doing a `ps aux |grep mycroft` and showing the output here? It's possible that more than one is running at once. Does it happen every time?

**Comment by kashyap32** [comment]
Yes it happens every time and no I don't think so that more than one process running at once!! Still will give you output in some time, Thanks

**Comment by aatchison** [comment]
I see. Hmm, I bet that there is an issue with the say_command utility itself then. Thanks for reporting!

**Comment by pwobus** [comment]
I'm having the same problem of Mycroft giving the same answer two times.  
It appears there are two mycroft-speech-client processes running.
Here is the output from ps aux |grep mycroft:

mycroft    629  0.0  0.3   4972  3372 ?        Ss   18:37   0:00 /lib/systemd/systemd --user
mycroft    642  0.0  0.1   6900  1316 ?        S    18:37   0:00 (sd-pam)
mycroft    709 45.9  6.0 348088 53332 ?        Sl   18:37   9:27 python2.7 /usr/local/bin/mycroft-speech-client
root       711  1.1  2.8 145308 24964 ?        Sl   18:37   0:14 python2.7 /usr/local/bin/mycroft-wifi-setup-client
mycroft    713  5.1  2.7  28280 24256 ?        S    18:37   1:04 python2.7 /usr/local/bin/mycroft-messagebus
mycroft    715 22.8  4.5 203836 40248 ?        Sl   18:37   4:41 python2.7 /usr/local/bin/mycroft-skills
mycroft   1302  6.2  0.9 101340  8652 ?        Sl   18:37   1:16 /usr/bin/pulseaudio --start --log-target=syslog
mycroft   2620 47.5  6.0 347804 53272 ?        Sl   18:38   9:15 python2.7 /usr/local/bin/mycroft-speech-client
pi        2663  0.1  0.0   3432   384 tty1     S+   18:38   0:01 tail -f /var/log/mycroft-speech-client.log
pi        2878  0.0  0.2   4272  1948 pts/0    S+   18:58   0:00 grep --color=auto mycroft

**Comment by el-tocino** [comment]
pwobus, kill one of the speech clients off, if you haven't already. Do you know how you got two instances running?

**Comment by robboz4** [comment]
Today Picroft updated and after a reboot  the double instance has gone away. After the update and before the reboot I had 8 responses to a request. They were also  two slightly different answers. But as I stated the reboot fixed it.

**Comment by forslund** [comment]
I believe the updated picroft images has solved this issue. I'm closing this issue, if you disagree reopen in and we'll continue troubleshooting your issue.
