### ISSUE TITLE
On the cerberus website, the selected menu item doesn't get the selected style

### ISSUE THREAD

**Issue by elopio** [MycroftAI/mycroft-core#6]
On the cerberus website there is a main menu with Home, Profile, Register and Devices items. The selected item seems to be marked with a blue underline, but this underline is always under the Home item even if other is selected.

The attached screenshot shows the Devices page open, but the page shows no indication that it is the active menu item.
![ekrankopio de 2016-05-20 13-01-23](https://cloud.githubusercontent.com/assets/617831/15438898/985d1be4-1e8b-11e6-9c88-11d6f269402f.png)

To reproduce:
Go to https://cerberus.mycroft.ai/device

**Comment by aatchison** [comment]
Thanks, this is also another known issue we are working on. ;)
