### ISSUE TITLE
Limit WolframAlpha fallback usage

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#600]
Right now the "fallback" handling in the WolframAlpha skill gets called for any utterance which isn't recognized as an intent.  This is handy for questions like "how tall is the Washington monument", but not very useful if Mycroft misunderstands a command statement or is just triggered unintentionally and random conversation is heard.  In these cases Mycroft stupidly says "I could not find an answer for whatever random gibberish, perhaps you meant random gibberish?"

Limiting the usage of WolframAlpha to utterances which look like questions solves this.  So we'll only invoke it when the utterance looks like a question, e.g. has what/how/where/when/etc.

**Comment by MatthewScholefield** [comment]
Ultimately, I think we need to send multiple requests to wolfram, wikipedia, and perhaps another api (like you said Christopher did), and generate confidences for the results each one fetches.
