### ISSUE TITLE
Intent Layers - giving state to mycroft

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#606]
More complicated skill will require state

user: ask me a question
mycroft: trigger AskQuestionIntent 
             - speak "Choose 1, black or white" , 
              - go to next state

user: "black"
mycroft: trigger Answer1Intent 
            - speak "good choice" , 
            - back to ground state (or next state)

user: "black"
mycroft: trigger wolphram alpha skill (i guess)

            from mycroft.skills.intent_parser import IntentTree

            in initialize

            layers = [ ["AskQuestionIntent"], ["Answer1Intent", "Answer2Intent]]
            # 60 is the number of seconds for the layer timer
            self.tree = IntentTree(self.emitter, layers, 60)
            self.emitter.on('enable_intent', self.handle_enable_intent)

            to activate next layer/state -> self.tree.next()
            to activate previous layer/state -> self.tree.previous()
            to activate layer/state 0 -> self.tree.reset()
            to get current layer/state -> state = self.tree.current_layer

            each state as a timer, after changing state this timer starts and at the end resets the tree
            to disable timer, after doing next/previous -> self.tree.stop_timer()

            on converse -> parse intent/utterance and reset tree if needed (bad sequence)

Intent Tree code
  
            class IntentTree():
                def __init__(self, emitter, layers = [], timer = 500):
                    self.emitter = emitter
                    # make intent tree for N layers
                    self.tree = []
                    self.current_layer = 0
                    self.timer = timer
                    self.timer_thread = None
                    for layer in layers:
                        self.add_layer(layer)
                    self.activate_layer(0)
            
                def disable_intent(self, intent_name):
                    """Disable a registered intent"""
                    self.emitter.emit(Message("detach_intent", {"intent_name": intent_name}))
            
                def enable_intent(self, intent_name):
                    """Reenable a registered self intent"""
                    self.emitter.emit(Message("enable_intent", {"intent_name": intent_name}))
            
                def start_timer(self):
            
                    self.stop_timer()
            
                    # set new timer
                    def timer():
                        logger.info("New Timer Started")
                        start_time = time.time()
                        while time.time() - start_time <= self.timer:
                            time.sleep(1)
                        # on end of timer reset tree
                        logger.info("Timer Ended - resetting tree")
                        self.reset()
            
                    self.timer_thread = Process(target=timer)
                    self.timer_thread.start()
            
                def stop_timer(self):
                    logger.info("Stopping previous timer")
                    try:
                        # cancel previous timers
                        self.timer_thread.terminate()
                    except:
                        pass
            
                def reset(self):
                    logger.info("Reseting Tree")
                    self.stop_timer()
                    self.activate_layer(0)
            
                def next(self):
                    logger.info("Going to next Tree Layer")
                    self.current_layer += 1
                    if self.current_layer > len(self.tree):
                        logger.info("Already in last layer, going to layer 0")
                        self.current_layer = 0
                    if self.current_layer != 0:
                        self.start_timer()
                    self.activate_layer(self.current_layer)
            
                def previous(self):
                    logger.info("Going to previous Tree Layer")
                    self.current_layer -= 1
                    if self.current_layer < 0:
                        self.current_layer = len(self.tree)
                        logger.info("Already in layer 0, going to last layer")
                    if self.current_layer != 0:
                        self.start_timer()
                    self.activate_layer(self.current_layer)
            
                def add_layer(self, intent_list=[]):
                    self.tree.append(intent_list)
                    logger.info("Adding layer to tree " + str(intent_list))
            
                def activate_layer(self, layer_num):
                    # error check
                    if layer_num < 0 or layer_num > len(self.tree):
                        logger.error("invalid layer number")
                        return
            
                    self.current_layer = layer_num
            
                    # disable other layers
                    logger.info("Deactivating active layers")
                    for i in range(0, len(self.tree)):
                        self.deactivate_layer(i)
            
                    # TODO in here we should wait for all intents to be detached
                    # sometimes detach intent from this step comes after register from next
                    time.sleep(0.3)
                    # enable layer
                    logger.info("Activating Layer " + str(layer_num))
                    for intent_name in self.tree[layer_num]:
                        self.enable_intent(intent_name)
            
                def deactivate_layer(self, layer_num):
                    # error check
                    if layer_num < 0 or layer_num > len(self.tree):
                        logger.error("invalid layer number")
                        return
                    logger.info("Deactivating Layer " + str(layer_num))
                    for intent_name in self.tree[layer_num]:
                        self.disable_intent(intent_name)

**Comment by krisgesling** [comment]
Hey Jarbas, is the intention here to be a more detailed and layered version of conversational context?

**Comment by JarbasAl** [comment]
see usage here https://github.com/JarbasAl/skill-moon-game   non functional due to age

this is packaged in my jarbas_utils - https://github.com/OpenJarbas/jarbas_utils/blob/dev/jarbas_utils/intents/layers.py

closing this issue in favor of a possible PR or maybe just docs for the above. at very least i intend to provide decorators
