### ISSUE TITLE
how can i use google sst instead of mimic?

### ISSUE THREAD

**Issue by disheet** [MycroftAI/mycroft-core#607]
I want to use google sst engine instead of mimic ? what is the procedure?

**Comment by forslund** [comment]
Do you mean Speech to text or Text To Speech?

In the latter case it's really easy, just login to your account at https://home.mycroft.ai and then go to Settings->Advanced and select *Google* under Text-to-speech engine. Save changes at the top of the page and restart Mycroft for the changes to take effect.

**Comment by disheet** [comment]
ok and For that i have to do any changes in program?

**Comment by forslund** [comment]
For text to speech, no. Speech to text I can't say since I haven't tried to use an alternative.

**Comment by disheet** [comment]
ok sir

And more thing i changed wake word as per my requirement. But after that
without speaking wake word it was continuously working...means It is not
waiting for wake word..."hy mycroft"....why its happening?Because of
threshold or some other thing???

**Comment by forslund** [comment]
As this question was answered in another issue I'm closing this. Once again if you have more questions feel free to ask!
