### ISSUE TITLE
after changing wake word it was running continuously with waiting for wake word

### ISSUE THREAD

**Issue by disheet** [MycroftAI/mycroft-core#608]
I changed wake word as per requirement. But after that without speaking wake word it was continuously working...means It is not waiting for wake word..."hy mycroft"....why its happening?Because of threshold or some other thing???

**Comment by MatthewScholefield** [comment]
Yes, try changing the threshold around.

**Comment by forslund** [comment]
I'm closing this since the question seem to have been answered. If you have more questions feel free to open more issues.
