### ISSUE TITLE
Listener Improvements Remove Ability to put "Mycroft" at End of Sentence

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core#61]
Upon further testing of Listener Improvements, PR #45 - it appears that the overall listener has improved, but upon being asked, "What time is it Mycroft" or "What's the weather, Mycroft" - the sentence before is ignored and Mycroft prompts the user to "Go Ahead."

**Comment by ryanleesipes** [comment]
Upon more testing it appears as though the new improvements do often cause Mycroft to opt for call and response "Go Ahead", even when it seems as though it should have been able to process the request.

**Comment by Wolfgange3311999** [comment]
I'm assuming this is the same issue I originally encountered when making this:
The end marker is generated first and often is a bit too far into the wake word segment by a small margin. Afterwards, when generating the begin marker, `self.recognizer.is_recognized()` will always return `False` pushing the begin marker to 0 resulting in the first part of the phrase being cut out.

So to fix this, there are two options. One is to save the last end position where `self.recognizer.is_recognized()` returned true and use it when finding `self.begin`. Another option is to push `self.end` back by something like `2*self.precision` before finding `self.begin`. After finding both markers, `self.end` should be set back to the correct value. Note that `self.end` should not simply be set to the end of the audio file as that would cause it to freak out with something like "mycroft, what is mycroft".

**Comment by ryanleesipes** [comment]
Adding assignee @Wolfgange3311999 to help move this along.

**Comment by Wolfgange3311999** [comment]
@ryanleesipes: Does the silence threshold PR fix this 100% of the time?
