### ISSUE TITLE
i18n: language codes are not always two words.

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [MycroftAI/mycroft-core#610]
Language codes are not always one pair of two letters with "-" as separator. ISO 639 / BCP 47 / IETF language tags (see [here](https://en.wikipedia.org/wiki/IETF_language_tag#ISO_639-3_and_ISO_639-1)) is a near than incomprehensible standard. 

In short, we can say that valid language codes are "es", "en-US", someone with three parts, ... .

Code in stt/__init__.py expects always two words. It could be modified to accept remainder formats.

**Comment by eccco3** [comment]
Is this something that a relative beginner could tackle? I have about 6 months experience with using Python and 1 year of experience programming before that.

**Comment by SoloVeniaASaludar** [comment]
Tests can be done changing in conf file "lang" from default "en-US" to "es".
