### ISSUE TITLE
Weather Location Not Matching Configuration

### ISSUE THREAD

**Issue by devthane** [MycroftAI/mycroft-core#613]
Whenever I change my location via the website device interface, then save, and then refresh, 
everything but the city gets removed.

However, when asking for the weather, (letting mycroft assume I want it at my location) the following happens:

Lets say I have it set for Nashville, TN, US (both in local configuration and online).

Mycroft uses this query to get the weather:
`/v1/owm/forecast?q=Nashville%2C+Tamil+Nadu%2C+India&lang=en`

Seems like no matter what city I put, Nadu India gets appended to the query, 
if I don't specifically say where I would like the weather checked.

This is happening on master currently. I don't believe it's fixed in dev either.

**Comment by augustnmonteiro** [comment]
Hi @thane421 you still having this issue?

**Comment by KaelBaldwin** [comment]
It's been a while since I tried, had to reconfigure my pi to use with octoprint for 3d printing and haven't gotten around to setting up mycroft again. We can close this for now and I'll reopen if I run into it again.

**Comment by wligtenberg** [comment]
I have a similar error.
I selected Tilburg, The Netherlands.
But in the logs I see this:
Tilburg%2C+New+Brunswick%2C+Canada

This leads to obvious wrong results...
This is using a mark 1 unit.

**Comment by forslund** [comment]
This has been a tricky beast to tame but I think earlier this year a couple of fixes relating to the location service finally closed these. I'm closing this issue, but if there still are issues feel free to reopen and/or shout at me for doing this.
