### ISSUE TITLE
E: Unable to locate package pkgconfig

### ISSUE THREAD

**Issue by abhi98khandelwal** [MycroftAI/mycroft-core#615]
I am installing Mycroft(dev branch) for the first time in Ubuntu16. When I run `./build_host_setup_debian.sh` the terminal shows an error "E: Unable to locate package pkgconfig."

I suppose this is due to some typo error of pkg-config in build_host_setup_debian.sh, as it should be "pkg-config" instead of "pkgconfig"

**Comment by aatchison** [comment]
Ahh, thanks. That's my fault. I'll take care of it here.
