### ISSUE TITLE
what is this "voice"?

### ISSUE THREAD

**Issue by disheet** [MycroftAI/mycroft-core#626]
![untitled](https://cloud.githubusercontent.com/assets/19913329/24600535/b79fd80c-1872-11e7-9847-a8876c662254.png)

**Comment by matueranet** [comment]
This is probably the voice argument that is supplied to the espeak command. See https://linux.die.net/man/1/espeak If you manually run `espeak --voices` you get a list of voices.

**Comment by disheet** [comment]
hello sir,

In previous version (0.8.8), There is one directory called Personal was
there in skills directory.But in version 0.8.10  ,It was there. So can you
tell me where I can find that?

Thanks

**Comment by disheet** [comment]
Hello Sir,

I don't want to update mycroft automatically.How can I stop that?

Thanks

**Comment by disheet** [comment]
hello sir,

In previous version (0.8.8), There is one directory called Personal was
there in skills directory.But in version 0.8.10  ,It was there. So can you
tell me where I can find that? And I don't want to update mycroft
automatically.How can I stop that auto update?

Thanks

**Comment by penrods** [comment]
@disheet, If you are using a package install of Mycroft (i.e. via 'apt-get') then there is an automatic update job running once a day.  You can edit that using 'sudo crontab -e'.

With the 0.8.10 release, the Skills are no longer part of mycroft-core.  Skills are now independent.  The default skills are automatically downloaded to /opt/mycroft/skills instead.  So the 'personal' skill is now found at '/opt/mycroft/skills/skill-personal'.

**Comment by forslund** [comment]
I'm closing this since the last questions seem to be answered. If you have more questions feel free to open new issues!
