### ISSUE TITLE
"Waiting for wakeword"

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-core#634]
Should display "Waiting for wake word" every time that's happening.

**Comment by MatthewScholefield** [comment]
For clarification, do you mean constantly like every few seconds or so?

**Comment by kfezer** [comment]
It was mostly a thought, but it's a good indicator that it's ready. I think really it just needs to do it once every time it's done with a dialog out or responding.

**Comment by MatthewScholefield** [comment]
Yeah. It should do it at the moment but it does it instantly after finishing recording so it gets caught up way above. So, I guess we should have it output this once Mycroft finishes executing the skill. Perhaps then, this?:
### Task List
- [ ] Emit event when skill is complete
- [ ] Output "Waiting for wakeword..." only after skill finishes (and mic is unmuted)

**Comment by kfezer** [comment]
Yeah, that makes sense. It might be handy to have events whenever a skill finishes anyway if that isn't something we're already doing. 

For example: 

Music player pauses while you interrupt with a different skill and listens for the event that indicate event finishes, then continues playing.

**Comment by krisgesling** [comment]
Hi there, closing this old issue as things have changed a lot in 3 years. If you still think this is needed please reopen.
