### ISSUE TITLE
Add event when skill completes

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#640]
This is needed for #634 and future things like restarting a media skill when muted while Mycroft speaks.

A rough outline of what I'm pretty sure needs to be done is the following:
- [x] [Here][audio-speech] and [here][audio-text], make `audio_output_end` events only get emitted when the audio is truly done (not another one queued up). Note that currently I believe speak requests get "queued" up by acquiring and releasing a mutex (called `lock`) that prevents the function from executing in different threads at the same time.
  - [x] Abstract out `speak()` (currently it's a bit ugly in the text client and repeats what's in the speech client)
- [ ] [Over here][intent-handler] set an event emitter to execute something that outputs another event once on the next `audio_output_end`.

[audio-speech]:https://github.com/MycroftAI/mycroft-core/blob/0fe6ee65e0bcb737a13942a25b1d50b2a24dd094/mycroft/client/speech/main.py#L73
[audio-text]:https://github.com/MycroftAI/mycroft-core/blob/dc53c9571bb467b2422cf0378c4657ce6974918f/mycroft/client/text/main.py#L195
[intent-handler]:https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/core.py#L251

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
