### ISSUE TITLE
Picroft pairing issue.

### ISSUE THREAD

**Issue by amcgee7** [MycroftAI/mycroft-core#658]
It seems that a fresh install of picroft can have some trouble pairing.The time I did it required that I reboot a couple of times to get updates and to get it working.  It did seem to pair the first time but Picroft didn't think it was paired.  I deleted the device and tried to re-pair and I found it wouln'd accept the code.  The code hadn't changed.  After a reboot and update it seem to show up as paired and seems to work.  But I don't have the device on home.mycroft.ai because I deleted it from before.

**Comment by amcgee7** [comment]
@aatchison remember the user isn't likely to wait.   Just try to jump right in and pair.  Other wise we should make part of the process of connecting to wifi to reboot and update before pairing.  I also did this with a code displayed on the cli

**Comment by augustnmonteiro** [comment]
Fixed!
