### ISSUE TITLE
Git install broken after pull

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#659]
The recent change breaking out Skills from mycroft-core has broken installations in several ways:
* Naming the file Intent.py doesn't work on a pre-existing install, the folder Intent exists already and contains __init__.pyc.  So "import mycroft.skill.intent brings in the folder's __init__.py, not the intent.py file.
* The msm.sh script isn't necessarilly on the system, thus skill installation breaks.

**Comment by augustnmonteiro** [comment]
Fixed!
