### ISSUE TITLE
When Skill Intent fails, does not notify user audibly

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-core#673]
Add audible signal that the intent failed:

Right now all that happens is silence and a debug message. This should be an error, IMO.

For example:
Skills - DEBUG - {"type": "intent_failure", "data": {"lang": "en-US", "utterance": "what time is it"}, "context": null}

**Comment by forslund** [comment]
This has been implemented. An apology is extended when no skill can handle the intent.
