### ISSUE TITLE
Mycroft doesn't starts if /etc/mycroft/mycroft.conf exists and has comments

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [MycroftAI/mycroft-core#685]
In log.py there are these statements:

if isfile(SYSTEM_CONFIG):
    with open(SYSTEM_CONFIG) as f:
        config = json.load(f)
        log_level = config.get("log_level", "DEBUG")

note no filter of comments has been done using "load_commented_json".

Note: no pull request will be done, because could be the best solution is do not load any config here but use the common configuration procedure.

**Comment by aatchison** [comment]
Thanks!
We do actually use that config file for system specific configuration such as platform detection in a Picroft image, so it has some purpose for us.
In a development setup, it would probably be best to use the user level mycroft.conf.

**Comment by penrods** [comment]
All of our JSON loading should use load_commented_json().  Thanks for pointing this out.

**Comment by SoloVeniaASaludar** [comment]
Hi Arron, 

I do not discuss the necessity of the file /etc/mycroft/mycroft.conf. However,  "log.py" has its own config data and load method (using a single file). Could be interesting this module uses the common config data and the common load method of this data (including the usual multi-file configuration).

Kind regards.
