### ISSUE TITLE
Use python included uuid rather than third party

### ISSUE THREAD

**Issue by nullr0ute** [MycroftAI/mycroft-core#690]
Git commit cd1a36b added uuid (https://pypi.python.org/pypi/uuid/1.30) as a dependency that doesn't support python3 and is unmaintained (last release was 2007). The python standard library already includes a rfc4122 generator so that should be used instead (https://docs.python.org/2/library/uuid.html).

**Comment by aatchison** [comment]
Thanks!

**Comment by nullr0ute** [comment]
I don't believe this is fixed, it still lists the other uuid in the requirements.txt in master

**Comment by forslund** [comment]
Hmmm, it's present in the dev branch too. The package doesn't seem to be neccessary. Mycroft seems to run fine without it installed (using the one from standard lib). @ethanaward is looking over the requirements.txt in PR #805. I'll ask him to look at this aswell.

**Comment by MatthewScholefield** [comment]
Closing since uuid is no longer in the requirements.
