### ISSUE TITLE
Offer celsius as a temperature unit

### ISSUE THREAD

**Issue by afranke** [MycroftAI/mycroft-core#714]
The weather skill gives temperatures in fahrenheit. The settings on the website let me choose some units but not for temperatures.

**Comment by penrods** [comment]
This surprised me, I assumed it used the system_unit to check!  Thanks for pointing this out.  It will use the Metric / English setting on home.mycroft.ai

We'll update it, but it'll be performed over in the skill-weather repo.  Each Skill now has its own issue section (both a good and a bad thing).

**Comment by afranke** [comment]
> It will use the Metric / English setting on home.mycroft.ai

This won’t work. Different locations use different combinations of units. UK for instance use miles and Celsius.

Also [US and imperial units differ](https://en.wikipedia.org/wiki/Imperial_and_US_customary_measurement_systems#Units_in_use).

**Comment by penrods** [comment]
Yeah, this is a stopgap I know.  The settings are minimal at this point, I know, but this provides at least some basic control via the web UI.  We are working on getting per-skill settings.

**Comment by btotharye** [comment]
Think this personally would be better per skill or a overall setting that we settle on from the home gui that can be used in skills downstream, for example temp_unit or something

**Comment by augustnmonteiro** [comment]
Fixed, to use Celsius is just change to Metric system
