### ISSUE TITLE
Trouble packaging with prepare-msm

### ISSUE THREAD

**Issue by rafamanzo** [MycroftAI/mycroft-core#718]
I'm poorly maintaining an [Arch Linux AUR package](https://gitlab.com/rafamanzo/aur-mycroft-core) due to lack of time. I'm trying to update it to v0.8.10 but I'm facing issues with start.sh calling prepare-msm.sh which always tries to chmod something that is already set.

My question is this is a "stable" version for this script? If so I'll probably start applying a patch that removes its call from start.sh. I can do this kind of setup at the PKGBUILD level there.

Or do you plan to add more logic into it? Then my patch solution would be broken for the next version.

**Comment by augustnmonteiro** [comment]
Hi @rafamanzo we moved msm to mycroft-core, basically prepare-msm.sh give permission to msm install skills on the /opt folder
