### ISSUE TITLE
i18n: adapt/..../tokenizer vs mycroft/util/parse.py 

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [MycroftAI/mycroft-core#723]
When an utterance is received at intent_service, method "normalize" of mycroft/util/parse.py is called. This call not only prepares the string but also executes some conversions as replace textual numbers to decimal ones. These conversiones are done taken into account the language of the utterance being handled.

Latter, adapt library is called. This one executes a tokenizer. By default, EnglishTokenizer is called. This tokenizer handles symbols. Moreover, it also replaces some common English acronyms. 

It is difficult change the Tokenizer to be used without a strong reconfiguration of the adapt library. The utterance language is not yet available, the tokenizer is selected in constructor of the library, ... .
 
My suggestion is convert EnglishTokenizer to a generic and language independent one, keeping the handling of symbols and moving the handling of acronyms to mycroft "normalize_en/normalize_es/..." methods.

Opinions?

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
