### ISSUE TITLE
Missing field on home.mycroft.ai for MaryTTS Text-to-Speech Config

### ISSUE THREAD

**Issue by chrison999** [MycroftAI/mycroft-core#736]
There needs to be a "url" field added to the online config for MaryTTS text-to-speech so that Mycroft can find the local server.  Keyword is "url" and the parameter is the URL to the local host (e.g. "http://localhost:59125")

**Comment by forslund** [comment]
The Mary TTS has been removed from home and is a config file only feature at the moment. Closing this issue.
