### ISSUE TITLE
build_host_setup.sh return error in a fresh Ubuntu 16.04

### ISSUE THREAD

**Issue by jdorleans** [MycroftAI/mycroft-core#74]
Error message after running `build_host_setup.sh`:
`sudo: easy_install: command not found`

We probably need to add two new dependencies:
`python-setuptools` and `python-pip`

**Comment by ryanleesipes** [comment]
Do those two dependencies fix the issue?

**Comment by jdorleans** [comment]
Ok, I can confirm that `python-setuptools` fixes this problem and `python-pip` is an dev dependency which is solved in the `dev_setup.sh`.

**Comment by ryanleesipes** [comment]
@ethanaward can you confirm that you were able to install and set up master without issue on Ubuntu 16.04?

**Comment by ethanaward** [comment]
I had no problems installing and setting it up, no.

**Comment by ryanleesipes** [comment]
Seems to have been fixed by commit 2a241d3
