### ISSUE TITLE
Message bus warning - disconnecting on error

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#75]
When running Mycroft on my Ubuntu 16.04 machine, it will occasionally give the following error in the terminal:

2016-05-31 11:59:02,796 - Skills - DEBUG - {"message_type": "recognizer_loop:audio_output_end", "context": null, "metadata": {}}
WebSocketConnectionClosedException('Connection is already closed.',)
2016-05-31 11:59:03,273 - mycroft.messagebus.client.ws - WARNING - Disconnecting on error, reconnecting in 32 seconds.

Mycroft still seems to be responding, but is somewhat slow to respond when this error is given.

**Comment by esoleyman** [comment]
Are you starting the three services in different terminal windows? If you do that, you'll notice that the error goes away.

./start.sh service
./start.sh skills
./start.sh voice

**Comment by ethanaward** [comment]
Yes, they were all started in different terminal windows and I was still noticing the errors.

**Comment by ryanleesipes** [comment]
Well @ethanaward - you are tasked with solving your own problem! :stuck_out_tongue_closed_eyes:

**Comment by ethanaward** [comment]
I haven't gotten that error in the last few days when running Mycroft correctly, so it's possible that it was what @esoleyman said. I think I just didn't have one of the services running at the time. It was either that or the wifi cutting in and out that did it, not any problem with Mycroft.
