### ISSUE TITLE
few question

### ISSUE THREAD

**Issue by Notsky-Mikle** [MycroftAI/mycroft-core#755]
Hi! 
Answer few question pleas
1. Mycroft is сloud service or unfolds locally?
2. Is there a Russian language?
Thanks :)

**Comment by forslund** [comment]
Hi!

1. Mycroft is a bit of both. many parts runs locally but things that require more computing power such as Speech To Text is offloaded to a server. There are also websettings that are remote. Technically if you have time, energy and skills you can make it completely local.

2. No russian yet. Currently the only language supported is English, Spanish is in the works. and beyond that we'll see.

**Comment by Notsky-Mikle** [comment]
And then this is the question. Does the system have ai elements? If not, then the system is not so complicated and I could at least translate for myself. It's more pleasant to speak your native language)

**Comment by forslund** [comment]
You are welcome to translate yourself, the system is prepared for it and there may very well be tts and stt systems that works fine with Russian. (I know someone got Spanish working)

**Comment by Notsky-Mikle** [comment]
Thank very march)
Last question. Mycroае has ai? Apparently not, otherwise rasberry does not have enough processing power

**Comment by forslund** [comment]
Mycroft is a virtual assistant. This means that mycroft is a framework for interacting with a computer using your voice. The "skills" that get invoked can then be heavy A.I. applications (local or somewhere in the cloud) or simple command parsers (`read the article about cute furry animals`).

**Comment by testman42** [comment]
@Notsky-Mikle define "AI"
Is something artificially intelligent when it can look up current time and tell it to you? Then yes.
Is something artificially intelligent when it can take a best guess at what you actually wanted to ask? Then yes
Is something artificially intelligent when it can use GUI written in Visual Basic to track killer's IP? Then no.

**Comment by nealmcb** [comment]
You can usually get faster answers to questions at the community forum: https://community.mycroft.ai/
or the slack channel: http://mycroft-ai-slack-invite.herokuapp.com/

I think the questions have been addressed here, and this issue can be closed now.

Thanks!

**Comment by forslund** [comment]
Agreed, closing. @Notsky-Mikle hoping to see you in the community later!
