### ISSUE TITLE
Audio In/Output card not set up properly

### ISSUE THREAD

**Issue by Dschorim** [MycroftAI/mycroft-core#758]
The intern audio card of the raspberry pi is terrible, so I'm using an external usb soundcard
and I've disabled the internal card. The card has In- and Output.
If I set der Card number to 0, i can use the card as an Output, works fine,
but then the Input doesn't work. If I set the Card number to 1, I can get the Inputmicrophone
working, but the Output doesn't work.
Has anybody figured out where to config the In- and Output Cardnumber?

**Comment by SoloVeniaASaludar** [comment]
Could be step 2 in [this post](https://community.mycroft.ai/t/install-on-linux-mint/1420) is useful

**Comment by jorimb** [comment]
I tried out step 2, but it still isn'n working:
the python script returns
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_hw.c:1667:(_snd_pcm_hw_open) Invalid value for card
Input Device id  0  -  ROCCAT Juke: USB Audio (hw:0,0)
Input Device id  1  -  sysdefault
Input Device id  5  -  spdif

arecord -l returns:
**** List of CAPTURE Hardware Devices ****
card 0: Juke [ROCCAT Juke], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

which leads to my assumption that I need card 0.
This is part of my /path/to/mycroft-core/mycroft/configuration/mycroft.conf file:
"listener": {
    "device_index": 0,
    "sample_rate": 16000,
    "channels": 1,
    "record_wake_words": false,
    "wake_word": "hey mycroft",
    "phonemes": "HH EY . M AY K R AO F T",
    "threshold": 1e-90,
    "multiplier": 1.0,
    "energy_ratio": 1.5
  },

but the cli returns
ALSA lib pcm_hw.c:1667:(_snd_pcm_hw_open) Invalid value for card
arecord: main:722: audio open error: No such file or directory
if i try to record something.

**Comment by SoloVeniaASaludar** [comment]
When you say "if i try to record something" it means that you are triggering some skill and this one is trying to record something?

If the answer to previous is "yes", it could be taken into account some known particularities on this part of mycroft (see issue #609):

a) arecord fails if input device is the same device than mycroft one
b) arecord arguments are currently hardcoded  in file mycroft/util/__init__.py. In particular, no way to change input device.

A different strategy is do not record with "arecord" but use the same method that is used for voice commands. You can see an implementation with this approach [here](https://github.com/SoloVeniaASaludar/mycroft-core/tree/next/mycroft/client/lspeech).

**Comment by jorimb** [comment]
with "if i try to record something" i mean i type in the cli
"start recording"

and to the second part:
do you mean I can't use a soundcard with In and Output?
Do I have to use to different soundcards, one for in and one for out?

**Comment by SoloVeniaASaludar** [comment]
No problem with use a single card that has in/out capabilities. In fact, is the most usual hardware.

**Comment by jorimb** [comment]
Does this mean, I can't use the recording skill of Mycroft (which uses arecord)

**Comment by SoloVeniaASaludar** [comment]
According to my tests, no, recording skill can not be used if the mycroft voice client is on.

**Comment by MichaIng** [comment]
In my case btw `"sample_rate": 48000,` with a very simple non PulseAudio asound.conf:
```
pcm.!default {
    type hw
    card 0
    device 0
}
ctl.!default {
    type hw
    card 0
}
```
- Default sample rate 16000 in this case was not supported in combination with the "type hw" module on all tested devices.

**Comment by forslund** [comment]
The picroft initial setup has been updated to cover some of the cases touched on here. Since this is picroft platform specific I'm closing this issue. If the latest picroft image could be improved please reopen an issue in the [enclosure-picroft repo](https://github.com/MycroftAI/enclosure-picroft/)
