### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by inzanedesignerz** [MycroftAI/mycroft-core#767]
Hi,

       I was thinking about a few ideas-
1.Multi User support like new google home.(I have looked into voiceid)
2. Context Aware & user data persistence.(I have looked into tensor flow )
3.Multi device support.

**Comment by nealmcb** [comment]
Some of these ideas are already included in the wiki:  https://github.com/MycroftAI/mycroft-core/wiki

You can help flesh out these ideas and proposals there.

**Comment by forslund** [comment]
Closing this issue, some of these are implemented in at least some fashion.
