### ISSUE TITLE
KDE Neon version doesn't include skill-date-time

### ISSUE THREAD

**Issue by chrison999** [MycroftAI/mycroft-core#769]
When I installed the KDE Neon version of Mycroft I discovered that the skill-date-time skill isn't installed so when you ask "what time is it" Mycroft drops through to Wolfram-Alpha and you don't get a response.

The installation is in a virtual machine being run by Virtual Box on an Ubuntu 16.04LTS system.

**Comment by forslund** [comment]
Hi, is this still true? I know the installation procedure has been updated and according to the DEFAULT files the skill-date-time should be included for the KDE installation nowadays.

**Comment by forslund** [comment]
Since there's been no communication for some months I'm closing this issue. If there's still problems feel free to reopen this issue, Thanks.
