### ISSUE TITLE
STT engine is invoked when recorded audio is not loud enough

### ISSUE THREAD

**Issue by labiadh** [MycroftAI/mycroft-core#771]
The AudioConsumer sends unnecessary STT request when no speech/noise is recorded after the detection of the wake up word.

I traced some variables in mycroft.client.speech.mic, exactly ResponsiveRecognizer::_record_phrase() :
when quiet_enough=True, was_loud_enough=False, recorded_too_much_silence=True (absolute silence), the audio_data is returned back to the AudioProducer, then pushed to the AudioConsumer which executes the STT engine. I think the last call is unnecessary.

possible solutions :
- in ResponsiveRecognizer::_record_phrase(), don't add quiet chunk to  byte_data; may introduce some audio distortions,
- in AudioConsumer::process(), check the energy of the audio data before calling transcribe(); may introduce latency when the audio is too long, 
- in ResponsiveRecognizer::listen(), get "was_loud_enough" from _record_phrase() and loop when was_loud_enough=False, means jumping back to adjust_for_ambient_noise() + _wait_until_wake_word(); may block the AudioProducer
- in AudioProducer::run(), reject quiet audio, probably by returned back the "was_loud_enough" variable

I just installed Mycrof a few days ago (now upgraded to 0.8.13) and still discovering it. maybe there are other methods to adjust this issue.

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
