### ISSUE TITLE
Changing mycroft voice on picroft from "ap" to "slt"

### ISSUE THREAD

**Issue by ktodyruik** [MycroftAI/mycroft-core#776]
Hi,

I'm new to mycroft and learning. I'm trying to change mycroft's voice on picroft. It sounds like the default is "ap"

These all work:
```
$ mimic -lv
Voices available: ap slt kal awb kal16 rms awb_time 

$ mimic -voice ap "Hello World"

$ mimic -voice slt "Hello World"
```

I created a config file in `~/.mycroft/mycroft.conf`

```
{
"tts": {
"module": "mimic",
"mimic": {
"voice": "slt",
"path":"/usr/local/bin/mimic"
}
}
```

I've even tried changing the other conf files. The voice doesn't change.

I've also tried changing the voice online in https://home.mycroft.ai

No luck.

Can somebody point me to what I'm missing here?

Thanks.
Kerry

**Comment by forslund** [comment]
Hi Kerry,

In your config you're missing a `}` at the end, the parsing will discard the entire thing I'm afraid.

Trying the following
```json
{
"tts": {
"module": "mimic",
"mimic": {
"voice": "slt",
"path":"/usr/local/bin/mimic"
}
}
}
```

works for me. (Well, I removed the path since I run mimic from another location)

You should be able to use the web-settings. However this currently require a restart of mycroft to take effect.

**Comment by nealmcb** [comment]
Does the mycroft.conf parser display an error for such failures?

If so, where?

If not, or if it's too hard to find, sounds like this is ripe for a bug or feature request.

**Comment by forslund** [comment]
The load error is logged but it could be better at reporting exactly where the error occurred.

As there has been no response from the original author I'm closing this. @ktodyruik if this still is an issue feel free to reopen this issue and I'l try to provide more help
