### ISSUE TITLE
Configuring the current location and temperature units

### ISSUE THREAD

**Issue by ktodyruik** [MycroftAI/mycroft-core#777]
Hi,

I am using pycroft and new to mycroft and learning. I'm trying to configure the current location and temperature units. I copied and modified a couple sections from the mycroft-core mycroft.conf file, and added the following sections to `~/.mycroft/mycroft.conf`

```
{
  "location": {
    "city": {
      "code": "Calgary",
      "name": "Calgary",
      "state": {
        "code": "AB",
        "name": "Alberta",
        "country": {
          "code": "CA",
          "name": "Canada"
        }
      }
    },
  "WeatherSkill": {
    "api_key": "",
    "proxy": true,
    "temperature": "celcius"
  }
}
```

I checked the log files, and they say that `~/.mycroft/mycroft.conf` was loaded.

I would have expected these values to override the defaults. Strange, the weather skill still is reporting weather values from Kansas and in Fahrenheit.

I wonder if configuration is working the way it is documented. Configuration does seem to be a tricky aspect of mycroft.

Could somebody make some suggestions? Is configuration working? How should I go about configuring things like the weather app? Am I missing something here?

Thanks.

**Comment by forslund** [comment]
Hi, if you're using picroft I believe you need to use `/etc/mycroft/mycroft.conf` to change configuration in the picroft install. (mycroft is run under the user _mycroft_ not under _pi_ if memory serves)

**Comment by forslund** [comment]
To configure location under the web settings go to devices, select your picroft device and enter the location there.

**Comment by redadmiral** [comment]
The issue with degree Fahrenheit in countries with metric system has just been closed and the code is merged.
https://github.com/MycroftAI/skill-weather/issues/2
