### ISSUE TITLE
Add a format utility to format decimals to english fractions

### ISSUE THREAD

**Issue by ashwinjv** [MycroftAI/mycroft-core#785]
I was writing a mycroft skill to pull yelp ratings for businesses and realized that they were no utilities to format decimals to english fractions. For example 4.5 stars to 4 and a half stars.

**Comment by penrods** [comment]
@ashwinjv I merged your code.  I think this is ready to be closed, right?

**Comment by ashwinjv** [comment]
@penrods Sure, closing this issue
