### ISSUE TITLE
workon should add mycroft-core to the PYTHONPATH if not present

### ISSUE THREAD

**Issue by ashwinjv** [MycroftAI/mycroft-core#787]
By default mycroft-core is not in the python path. When I am in the mycroft-core folder with the mycroft enviroment enabled and try to run individual tests like `python test/utils/test_parser.py` it fails to find the mycroft package. If you are working on the mycroft environment, it would make sense to have mycroft-core folder to be in the PYTHONPATH.

**Comment by forslund** [comment]
This was added in dd2aa0900c97fb771207dd5945ccb4d4c7abeed7. Closing.
