### ISSUE TITLE
Wolfram Queries feature a trailing ' - messing up responses

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core#79]
This is something we need to figure out, as it renders Wolfram nearly completely useless in many cases.

**Comment by Wolfgange3311999** [comment]
Note: this is the cause of issue #28 and is believed to happen somewhere near when a request is sent to Cerberus.

**Comment by ethanaward** [comment]
When I ask Mycroft for `what's 2 times 2` Mycroft receives the output from Wolfram as `feet x 2 x 2`, which means that Wolfram is receiving the output as `'2x2`. So it's adding on a `'` at the beginning, not end.

**Comment by ryanleesipes** [comment]
This has been fixed by @ethanaward via a change to the Cerberus proxy service, there are still problems with the Wolfram skill, however, being tracked in #63
