### ISSUE TITLE
Removing "to" in keywords

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-core#791]
The keyword phrase can be "post to twitter" doesn't work yet
"post twitter" does. This is confusing.

Is this part of normalize?

**Comment by btotharye** [comment]
This seems to be working right now, will monitor and update after a few days

**Comment by forslund** [comment]
@kfezer, @btotharye is this still an issue?

**Comment by forslund** [comment]
Closing this issue, since I think it's been quite ok for quite a while.
