### ISSUE TITLE
Add Mycroft List skills skill

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-core#792]
Have skill that lists all available skills for mycroft

**Comment by JarbasAI** [comment]
you mean installed or available skills, or both?

#783 gives a loaded skill manifest, in case it's relevant, my control center skill does that

**Comment by JarbasAI** [comment]
https://github.com/JarbasAI/JarbasAI/tree/jarbas-core/jarbas_skills/skill_control_center

maybe related

**Comment by forslund** [comment]
The skill manager can now be queried for registered and running skills. I'm sure that it can be expanded upon. Will close this since the actual skill implementation lies outside the scope of core.
