### ISSUE TITLE
Wi-Fi Setup client should redirect client to captive portal if detected

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#795]
When setting up a wireless connection via the setup client, we should be able to:

- detect if the newly connected network has a captive portal
- if so: forward the connection through the p2p interface and redirect the clients browser to the portal page
- if not: bring down the legacy p2p network as normal and re-direct to home.mycroft.ai

**Comment by forslund** [comment]
Opened issue on wifi-setup client repo: https://github.com/MycroftAI/mycroft-wifi-setup/issues/26. Closing this one
