### ISSUE TITLE
Is it possible for skills to share information?

### ISSUE THREAD

**Issue by poplav** [MycroftAI/mycroft-core#799]
Imagine a hypothetical case where you have two skills one for food near me and one for the weather near me.  The food skill will ask for my current zip code to use to help search near me.  On subsequent requests it should know the zip code as I already gave that information.  Then I invoke a new skills that gives me the weather near me.  Can it use that zip code from the other skill or will it have to prompt the user again?  I would like to do this without setting up my own external resources for storing this information.  So is there a core level way to share variables across skills.  I just saw this project for the first time today, so new and just curious.

**Comment by forslund** [comment]
There is currently no mechanism for this. It has been mentioned a couple of times in discussion and is a planned feature.

I think basic work has been done with a context manager in the intent parsing library *adapt*. The idea there is that if for example two intents require a `LocationKeyword` and you specify the location in the first utterance the second will get the same Location (if not another is specified)

*When's the next train to Stockholm*
**- 14.50**
*What's the weather going to be?*
Mycroft will remember `Stockholm` as the context of this conversation and reply:
**- The weather is always nice in the glorious capital of Sweden** (Or something along those lines I'm sure)

**Comment by poplav** [comment]
@forslund , Thanks for the update.  I am very interested in this feature landing!  I believe it is critical for a more natural dialogue.
