### ISSUE TITLE
Links incorrect on docs website.

### ISSUE THREAD

**Issue by Explouad** [MycroftAI/mycroft-core#8]
Multiple links lead to 
https://github.com/MycroftAI/mycroft
as opposed to 
https://github.com/MycroftAI/mycroft-core

Specifically, the links on https://docs.mycroft.ai/development/skills-sdk are broken.

**Comment by ryanleesipes** [comment]
Thanks! The docs have a repo, so I can hit this - or if you want to beat me to it the repo is at https://github.com/MycroftAI/mycroft-core-documentation !

**Comment by Explouad** [comment]
Sorry, on my phone currently. You can close it when you remedy it. Glad to help.

**Comment by Explouad** [comment]
Resolved with PR #1
