### ISSUE TITLE
setup_base.py uses deprecated __version__.py calls.

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#801]
Setup_base.py by default tries to get the current version by importing `mycroft.__version`. However, this is no longer used. It should be updated to use the new versioning system.

**Comment by ethanaward** [comment]
Closed by #802

**Comment by MatthewScholefield** [comment]
Looks like #802 got reverted a couple of times but in the end, it no longer uses __version__ so I'm marking as closed.
