### ISSUE TITLE
MSM can indicate success on empty parameter

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mycroft-core#807]
$ msm install

returns "Skill installed!" when it should return an error.

**Comment by forslund** [comment]
Thanks for reporting, this should be fixed in _dev_ since May 23 and will be available in the next release.

This is the output I get now
```shell
(mycroft) ake@roadrunner:~/projects/python/mycroft-core/msm$ ./msm install
#######  Mycroft Skill Manager #######
You must pass the git url or skill name
(mycroft) ake@roadrunner:~/projects/python/mycroft-core/msm$ echo $?
1
```

Does that look good enough?

**Comment by el-tocino** [comment]
I'll post a pr shortly with what i did.

**Comment by el-tocino** [comment]
https://github.com/MycroftAI/mycroft-core/pull/812

**Comment by el-tocino** [comment]
https://github.com/MycroftAI/mycroft-core/pull/813

**Comment by el-tocino** [comment]
Closing as it's fixed one way or another.
