### ISSUE TITLE
DuckDuckGo fallback engine

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#810]
We should consider adding DuckDuckGo as an optional backend, perhaps alongside wolfram. They have a [nice API][api], a [python library][pypi], and as another plus, are [mostly open source][github].

[api]:https://duckduckgo.com/api
[pypi]:https://pypi.python.org/pypi/duckduckgo2/
[github]:https://github.com/duckduckgo

**Comment by marksev1** [comment]
How good is it compared to Wolfram for answering random stuff?

**Comment by arjenlentz** [comment]
DuckDuckGo is getting much better, at least as a replacement for Google searches and questions.
I use it most of the time for in-browser searches and I am pretty pleased with it - and increasingly so.

**Comment by MatthewScholefield** [comment]
Btw, #1129 fixes this.

**Comment by arjenlentz** [comment]
k just browsing through the issues and PRs I think it'd be good if they were cross-referenced.
Github will auto-link items when mentioned, like so: https://help.github.com/articles/autolinked-references-and-urls/

Doing this will also enable issues to be marked as fixed and closed when related pull requests are merged (as well as prevent potential duplicate fixes for an issue)

**Comment by MatthewScholefield** [comment]
Yeah, I should have done that but I forgot xD

**Comment by forslund** [comment]
As the duckduckgo-fallback is now included as default I'm closing this issue
