### ISSUE TITLE
pocketsphinx on rpi3

### ISSUE THREAD

**Issue by hersche** [MycroftAI/mycroft-core#815]
hello, as you may know from slack, i'm working on bringing mycroft to german.

well, beside pocketsphinx seems to use too much power for this little processor, i also always see this:

2017-06-12 02:14:02,278 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/stt?lang=de&limit=1 HTTP/1.1" 200 None

2017-06-12 02:14:02,373 - mycroft.client.speech.listener - ERROR - list index out of range
2017-06-12 02:14:02,374 - mycroft.client.speech.listener - ERROR - Speech Recognition could not understand audio

the exception comes from client/speech/listener.py, but i have no idea, what to do with. looks like pocketsphinx-speechreconizerpart may reinitialise all the time?

often, after the first (mostly successfull) query it beginns to hang. it has a long while until the "pling"-sound came, with a immedietly "i didn't catch that".

after a while i sometimes could do successfully requests also. but it never really disappear and felt realy unstable (well it's dev)..

because of the cpu-use of over 100%, i assume it could also be a performance-problem.

what helps against this are smaller dicts, as i read. at least for pocketsphinx. would it be possible to have separeted dict's for hotwords and speaking? the process which would wait for start-speaking would be able to react much faster, when i'm right. if there's a mechanism for this, let me know 

Well, i hope you have a idea there :)

**Comment by forslund** [comment]
Closing Issue since we're archiving the repo
