### ISSUE TITLE
local skill config

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#816]
installing skills that require config is somewhat troublesome, skills don't load on missing fields, we need to constantly manually edit the same huge file to add/configure skills

i think it would make sense if:
- each skill has a skill.config
- on loading skill this is loaded before normal config
- normal config updates any value if skill is listed there

this allows:
- including default skill parameters / options
- ensure skill loads, optionally (if skill maker desires) throw vocal warnings on what's missing
- change skill values while keeping skill defaults for backup in folder
- skill default config is also updated with msm
- easier dev, change skill.config, skill reloads, no need to restart skills service to reload skill config changes

**Comment by forslund** [comment]
Check out the skill settings. It is available as `self.settings`, the this dict is loaded from `settings.json` in the skill directory. The skill can change it and add new values to it and on shutdown the file is saved.

This feature is missing the defaults feature but that could be added easily.

**Comment by JarbasAI** [comment]
but the idea is some values being configurable in a config file instead of hard-coded, so settings is not quite the solution

**Comment by el-tocino** [comment]
There may in the future also be the want for user-specific configuration items on a skill.

**Comment by forslund** [comment]
@JarbasAI settings is mapped to a config file located in the skill directory and is not hard coded. I may misunderstand you but to me adding a `default.json` config that is overridden by the `settings.json` would do what you propose. since the settings.json can be edited my hand and not only from the skill.
