### ISSUE TITLE
Error While Executing ./dev_setup.sh

### ISSUE THREAD

**Issue by shirshankdeepankar** [MycroftAI/mycroft-core#822]
Hi

I am trying to configure Mycroft on Raspberry PI 3, 
By following Github approach I am frequently getting below error on installation, have tried clean installation but it didn't wok out.

  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_10_durmodel.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_12_mcep_trees.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_12_params.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_17_durmodel.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_17_mcep_trees.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_17_params.lo
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:3848: recipe for target 'lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_01_params.lo' failed
make[1]: *** [lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_01_params.lo] Error 1

make[1]: *** Waiting for unfinished jobs....

Could anybody guide me in resolving the issue, Thanks in advance?

[Log.txt](https://github.com/MycroftAI/mycroft-core/files/1072606/Log.txt)

Thanks
Shirshank

**Comment by el-tocino** [comment]
This is likely due to memory issues. 

I made a branch for an update to dev_setup to run with a single core for low (<1.5gb) memory systems.  The interim fix maybe be to adjust dev_setup.sh to have "CORES=1" instead of $nproc.

**Comment by shirshankdeepankar** [comment]
Thanks for your reply.

Yes, this was a memory issue, made two changes to make it run properly.
1) "CORES=1" instead of $nproc as suggested.
2) Change CONF_SWAPSIZE=1024 by changing /etc/dphys-swapfile
