### ISSUE TITLE
Novelty skill

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#83]
Mycroft should be able to respond to various quotes and phrases in novel ways, e.g.

User: Mycroft, open the pod bay doors
Mycroft:  I'm sorry, Dave. I'm afraid I can't do that. 

User: Mycroft, what do you think of Siri?
Mycroft: I think she needs to be more open-minded.

**Comment by ryanleesipes** [comment]
@ethanaward you are assigned now, this should be similar to the welcome skill, but with more intents.

**Comment by marksev1** [comment]
Also some jokes, from some repository of jokes, if there is any such repository :D?

**Comment by ryanleesipes** [comment]
@marksev1 I think we may have discussed this, but [pyjokes](https://github.com/pyjokes/pyjokes) is currently in use in the jokes skill.  Going to open up a new ticket to look into getting some more general jokes into the repo.

@ChristopherRios7 can you review this and perhaps look into maintaining our own joke dialog files?

**Comment by ryanleesipes** [comment]
Actually moving this to ticket #142. Closing this ticket.
