### ISSUE TITLE
Any plan to support Chinese?

### ISSUE THREAD

**Issue by hguomin** [MycroftAI/mycroft-core#831]
Hi team,

Does Mycroft has any plan to support the communication in Chinese? thanks.

**Comment by troy-lamerton** [comment]
@vavrek said that Chinese is being considered at the least. He will have more accurate info on this though.

**Comment by forslund** [comment]
Closing this question as it is answered, there is no official multi-language support yet but contributing translations through https://translate.mycroft.ai should enable Chinese. (I don't believe there's any technical limitation at this point)
