### ISSUE TITLE
mimic tts BIN is None

### ISSUE THREAD

**Issue by krabovm** [MycroftAI/mycroft-core#839]
Os: elementary 4.1
Branch: master

I got some errors, so in mimic_tts.py I did
`LOGGER.debug(self.args)`
right before `phonemes = subprocess.check_output(self.args + [...])`
I got
`[None, '-voice', u'ap', '-psdur']`

I also got this warnings

```
mycroft.configuration - INFO - Loading configuration: /etc/mycroft/mycroft.conf
mycroft.configuration - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not found
mycroft.configuration - DEBUG - Configuration '/home/krab/.mycroft/mycroft.conf' not found
mycroft.configuration - INFO - Loading configuration: /home/krab/.mycroft/mycroft.conf
mycroft.configuration - DEBUG - Configuration '/home/krab/.mycroft/mycroft.conf' not found
mycroft.configuration - DEBUG - Configuration '/home/krab/.mycroft/mycroft.conf' not found
```

Mb this is the reason I can't get it working

**Comment by forslund** [comment]
Hi,

I've run some tests on this and I think mimic might have failed to install.

Mimic build is quite memory intensive and depending on memory and settings fails on certain CPU/memory/swap configurations. #822 lists a way to get it working, also @el-tocino has submitted a PR #823 that should make it a bit more reliable. If there is a compilation issue, It would be great if you could try his PR and see if it works for you.

**Comment by krabovm** [comment]
@forslund Thank you, rebuilding has helped. You're right, it was mimic issue.
