### ISSUE TITLE
Don't instantiate ConfigurationManager

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#847]
The `ConfigurationManager` class is all static meaning places that use code like `ConfigurationManager().get()` can just be `ConfigurationManager.get()`.

**Comment by esoleyman** [comment]
I only found two instances where this was happening. Please see the attached diff.

[dont-instantiate.txt](https://github.com/MycroftAI/mycroft-core/files/1202616/dont-instantiate.txt)

**Comment by forslund** [comment]
Thanks for taking the time to go through the code and fixing these few places. A Pull request would be welcome but I can probably work with the patch in case that would be a problem.
