### ISSUE TITLE
Patch for mycroft-core :  build_host_setup script for Mageia linux distro

### ISSUE THREAD

**Issue by yannick56** [MycroftAI/mycroft-core#848]
Hello,

Can you add in the mycroft-core git repositery the following script for Mageia Linux (https://en.wikipedia.org/wiki/Mageia ): 
build_host_setup_mageia.sh ?

Thank you 

Best regards

**Comment by yannick56** [comment]
[build_host_setup_mageia.sh.txt](https://github.com/MycroftAI/mycroft-core/files/1100682/build_host_setup_mageia.sh.txt)

**Comment by yannick56** [comment]
Patch for mycroft-core : build_host_setup script for Mageia linux distro

**Comment by yannick56** [comment]
Patch for mycroft-core : build_host_setup script for Mageia linux distro

[build_host_setup_mageia.sh.txt](https://github.com/MycroftAI/mycroft-core/files/1100686/build_host_setup_mageia.sh.txt)

**Comment by MatthewScholefield** [comment]
Hello, please submit a pull request including the new file and we'd love to add it into mycroft-core.

**Comment by forslund** [comment]
I'm closing this issue. The `build_host_setup_*` script have merged into `dev_setup.sh`.

We'd love to see a PR for mageia installation support.
