### ISSUE TITLE
Dialogue with Mycroft

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#85]
Mycroft should be able to carry on a conversation about certain things, such as ordering a pizza.

User: Mycroft, I want to order a pizza from [pizza place].
Mycroft: Sure, what would you like on your pizza?
User: Pepperoni.
Mycroft: Would you like anything else on it?
User: No, that's it.
Mycroft: What size of pizza would you like?
...

**Comment by ryanleesipes** [comment]
This is an ENORMOUS task. But we should look into it. I have some ideas for how to accomplish this, but we will need to have some conversations about it.

**Comment by virtadpt** [comment]
This might be a good feature for users to build slowly, i.e., training Mycroft to personalize itself to the user.  Plus, the database of asks could be pretty easy to back up (SQLite).

**Comment by forslund** [comment]
This has been implemented in a couple of different way (MycroftSkill.get_response(), converse and context).

It will likely evolve in the future as well. Closing this issue.
