### ISSUE TITLE
Hey we have mimic already installed

### ISSUE THREAD

**Issue by kuboosoft** [MycroftAI/mycroft-core#850]
We have mimic in Fedora 26 and Rawhide; maybe other distributions coming soon...

**Comment by aatchison** [comment]
Wahoo!

**Comment by el-tocino** [comment]
https://github.com/MycroftAI/mycroft-core/pull/882

**Comment by MatthewScholefield** [comment]
Marking as fixed since the script now checks if mimic is already installed.
