### ISSUE TITLE
sudo is not commonly activated in Fedora

### ISSUE THREAD

**Issue by kuboosoft** [MycroftAI/mycroft-core#852]
We can run dnf using polkit... here "build_host_setup_fedora.sh"

**Comment by MatthewScholefield** [comment]
Would you be able to show the changes necessary and perhaps submit a pull request? Thanks!

**Comment by krisgesling** [comment]
Hi there, as this issue hasn't had a response for a while it will be closed. 

Please jump into the [Community Forums](https://community.mycroft.ai/) or [Chat](https://chat.mycroft.ai/community/channels/troubleshooting) if you're still having issues, or reopen this issue if you feel it should not have been closed. 

Thanks
