### ISSUE TITLE
Personal interactions with Mycroft

### ISSUE THREAD

**Issue by ethanaward** [MycroftAI/mycroft-core#86]
Mycroft should be able to tell you about himself, as well as be able to respond to phrases directed at him. So `Thanks, Mycroft` should make him respond `You're welcome` rather than searching for `Thanks`.

**Comment by ryanleesipes** [comment]
The beginning of this is solved. We need a "personal" skill. Some ideas:
- Where were you born?
- When were you born?
- Who made you?
- Who is your father/daddy/mother?
- What are you?
- Who are you?

**Comment by grahamreeds** [comment]
This should either be where HAL was created or Cyberdyne systems if we are
looking to reference pop culture.

If the user then says "Seriously, Mycroft?" he will go into the actual
creation of Mycroft spiel.

GR

**Comment by ethanaward** [comment]
Addressed further by #184

**Comment by isaacnward** [comment]
#184 solves this.
