### ISSUE TITLE
msm may not handle mk1 correctly.

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mycroft-core#887]
https://community.mycroft.ai/t/mark-1-workon-command-not-found/1810
looks like need to account for picroft and mk1 similarly, though, shouldn't be too difficult to fix.

**Comment by el-tocino** [comment]
Maybe....if [[ "$(hostname)" == 'picroft' ]] || [[ "$(hostname)" =~ "mark1" ]] &&  [[ -x /usr/local/bin/mycroft-wifi-setup-client ]] ;

**Comment by nealmcb** [comment]
I'm not quite sure where you mean that to run, but note there's an underscore in the hostname "`mark_1`"
 (though it causes confusion with mdns....):

```
if [[ "$(hostname)" == 'picroft' ]] || [[ "$(hostname)" =~ "mark_1" ]] &&
 [[ -x /usr/local/bin/mycroft-wifi-setup-client ]]
```

**Comment by el-tocino** [comment]
Nowhere yet, saving notes.  Agree that the underscore is probably not a good choice, I'd have gone with the hyphen if anything.

**Comment by ChrisFernandez** [comment]
I just run into this issue trying to install some 3rd party skills on my new mark1

**Comment by el-tocino** [comment]
Can you try this version of msm and see if it resolves the issue?
https://github.com/el-tocino/mycroft-core/blob/46d5fc7d3306b44b20fbc7f5f2ba3dc74b721e49/msm/msm

**Comment by shaun040** [comment]
@el-tocino That did the trick! Able to install skills via msm now. Cheers!

**Comment by nealmcb** [comment]
Worked for my Mark 1 also, which has an unchanged hostname. Thanks! 

But I left a comment on the code commit to try to make it more robust.

**Comment by el-tocino** [comment]
Not sure there's a better way to handle it other than only checking for the wifi setup client, since both picroft and mk1 units can both have that changed.  I'd have to look up the way to edit docs or get one of the mycroft folks to do so to indicate that, perhaps.  Or have an /etc/mycroft/[my,pi]croft-release file or something that's part of those installs.

**Comment by nealmcb** [comment]
Yes - I was thinking about something like a mycroft release file.

**Comment by el-tocino** [comment]
PR merged, closing.
