### ISSUE TITLE
A Smarter, More Personable Mycroft.

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core#89]
Mycroft is a little dull right now, very rigid in you ask a question, he answers. Let's give him a personality and make him a little smarter. This is an Epic task that incorporates many subtasks. Some example improvements are:
- Personal Skill: Make Mycroft "aware" of who he is and where he came from.
- Context Awareness: If Mycroft could maintain the entity of the last query and use that with the current query (if it applies), that would be awesome.
- Novelty Skill: Mycroft should have interesting responses to some queries.
- Dialogue Capability: Perhaps Mycroft could engage in a conversation regarding a topic. Who knows if we can pull this off, but we can try.

**Comment by virtadpt** [comment]
How about this?

Mycroft's users have a way of adding questions to Mycroft's database.  Those user-added questions can then, if the user so wishes, be added to an online registry of questions at mycroft.ai which is user-curated, and Mycroft users can select batches of questions they'd like to add to their own Mycroft instances.

**Comment by aatchison** [comment]
Wow, an utterance database! They could be categorized too. That would be
cool.

**Comment by aatchison** [comment]
...and if you could load them into skills as well.
You could load a list of apologies for errors for example.

**Comment by LongBoolean** [comment]
Would also be nice to have multiple variations of responses. (currently, multiple lines in the .dialog file)
Example: "Thank you mycroft", Mycroft then responds with one of these: 
```
Your welcome.
Any time.
No problem.
Glad to help.
Glad to be of service.
```
That way responses would be less repetitive over time.

**Comment by ryanleesipes** [comment]
@LongBoolean good idea. Someone should put those in a PR.

**Comment by the7erm** [comment]
>     Your welcome.
    Any time.
    No problem.
    Glad to help.
    Glad to be of service.

I didn't do much for this, just randomized the dialog.

**Comment by LongBoolean** [comment]
nice

**Comment by krisgesling** [comment]
Closing this very old issue. So much has happened in 4 years, and the 4 points in this ticket are certainly implemented.

**Comment by ryanleesipes** [comment]
Good job Mycroft team!
