### ISSUE TITLE
On the register page of the cerberus webiste, it's possible to try to submit without a code

### ISSUE THREAD

**Issue by elopio** [MycroftAI/mycroft-core#9]
When I hit the submit button without entering a code, I get back an error message saying: Failed to pair with device. I think it would be better if the button was disabled until I entered a code.

![ekrankopio de 2016-05-20 13-10-27](https://cloud.githubusercontent.com/assets/617831/15439265/55674dc6-1e8d-11e6-8a7a-14751289b733.png)

To reproduce:
Go to https://cerberus.mycroft.ai/register
Click the submit button

**Comment by senseiner** [comment]
We need to take a look on this @jdorleans
