### ISSUE TITLE
Install and Configure SonarQube for all Mycroft code

### ISSUE THREAD

**Issue by jdorleans** [MycroftAI/mycroft-core#90]
Many are the reports and concerns about the quality of our projects source code. We have to start addressing those issues sooner than later. SonarQube provides a rich and high level quality platform which help us to easily identify quality problems on the code. For more details read http://www.sonarqube.org/

**Comment by ryanleesipes** [comment]
@aatchison @jdorleans please talk amongst each other an evaluate this.

**Comment by aatchison** [comment]
I was working on this, shall I continue?

**Comment by aatchison** [comment]
This should be part of our CI project instead.
