### ISSUE TITLE
Mark 1 MSM Install Error

### ISSUE THREAD

**Issue by btotharye** [MycroftAI/mycroft-core#909]
Looks like on the mark 1 msm is having issues on installing dependencies in the requirements.txt file

msm install https://github.com/btotharye/mycroft-homeassistant.git
/usr/local/bin/msm: line 40: locate: command not found
#######  Mycroft Skill Manager #######
Attempting to install https://github.com/btotharye/mycroft-homeassistant.git...
Cloning repository
Cloning into 'mycroft-homeassistant'...
remote: Counting objects: 271, done.
remote: Total 271 (delta 0), reused 0 (delta 0), pack-reused 271
Receiving objects: 100% (271/271), 33.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (113/113), done.
Checking connectivity... done.
Installing libraries requirements
/usr/local/bin/msm: line 140: workon: command not found
Unable to activate mycroft virtualenv!
/usr/local/bin/msm: line 148: deactivate: command not found
Sorry I'm unable to complete the request! Check the error messages above for why. Err 120

Still investigating what is causing it.

**Comment by el-tocino** [comment]
Covered in #887

**Comment by el-tocino** [comment]
I think this one can be closed now.
