### ISSUE TITLE
Skill not running __init__ on first load?

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#917]
I have a skill that is supposed to run a function when loaded, and it used to, but not anymore.
Did the decorator changes change the way the skills are initialized?

**Comment by forslund** [comment]
I shouldn't change this. it adds a procedure after the skill is loaded to populate intents if there are decorated intents.

`__init__()` is run by `create_skill()` in the skill module.

Will investigate.

**Comment by forslund** [comment]
@aatchison is this still an issue or did the msm fix solve it?

**Comment by forslund** [comment]
I'm pretty sure this has been resolved. Closing.
