### ISSUE TITLE
Math Skill

### ISSUE THREAD

**Issue by Wolfgange3311999** [MycroftAI/mycroft-core#92]
This should at least be able to do basic operations (+-*/).

**Comment by ryanleesipes** [comment]
@ethanaward please review this and see what you think.

**Comment by marksev1** [comment]
This would be good... Could you maybe expand it with conversion of physical properties or maybe also currencies, or should we look at different skills to do that...Maybe Wolfram Alpha I don't know?

**Comment by ryanleesipes** [comment]
PR for this closed. Closing accompanying issue.
