### ISSUE TITLE
RuntimeError: new_Decoder returned -1

### ISSUE THREAD

**Issue by ThomasKoscheck** [MycroftAI/mycroft-core#922]
Hello together,
after rebooting my Pi I get this error:

```
loop = RecognizerLoop()
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.1-py2.7.egg/mycroft/client/speech/listener.py", line 184, in __init__
    self.mycroft_recognizer = self.create_mycroft_recognizer(rate, lang)
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.1-py2.7.egg/mycroft/client/speech/listener.py", line 194, in create_mycroft_recognizer
    return LocalRecognizer(wake_word, phonemes, threshold, rate, lang)
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.1-py2.7.egg/mycroft/client/speech/local_recognizer.py", line 40, in __init__
    self.decoder = Decoder(self.create_config(dict_name))
  File "/usr/local/lib/python2.7/site-packages/pocketsphinx/pocketsphinx.py", line 271, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1
```
I also reinstalled it and tried it again. But I also got this error after rebooting the pi.

Does anybody know how to handle this?

Thank you very much

**Comment by forslund** [comment]
Hi,

I've seen two possible sources for this problem:

1. The Phonemes for the wakeword (or Capital letters for wake word plain text setting in versions from a couple of weeks ago) set at https://home.mycroft.ai are incorrect
2. The model pocketsphinx is using is missing or faulty

Since the problem persisted can you verify that the settings are correct at home.mycroft.ai
Wakeword `hey mycroft`
Phonemes `HH EY . M AY K R AO F T`

Is this a picroft-install or a custom install using git?

**Comment by ThomasKoscheck** [comment]
Thanks! The problem source was, that the wakewords weren't the same!

**Comment by TH4NOS** [comment]
@ThomasKoscheck  So when you change both the wake word and phonemes it works?

**Comment by ThomasKoscheck** [comment]
No, sadly not. It just works with "Hey Mycroft"

-------- Original-Nachricht --------
An 23. Aug. 2017, 08:33, TH4NOS schrieb:

**Comment by TH4NOS** [comment]
@ThomasKoscheck  have you tried changing the phonemes WRT to the wake word in both the website as well as the configuration file?

**Comment by ThomasKoscheck** [comment]
Yes, i changed both but with no success

**Comment by choudharykrish** [comment]
This solved my problem

https://stackoverflow.com/questions/44339312/new-decoder-returned-1-when-trying-to-run-pocketsphinx-on-raspberry-pi/51346264#51346264
