### ISSUE TITLE
dev_setup.sh fails

### ISSUE THREAD

**Issue by Rotho98** [MycroftAI/mycroft-core#926]
I ran the dev_setup.sh and I ran into an error while trying to install.
`  Running setup.py install for pillow
    Complete output from command /home/brain/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-z0nvhK/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-l4xSSJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/brain/.virtualenvs/mycroft/include/site/python2.7/pillow:
    running install
    running build
    running build_py
    running egg_info
    writing requirements to Pillow.egg-info/requires.txt
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z0nvhK/pillow/setup.py", line 756, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/home/brain/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-z0nvhK/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-l4xSSJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/brain/.virtualenvs/mycroft/include/site/python2.7/pillow" failed with error code 1 in /tmp/pip-build-z0nvhK/pillow
`

**Comment by Rotho98** [comment]
I fixed this by installing libjpeg62-turbo-dev,
SO closing the issue

**Comment by forslund** [comment]
Reopening this issue since it shows that the `build_host_*.sh` scripts aren't up to date, they should install the packages required for setting up the development environment.

Thank you for reporting this!

**Comment by mil1i** [comment]
I am also unable to build Mycroft on my system. The build_host script successfully installs everything. python-devel. I am on Fedora 26 x64. Below is the final error before it stops, as well as a link to the entire output of the dev_setup.sh script.

> `Command "/home/milli/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-J6Py5x/PyAudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-QOHBK8-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/milli/.virtualenvs/mycroft/include/site/python2.7/PyAudio" failed with error code 1 in /tmp/pip-build-J6Py5x/PyAudio
> `

[Pastepin](https://pastebin.com/UQzakQWK)

**Comment by el-tocino** [comment]
Looking through the pastebin you have a bunch of gcc failures(https://stackoverflow.com/questions/34624428/g-error-usr-lib-rpm-redhat-redhat-hardened-cc1-no-such-file-or-directory), googling those indicates that a "dnf install redhat-rpm-config" should fix it.

**Comment by mil1i** [comment]
I was just about to post, that is what I did and that seems to have fixed it. It's still working on finishing the install right now!

Thank you @el-tocino

**Comment by forslund** [comment]
Closed by #928.

@mil1i could you open a separate issue about the missing `redhat-rpm-config` package for fedora?
