### ISSUE TITLE
Converting mycroft-core from GPLv3 to Apache 2.0

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mycroft-core#927]
As described in this blog post (https://mycroft.ai/right-license/), the GPLv3 license chosen originally for mycroft-core is having the opposite effect intended -- it is limiting the potential platforms that can use this software rather than expanding them.  The provisions of the GPLv3 for "anti-tivoization" have the effect of closing out software licensed that way from any use in equipment requiring regulatory approval (such as healthcare, automotive and other highly regulated industries); and fears of patent-left are scaring off other companies.

To address this concern we have looked into many licensing options with one of the most respected Silicon Valley lawyers in open source.  Our belief is that the Apache 2.0 license achieves the type of code-sharing we want, and it has the clearest legal standing of all the popular open-source licenses.  Going forward we will ask all contributors to fill out a Contributor License Agreement, which clarifies that they (the contributor) retain complete ownership of all contributed code, they are just providing a license to the Mycroft project and its ultimate users.

In order to make this license transition, we need the agreement of those who are participants in the project already.  So this issue is being used to reach out to existing project contributors who need to be contacted yet.

If you are in this list, please use the https://mycroft.ai/cla form to request a link for digitally signing the Individual Contributor License Agreement.  In order to be valid, we do need to know your legal name and address (courts don't recognize Github usernames yet :) ) but we will keep your name hidden if you would prefer to just be known publicly by your Github username.

If you have any questions or concerns, please feel free to ask them either here or directly via my email.  

Thank you for your contributions and help!

    - Steve (steve.penrod@mycroft.ai)

Existing Contributors needed to sign via https://mycroft.ai/cla
========================================
@akacipher
@akegalj
@ashwinjv
@bashterm
@chrison999
@chrisvella
@cincodenada
@CloneMMDDCVII
@clusterfudge
@el-tocino
@flexiondotorg
@gregmccoy
@isaacnward
@JarbasAI
@jasonehines
@jdorleans
@joshymcd
@kagesenshi
@liviu-vasut
@Matlar
@metaheap
@ncouture
@nealmcb
@nullr0ute
@ParkerMc
@robocoder99
@SoloVeniaASaludar
@Sujan4k0
@Teagan42
@the7erm
@tmajibon
@UberPanda
@williamcaesar
@wligtenberg
@z3ntu
@zeehio

**Comment by zeehio** [comment]
Is it possible to, for the sake of openness and transparency, get the CLAs published?

**Comment by penrods** [comment]
Sure, I'll add a copy of the Individual Contributor License Agreement text here.  Note that there is nothing that forces you to sign once you request a CLA or that prevents you from publishing the contents.  They aren't confidential.

**Comment by penrods** [comment]
[Mycroft Individual CLA (7-23-2017).pdf](https://github.com/MycroftAI/mycroft-core/files/1169032/Mycroft.Individual.CLA.7-23-2017.pdf)

[Mycroft Corporate CLA (6-15-2017) - corrected.pdf](https://github.com/MycroftAI/mycroft-core/files/1169035/Mycroft.Corporate.CLA.6-15-2017.-.corrected.pdf)

**Comment by z3ntu** [comment]
@penrods When entering my phone number in the CLA, I get an error 

> Please enter a 10- or 11-digit telephone number

It's in the format +436801234567

**Comment by penrods** [comment]
Well that isn't a good validator...

That field is optional, right?  So you can ignore it..  I'll change it to simple text for future forms.  (Once they are sent they can't be changed.)

**Comment by z3ntu** [comment]
Okay I left it empty.

**Comment by nealmcb** [comment]
The phone number was not listed as required, but had a star.
The form showed up with one mystery required field, which was floating in and obscuring the text of the paragraph just above the signature area. I just filed it out with a question like "what is this field" and it let me get thru, but I doubt that's what you wanted...

**Comment by z3ntu** [comment]
@nealmcb I put a bunch of question marks into that field :smile:

**Comment by penrods** [comment]
Let me check in on that, the HelloSign field creation tool is a little quirky and I must have dropped a field there.  Sorry, I've corrected that for future signers!  The phone number is also no longer validated.

The extra field shouldn't cause and hassle to those of you who received requests with it.  You can either just put in "ignore" or whatever you'd like or you can re-request the form and I'll send you a clean copy.

**Comment by tmajibon** [comment]
I find it amusing (in a negative way) that I did one update, that has been completely rewritten since... but you still need me to sign this agreement.

Legal can be so horrible to projects sometimes. (I don't mind signing, just screwed up that such a minor contribution could create a potential problem)

**Comment by penrods** [comment]
@tmajibon You are right that legal stuff can be tricky and funny in a not-so-funny way.  And legally, we could probably skip getting your agreement if what you say is totally true.  But I want to tackle this in the most forthcoming manner possible -- I don't want anyone feeling like we pulled some sort of slight of hand in this process.

**Comment by tmajibon** [comment]
@penrods Yeah, and there's always the line between "legal" and "can start a legal battle that will cost you boatloads of money even if you know you're going to win".

I credit you guys for good behavior, and I hope this license change helps the project spread!

(Got the request and signed it)

**Comment by z3ntu** [comment]
@tmajibon Well I only [did one commit](https://github.com/MycroftAI/mycroft-core/commits/dev?author=z3ntu) to add an option to a command 😆

**Comment by forslund** [comment]
I believe this has been performed in #1128. Closing.
