### ISSUE TITLE
devsetup fatal: could not create work tree dir 'mimic': Permission denied

### ISSUE THREAD

**Issue by absentdream** [MycroftAI/mycroft-core#931]
ok running devsetup as a user and get 

fatal: could not create work tree dir 'mimic': Permission denied

do you know what folder

ubuntu 17.04

**Comment by absentdream** [comment]
doh worked it out... dont root git and user compile..

**Comment by fireblox** [comment]
can you explain better? pls?

**Comment by el-tocino** [comment]
Absentdream likely sudo'd and ran the setup scripts.  They should NOT be run as root, or when you've sudo'd.
