### ISSUE TITLE
Wolfram Alpha Response Phrasing - Setting Yoda

### ISSUE THREAD

**Issue by joshua-montgomery** [MycroftAI/mycroft-core#935]
Asking Mycroft "How tall was Abraham Lincoln" queries Wolfram Alpha.

Mycroft should respond: "Abraham Lincoln was six four"

Mycroft currently channels Yoda and responds: "Was Abraham Lincoln tall six four"

Can someone look at the Wolfram response parsing and deal with this please or, as Mycroft would say,
"This please deal with look someone at Wolfram skill"

**Comment by el-tocino** [comment]
This should be a setting you can enable (or, I suppose, disable).

**Comment by forslund** [comment]
I've sent a PR for this particular case but there are many types of questions that the skill has problems with. Will need to look into a more general solution.

**Comment by forslund** [comment]
This has been handled. Also we've recently switched to the spoken api of wolfram alpha which should guarantee that all possible permutations of this issue should be handled. Closing
