### ISSUE TITLE
On and Off keywords (resolved)

### ISSUE THREAD

**Issue by abelfodil** [MycroftAI/mycroft-core#936]
Let's have the general case "Turn **!device!** **!state!** in **!room!**"

When I say "Turn the **!device!** on in **!room!**", only **!state!** (which is "on" in this case) and **!room!** show up in message.data, but when I pass "off" as **!state!**, this time **!device!** and **!room!** show up.

When I tried other words such as "new", "dad" or anything that is not "on" and "off" in **!state!**, it works fine.

EDIT: Fixed formating issues

**Comment by forslund** [comment]
Hi,

could you please explain in a little bit more detail. I'm not sure I understand what you're expecting to happen when you say "turn the on in" or "turn the off in"

From the sound of it this is related to some skill? which skill in that case?

Or is it an Speech to text issue?

**Comment by abelfodil** [comment]
I am deeply sorry, I forgot to double check after I posted :(
I was using < instead of ! in my post.

I am currently coding a home automation skill, but when I try to use the "on" and "off" keywords, message.data has a strange behaviour.  Like I said, two out of three variables show up. But when using anything else like dim or brighten, it works just fine.

**Comment by abelfodil** [comment]
It turns out that I had to restart Mycroft each time I updated the my regex.

**Comment by forslund** [comment]
Great to hear you got it working!

Since you've marked the thread as resolved, I'll go ahead and close it.
