### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jony0008** [MycroftAI/mycroft-core#937]
Would be great to have mycroft in different languages. I can recommend Crowdin or Weblate for managing the translations.

**Comment by forslund** [comment]
That's a good suggestion, Thanks.
We have a system for handling translations but it can surely be improved. I've used crowdin to provide translations for c:geo so I might start looking at that.

Do you have any experience in integrating one of those?

**Comment by jony0008** [comment]
No, I have only used them for contributing translations.

**Comment by forslund** [comment]
Hi, we finally settled on using pootle to handle translations. We're slowly starting to import them into the skills.

I'm closing this issue for now.

**Comment by forslund** [comment]
Oh, forgot: https://translate.mycroft.ai in case you'd like to help out :)
