### ISSUE TITLE
execute: dev_setup.sh return: fatal: not in a git directiory

### ISSUE THREAD

**Issue by StephenDecatur** [MycroftAI/mycroft-core#982]
Hello,

I am new to Mycroft, Git, and Ubuntu. So this error is most likely due to my own lack of knowledge.  I have executed build_host_setup_desbian already and that went well. However, when I attempt to execture dev_setup.sh, it does not go well and I receive the error fatal: not in a git directory I looked online and through a few pages of the issues, but did not see my issue. So I assume two things: other people don't have this problem and it is due to my lack of knowledge.  Any help would be greatly appreciated.  I have included what I have ran this far

johnanaya@osboxes:~$ '/home/johnanaya/Programs/mycroft-core-master/build_host_setup_debian.sh' 
[sudo] password for johnanaya: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-9).
automake is already the newest version (1:1.15-4ubuntu1).
bison is already the newest version (2:3.0.4.dfsg-1).
libffi-dev is already the newest version (3.2.1-4).
libjpeg-dev is already the newest version (8c-2ubuntu8).
libtool is already the newest version (2.4.6-0.1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
portaudio19-dev is already the newest version (19+svn20140130-1build1).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
python-gobject-dev is already the newest version (3.20.0-0ubuntu1).
python-setuptools is already the newest version (20.7.0-1).
screen is already the newest version (4.3.1-2build1).
flac is already the newest version (1.3.1-4).
mpg123 is already the newest version (1.22.4-1).
s3cmd is already the newest version (1.6.1-1).
swig is already the newest version (3.0.8-0ubuntu3).
virtualenvwrapper is already the newest version (4.3.1-2).
curl is already the newest version (7.47.0-1ubuntu2.2).
git is already the newest version (1:2.7.4-0ubuntu1.2).
libglib2.0-dev is already the newest version (2.48.2-0ubuntu1).
libicu-dev is already the newest version (55.1-7ubuntu0.2).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.8).
python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 52 not upgraded.
johnanaya@osboxes:~$ '/home/johnanaya/Programs/mycroft-core-master/dev_setup.sh' 
fatal: not in a git directory

Thank you again for any help, looking forward to getting Mycroft running soon!

**Comment by penrods** [comment]
I think I just responded to you in Mattermost.   It looks like you didn't run from _inside_ the download directory.  I.e. you should run:

johnanaya@osboxes:$ git clone https://github.com/MycroftAI/mycroft-core.git
johnanaya@osboxes:$ cd mycroft-core
johnanaya@osboxes:$ ./build_host_setup_debian.sh
johnanaya@osboxes:$ ./dev_setup.sh

Make sense?

**Comment by johnluisanaya** [comment]
Yes that does, and I will try that write now.

**Comment by johnluisanaya** [comment]
Alright, so I followed your instructions and a few errors seem to have occurred after executing ./dev_setup.sh
1
johnanaya@osboxes:~/mycroft-core$ ./dev_setup.sh
./dev_setup.sh: line 52: hash: mimic: not found
2
File "/home/johnanaya/.virtualenvs/mycroft/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 240, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
3
OSError: Command /home/johnanaya/.vir...ycroft/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 2

I ran ./mycroft.sh start and that looked fine, no errors. 

I ran ./dev_setup.sh again and two errors were present
1 & 2
./dev_setup.sh: line 52: hash: mimic: not found
./dev_setup.sh: line 65: /home/johnanaya/.virtualenvs/mycroft/bin/activate: No such file or directory

Thank you for you help!

**Comment by forslund** [comment]
For the mimic issue I think there is a fix (see #983) If you want to hand edit the script the relevant line is here: https://github.com/MycroftAI/mycroft-core/pull/983/files#diff-18dbf5207379240f00af7b954cde81ffR52
